### ISSUE TITLE
configurable products display a weird price after updating from 1.9.2.2 to 2.0.7

### ISSUE THREAD

**Issue by dmcmillin** [magento/data-migration-tool#102]
Take for an example: http://www.vasariplaster.com/magento2/plaster-stucco/venetian-plaster-stucco/veneziano-2-gal.html

Which is directly copied from 
http://www.vasariplaster.com/veneziano-2-gal.html

It feels like it took a price from somewhere non standard and I can't figure out what happened.

**Comment by dmcmillin** [comment]
found that the migration tool is adding special prices with random amounts. erased  the field and it fixed the problem

**Comment by ilol** [comment]
We will investigate special process migration. Anyway the special prices should be migrated if the special prices is still actual or future. Don

**Comment by victor-v-rad** [comment]
Please try the latest Data Migration Tool 2.1 It could help

**Comment by victor-v-rad** [comment]
I am closing the issue. Feel free to reopen if it is still actual
