### ISSUE TITLE
magento/data-migration-tool 2.0.6 not installed successfully.

### ISSUE THREAD

**Issue by anoopaugustin** [magento/data-migration-tool#104]
D:\Projects\magento206.com>composer config repositories.data-migration-tool git
https://github.com/magento/data-migration-tool

D:\Projects\magento206.com>composer require magento/data-migration-tool:2.0.6
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/data-migration-tool 2.0.6 exists as magento/
data-migration-tool[2.0.0, 2.0.2, 2.0.5, 2.0.7, 1.0.0-beta] but these are reject
ed by your constraint.

Installation failed, reverting ./composer.json to its original content.
Which version should i use to migrate magento 1.9.2.4 to magento2.0.6

**Comment by qrider** [comment]
I am experiencing a similar issue for 2.1

**Comment by victor-v-rad** [comment]
Try the latest Data Migration Tool  2.1.0
