### ISSUE TITLE
password in xml config

### ISSUE THREAD

**Issue by asavchenko** [magento/data-migration-tool#110]
I'm having issues with migration because inside
vendor/magento/data-migration-tool/etc/ce-to-ce/1.6.2.0/config.xml i have to specify mysql credentials inside this node
` <database host="localhost" name="magento" user="root"/>`
but my password contains '&' symbol which is not allowed in xml documents. Possible workaround could be CDATA tag, but with current xml structure it's not possible.

Error in console:
```
 [Magento\Framework\Config\Dom\ValidationException]
  xmlParseEntityRef: no name
  Line: 99
  xmlParseEntityRef: no name
  Line: 102
```

**Comment by kandy** [comment]
Can you try use &#038; instead of  '&' ?

**Comment by asavchenko** [comment]
Yeah + others not mentioned:
<  &lt;
& &amp;
> &gt;
'  &apos;
" &quot;

But i think the error message should be more explicit. Or avoid this escaping entirely by changing the xml structure and allow use of CDATA.
Thx.

**Comment by victor-v-rad** [comment]
Hi @asavchenko 

Probably changing the password will be the easiest way. In case it is not possible you can override 
`\Migration\ResourceModel\Adapter\Mysql` by option resource_adapter_class_name. See `\Migration\ResourceModel\AdapterFactory`

**Comment by kandy** [comment]
@asavchenko, Special symbol escaping is common of any xml. Please use xml editor that show warning about not properly escaped symbols. 
Use CDATA for the password will be BC break, so we cannot do it, so I am closing this issue. Feel free to reopen it if we missed anything.

**Comment by jaimin-iverve** [comment]
@kandy thanks, my database contains "&" character so i have replaced with "&amp;" and it worked. thanks
