### ISSUE TITLE
 Installation Issue with Magento 2.0.7 & 2.1.0 CE

### ISSUE THREAD

**Issue by abdul-ghaffar** [magento/data-migration-tool#116]
I am getting error while installing the data migration tool on the latest Magento 2.1.0

`composer require magento/data-migration-tool`

I have also tried older version  Magento 2.0.7, both have same error,
I am using OS X Yosemite 10.10.5 , php 5.6.10 and MySQL 5.6.25 on my system.
I am getting following error

![2f9c14ea-4a71-11e6-9c55-b1d98c63ac89](https://cloud.githubusercontent.com/assets/20470196/16864505/9898c56a-4a76-11e6-8724-7ca328a60c8e.png)

**Comment by victor-v-rad** [comment]
Try with https
composer config repositories.magento composer https://repo.magento.com
composer require magento/data-migration-tool:2.1.0

**Comment by victor-v-rad** [comment]
Internal issue MAGETWO-55436
