### ISSUE TITLE
Customer cannot login after migration

### ISSUE THREAD

**Issue by MagePsycho** [magento/data-migration-tool#117]
I have updated the M2's config.xml > `crypt_key` from the M1's > `app/etc/local.xml` before data-migration.
After successful migration, I can see the customers listed in the backend grid. 
But when the customer tries to login in the frontend, it says:

> Invalid login or password.

**Comment by victor-v-rad** [comment]
You can debug your problem here \Migration\Step\Customer\Helper::upgradeCustomerHash()

**Comment by victor-v-rad** [comment]
@MagePsycho have you managed to solve your issue?

**Comment by MagePsycho** [comment]
@victor-v-rad not sure how but later it worked suddenly. What I did was to change the crypt key in app/etc/env.php with the one from Magento1. But later when I changed it back login was still working fine. So not sure what fixed the issue :)
