### ISSUE TITLE
Warning: DOMDocument::loadXML()

### ISSUE THREAD

**Issue by bobbyn** [magento/data-migration-tool#118]
When I start migration of data with the command below this error appears: 

[mage@localhost magento2]$ bin/magento migrate:data --reset /var/www/vhosts/magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.6.1.0

  [Exception]
  Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www
  /vhosts/magento/vendor/magento/framework/Config/Dom.php on line 379

migrate:data [-r|--reset] config

How to solve this problem? It's brand new Magento 2 installation and I am trying to get data from my old store (1.6.1).

**Comment by redboxmarcins** [comment]
You need to supply full filename path to XML file not just directory

**Comment by bobbyn** [comment]
Thanks :) worked

**Comment by ilol** [comment]
Thank you @bobbyn

**Comment by ilol** [comment]
Thank you, @redboxmarcins
