### ISSUE TITLE
unserialize(): Error

### ISSUE THREAD

**Issue by coolocean** [magento/data-migration-tool#119]
Hi,

Getting 

`[Exception]                                                                                                                       
  Notice: unserialize(): Error at offset 0 of 1 bytes in magento/vendor/magento/data-migration-  
  tool/src/Migration/Handler/SerializeToJson.php on line 28 `

**Comment by victor-v-rad** [comment]
Hi,

Please look at your DB fields 
sales_flat_order_item.weee_tax_applied 
sales_flat_quote_item.weee_tax_applied
sales_flat_creditmemo_item.weee_tax_applied
sales_flat_invoice_item.weee_tax_applied
Do they have data serialized data?

Can you show this incorrect data in $value in line 28 of tool/src/Migration/Handler/SerializeToJson.php ?

**Comment by coolocean** [comment]
We do have sales_flat_order_item.product_options serialised. Here is one of the value.

`a:1:{s:15:"info_buyRequest";a:5:{s:4:"uenc";s:84:"aHR0cDovL3d3dy5idXlydWRyYWtzaGEuY29tL2JyYXNzLXNoaXYtcGFyaXdhci1pZG9sLTcwMGcuaHRtbA,,";s:7:"product";s:2:"94";s:8:"form_key";s:16:"vGazj7qHyuduCtON";s:15:"related_product";s:0:"";s:3:"qty";s:1:"1";}}`

**Comment by victor-v-rad** [comment]
Why did you show sales_flat_order_item.product_options instead of 
sales_flat_order_item.weee_tax_applied 
sales_flat_quote_item.weee_tax_applied
sales_flat_creditmemo_item.weee_tax_applied
sales_flat_invoice_item.weee_tax_applied
?

**Comment by coolocean** [comment]
Hi,

Sorry. But the data on those is not serialised.

**Comment by coolocean** [comment]
Sorry here is the data 

`a:0:{}`

**Comment by coolocean** [comment]
Got it resolved. There were few entries which were not serialised. Manually fixed it.

**Comment by joshspivey** [comment]
Just echo out the field name on SerializeToJson.php above line 28. When it errors out it will tell you which field. For me I had numbers in the wee tax field so I just made a query to check if its a number. 

SELECT * FROM sales_flat_order_item WHERE weee_tax_applied REGEXP '^[0-9]+\\.?[0-9]*$'

Then I added the a:0:{} to the field value.

**Comment by VZeroCool** [comment]
I'm having same issue while migration How to fix ? @victor-v-rad
