### ISSUE TITLE
Clean database with 1.9.1

### ISSUE THREAD

**Issue by seabird** [magento/data-migration-tool#12]
Hi everyone,

created a clean install via composer and never even logged in. I dumped the database and am trying to get my data-migration tool to sync my settings and information.

unfortunatly I get this error:
[PDOException]

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'association-2' for key 'SEARCH_QUERY_QUERY_TEXT_STORE_ID' 

Any clues how to solve this?

**Comment by chrissm79** [comment]
I had to search and remove duplicates in my catalogsearch_query table (Magento 1.x). I found them by running the following:

```sql
SELECT query_text, COUNT(*) c FROM catalogsearch_query GROUP BY query_text HAVING c > 1;
```

**Comment by ilol** [comment]
Thanks @chrissm79 
@seabird would you close the ticket?

**Comment by victor-v-rad** [comment]
The Migration Tool should not transfer these duplicates. According internal issue (MAGETWO-47876) was created to solve it

**Comment by dwdonline** [comment]
Same issue migrating 1.9.11 > 2.0.0.

Thanks @chrissm79 - that did it for me.

**Comment by seabird** [comment]
On the double ones, what is the impact of which one you delete? Is it possible to do this automated?
"DELETE FROM `catalogsearch_query` WHERE c > 1"?

**Comment by ilol** [comment]
@seabird can close?

**Comment by seabird** [comment]
Sorry, due to other problemo did not have time to look into this further. Sure thing, close it.
