### ISSUE TITLE
Migration ee-to-ce

### ISSUE THREAD

**Issue by AVATOR** [magento/data-migration-tool#120]
Hi.
I need to make migration from Magento 1.11.1.0 EE to Magento 2.1.0 CE. I could not find folder ee-to-ce in <your Magento 2 install dir>/vendor/magento/data-migration-tool/etc .

Please advice.

**Comment by ilol** [comment]
Migration of EE to CE is a bad choice. We didn't provide configuration for such migration

**Comment by AVATOR** [comment]
Hi @ilol.
Does scripts "ee-to-ee" work fine to migrate Magento 1.11.1.0 Prof to Magento 2.1 EE?

**Comment by ilol** [comment]
I am not sure... we didn`t create the config file for that and didn`t test.
But you can try, the system will show you information about inconsistency and you will be able to fix it yourselves.

**Comment by jlaustill** [comment]
@AVATOR what was your mileage on this?  I'd love to do a migration for demo purposes, but obviously ee isn't an option for a one-off demo.
