### ISSUE TITLE
issue in edit product using admin panel

### ISSUE THREAD

**Issue by meenarajendran** [magento/data-migration-tool#123]
Using this tool i have migrated our magento CE 1.9.2.1 Database to our magento EE 2.1.0.
After migration not able to edit the product from admin panel. When click on edit product(Product->catalog->any product edit) getting the error"

"The configuration parameter "componentType" is a required for "design" component."

Anybody please advise.

Thank you.

**Comment by victor-v-rad** [comment]
Please look in eav_attribute_group table. There should be records with "design" in attribute_group_code

**Comment by meenarajendran** [comment]
yes there is a record, its attribute_group_id is 1124.

**Comment by meenarajendran** [comment]
i am new to magento. please advise me like how to fix this issue.

**Comment by victor-v-rad** [comment]
Hi @quienti 
It is hard to figure out what wrong in your case
You could share your DB dump of the next Magento 1 tables:
eav_attribute_group
eav_attribute_set
eav_attribute
eav_entity_attribute
catalog_eav_attribute
customer_eav_attribute
eav_entity_type
You can send it through the email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it.

**Comment by victor-v-rad** [comment]
@meenarajendran 
I am closing the issue. Please recheck it on the latest version of the tool and reopen if it is still actual
