### ISSUE TITLE
Sales Order Grid Migration bug?

### ISSUE THREAD

**Issue by mikeymike** [magento/data-migration-tool#125]
I might be missing something completely but I can't help think this is a glaring bug. For reference I'm doing a migration from M1 CE -> M2 EE. That though should not really matter.

When doing the migration step for Sales order grid it seems to be working fine but then after checking the volume kicks out a few warnings and an error 

```
[WARNING]: Mismatch of entities in the document: sales_order_grid
[WARNING]: Mismatch of entities in the document: sales_invoice_grid
[WARNING]: Mismatch of entities in the document: sales_shipment_grid
[WARNING]: Mismatch of entities in the document: sales_creditmemo_grid

  [Migration\Exception]
  Volume Check failed
```

So I thought I'd take a look through the code and debug it. Turns out it seems to do an insert from a select. The insert is into the destination DB and the select is also from the destination DB. 

You can see this in `Migration\Step\OrderGrids\Data` on lines `120` ... `155`  and `192` ... I honestly can't think of any reason why it would actually want to migrate data from itself into itself 😂 

Can you confirm what the actual behaviour is here, how it should function and if this is actually a bug or not? 

Thanks 😄

**Comment by victor-v-rad** [comment]
Magento 1 grid table is totally different than Magento 2 grid table and it cannot be migrated as is. Thus the Magento 2 grid is formed from migrated data. But it is fine for volume check to compare count of M1 grid and M2 grid. As for warning you get it can occur when during migration in M1 store front order is placed. But it should not stop migration by throwing exception

**Comment by mikeymike** [comment]
Ah right so effectively the order of my migration steps is incorrect. I'll try to re-order things to get this working, Thanks!

_Side note: These are the kind of things that should be documented, either in the docs, readme or in comments on the code._

**Comment by mikeymike** [comment]
Moving the sales data migration step before the order grid step resolved the first initial warning but now I'm confused at how to resolve the next three warnings regarding `sales_invoice_grid`, `sales_shipment_grid` and `sales_creditmemo_grid`. 

Looking at their respective methods they pull the data from their specific M2 tables so I'm assuming these are again run after migrating `invoice`, `shipment` and `creditmemo` data as per the order grid issue before. 

The problem I see is that there doesn't seem to be any migration of this data, unless again I'm blindly missing something. 

Any pointers on this would be great!

**Comment by victor-v-rad** [comment]
sales_invoice sales_shipment tables migrate in Map step which run before OrderGrids step. Thus you should not have the issues you faced

**Comment by mikeymike** [comment]
I think the problem stemmed from the fact I'm having to construct my own configuration because the CE -> EE `.dist` files don't seem to have sales data migrations. 

Funnily enough the map step I removed completely because that gave my this exception

`Warning: Error while sending QUERY packet`

After trying to do 37k row insertion in one statement built in a single sprintf, which I'm mesmerised at... I guess I'll have to either increase the max packet size value in MySQL until this works or look at putting a more permanent solution in place.

**Comment by mikeymike** [comment]
Increasing the memory resolved that, although I believe it might be better to chunk these inserts to better handle larger data sets (my example isn't a large one imo) 

Closing now, thanks for the help @victor-v-rad much appreciated!

**Comment by gouravsyscraft** [comment]
I am getting exactly same error also when migrating only order.

**[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_order_grid
[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_invoice_grid
[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_shipment_grid
[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_creditmemo_grid**


And data not migrating, can you please help me to sort out this.

**Comment by neetu-mittal** [comment]
I have exactly same issue, anyone have solution, Kindly let me know.

**Comment by dnesdeveloper** [comment]
@gouravsyscraft - have you found the solution?

**Comment by jimains** [comment]
+1 I have the same issue and can see no clear resolution

**Comment by ghost** [comment]
anyone have a solution on this I am also getting the same error

**Comment by ruipns** [comment]
Hey,
I had the same issue

https://github.com/magento/data-migration-tool/issues/467#issuecomment-627912182

Hope it helps someone!

**Comment by Eddcapone** [comment]
@ruipns I tried your solution, it imports customers but it does not imports the data, it is all null but E-Mail. No Firstname, Lastname, Password etc.
