### ISSUE TITLE
PHP FATAL error during data migration

### ISSUE THREAD

**Issue by onepack** [magento/data-migration-tool#126]
We have been running into this error for many times now and no matter what we do it stays.
Magento: 1.9.2.2 to magento 2.1.0 migration
PHP 7.0.8
CENTOS 7
Cleared compiled files and cache.

System settings runs ok but Data migration keeps on giving this error:

100% [============================] Remaining Time: 1 sec
[2016-08-01 20:36:54][INFO][mode: data][stage: integrity check][step: PostProcessing Step]: started
0% [>---------------------------] Remaining Time: 1 sec   PHP Fatal error:  Uncaught Error: Call to a member function getStructure() on boolean in /apps/web/dev.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/PostProcessing/Integrity.php:85
Stack trace:
#0 /apps/web/dev.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/PostProcessing/Integrity.php(70): Migration\Step\PostProcessing\Integrity->checkFields(Array, 'destination')
#1 /apps/web/dev.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php(73): Migration\Step\PostProcessing\Integrity->perform()
#2 /apps/web/dev.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(88): Migration\Mode\AbstractMode->runStage(Object(Migration\Step\PostProcessing\Integrity), 'PostProcessing ...', 'integrity check')
#3 /apps/web/dev.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(61): Migration\Mode\Data->runIntegrity(Object(Migration\App\Mode\StepList))
#4 /apps/web/dev.site in /apps/web/dev.site.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/PostProcessing/Integrity.php on line 85

**Comment by victor-v-rad** [comment]
Getting such error could mean you do not have one of the next tables in your Magento 2 DB:
catalog_product_entity_datetime
catalog_product_entity_decimal
catalog_product_entity_int
catalog_product_entity_text
catalog_product_entity_varchar
Please check this out

**Comment by onepack** [comment]
They are all in place.
It is a database that is not running on the same server and the tables are prefixed.
Could this be the related to this issue?
Importing the settings was no problem though.

sow_catalog_product_entity                               |
| sow_catalog_product_entity_datetime                      |
| sow_catalog_product_entity_decimal                       |
| sow_catalog_product_entity_gallery                       |
| sow_catalog_product_entity_int                           |
| sow_catalog_product_entity_media_gallery                 |
| sow_catalog_product_entity_media_gallery_value           |
| sow_catalog_product_entity_media_gallery_value_to_entity |
| sow_catalog_product_entity_media_gallery_value_video     |
| sow_catalog_product_entity_text                          |
| sow_catalog_product_entity_tier_price                    |
| sow_catalog_product_entity_varchar

**Comment by victor-v-rad** [comment]
Specify prefix for tables in Magento 1 and 2 in your config.xml > source_prefix and dest_prefix
I see \Migration\Step\PostProcessing\Helper::getProductDestinationDocumentFields should return table names with prefix

**Comment by onepack** [comment]
This is what is defined in the config.xml
        <source_prefix />
        <dest_prefix>sow_</dest_prefix>
Please let me know if this should be different.

**Comment by onepack** [comment]
I have changed the config like this but logically with the same result.
```
<options>
        <source_prefix></source_prefix>
        <dest_prefix>sow_</dest_prefix>
</options>
```

**Comment by onepack** [comment]
We made a complete new installation and started all over again.
This time it was more successful however other issues appeared after the migration that I will log in a different case is not logged already.

**Comment by cristianclick01** [comment]
I have the same issue...
How you @onepack solved the error?

**Comment by phudu25** [comment]
I have the same problem when trying to migration data from 1901 to 211...
