### ISSUE TITLE
Very Vague Integrity constraint violation Duplicate Key Error

### ISSUE THREAD

**Issue by beckindesigns** [magento/data-migration-tool#128]
I am attempting to transfer the data over using the data migration tool. I have ported the settings already but I run into issues while trying to port over the data. After running the following command:

```
php56 bin/magento migrate:data vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.3/config.xml
```

I get the following error:

```
[2016-08-02 20:26:32][INFO][mode: data][stage: data migration][step: EAV Step]: started
71% [====================>-------] Remaining Time: 1 sec
[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '249' for key 'PRIMARY'
```

This is just too general to figure out what table has the problem and why. Does anyone know which file I can log to get a more detailed version of the sql query that is running to figure out why this is happening and what table it is on? I think it may have something to do with the eav_attribute_set but I'm not sure why. I checked my mysql log and found this:

`10 Query	INSERT INTO eav_attribute_set (`attribute_set_id`,`entity_type_id`,`attribute_set_name`,`sort_order`) VALUES ('1','1','Migration_Default','100'),('2','2','Migration_Default','100'),('3','3','Migration_Default','100'),('4','4','Migration_Default','100'),('5','5','Migration_Default','100'),('6','6','Migration_Default','100'),('7','7','Migration_Default','100'),('8','8','Migration_Default','100'),('9','4','Migration_Mattress / Bedding Accessories','100'),('10','4','Migration_Mattresses','100'),('11','4','Migration_Upholstery','100'),('12','4','Migration_Dining Tables','100'),('13','4','Migration_Dining Chairs','100'),('14','4','Migration_Case Goods','100'),('15','4','Migration_Beds','100'),('16','4','Migration_Rugs','100'),(NULL,'1','Migration_Default','100'),(NULL,'2','Migration_Default','100'),(NULL,'3','Migration_Default','100'),(NULL,'4','Migration_Default','100'),(NULL,'5','Migration_Default','100'),(NULL,'6','Migration_Default','100'),(NULL,'7','Migration_Default','100'),(NULL,'8','Migration_Default','100'),(NULL,'4','Migration_Mattress / Bedding Accessories','100'),(NULL,'4','Migration_Mattresses','100'),(NULL,'4','Migration_Upholstery','100'),(NULL,'4','Migration_Dining Tables','100'),(NULL,'4','Migration_Dining Chairs','100'),(NULL,'4','Migration_Case Goods','100'),(NULL,'4','Migration_Beds','100'),(NULL,'4','Migration_Rugs','100'),(NULL,'1','Default','2'),(NULL,'2','Default','2'),(NULL,'3','Default','1'),(NULL,'4','Default','1'),(NULL,'5','Default','1'),(NULL,'6','Default','1'),(NULL,'7','Default','1'),(NULL,'8','Default','1')`

**Comment by victor-v-rad** [comment]
use -vvv parameter to see more detailed information. By the way your problem could be solved in the upcoming release 2.1.1 since there are a lot of changes in EAV Step

**Comment by beckindesigns** [comment]
Thanks @victor-v-rad 

This was helpful to find the file to log the sql query. The logged queries look like this.

`[2016-08-03 15:05:58] main.DEBUG: INSERT INTO catalog_eav_attribute (`attribute_id`,`frontend_input_renderer`,`is_global`,`is_visible`,`is_searchable`,`is_filterable`,`is_comparable`,`is_visible_on_front`,`is_html_allowed_on_front`,`is_used_for_price_rules`,`is_filterable_in_search`,`used_in_product_listing`,`used_for_sort_by`,`apply_to`,`is_visible_in_advanced_search`,`position`,`is_wysiwyg_enabled`,`is_used_for_promo_rules`,`is_required_in_admin_store`,`is_used_in_grid`,`is_visible_in_grid`,`is_filterable_in_grid`,`search_weight`,`additional_data`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) {"is_exception":false} []`

Any idea why?

**Comment by beckindesigns** [comment]
@victor-v-rad 

Ok, I see what is happening now. It is inserting into the catalog_eav_attribute table twice. The first insert which runs fine inserts attribute_id 41 - 262. Then the second insert runs which fails b/c it tries to insert 249 -257.

Any thoughts how to fix that? I see the first insert run is what I have on the live v1 database. What is the second insert for? Where does it get that data? Unused original v2 data that was not in the v1 version so it tries to add it back maybe?

**Comment by beckindesigns** [comment]
Found the problem. I added the following to the class-map.xml file.

```
    <rename>
        <from>ultramegamenu/category_attribute_source_dropdown_type</from>
        <to>Infortis\UltraMegamenu\Model\Category\Attribute\Source\Dropdown\Type</to>
    </rename>
```

and etc...

**Comment by victor-v-rad** [comment]
Ignored attributes should not cause error in volume check
Internal ticket MAGETWO-56371
