### ISSUE TITLE
Undefined offset: 14 in /vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433

### ISSUE THREAD

**Issue by rtowings** [magento/data-migration-tool#132]
Magento Source = 1.9.2.2
Magento Dest = 2.1
Data Migration Tool 2.1.0
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: EAV Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: Map Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: Log Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: integrity check][step: PostProcessing Step]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: setup triggers][step: Stage]: started
[2016-08-04 22:51:16][INFO][mode: data][stage: data migration][step: EAV Step]: started
57% [================>-----------] Remaining Time: 2 secs

  [Exception]
  Notice: Undefined offset: 14 in /var/public/html/magento2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433

stack trace shows that this was called by Data.php line 400:
$this->moveAttributeToGroup($recordsToSave, 'price', 'product-details');

-- As a test, I deleted ALL products - same error
-- deleted ALL attribute sets (other than default)  - same error
-- deleted ALL non-system (i.e, user added) 'required' attributes - same error
-- deleted ALL non-system attributes - same error
-- deleted ALL rewrite rules -- same error

At this point, I'm looking at an almost empty database and I'm thinking the offending data is in what's left.  Any suggestions about where to start looking?

**Comment by rtowings** [comment]
Further testing.  Started with a clean, empty installation of 1.9.2.2 (fresh install) and a fresh install of 2.0.
Ran migrate:settings & migrate:data - success!  

Then ran migrate:data --reset     error in step: EAV Step  28%
[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

ran migrate:data --reset again    error in step: EAV Step 14%
[Exception]
  Notice: Undefined offset: 1 in /var/www/html/magento2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 209

**Comment by victor-v-rad** [comment]
>[Exception]
Notice: Undefined offset: 14 in /var/public/html/magento2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433
Make sure in M1 eav_attribute_group.attribute_group_name you have all the next values;
General
Prices
Design

**Comment by toddliningerdesign** [comment]
@victor-v-rad  @rtowings is there any solution for that?

**Comment by rtowings** [comment]
Hi @victor-v-rad

All of the attribute sets contain those three group names, with the exception of attribute sets 1-8, which are labeled in eav_attribute_set as "Default".

There is an anomaly that I should mention.  There are attribute sets in eav_attribute_group that do not have a corresponding entry in eav attribute_set.  All of these orphan sets seem correctly formed, in that they include all of the system attribute groups (General, Prices, Meta Information, Images, Recurring Profile,  Design, Gift Options).

**Comment by rtowings** [comment]
The issue was the orphaned sets. 
After identifying attribute sets in eav_attribute_group that did not have a corresponding entry in eav_attribute_set, I created the missing entries (INSERT INTO `eav_attribute_set` VALUES (Missing-set-1,4,'Missing1',0), (Missing-set-2,4,'Missing2',0),(Missing-set-3,4,'Missing3',0),(Missing-set-4,4,'Missing4',0); ) and re-ran the migration from the beginning.

I suppose I could just as easily have deleted the orphan attribute sets, but that seemed more intrusive than creating the missing headers.

Success!  Thanks to @victor-v-rad for pointing me in the right direction.

**Comment by baltechies** [comment]
Hi,
I have same issue. But did not get you. How to resolve this issue?

**Comment by Moinashraf** [comment]
Hi,
Can anyone solved this issue?

**Comment by rtowings** [comment]
Hi Moin,

This specific issue was caused by orphaned eav_attribute_sets and was resolved by recreating the missing headers (as noted above).  If you are getting exactly the error in the title (Undefined offset: in /vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433), then I can possibly assist.  

I should note, though, that this thread is somewhat dated and I suspect the Data Migration tool is more forgiving of this issue and less likely to present this error.
