### ISSUE TITLE
Exclude custom category attributes?

### ISSUE THREAD

**Issue by andidhouse** [magento/data-migration-tool#134]
I wonder if there is a possibility to exclude custom created category attributes?

Thanks!

**Comment by victor-v-rad** [comment]
etc/ce-to-ce/eav-attribute-groups.xml.dist could be helpful

**Comment by MagePsycho** [comment]
But the problem with this is, if your attribute code matches with other entity types, it will still be ignored. As per core team as of now there is no way to ignore EAV attributes by entity types.

**Comment by victor-v-rad** [comment]
Yes and to make it possible we created internal ticket MAGETWO-56809

**Comment by victor-v-rad** [comment]
The bug was fixed in the recent release. Please try it out. Feel free to reopen the issue if it is still relevant.
