### ISSUE TITLE
Custom rewites key integrity issue

### ISSUE THREAD

**Issue by martinboy** [magento/data-migration-tool#135]
## Preconditions
Magento 2 URL rewriting mechanism stores CMS pages rewrites among all other rewrites.  There might be situations when CMS page URL key is the same as a custom rewrite request_path in Magento 1 database. 

## Steps to reproduce
1. Add a custom rewrite in M1 database, i.e. 
```
request_path = contact-us
target_path = contacts
```
2. Add CMS page with the URL key  `contact-us`
3. Run migration tool

## Actual result
You'll see the following error
 ```
[stage: volume check][step: Url Rewrite Step]
[ERROR]: Mismatch of entities in the document: url_rewrite
```
In verbose mode you'll see the following MySQL error:
```
SQLSTATE[23000]: Integrity constraint violation: 1586 Duplicate entry '%s' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'
```
## Expected result

Migration should be completed without errors. URL path collision should be solved.

## Additional information
The possible solution is in my [pull request](https://github.com/magento/data-migration-tool/pull/98)

**Comment by victor-v-rad** [comment]
Hi @martinboy 
Thank you for your contribution to the project. We have already fixed the issue in our internal ticket MAGETWO-56087 . It will be available in the next release 2.1.1

**Comment by victor-v-rad** [comment]
Please recheck the issue on the last release of the tool 2.1.1

**Comment by victor-v-rad** [comment]
I am closing the issue. Feel free to reopen if it is still actual
