### ISSUE TITLE
Suggestion: Pre & Post migration commands

### ISSUE THREAD

**Issue by MagePsycho** [magento/data-migration-tool#137]
It would be better to have pre and post migration commands so that we can hook into our custom commands.
If we want to add it, what would be good place to start with? 
Badly need such features to automate everything.

**Comment by craigcarnell** [comment]
👍 Very much like this feature

**Comment by victor-v-rad** [comment]
nothing stops you from creating your own steps and put into customized config.xml

**Comment by MagePsycho** [comment]
Ok. 
I have added following custom steps in config.xml:
```
<steps mode="preMigration"> <!-- custom step -->
    <step title="Pre Migration Step">
        <data>Migration\Step\PreMigration\Data</data>
    </step>
</steps>

<steps mode="settings"...>
<steps mode="data"...>
<steps mode="delta"...>

<steps mode="postMigration"> <!-- custom step -->
    <step title="Post Migration Step">
        <data>Migration\Step\PostMigration\Data</data>
    </step>
</steps>
```

But seems this is an step which in each is a separate command. Or what you mean by own steps which doesn't require separate commands?

**Comment by victor-v-rad** [comment]
```
<steps mode="data"> <!-- custom step -->
    <step title="Pre Migration Step">
        <data>Migration\Step\PreMigration\Data</data>
    </step>
    <step title="EAV Step">
        <integrity>Migration\Step\Eav\Integrity</integrity>
        <data>Migration\Step\Eav\Data</data>
        <volume>Migration\Step\Eav\Volume</volume>
    </step>
....
    <step title="PostProcessing Step">
        <integrity>Migration\Step\PostProcessing\Integrity</integrity>
        <data>Migration\Step\PostProcessing\Data</data>
    </step>
    <step title="Post Migration Step">
        <data>Migration\Step\PostMigration\Data</data>
    </step>
</steps>
```

**Comment by MagePsycho** [comment]
Thanks for the input @victor-v-rad . That makes some sense. 
I would even love to have separate commands: `migrate:preOperation` & `migrate:postOperation` so that I can run the commands on demand.
Here(the example that you have shown), the problem is the tight integration with the `migrate:data `. Testing of post migration operation can take ages as we have to wait for other lengthy steps to be completed.
Not sure if in this case hack can be commenting all the steps in order to quick test of post Migration Step?

**Comment by victor-v-rad** [comment]
>Not sure if in this case hack can be commenting all the steps in order to quick test of post Migration Step?

Some steps are quite depended on other steps.
