### ISSUE TITLE
Grouped Products Migrating New Unique Index Issues with Multi-Store

### ISSUE THREAD

**Issue by BtotheT** [magento/data-migration-tool#139]
Running the migration from 1.11.0.0 EE over to 2.0.7, and we get as far as the product migration until this happens:

![duplicate-key](https://cloud.githubusercontent.com/assets/6549676/17791977/5573820a-656c-11e6-8d3d-5bf66e22fe8b.PNG)

I am not 100% but I believe this is due to the change in Index CATALOG_PRODUCT_LINK_LINK_TYPE_ID_PRODUCT_ID_LINKED_PRODUCT_ID being UNIQUE in Magento 2, but NOT unique in Magento 1, with multiple stores. Each store has it's own ID (link_id), leading Magento 2 to not be able to import these tables with the unique product_id,linked_product_id,link_type_id INDEX on it. Because of this, grouped products will import as individual products just fine, until simples are attempted to be attached and then fail on import.

Attached indexes
M1:
![m1-non-unique](https://cloud.githubusercontent.com/assets/6549676/17792102/06c0f54c-656d-11e6-9fae-03bec1972a0c.PNG)

M2: 
![m2-unique](https://cloud.githubusercontent.com/assets/6549676/17792110/0c72daaa-656d-11e6-8021-e71652fe4404.PNG)

**Comment by victor-v-rad** [comment]
Hi, 
I see UNQ_CAT_PRD_LNK_LNK_TYPE_ID_PRD_ID_LNKED_PRD_ID key exists in 1.11.0.0 EE. 
Have you tried to do migration direct_document_copy option disabled?

**Comment by BtotheT** [comment]
Hey Victor,

I disabled the direct_document_copy and still getting same issue, just less info provided.

![issue2](https://cloud.githubusercontent.com/assets/6549676/17913863/4b3556c6-696b-11e6-8977-51a9ea23a476.PNG)

You can see it is an empty table:
![0-returned](https://cloud.githubusercontent.com/assets/6549676/17913885/87f7959c-696b-11e6-8927-63a720dade05.PNG)

Is it an issue with multiple stores in M1 and the unique index in M2 (where it is not unique in M1)?

**Comment by victor-v-rad** [comment]
It is hard to figure out what wrong in your case
You could share your DB dump of your Magento 1 (remove all passwords before sending)
You can send it through the email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it.

**Comment by BtotheT** [comment]
Hey Victor,

Sorry for the delayed response. I've emailed you the DB with all passwords removed.

Thank you!

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-59777 was created to fix the issue.

**Comment by ygrigoriev** [comment]
You wrote that you tried to migrate to version 2.0.7, however we currently support only the latest version of Magento 2 as migration destination target.

Regarding your database, - i was able to migrate it to version 2.1.2. The main problem as you mentioned is connected with CATALOG_PRODUCT_LINK_LINK_TYPE_ID_PRODUCT_ID_LINKED_PRODUCT_ID key in `catalog_product_link` table, that is restricted to be unique in M2 and is not unique in M1. So before migration you should remove from M1 table all duplicates for this key. You can use SQL query to fild them:

`SELECT product_id, CONCAT(product_id, '_', linked_product_id, '_', link_type_id) AS compound FROM catalog_product_link GROUP BY compound HAVING COUNT(compound)>1;`

We can send you config and map files for the latest version if you need.

**Comment by BtotheT** [comment]
@ygrigoriev we were able to find the duplicates and remove - had to do it for a few other tables as well (media gallery), and were able to import from there and run the map step. Thank you. So 2.1.2 you were able to import with no issues?
