### ISSUE TITLE
migrated attributes > manage labels > manage titles empty on configurable products. 2.0.7

### ISSUE THREAD

**Issue by dmcmillin** [magento/data-migration-tool#140]
steps to replicate: 

1) have 1.9.x installed
2) have a configurable product with attributes.
3) migrate to 2.0.7 
4) check attributes
5) click manage labels
6) nothing is shown at all for values.

**Comment by victor-v-rad** [comment]
Hi,
Have just migrated 1.9.2.1 . Labels are migrated without problems. Please check your eav_attribute_label table in Magento 1 db and Magento 2 db

**Comment by victor-v-rad** [comment]
I am closing the issue. Feel free to reopen if it is still actual
