### ISSUE TITLE
Compatible with Magento 2.1

### ISSUE THREAD

**Issue by andidhouse** [magento/data-migration-tool#142]
I am wondering if the data migration tool is compatible with magento version 2.1?

Where can i find this info?

In the documentation it says:
composer require magento/data-migration-tool:2.1.0

Thanks!

**Comment by victor-v-rad** [comment]
Currently the tool 2.1.0 compatible with Magento 2.1.0

**Comment by andidhouse** [comment]
thanks @victor-v-rad 

Is there a changelog where we can see if the former bugs are solved?

Thanks!
