### ISSUE TITLE
Database realated issue?

### ISSUE THREAD

**Issue by aarondong2005** [magento/data-migration-tool#143]
I am trying to migrate 1.9.0.1 to 2.1.0. I already fixed the map and map-eav issue when doing the migrating data. But I got the following error. Please help!
![magento2-exception](https://cloud.githubusercontent.com/assets/15516555/17922266/faa757cc-6992-11e6-90e8-251029a6404b.jpg)

`[Zend_Db_Statement_Exception]
  SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_tr
  ust_function_creators variable), query was: CREATE TRIGGER trg_catalog_compare_item_after_insert AFTER INSERT ON catalog_compare_item FOR EACH ROW
  BEGIN
  INSERT INTO m2_cl_catalog_compare_item (`catalog_compare_item_id`, `operation`) VALUES (NEW.catalog_compare_item_id, 'INSERT')ON DUPLICATE KEY UPDATE op
  eration = 'INSERT';
  END`

`[PDOException]
  SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_tr
  ust_function_creators variable)`

**Comment by victor-v-rad** [comment]
> You do not have the SUPER privilege

The error message might have a clue

**Comment by aarondong2005** [comment]
It was server end issue. It have been fixed. If some one have this same issue. You should try to create a temp DB on target server and give a test run. If it will pass. That means that the issue related to firewall or server end.
