### ISSUE TITLE
two hours date difference

### ISSUE THREAD

**Issue by strauss69400** [magento/data-migration-tool#145]
hi,
i use the tool for migrate my data from my 1.7.0.2 to 2.1 magento.
it works except a un problem with date of purchase.
there is a difference of two hours, however the time zone('Europe/Paris') is the same on the two version!!

is there something to be configured for migration?

thanks
best regards

**Comment by victor-v-rad** [comment]
Hi,

You can use \Migration\Handler\Timezone handler in your map file for this
http://devdocs.magento.com/guides/v2.1/migration/migration-migrate-additional.html

**Comment by strauss69400** [comment]
ok, thank you for your response.
in map file i have some instruction such as : 
`            <transform>
                <field>cms_page.root_template</field>
                <handler class="\Migration\Handler\Convert">
                    <param name="map" value="[one_column:1column;two_columns_left:2columns-left;two_columns_right:2columns-right;three_columns:3columns]" />
                </handler>
            </transform>`

what do I need to change to keep the right date of purchase of my orders?

**Comment by strauss69400** [comment]
i manage to resolve my problem like a charm.below the solution :
 `            <transform>
                <field>sales_order.created_at</field>
                <handler class="\Migration\Handler\Timezone">
                    <param name="offset" value="+2" />
                </handler>
            </transform>`

**Comment by meezin** [comment]
@strauss69400  Which map file did you use ?

**Comment by schizek** [comment]
Per https://devdocs.magento.com/guides/v2.3/migration/migration-migrate-follow-up.html

> **Configure time zone offset**
> If your Magento 1 server has the time zone set to anything other than UTC, you must configure the offset to migrate timestamp fields. To transform time to a different time zone, use the Data Migration Tool’s \Migration\Handler\Timezone handler.
> 
> In the following example, the Magento 1 server timezone is UTC-7. To convert the customer account creation date properly, add the following rule to map-customer.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../map.xsd">
  <!--...-->
  <destination>
      <field_rules>
          <!--...-->
          <transform>
              <field>customer_entity.created_at</field>
              <handler class="\Migration\Handler\Timezone">
                  <param name="offset" value="-7" />
              </handler>
          </transform>
      </field_rules>
  </destination>
</map>
```

It seems like if the server is running on anything other than UTC you need to set this for every time field in the DB.  Geesh.
