### ISSUE TITLE
enterprise_url_rewrite_redirect not ignored in map.xml

### ISSUE THREAD

**Issue by Orims14** [magento/data-migration-tool#146]
Hi,
I am getting the below error when trying to migrate data from EE1.14.2.4 to EE2.1.0. Other tables added to the document rule were ignored but for some reason the enterprise_url_rewrite_redirect is not being ignored and i get a structure mismatch error. I have followed examples by adding to map eav xml file but still no luck.

**Config.xml option setting;**
`<options>
        <map_file>etc/ee-to-ee/1.14.2.4/map.xml</map_file>
        <eav_map_file>etc/ee-to-ee/map-eav.xml</eav_map_file>
</options>`

**Console Error**
`[2016-08-30 15:08:56][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
57% [================>-----------] Remaining Time: 1 sec
100% [============================] Remaining Time: 1 sec not meet expectation: enterprise_url_rewrite_redirect`

**Migrate log**

> [2016-08-30 15:08:56][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
> [2016-08-30 15:08:56][ERROR]: Source table structure does not meet expectation: enterprise_url_rewrite_redirect

**Comment by victor-v-rad** [comment]
Url rewrite step for EE does not use map files. Instead \Migration\Step\UrlRewrite\Version11300to2000::$structure
OR
\Migration\Step\UrlRewrite\Version11410to2000::$structure
is begin used on integrity check

**Comment by Orims14** [comment]
Thanks @victor-v-rad 
I added the missing fields to the \Migration\Step\UrlRewrite\Version11410to2000::$structure and it was fixed.
