### ISSUE TITLE
Multiple Store and Multi Language

### ISSUE THREAD

**Issue by aarondong2005** [magento/data-migration-tool#148]
For my 1.9.0.1. The default store language is English. Another is Chinese. After migration. My Chinese pages and block Chinese language become question marks "?????????". How do I fix it?

**Comment by victor-v-rad** [comment]
Probably the issue is duplicate of #18

**Comment by aarondong2005** [comment]
Thank you. I will try the solution.

**Comment by aarondong2005** [comment]
Well. I tried the https://github.com/magento/data-migration-tool/pull/109 and https://github.com/magento/data-migration-tool/pull/28. The Chinese still become ?????

**Comment by aarondong2005** [comment]
Finally. I fixed the issue by looking at this https://github.com/magento/data-migration-tool/issues/111

File: vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php > getResourceConfig()
 $config['initStatements'] = $destination[$destinationType]['initStatements']; 
 which should be
 $config['database']['initStatements'] = $destination[$destinationType]['initStatements']; 

And similar change for  vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php

**Comment by victor-v-rad** [comment]
Seems the issue is fixed. Closing it
