### ISSUE TITLE
problem to transfer method paiement

### ISSUE THREAD

**Issue by strauss69400** [magento/data-migration-tool#149]
hi,
i have an other problem about the transfer of my datas.
the payment method hasn't been transfered.
in my new site (magento2.1), in the zone "Payment Information", it is write :

"The order was placed using CHF.
is not available. You still can process offline actions."

wheras this order has been placed in CB.

**on magento 1.7.0.2**

![screenshot_4](https://cloud.githubusercontent.com/assets/8798254/18132294/8f857244-6f96-11e6-8996-7de72346faeb.png)

**on magento 2.1**

![screenshot_2](https://cloud.githubusercontent.com/assets/8798254/18132172/027a726e-6f96-11e6-869a-cf3d492d2ff0.png)

does anyone has had the problem??

**Comment by aarondong2005** [comment]
Same here. The transaction payment and shipping method detail were gone after migration

**Comment by victor-v-rad** [comment]
@strauss69400 @aarondong2005 
Supposedly 3-rd party shipping and payment methods what are not exist in Magento 2

**Comment by strauss69400** [comment]
ok,
so i installed my method payement, the information will appear??
it's a shame.it is just a block "information"

**Comment by victor-v-rad** [comment]
@strauss69400 @aarondong2005 
Most likely your issue because you use payment/shipping methods of 3-rd party extensions that do not exist in Magneto 2. Please install these extensions and see if it is solve your problem

**Comment by VignaPranav** [comment]
Hi @strauss69400 @aarondong2005
Once after installing the 3rd party extensions , has that problem been resolved?
Even I am facing this problem.

**Comment by strauss69400** [comment]
yes, i changed manually in database the name of payment method :)

**Comment by VignaPranav** [comment]
@strauss69400 
Sorry, I can't get you clearly. Could you explain me.
I am trying to install the 3rd party extension

**Comment by roma-glushko** [comment]
@victor-v-rad Hi, actually the same issue goes for the default Paypal payment methods. We are having this porting Magento Commerce 1.14.1.0. Here is the mapping that we need to perform (M1 -> M2):

- paypaluk_express -> paypal_express
- paypal_direct -> paypal_express_bml 

That'd be great to have out-of-box.
