### ISSUE TITLE
Product info not showing in single product page magento2 admin

### ISSUE THREAD

**Issue by kapilpatel** [magento/data-migration-tool#151]
Hello,

I have migrated database from 1.7 to 2.1 by using Uber theme data migration tool. I'm facing problem with products on admin as it have many custom attributes.

The problem is product title is showing in list but not showing on single page and other info too, also unable to edit products.

How can I solve this?

**Comment by victor-v-rad** [comment]
As far I understand Uber theme data migration tool is a compliantly different product then Data Migration Tool of Magento company. Thus you better get in touch with ubertheme.com
