### ISSUE TITLE
Notice: Undefined offset: 19 in on EAV Step

### ISSUE THREAD

**Issue by baltechies** [magento/data-migration-tool#152]
Magento1 version -> 1.9.2.2
Magento2 version -> 2.1.1
Data migration Tool -> 2.1.1
 its throwing an error on EAV step. error is
[Exception]                                                                  
  Notice: Undefined offset: 19 in /Users/balvinderSingh/Sites/comit211/vendor  
  /magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 248 

![screen shot 2016-09-06 at 1 21 26 pm](https://cloud.githubusercontent.com/assets/13519944/18267776/5ffbf5a0-743e-11e6-9ed4-9cd9de45faf5.png)

**Comment by victor-v-rad** [comment]
@baltechies 
It is hard to figure out what is wrong in your case
You could share your DB dump of the next Magento 1 tables:
eav_attribute_group
eav_attribute_set
eav_attribute
eav_entity_attribute
catalog_eav_attribute
customer_eav_attribute
eav_entity_type
You can send it through the email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it.

**Comment by baltechies** [comment]
@victor-v-rad 
I have sent these table through the email.
Also please note that when I migrated magento 1.9.2.2 to magento 2.0.9 then after migration, category_ids attributes was missed from attribute and attribute sets.

**Comment by victor-v-rad** [comment]
the only errors I got from your tables are
`[2016-09-06 13:12:14][WARNING]: Mismatch of data types. Source document: eav_attribute. Fields: default_value`
`[2016-09-06 13:12:14][WARNING]: Mismatch of data types. Destination document: eav_attribute. Fields: default_value`

please recheck your version of the tool and Magento

**Comment by baltechies** [comment]
Magento version is 2.1.1 and migration tool version is also 2.1.1

![screen shot 2016-09-06 at 7 46 20 pm](https://cloud.githubusercontent.com/assets/13519944/18277075/c70248ea-746a-11e6-8c71-532f1b94bed7.png)


Also I tried same magento 1.9.2.2 database with magento 2.0.9 and tool version was 2.0.7.
But in that case all is working fine except category_ids and quantity_and_stock_status attribute. After migration category_ids and quantity_and_stock_status was no more in backend.

**Comment by victor-v-rad** [comment]
Did you get those `[WARNING]: Mismatch of data types`?

**Comment by baltechies** [comment]
Yes. I get "[WARNING]: Mismatch of data types" on [stage: integrity check]. But its throwing an error on [stage: data migration].

**Comment by victor-v-rad** [comment]
Got the error you have )
You run the tool for the second time and forget to revert your M2 database to its initial state.

**Comment by baltechies** [comment]
I have tried it with new magento 2.1.1 setup as well. But I will try it again and let you know.

**Comment by baltechies** [comment]
@victor-v-rad
I have tried it on fresh magento 2.1.1 as well, but same error. Stuck on EAV step at 28%

**Comment by victor-v-rad** [comment]
@baltechies 
I have not manage to reproduce this issue. Please feel free to reopen it in case you found exact reason of its occurrence.

**Comment by SolsWebdesign** [comment]
Hi, is there a work around for this?

Magento1 version -> 1.8.1.0
Magento2 version -> 2.2.2
Data migration Tool -> 2.2.2
[2018-02-21 12:45:17][INFO][mode: data][stage: data migration][step: EAV Step]: started
28% [========>-------------------] Remaining Time: < 1 sec
[Exception]
  Notice: Undefined offset: 19 in /home/vpssolswebusr/scrittura.solsweb.nl/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 278
thank you

**Comment by jagejobs** [comment]
@SolsWebdesign 
Hi, I'm getting almost exact error message while running the migration tool
Notice: Undefined index:  in /home/vendor/magento/data-migration-tool/src/Migration/Ste
  p/Eav/Data.php on line 279

I think you have resolved issue by adding couple of if(isset()) to Data.php

where did you add it? before or after
  $record['entity_type_id'] = $this->mapEntityTypeIdsDestOldNew[$record['entity_type_id']];
Can you send the exact code?

Thanks

Jag

**Comment by jmonrove** [comment]
I'm getting the same error message

[Exception]                                                                                                                                           
  Notice: Undefined offset: 19 in /var/www/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 278

This is a fresh Magento 2, migrating from Magento 1.14.0.1 database.

Here's the full trace:

`bin/magento migrate:data -r -a -vvv vendor/magento/data-migration-tool/etc/commerce-to-commerce/1.14.0.1/config.xml

Reset the current position of migration to start from the beginning

[2019-03-26 21:02:01][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
[2019-03-26 21:02:08][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:08][INFO][mode: data][stage: integrity check][step: Custom Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:08][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:08][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:12][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: SalesOrder Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:13][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
[2019-03-26 21:02:18][INFO][mode: data][stage: data migration][step: EAV Step]: started
25% [=======>--------------------] Remaining Time: 3 secs
                                                                                                                                                        
  [Exception]                                                                                                                                           
  Notice: Undefined offset: 19 in /var/www/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 278  
                                                                                                                                                        

Exception trace:
 () at /var/www/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /var/www/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:278
 Migration\Step\Eav\Data->migrateAttributeSetsAndGroups() at /var/www/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:189
 Migration\Step\Eav\Data->perform() at /var/www/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:79
 Migration\Mode\AbstractMode->runStage() at /var/www/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:119
 Migration\Mode\Data->runData() at /var/www/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /var/www/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/magento/framework/Console/Cli.php:102
 Magento\Framework\Console\Cli->doRun() at /var/www/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/bin/magento:23

migrate:data [-r|--reset] [-a|--auto] [--] <config>
`

**Comment by pajtai** [comment]
I'm getting the same error too Magento 2.3.3

```
28% [========>-------------------] Remaining Time: < 1 sec
In ErrorHandler.php line 61:

  Notice: Undefined offset: 19 in /vagrant/httpdocs/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 279


migrate:data [-r|--reset] [-a|--auto] [--] <config>
```

**Comment by pajtai** [comment]
@victor-v-rad is there a work around? a bunch of people seem to be having this issue

**Comment by krearthur** [comment]
I'm getting the same error, also with v. 2.3.3 :/
