### ISSUE TITLE
Notice: Undefined offset: 564 in /vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

### ISSUE THREAD

**Issue by baltechies** [magento/data-migration-tool#153]
I am able to migrate data from magento 1 to magento 2.1 with data migration tool 2.1.1.
But I faced some issues, Like
1) products and categories are not showing on frontend.
2) In admin panel, category page (Product-> categories) throwing exception error. Error is
a:4:{i:0;s:139:"Notice: Undefined offset: 564 in [Magento_PATH]/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166";i:1;s:6828:"#0

**Comment by victor-v-rad** [comment]
Thank you for reporting the issue.
Internal tickets MAGETWO-58175 MAGETWO-58176 MAGETWO-58177 were created to solve it
