### ISSUE TITLE
Incompatibility in data. Source document: eav_attribute_group. Field: attribute_group_name

### ISSUE THREAD

**Issue by quienti** [magento/data-migration-tool#156]
Magento 1.9.2.2 to Magento 2.1.1

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/18520070/8e340584-7aa6-11e6-887d-2e47c9ce4d2c.jpg)

I don't know if this error is a bug, or I need to add anything in xml.
(I want ignore 'attribute set' because I don't need this in Magento 2.1.1)

After that, I have this :
`[Migration\Exception]
  Integrity Check failed
`

And any data aren't migrated, no customer, no order, etc...
Only migrate:settings work correctly

Thanks

**Comment by victor-v-rad** [comment]
you need to open admin panel of your Magento 1 store and fix mentioned Attribute Sets. Maybe attribute names (General, Design, Prices) were renamed. Revert its names back.

**Comment by quienti** [comment]
Nice, It works fine !

Thank you

**Comment by wakar** [comment]
I've only DB & not Magento admin panel while i've checked in the DB where all attribute groups(General, Design, Prices) are original.

So how can i fix it ?

It's urgent so please help me.

Thanks!!!
