### ISSUE TITLE
Exception Undefined index

### ISSUE THREAD

**Issue by gfxguru** [magento/data-migration-tool#158]
\vendor\magento\data-migration-tool\src\Migration\ResourceModel\Source.php on line 42

command:php magento migrate:settings "c:\www\domain.com\wwwroot\vendor\magento\data-migration-tool\etc\ce-to-ce\1.9.2.4\config.xml"

**Comment by victor-v-rad** [comment]
Hi @gfxguru 
check your config.xml . Probably the attribute 'user' is empty in <database> tag
