### ISSUE TITLE
Multi Website: little bug

### ISSUE THREAD

**Issue by quienti** [magento/data-migration-tool#160]
Hi,

I have a little problem , I have 2 web site, everything has been correctly migrated , but there is one place that has not created :

Core_webiste in database from magento 1.9.2.2
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/18552856/99ded2ca-7b5e-11e6-938f-8fe5b68f9eff.jpg)

Store website in database from Magento 2.1.1
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/18552887/b3d5dae8-7b5e-11e6-87fd-bcebbf707cfe.jpg)

It missing webiste 3, and only here ^^

If I created my website with a correct ID, all works fine !

So, just a little bug, maybe just with my database...

**Comment by victor-v-rad** [comment]
Hi @quienti 
Thank you for reporting this issue. I tried to reproduce it but without success. Feel free to reopen this issue in case you have exact steps to reproduce it.

**Comment by PascalBrouwers** [comment]
Hmm, I have this exact problem too. 4 websites in old magento, but only 1 shows up in magento 2.1.1

**Comment by PascalBrouwers** [comment]
Of course the real problem is this: 
<img width="732" alt="screen shot 2016-10-10 at 10 31 06" src="https://cloud.githubusercontent.com/assets/17834386/19230431/b502e170-8ed4-11e6-91ed-5256ff3d10bf.png">

How can the volume check not give an error when the is clearly a difference in volumes between websites?

**Comment by PascalBrouwers** [comment]
Hmm, I ran the migration for settings again with the --reset flag. Now it copied everything.

**Comment by PascalBrouwers** [comment]
Tried it again with a migration from 1.9.0.1 to 2.1.2 and still the same problem with missing websites. Running bin/magento migrate:settings with the flag --reset afterwards copies the websites.

**Comment by PascalBrouwers** [comment]
@victor-v-rad looked into this again. Using --reset flag does add the missing websites and they show up in Settings-> All Stores but I can't select them in Settings -> Configuration

**Comment by surendramishra999** [comment]
I got the same issue as @PascalBrouwers got. I think it occurs when website Ids are not in sequence. I have website with Id 0,1,5,6 and i got the same issue.
