### ISSUE TITLE
Settings migration mode: ignore all "advanced/modules_disable_output" keys

### ISSUE THREAD

**Issue by mzeis** [magento/data-migration-tool#161]
The `settings.xml.dist` files tell the migration tool to ignore the `advanced/modules_disable_output` settings by defining the exact name for each core module:

    <settings xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../settings.xsd">
        <key>
            <ignore>
                <path>advanced/modules_disable_output/Mage_Connect</path>
            </ignore>
            <ignore>
                <path>advanced/modules_disable_output/Mage_Contacts</path>
            </ignore>
             ...

As these entries won't be used in Magento 2 anyways, developers would have to add the ignore commands for the `advanced/modules_disable_output` entries of extensions in their store manually or live with clutter in the M2 database.

You can help developers if you add a wildcard entry which should be possible according to the [documentation](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-internal-spec.html) ("Wildcards can be used in this node.").

**Comment by victor-v-rad** [comment]
Hi @mzeis 
Thank you for reporting this issue. Internal ticket to solve it MAGETWO-58706

**Comment by victor-v-rad** [comment]
The bug was fixed in the recent release. Please try it out. Feel free to reopen the issue if it is still relevant.
