### ISSUE TITLE
After migration increment ID for all stores are the same

### ISSUE THREAD

**Issue by Got-iT-Services-Inc** [magento/data-migration-tool#163]
Magento/migration tool version 2.1.1. After migration all increment id's across all stores are identical. Stores 2,3 and 4 took on the increment ID for store 1. This includes invoice and credit memo increment ID's as well.

it also looks like the SalesIncrement test only tests the first store profile, and does not iterate through all store profiles in the database

**Comment by victor-v-rad** [comment]
Hi @Got-iT-Services-Inc 
According to the [documentation](http://devdocs.magento.com/guides/v2.1/migration/migration-migrate-additional.html) there are changes in policy of forming increment ID in Magento 2. As far I know in Magento 2 next increment ID is based not on "store view" but "store" (former name "store group"). That is why you got such behavior. If you feel that it is a bug I would recommend post an issue in [Magento 2 GitHub](https://github.com/magento/magento2/issues)

**Comment by Got-iT-Services-Inc** [comment]
Since we're migrating from Magento1 to Magneto2, shouldn't the migration tool take that into account and take the current increment ID's from mangeto1 as magento1 uses them, and migrate them to the correct way magento2 uses it? I don't think this is a bug in magento2, but more of a bug in the migration from magento1 to magento2

**Comment by victor-v-rad** [comment]
The tool does not change migrated order/invoice... IDs from Magento 1, does it? But the way how new ID creates in Magento 2 is changed. Now it is based on Store, not on Store View.

> shouldn't the migration tool take that into account and take the current increment ID's from mangeto1 as magento1 uses them

Please make your proposal how exactly the tool can handle this

**Comment by ilol** [comment]
Registered as a bug: [MAGETWO-59523](https://jira.corp.magento.com/browse/MAGETWO-59523)

**Comment by Got-iT-Services-Inc** [comment]
I believe it's just a matter of having the tool look at the individual stores, I will check the code out later this week

**Comment by victor-v-rad** [comment]
> Now it is based on Store, not on Store View.

To be more clear. For new orders/invoices/... Magento 2 gets ID of default "store view" of a "store" 
In Magento 1 you have
Store 1 - Store View 1 (default) = order ID 10000001
Store 1 - Store View 2                = order ID 20000001
Store 2 - Store View 3 (default)  = order ID 30000001
Store 2 - Store View 4                = order ID 40000001

In Magento 2 for new orders you will get
Store 1 - Store View 1 (default) = order ID 10000001
Store 1 - Store View 2                = order ID 10000002
Store 2 - Store View 3 (default)  = order ID 30000001
Store 2 - Store View 4                = order ID 30000002

**Comment by victor-v-rad** [comment]
Prefix issue was fixed in Magento 2 https://github.com/magento/magento2/issues/14063 Now prefix of increment id, like in Magento 1, depends on store view id where order was placed
Store 1 - Store View 1 (default) = order ID 10000001
Store 1 - Store View 2 = order ID 20000001
Store 2 - Store View 3 (default) = order ID 30000001
Store 2 - Store View 4 = order ID 40000001

BUT in Magento 2 increment id has store id + **9 digits**, in according to \Magento\SalesSequence\Model\Sequence::DEFAULT_PATTERN
whereas Magento 1 increment id has store id + **8 digits**
