### ISSUE TITLE
url_redirect entries with request_path truncated at 255 char limit cause failure in Url Redirect Step

### ISSUE THREAD

**Issue by alessandrozucca** [magento/data-migration-tool#164]
I'm migrating data from M1 EE to M2 EE 2.1.1 for a customer and this customer has lots of categories very deeply nested.

This resulted on request_path on the M1 database that should be longer than 255 chars but they get truncated on INSERT.

This has caused an error `URL_REWRITE_REQUEST_PATH_STORE_ID` on the Url Rewrite Step.

My workaround for this is has been to remove the index `URL_REWRITE_REQUEST_PATH_STORE_ID` on the M2 database before doing the migration, then run the migration, resolve/remove the duplicate with custom sql, re-add the index `URL_REWRITE_REQUEST_PATH_STORE_ID`

**Comment by victor-v-rad** [comment]
Thank you for posting the issue. Internal ticket MAGETWO-59524 was created to solve it.

**Comment by fballiano** [comment]
Hi @victor-v-rad, was this bug solved? It seems I still experience it. Thanks!

**Comment by victor-v-rad** [comment]
Hi @fballiano 
Not yet

**Comment by fballiano** [comment]
it's more than 1 year :-D

**Comment by alessandrozucca** [comment]
It has been so long that since then I've changed job and even changed programming language (Golang)

**Comment by victor-v-rad** [comment]
The tool is not really permitted to alter existing tables of M2 in order to migrate data. But workaround (remove index, extend size for request_path field, add removed index) can be applied to migrate a store
