### ISSUE TITLE
Destination Fields Missing - map not being read appropriately?

### ISSUE THREAD

**Issue by BtotheT** [magento/data-migration-tool#166]
While migrating SalesOrder:

Destination fields are missing. Document: eav_attribute. Fields: reward_points_balance_refunded,reward_salesrule_points

EE 1.11.0.0 to 2.0.8

In  map-sales.xml:
 <destination>
        <field_rules>
          <ignore>
            <field>sales_order.reward_points_balance_refunded</field>
          </ignore>
          <ignore>
            <field>sales_order.reward_salesrule_points</field>

Why are these still trying to be pulled? I can set the <ignore> field to eav_attribute.reward_points_balance_refunded and eav_attribute.reward_salesrule_points but it does the same thing.

**Comment by ygrigoriev** [comment]
Hello @BtotheT,
These EAV attributes are installed by Reward module which is a part of Enterprise Edition.
They should be present in `eav_attribute` table during migration process.
If there are no such attributes after Magento EE installation, try to reinstall Magento.

**Comment by ilol** [comment]
Or use <ingnore> in Migration Tool config files to skip EE attributes.

**Comment by BtotheT** [comment]
Seems on initial install of 2.0.0 (original) for some reason these two did not get transferred. I installed a clean 2.0.9 copy and was able to just insert these into eav_attribute table and import.

Thank you!

**Comment by ilol** [comment]
Will test with Android.
Please clarify Android version and device

**Comment by ilol** [comment]
Why 2.0.9? Not latest 2.1.x?

**Comment by BtotheT** [comment]
We are not using 2.1.x - we have a lot of customization to 2.0.x and are still working through the issues at hand here before we try to update to the 2.1 branch.
