### ISSUE TITLE
Integrity constraint violation: 1048 Column 'store_id' cannot be null

### ISSUE THREAD

**Issue by DreLincolin** [magento/data-migration-tool#167]
[Zend_Db_Statement_Exception]  
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'store_id' cannot be null, query was: INSERT INTO `url_rewrite` (`entity_type`,`entity_id`,`request_path`,`target_path`,`store_id`,`is_autogene  
  rated`) VALUES (?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `request_path` = VALUES(`request_path`)

Thing about it is, that i dont have any records in core_url_rewrite with store_id NULL -> Tripple checked

**Comment by victor-v-rad** [comment]
Hi @DreLincolin 
I see you have reported many issues recently. Are they related to one DB of Magento 1 you trying to migrate? If so I would be glad to get it and try to migrate to reveal them and fix. You can send the db (remove all the passwords before) through the email (find it in my profile https://github.com/victor-v-rad)
