### ISSUE TITLE
Customer_entity_address try insert with missing mandatory fields

### ISSUE THREAD

**Issue by DreLincolin** [magento/data-migration-tool#169]
This issue has been encountered on every step basically, there seems no to be any database mapping classes that would check mandatory fields.
Its behaviour seems to be more lie a database table migration layer. All errors thrown come directly from SQL and at a bulk insert gives irrelevant error reporting, miss leading people to search the problem somewhere else, or just leaving with no clue.

First step in Data Migration guide should be stated that <bulk_size> in config.xml should be 1
like this <bulk_size>1</bulk_size>
And as default, since this is the only way you will get relevant error reporting on what is wrong at a precise record, since we are talking about moving very important data in big amounts (hundred of thousands of rows) and there is no physical way possible to pre check all that data by hand before starting the migration process, that all fields mandatory in the new database layout to be present.

Basically this issue can be solved either by removing all records with missing mandatory fields, like city, in a bulk delete query.
Or either you can just change by hand the layout of the table in the new database, to set the fields as NULL, or give them a default value if NULL.

When the bulk preset is set to 0 or any value than 1 .. will generate an error like : 
[PDOException]  
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens 

if bulk size is 1 then it will give you a precise error that will lead you to the problem

[PDOException]  
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'city' cannot be null

Hope this to be useful for anyone like it would have been for me
Hope this gets considered and fixed or at least stated as a recomendation to others

**Comment by victor-v-rad** [comment]
Hi @DreLincolin 
I see you have reported many issues recently. Are they related to one DB of Magento 1 you trying to migrate? If so I would be glad to get it and try to migrate to reveal them and fix. You can send the db (remove all the passwords before) through the email (find it in my profile https://github.com/victor-v-rad)
