### ISSUE TITLE
Data Migration for 2.1.2  Missing

### ISSUE THREAD

**Issue by sajidunnar** [magento/data-migration-tool#172]
I am installing data migration tool for 2.1.2 but it seems its not yet release ? any plans or schedules

` composer require magento/data-migration-tool:2.1.2
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                                 Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/data-migration-tool 2.1.2 exists as magento/data-migration-tool[2.0.0, 2.0.2, 2.0.5, 2.0.7, 2.1.0, 2.1.1, 1.0.0-beta] but these are rejected by your constraint.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by victor-v-rad** [comment]
Hi @sajidunnar 
It  will be available in the nearest future.

**Comment by victor-v-rad** [comment]
You can try it now

**Comment by sajidunnar** [comment]
Thanks everything worked
