### ISSUE TITLE
Products not showing in FrontEnd Category

### ISSUE THREAD

**Issue by DreLincolin** [magento/data-migration-tool#175]
After migration products not showing in category view -> frontEnd
In Back End everything seems fine:
* Products Visible in Category And Serch
* Products in Stock
* Products Stock Quantity Set
* Products Website View Set
* Category Products are being diplayed
* Products Categories also Set

By using Category Model Factory -> getProductCollection() works fine

After doing some debugging found what looks to me the issue in the code

Magento\Catalog\Block\Product\ListProduct being used

_getProductCollection() Method

seems to be a logical error

            if ($this->getShowRootCategory()) {
                $this->setCategoryId($this->_storeManager->getStore()->getRootCategoryId());
            }
This is not set as default -> and it should not if you dont want to display the root category in frontEnd

but along the code the curect category ID is not fetched at all

so as result $this->getCategoryId() is NULL
so eventually $this->_productCollection = $layer->getProductCollection(); is Also NULL

which as result in list.phtml

on if (!$_productCollection->count())
display's echo __('We can\'t find products matching the selection.')

If this is not an actual issue -> how to solve this ?

Many thanks

**Comment by DreLincolin** [comment]
Was able to force show the Products List Grid in the Category View
Had to hijack the method and change 2 lines

after 

        if ($this->getShowRootCategory()) {
            $this->setCategoryId($this->_storeManager->getStore()->getRootCategoryId());
        }

Add

            $this->setCategoryId($layer->getCurrentCategory()->getId());

and change

          $this->_productCollection = $layer->getProductCollection();
to

           $this->_productCollection = $category->getProductCollection();

![screen shot 2016-10-24 at 17 26 17](https://cloud.githubusercontent.com/assets/16080023/19654329/bb476628-9a0f-11e6-8c4f-ac43114005cb.png)

**Comment by DreLincolin** [comment]
Also a strange thing is that by dumping the $layer itself you get this

![screen shot 2016-10-24 at 17 24 15](https://cloud.githubusercontent.com/assets/16080023/19654368/d62a40fa-9a0f-11e6-9f0d-4d38b5d85c20.png)

**Comment by DreLincolin** [comment]
If anyone needs here is a generated Patch

[ShowProductsinCategoryView.patch.txt](https://github.com/magento/data-migration-tool/files/548405/ShowProductsinCategoryView.patch.txt)

**Comment by DreLincolin** [comment]
BTW my 2.1.2 version is an upgrade from 2.1.1
but i got the same issue before update to 2.1.2

**Comment by DreLincolin** [comment]
Closed since this issue is triggered by Cascade delete of ROOT category or Default Store

**Comment by Anees-Ahmad** [comment]
I have face the same issue and when i put above code it stops layered navigation working.So best solution is to copy your magento 1.9 Default root category(Same Name) into Magento 2 Manually.Both name should be same.
