### ISSUE TITLE
Ignored Fields Mysql Insert NULL

### ISSUE THREAD

**Issue by DreLincolin** [magento/data-migration-tool#176]
On any mapping with ignore fields list
Fields are being still inserted with NULL value
Where fields are SET as NOT NULL

This fields should be either totally ignored or inserted as SET DEFAULT

Examples:

catalog_eav_attribute.is_used_in_grid
catalog_eav_attribute.is_visible_in_grid
catalog_eav_attribute.is_filterable_in_grid
catalog_eav_attribute.search_weight

customer_eav_attribute.is_used_in_grid
customer_eav_attribute.is_visible_in_grid
customer_eav_attribute.is_filterable_in_grid
customer_eav_attribute.is_searchable_in_grid

eav_attribute_group.attribute_group_code

Side Note
Also on migration process missing values should be replaced to anything else than NULL
Example is customer_address_entity.city that might be missing but  is set NOT NULL in M2

According to Mysql Documentation it's ambiguous to insert a null value into a NOT NULL Field
As stated either don't specify any value or USE DEFAULT statement instead

All this cause errors and irevertable damage to the new migrated database

For people who encounter errors like:
Integrity constraint violation: 1048 Column 'is_required_in_admin_store' cannot be null
Integrity constraint violation: 1048 Column 'attribute_group_code' cannot be null
Integrity constraint violation: 1048 Column 'is_visible_in_grid' cannot be null
Integrity constraint violation: 1048 Column 'is_filterable_in_grid' cannot be null
Integrity constraint violation: 1048 Column 'search_weight' cannot be null
Integrity constraint violation: 1048 Column 'is_used_in_grid' cannot be null
Integrity constraint violation: 1048 Column 'city' cannot be null

Just Set those Fields as NULL
ALTER TABLE <**DATABASE**>.`catalog_eav_attribute` 
CHANGE COLUMN `is_required_in_admin_store` `is_required_in_admin_store` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Required In Admin Store' ,
CHANGE COLUMN `is_used_in_grid` `is_used_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Used in Grid' ,
CHANGE COLUMN `is_visible_in_grid` `is_visible_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Visible in Grid' ,
CHANGE COLUMN `is_filterable_in_grid` `is_filterable_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Filterable in Grid' ,
CHANGE COLUMN `search_weight` `search_weight` FLOAT NULL DEFAULT '1' COMMENT 'Search Weight' ;

ALTER TABLE <**DATABASE**>.`customer_eav_attribute` 
CHANGE COLUMN `is_used_in_grid` `is_used_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Used in Grid' ,
CHANGE COLUMN `is_visible_in_grid` `is_visible_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Visible in Grid' ,
CHANGE COLUMN `is_filterable_in_grid` `is_filterable_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Filterable in Grid' ,
CHANGE COLUMN `is_searchable_in_grid` `is_searchable_in_grid` SMALLINT(5) UNSIGNED NULL DEFAULT '0' COMMENT 'Is Searchable in Grid' ;

ALTER TABLE <**DATABASE**>.`eav_attribute_group` 
CHANGE COLUMN `attribute_group_code` `attribute_group_code` VARCHAR(255) NULL DEFAULT 'empty' COMMENT 'Attribute Group Code' ;

ALTER TABLE <**DATABASE**>.`customer_address_entity` 
CHANGE COLUMN `city` `city` VARCHAR(255) NULL DEFAULT '**<CITY>**' COMMENT 'City' ,
CHANGE COLUMN `country_id` `country_id` VARCHAR(255) NULL COMMENT 'Country' ,
CHANGE COLUMN `firstname` `firstname` VARCHAR(255) NULL COMMENT 'First Name' ,
CHANGE COLUMN `lastname` `lastname` VARCHAR(255) NULL COMMENT 'Last Name' ,
CHANGE COLUMN `region` `region` VARCHAR(255) NULL COMMENT 'State/Province' ,
CHANGE COLUMN `street` `street` TEXT NULL COMMENT 'Street Address' ,
CHANGE COLUMN `telephone` `telephone` VARCHAR(255) NULL COMMENT 'Phone Number' ;

Maybe not the best solution but works for me, at least it lets me pass over this errors on specific steps

Cheers

**Comment by petrich** [comment]
Hi
we running on the same issue while ```Delta Import``` (Full Import works fine).

In our case the error is for : ```customer_address_entity``` 
```Integrity constraint violation: 1048 Column 'telephone' cannot be null```

Changing the column will workaround it:
```sql
ALTER TABLE <DATABASE>.CHANGE COLUMN telephone telephone VARCHAR(255) NULL COMMENT 'Phone Number' ;
```

But Is it possible to declare a ```<transform></transform>``` Handler in ```map-eav.xml``` for this issue? 
And if... how?
 
Thank you in advance for any help.

**Comment by victor-v-rad** [comment]
Hi @petrich 

We have registered internal MAGETWO-62034 which should solve the problem you encountered. But it has not completed yet. 

>But Is it possible to declare a <transform></transform> Handler in map-eav.xml for this issue?
The bug hides in the Customer Attributes Step. It has its own map-customer.xml.dist file with customer_address_entity.telephone field marked as ignored. Give it a try with `<transform></transform>` tag there. But MAGETWO-62034 fix with different approach

**Comment by petrich** [comment]
Thank you for your answer. This helps me. I'll try it and if success i do report here.

**Comment by Morgy93** [comment]
I just ran into this issue.
M 1.9.4.5 to M 2.4.2-p1, Migration Tool v2.4.2

But as mentioned in https://github.com/magento/data-migration-tool/issues/176#issuecomment-282471078 I just allowed NULL on telephone. 🤷
