### ISSUE TITLE
Skipping Attribute set deletion

### ISSUE THREAD

**Issue by maderlock** [magento/data-migration-tool#179]
I've looked for documentation and through the code, but I cannot figure out how to skip the deletion of existing Magento 2 attribute sets. I already have created the relevant attributes, groups and sets and just want to map them. Instead I get an error:

`Integrity constraint violation: 1062 Duplicate entry '1-Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'`

And the eav attribute set table is emptied. Is it possible to just map M1 sets and groups to each other? Or even just skip this step all together?

I've tried adding the following to the destination part of map.xml:

```
             <ignore>
                <document>eav_attribute_set</document>
            </ignore>
            <ignore>
                <document>eav_attribute_group</document>
            </ignore>
```

**Comment by maderlock** [comment]
It looks like, having created all my attributes, groups and sets in Magento 2, I should skip the EAV data step? Will I still be able to map the old attributes to the new?

**Comment by maderlock** [comment]
Wait... where is the step where products and categories are copied over?! That's all I want and I cannot find it...

Oh my god, have I wasted all this time? Does this tool not do the migration of products and categories?

**Comment by victor-v-rad** [comment]
As far I know attribute sets and groups which are created during installation of Magento 2 should be preserved by migration tool after migration from Magento 1. Why not to create attribute sets and groups in Magento 2 after migration.
