### ISSUE TITLE
Migrate from Enterprise M1 to Community M2

### ISSUE THREAD

**Issue by milanstojanov** [magento/data-migration-tool#185]
Hi, 

The tool allows you to migrate from:

ce-to-ce
ce-to-ee
ee-to-ee

But a client who runs on M1 EE wants to migrate to M2 CE. How should we approach this? 

Would it be easier to convert:

1. M1 EE -> M1 CE (somehow) and then migrate to M2 (CE)
2. M1 EE -> M2 EE and then convert to M2 (CE) (somehow)
3. Any other idea?

Thanks in advance,
Milan

**Comment by victor-v-rad** [comment]
> How should we approach this?

Best approach would be to try to migrate to M2 CE then understand that it is really hard then convince the client to use M2 EE.

**Comment by milanstojanov** [comment]
If you don't mind me asking: why is it that hard? Did you try it? 

I was thinking about migrating M1 EE -> M1 CE and then to M2 CE, since this is working just fine. But I wanted to check if there's another (better) way of doing this.
