### ISSUE TITLE
unable to place order

### ISSUE THREAD

**Issue by strauss69400** [magento/data-migration-tool#186]
Hi,

I have just migrated from a magento 1.7.0.2 to a magento 2.1.Everything went well.

but i have a problem to place an order.

with new account, all it works but with the old account, i get this error when i trying to place an order :

"unable to place order.please try again later".

during the migration, i only use this commande : bin/magento migrate:data.

I hope you can help me.
thanks

**Comment by victor-v-rad** [comment]
See in logs there should be more informative error. Or put your site in developer mode to see full error with trace in browser

**Comment by strauss69400** [comment]
I have nothing to find particular in the logs but with Firebug , it saw that I had a 400 error on this page: "rest / en / V1 / carts / mine / payment-information".
i don't know why

**Comment by victor-v-rad** [comment]
maybe you use a payment method which do not exist in Magento 2

**Comment by strauss69400** [comment]
my payment method exist only in magento2.with certain account, it works.
it 's very strange.
i can this log :  

"#0 /home/dg-cm/www/website/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(17857, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))#1 /home/dg-cm/www/website/var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)#2 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(17857, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))#3 /home/dg-cm/www/website/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)#4 /home/dg-cm/www/website/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()#5 /home/dg-cm/www/website/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))#6 /home/dg-cm/www/website/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))#7 /home/dg-cm/www/website/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()#8 /home/dg-cm/www/website/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)#9 /home/dg-cm/www/website/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()#10 /home/dg-cm/www/website/index.php(43): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))#11 {main}"
