### ISSUE TITLE
«URL key for specified store already exists» after migration from Magento 1.x

### ISSUE THREAD

**Issue by xiaodonglv** [magento/data-migration-tool#190]
Hi

I migrated data from 1.x to 2.x with this tool and almost things were good.
But when I tried to change a category, it said error "URL key for specified store already exists" and data was not saved. It happened for only some categories couldn't be saved, not for all categories.
To solve the problem, I truncated table **url_rewrite** and run a mage2 command **bin/magento indexer:reindex**, but the issue was not solved yet.

Any helps?

**Comment by victor-v-rad** [comment]
Hi

Please look at this issue #133 It could help to solve your one

**Comment by xiaodonglv** [comment]
Thanks, but not working for me. I turned off the option "Create Permanent Redirect for old URL" in configuration page, and removed all attribute of a category, and then tried to save it again. But same issue happened.

**Comment by victor-v-rad** [comment]
As usual in case when we cannot identify the cause of an issue we recommend send us DB (cleaned from passwords) and we try to migrate and reproduce the issue. You can send the db through the email (find it in my profile https://github.com/victor-v-rad)
