### ISSUE TITLE
Version compatible?

### ISSUE THREAD

**Issue by andidhouse** [magento/data-migration-tool#192]
Can someone pls let us know which latest magento2 version is supported by the migration tool? We could not find any info here?

Can you guys pls point us to the page where the info is shown?

Is 2.1.2 supported?

Thanks!

**Comment by victor-v-rad** [comment]
Here
https://github.com/magento/data-migration-tool/releases
You can find the statement "Data Migration Tool 2.1.2 works with Magento 2.1.2"

**Comment by andidhouse** [comment]
Thanks @victor-v-rad
