### ISSUE TITLE
Debug migration error 1.9.2.4 > 2.1.2  -  "Notice: Undefined offset: 19"

### ISSUE THREAD

**Issue by magenx** [magento/data-migration-tool#193]
```
[2016-12-01 11:38:15][INFO][mode: data][stage: data migration][step: EAV Step]: started
28% [========>-------------------] Remaining Time: 1 sec

[Exception]                                                                                                                                                       
  Notice: Undefined offset: 19 in /home/magento/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line  
   248
```

what exactly means this error and how to properly debug it?

some shops migrate after you remove/correct attributes and attribute sets,
but others just stuck with this error.

new destination database from dump after every change in source db.

**Comment by victor-v-rad** [comment]
Current behavior of the EAV step is to preserve Magento 2 EAV structure after migration.
The data from table eav_entity_type is involved in your error. In most cases the data is equal in Magento 1 and Magento 2. Otherwise $this->mapEntityTypeIdsDestOldNew will contain differeces of IDs
