### ISSUE TITLE
permission_block and permission_variable not ignored for all versions

### ISSUE THREAD

**Issue by cykirsch** [magento/data-migration-tool#194]
I'm upgrading from 1.7.0.2. My "source documents not mapped" includes permission_block and permission_variable. I see that these are ignored for several versions but not mine:

https://github.com/magento/data-migration-tool/search?utf8=%E2%9C%93&q=permission_block

Looks like they were created in the Mage_Admin upgrade during the SUPEE-6788 patch. For my own purposes, I'll just add the `<ignore>` myself, but I'm guessing the ignores should be added to the repo to prevent confusion for others that installed the patch.

**Comment by victor-v-rad** [comment]
Thank you for posting this issue. Internal ticket to fix it MAGETWO-61835

**Comment by hostep** [comment]
Just noticed this as well (with version 1.9.1.0 in our case), the mapping should be based on the specific Magento versions where all official released SUPEE patches have been applied to.
