### ISSUE TITLE
Varchar handling

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#195]
Hi,

\Magento\Framework\DB\Ddl\Table::TYPE_VARCHAR does not exist.

When migrating m1 to m2, what is the method you are supposed to use? Use TYPE_TEXT? Seems wasteful of DB Space

**Comment by victor-v-rad** [comment]
In magento 2 \Magento\Framework\DB\Ddl\Table::TYPE_TEXT with limitation (e.g. 255) will be transformed to varchar type

**Comment by craigcarnell** [comment]
@victor-v-rad thanks

**Comment by craigcarnell** [comment]
@viktym Hi Victor, this does not appear to be the case at all.

Here is a module we have installed:

```
$table = $installer->getConnection()->newTable(
            $installer->getTable('mst_search_index')
        )->addColumn(
            'index_id',
            Table::TYPE_INTEGER,
            null,
            ['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
            'Index Id'
        )->addColumn(
            'code',
            Table::TYPE_TEXT,
            255,
            ['nullable' => false],
            'Index Code'
```

On checking my database, the column code is created with a TEXT field, not a VARCHAR with 255 length. With the TEXT field also no length is specified.

This is mysql 5.7.
