### ISSUE TITLE
button "capture" disappeared for invoice

### ISSUE THREAD

**Issue by strauss69400** [magento/data-migration-tool#198]
hi,
I made a migration to my new site a fortnight ago.
For now everything is good except for pending invoice.
For the invoices coming from the new site, no problem on the other hand for that of the old site, the button "capture" has disappeared.
So I do not fully validate my orders.
I need to capture payment for pending bills.
What can I do to make this button appear?

thanks for you hep

**Comment by victor-v-rad** [comment]
@strauss69400 
It could be in case when a payment method was exist in Magento 1 but no longer in Magento 2

**Comment by strauss69400** [comment]
yes exactly.
but is there a solution for resolve this problem?

**Comment by strauss69400** [comment]
i solved my problem in updating directly the method in phpmyadmin in the table 'sales_order_payement'
