### ISSUE TITLE
Magento 2 Custom Customer Attribute Save Data and edit data, i have problem

### ISSUE THREAD

**Issue by danielruedaa** [magento/data-migration-tool#200]
I create a customer module this module working good , when I migrate data  mangento 1.x to magento 2.x wiht migration tool and i wish crete a new customer don’t save data or edit any customer don’t show data

**Comment by danielruedaa** [comment]
![save](https://cloud.githubusercontent.com/assets/22922863/20941864/7a9399e8-bbc6-11e6-8748-75ba03521530.png)

image this my problem

**Comment by victor-v-rad** [comment]
Hi @danielruedaa I have found that the issue is related to custom attributes which are required. Seems it is reproducible on clean Magento 2. So the bug is in Magento 2 and not in Data Migration Tool

**Comment by danielruedaa** [comment]
tell me how make to revise in magento 2 this problem
first recomendation to begin

**Comment by victor-v-rad** [comment]
Probably it is known issue in [Magento 2 GitHub](https://github.com/magento/magento2/issues) . Try to find it there.
