### ISSUE TITLE
[Exception] Notice: Undefined index: entity_type_table (delta mode)

### ISSUE THREAD

**Issue by harimayco** [magento/data-migration-tool#203]
I successfully ran migration from magento 1.9.2.0 to magento 2.1.3 with data migration tool 2.1.2 which is compatible with 2.1.3 as you said in another issue   #202 .
but when try to run the delta mode it returns me the following error.
[Exception] Notice: Undefined index: entity_type_table
![delta error](https://screenshot.net/l10vmuz.jpg)

**Comment by harimayco** [comment]
I have updated data migration tool to version 2.1.3 but still facing this issue.
any help ? :sob:

**Comment by victor-v-rad** [comment]
Hi @harimayco 

I suppose your table eav_entity_store has references to eav_entity_type records which are not among the next entity types (order, invoice, creditmemo, shipment, rma_item). 
An internal ticket MAGETWO-62588 was created to investigate your issue.

**Comment by victor-v-rad** [comment]
Try this [fix](https://github.com/magento-nord/data-migration-tool/commit/bc2e2838a36589a85bdc904ad2d255f622526f0c)

**Comment by harimayco** [comment]
the fix works.
Thank you. (y)
