### ISSUE TITLE
FK_CATALOG_COMPARE_ITEM_CUSTOMER_ID_CUSTOMER_ENTITY_ENTITY_ID constraint fails

### ISSUE THREAD

**Issue by gputignano** [magento/data-migration-tool#208]
When I try to migrate data from magento v1.9.3.1 to magento v2.1.3 usind Migration Tool v2.1.3 I get this error message:
`[0;31m[2016-12-21 16:00:31][ERROR]: Foreign key (FK_CATALOG_COMPARE_ITEM_CUSTOMER_ID_CUSTOMER_ENTITY_ENTITY_ID) constraint fails. Orphan records id: 0 from `catalog_compare_item`.`customer_id` has no referenced records in `customer_entity`[0m`

This depends on a missing record in customer_entity table. The missing record, i think is for guest visitor with customer_id=0.

If I add this record with customer_id=0 it works. How can I solve without add manually this record?

**Comment by victor-v-rad** [comment]
you can 
- remove this step from your config.xml
- remove record in catalog_compare_item

**Comment by gputignano** [comment]
I resolved adding a new record with customer_id set to 0 in customer_entity table.
Many thanks.
