### ISSUE TITLE
Notice: Undefined offset: 1 in /var/www/html/magento213/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 266

### ISSUE THREAD

**Issue by hardiklinksture** [magento/data-migration-tool#209]
I got below error.

Notice: Undefined offset: 1 in /var/www/html/magento213/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 266

Magento migration 1.6.1.0 to 2.1.3

**Comment by victor-v-rad** [comment]
Hi @hardiklinksture 

If you use Data Migration Tool 2.1.3 then you should get an error about "Orphan records" likewise in #208 
Is that the [line 266](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Eav/Data.php#L266) are you talking about?

**Comment by hardiklinksture** [comment]
Yes 
when i try today again then found new error 
Run below command
sudo php bin/magento migrate:data -r --reset /var/www/html/magento213/vendor/magento/data-migration-tool/etc/ce-to-ce/1.6.1.0/config.xml
And throw below error

[PDOException]                                                                                                                                          
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

I migration multi store

**Comment by victor-v-rad** [comment]
It is because you did not clean your DB of Magento 2 after the second attempt of migration.

**Comment by hardiklinksture** [comment]
I try to fresh install magento 2 and start again then above error is solved 
Also i set below configuration
max_allowed_packet	= 999999M
But below still below error
SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes

**Comment by hardiklinksture** [comment]
After migration i showing the products on admin side
But **Attribute Set** is  Migration_Default instead of Default 
Also my all attribute sets is changed to Migration_****

**Comment by dfelton** [comment]
@hardiklinksture The migration tool does not perform a **merge** of the eav attribute set from the source database to the destination database, but instead performs a **copy** of the original attribute sets into the destination database. 

They get migrated over with "Migration_" prefix, because that is what you have configured in your `eav_map_file`. ("Migration_" is the default prefix that comes with the tool).
