### ISSUE TITLE
PHP Fatal error:  Redefinition of parameter $logger in src/Migration/Step/ConfigurablePrices/Volume.php on line 45

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#21]
Nice jobs guys, duplicate param in constructor, logger is there twice (PS that is sarcasm!)

PHP Fatal error:  Redefinition of parameter $logger in /Users/ccarnell/Sites/xxx/vendor/magento/data-migration-tool-ee/src/Migration/Step/ConfigurablePrices/Volume.php on line 45

```
public function __construct(
        Logger $logger,
        ResourceModel\Source $source,
        ResourceModel\Destination $destination,
        ProgressBar\LogLevelProcessor $progressBar,
        Helper $helper,
        Logger $logger
    )
```

I would post this in the EE repo, but since no one ever replies.. Same issue on CE anyway

**Comment by codigoaberto** [comment]
Change it to 

public function __construct(
        Logger $logger,
        ResourceModel\Source $source,
        ResourceModel\Destination $destination,
        ProgressBar\LogLevelProcessor $progressBar,
        Helper $helper
    )

**Comment by ilol** [comment]
@craigcarnell  does it  work for you?

**Comment by craigcarnell** [comment]
@ilol It worked for me, I already made that change a while ago (i've had to edit a few things to get it to work)
