### ISSUE TITLE
Invalid parameter number

### ISSUE THREAD

**Issue by gputignano** [magento/data-migration-tool#210]
After I removed all integrity check validation fails in my source db I get no errors about integrity but in Customer Attributes Step I get this message:
[PDOException]
`SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens.`
I tried from a magento1 v1.9.3.1 to a fresh magento2 v2.1.3 installation.
![invalidparameter](https://cloud.githubusercontent.com/assets/77434/21527807/24de645a-cd2e-11e6-96f1-e1d17b865416.png)

**Comment by victor-v-rad** [comment]
Hi @gputignano 

No need to run reindex after migration of settings. It might have caused the error "Invalid parameter number" you have. Also run migration of data with -vvv parameter it will show error with backtrace

**Comment by gputignano** [comment]
I've tried again with a fresh magento2 version without reindexing after migration of settings but I get the same error. I added -vvv parameter to show error with backtrace as you can see in the attached image.
![invalidparameter](https://cloud.githubusercontent.com/assets/77434/21548701/26add6b0-cdee-11e6-86bc-52ac2a873bcf.png)

**Comment by Yogesh7989** [comment]
Hello ,

@victor-v-rad is there any solution for this issue ? I am also facing same issue. 

Thanks
Yogesh

**Comment by gputignano** [comment]
I tried hundreds of times installing a fresh copy of magento v2.1.3 but at this point I get always the same error. I can send you (@victor-v-rad) the copy of database to try.

**Comment by Yogesh7989** [comment]
Hello @gputignano,

There is 2 Way to resolve that :

I had found the solution. please export your customer_entity table as CSV and check for wrong values I have found the invalid emails.

and also I have found null and some invalid emails - for eg: somename without @gmail.com and some special characters. This may help you to solve the issues.

Second method :
Skip Customer at time of migration by CLI. After migration successfully completed, Customer migration done by web migration Tool.

After complete Customer migration by web tool Add three field in customer_entity table **failures_num, 
 first_failure , lock_expires**.

Please find datatype and other things from fresh magento 2 database.

Please let me know if you are still facing that issue.

Thanks 
Yogesh

**Comment by gputignano** [comment]
I tried deleting all custom era but one, checking email and integrity and tried migration again. I get the same error.
I tried deleting all customers and it works.

**Comment by Yogesh7989** [comment]
Hello @gputignano ,

You can skip customer during migration process : 

Skip customer table mapping by using below code in map-cuctomer.xml in migration tool : ( Please place this code in source & Destination both) :- 

<document_rules>
           <ignore>
               <document>customer_address_entity</document>
           </ignore>
           <ignore>
               <document>customer_address_entity_datetime</document>
           </ignore>

           <ignore>
               <document>customer_address_entity_decimal</document>
           </ignore>
           <ignore>
               <document>customer_address_entity_int</document>
           </ignore>
           <ignore>
               <document>customer_address_entity_text</document>
           </ignore>
           <ignore>
               <document>customer_address_entity_varchar</document>
           </ignore>
           <ignore>
               <document>  customer_eav_attribute</document>
           </ignore>
           <ignore>
               <document>customer_eav_attribute_website</document>
           </ignore>
           <ignore>
               <document>customer_entity</document>
           </ignore>
           <ignore>
               <document>customer_entity_datetime</document>
           </ignore>
           <ignore>
               <document>customer_entity_decimal</document>
           </ignore>
           <ignore>
               <document>customer_entity_int</document>
           </ignore>
           <ignore>
               <document>customer_entity_text</document>
           </ignore>
           <ignore>
               <document>customer_entity_varchar</document>
           </ignore>
           <ignore>
               <document>customer_form_attribute</document>
           </ignore>
           <ignore>
               <document>customer_group</document>
           </ignore>
       </document_rules>

**Comment by gputignano** [comment]
I solved this issue. A long time ago I installed and after some months removed an extension that let customers to register with only email and password. So many custumers don't have first and last name in database records. I corrected this fields and now all works fine.

**Comment by victor-v-rad** [comment]
@gputignano glad to know that you solved your issue. We also encountered a similar one. Internal ticket MAGETWO-62034

**Comment by victor-v-rad** [comment]
Fixed in 2.1.6

**Comment by niksjethva** [comment]
Hello guys,

`I am trying to migrate Magento 1.9.3.10 to Magento 2.3.3 but I got stuck  [Eav step] data migration with the same error Like :`

> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

 
Please check below screenshot:
![image](https://user-images.githubusercontent.com/50106354/70142110-83db3500-16be-11ea-9dee-38c79d841571.png)


I have tried every possibility to get this resolved but bad luck every time and also tried with fresh Magento 2 db but still not getting any solution.

If anyone having idea about this error on how to get resolved then please share your thoughts for the same.

I am waiting for your feedback to get resolved this error.

Any help would be more appreciated.

Thanks in Advance.
