### ISSUE TITLE
Data migration issue

### ISSUE THREAD

**Issue by kavithakpits** [magento/data-migration-tool#217]
[Exception]
  Notice: Undefined offset: 9 in \vendor\magento\data-migration-tool\src\Migration\Step\Eav\Data.php on line 248

**Comment by dfelton** [comment]
@kavithakpits In order for anyone to help you with this more information will be necessary. I'd recommend modifying Data.php to add some additional output regarding the data that it is trying to work with.

**Comment by dfelton** [comment]
@kavithakpits It also looks like either you're not using the latest version of the migration tool, or this class file has already been modified from it's original. [Line 218 of Data.php](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Eav/Data.php#L248) would never throw this error in version 2.1.3 of the data migration tool.
