### ISSUE TITLE
Allow mapping files to be located outside vendor directory

### ISSUE THREAD

**Issue by scottsb** [magento/data-migration-tool#220]
Currently in order to customize the migration tool configuration, the custom configuration XML must be located inside the `vendor/magento/data-migration-tool` directory since the various map XML file paths specified in `config.xml` are interpreted relative to that directory. However, this violates the standard composer practice in which files inside `vendor/` are managed solely by composer and should never be directly modified. Indeed, the contents of this directory are ignored by default by Magento's provided `.gitignore`. While requiring unfortunate gymnastics, the git tracking issue can be resolved by adding `.gitignore` excludes. However, the problem then becomes that when `composer install` is run after the application repository is checked out, these custom files are wiped away.

Since the path to the main configuration XML is already customizable through a command line argument to the tool, I suggest that a new optional argument be added to specify the base path of the map XML files.

**Comment by dfelton** [comment]
If you want to store these map XML files outside of vendor, then simply specify paths to them in your main configuration file relative from `vendor/magento/data-migration-tool`. I've tested and confirmed just now that the tool allows for this. 

For example if you wanted to store them in `var/migration/mappings` (probably not appropriate place for them but just for the sake of this example) then in main configuration file would have values similar to the following:

```xml
        <!-- Relative from "/MAGENTO_INSTALL_DIR/var/magento/data-migration-tool" -->
        <map_file>../../../var/migration/mappings/map.xml</map_file>
        <eav_map_file>../../../var/migration/mappings/map-eav.xml</eav_map_file>
        <eav_document_groups_file>../../../var/migration/mappings/eav-document-groups.xml</eav_document_groups_file>
        <eav_attribute_groups_file>../../../var/migration/mappings/eav-attribute-groups.xml</eav_attribute_groups_file>
        <log_map_file>../../../var/migration/mappings/map-log.xml</log_map_file>
        <log_document_groups_file>../../../var/migration/mappings/log-document-groups.xml</log_document_groups_file>
        <settings_map_file>../../../var/migration/mappings/settings.xml</settings_map_file>
        <customer_map_file>../../../var/migration/mappings/map-customer.xml</customer_map_file>
        <customer_document_groups_file>../../../var/migration/mappings/customer-document-groups.xml</customer_document_groups_file>
        <customer_attribute_groups_file>../../../var/migration/mappings/customer-attribute-groups.xml</customer_attribute_groups_file>
        <sales_order_map_file>../../../var/migration/mappings/map-sales.xml</sales_order_map_file>
        <delta_document_groups_file>../../../var/migration/mappings/deltalog.xml</delta_document_groups_file>
        <customer_attr_map_file>../../../var/migration/mappings/customer-attr-map.xml</customer_attr_map_file>
        <customer_attr_document_groups_file>../../../var/migration/mappings/customer-attr-document-groups.xml</customer_attr_document_groups_file>
        <order_grids_document_groups_file>../../../var/migration/mappings/order-grids-document-groups.xml</order_grids_document_groups_file>
        <class_map>../../../var/migration/mappings/class-map.xml</class_map>
        <visual_merchandiser_map>../../../var/migration/mappings/visual_merchandiser_map.xml</visual_merchandiser_map>
        <visual_merchandiser_document_groups>../../../var/migration/mappings/visual_merchandiser_document_groups.xml</visual_merchandiser_document_groups>
        <visual_merchandiser_attribute_groups>../../../var/migration/mappings/visual_merchandiser_attribute_groups.xml</visual_merchandiser_attribute_groups>
        <map_document_groups>../../../var/migration/mappings/map-document-groups.xml</map_document_groups>
        <tier_price_map_file>../../../var/migration/mappings/map-tier-price.xml</tier_price_map_file>
```

Then in your mapping files, modify the path to the XSD appropriately. Example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classmap xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../../vendor/magento/class-map.xsd">
```

Correcting the XSD path seems to be optional. The tool doesn't seem to enforce it.
