### ISSUE TITLE
Can't specify port different than default

### ISSUE THREAD

**Issue by mowreggioemilia** [magento/data-migration-tool#221]
in data migration tool config.xml, database settings it's not possible to set a port different than default one: neither host parameter accepts hostname:port syntax nor it's possible to set a "port" parameter.

**Comment by victor-v-rad** [comment]
Hi @mowreggioemilia 
Your are right. It should be ability to specify a custom port in config.xml file. Internal ticket MAGETWO-63223 for this. As hotfix could be manually adding 'port' parameter to $config array in \Migration\ResourceModel\Adapter\Pdo\MysqlBuilder::getConfig() method

**Comment by victor-v-rad** [comment]
Implemented
