### ISSUE TITLE
Notice: unserialize(): Error at offset 0 of 180 bytes in \Magento\vendor\magento\data-migration-tool\src\Migration\Handler\Rule\SerializedData.php on line 36

### ISSUE THREAD

**Issue by ramapemmasani** [magento/data-migration-tool#222]
hi,
while migrating data from M1 to M2 getting the below error.
 [Exception]
 Notice: unserialize(): Error at offset 0 of 180 bytes in \Magento\vendor\magento\data-migration-tool\src\Migration\Handler\Rule\SerializedData.php on line 36

In line no36 code is as below.
$unserializedData = unserialize($recordToHandle->getValue($this->field));

**The log as below**
[2017-01-18 11:55:15][INFO][mode: data][stage: data migration][step: Map Step]: started
28% [=======>--------------------] Remaining Time: 1 hr

  [Exception]
  Notice: unserialize(): Error at offset 0 of 180 bytes in MagentoMG\vendor\magento\data-migration-tool\src\Migration\Handler\Rule\SerializedData.php on line 36

migrate:data [-r|--reset] config

**Comment by victor-v-rad** [comment]
Hi @ramapemmasani 
Probably serialized data is corrupted. You can manually check it in the next fields
catalogrule.conditions_serialized
catalogrule.actions_serialized
salesrule.conditions_serialized
salesrule.actions_serialized
You can try to re-save catalogrule or salesrule in Admin Panel of Magento 1

**Comment by ramapemmasani** [comment]
Hi victor-v-rad,
Thanks for update, I removed the the catalog rule data and sales rule data from sql. 
In next data migration run getting below error. 

28% [=======>--------------------] Remaining Time: 1 hr   PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Handler\Rule\SerializedData.php on line 36 
PHP Stack trace: 
PHP   1. {main}() C:\xampp\htdocs\MagentoMG\bin\magento:0 
PHP   2. Symfony\Component\Console\Application->run() C:\xampp\htdocs\MagentoMG\bin\magento:23 
PHP   3. Magento\Framework\Console\Cli->doRun() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Application.php:126 
PHP   4. Symfony\Component\Console\Application->doRun() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Console\Cli.php:96 
PHP   5. Symfony\Component\Console\Application->doRunCommand() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Application.php:195 
PHP   6. Symfony\Component\Console\Command\Command->run() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Application.php:874 
PHP   7. Migration\Console\MigrateDataCommand->execute() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Command\Command.php:257 
PHP   8. Migration\Mode\Data->run() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Console\MigrateDataCommand.php:51 
PHP   9. Migration\Mode\Data->runData() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Mode\Data.php:68 
PHP  10. Migration\Mode\AbstractMode->runStage() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Mode\Data.php:116 
PHP  11. Migration\Step\Map\Data->perform() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Mode\AbstractMode.php:73 
PHP  12. Migration\Step\Map\Data->getRecordTransformer() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Step\Map\Data.php:142 
PHP  13. Migration\RecordTransformer->init() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Step\Map\Data.php:199 
PHP  14. Migration\RecordTransformer->initHandlerManager() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\RecordTransformer.php:82 
PHP  15. Migration\Handler\Manager->initHandler() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\RecordTransformer.php:102 
PHP  16. Magento\Framework\ObjectManager\ObjectManager->create() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Handler\Manager.php:52 
PHP  17. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\ObjectManager.php:57 
PHP  18. Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:70 
PHP  19. Magento\Framework\Interception\Config\Config->hasPlugins() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Interception\ObjectManager\Config\Developer.php:61 
PHP  20. Magento\Framework\Interception\Config\Config->_inheritInterception() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Interception\Config\Config.php:176 
PHP  21. Magento\Framework\ObjectManager\Relations\Runtime->has() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Interception\Config\Config.php:153 
PHP  22. class_exists() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Relations\Runtime.php:38 
PHP  23. spl_autoload_call() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Relations\Runtime.php:38 
PHP  24. Composer\Autoload\ClassLoader->loadClass() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Relations\Runtime.php:38 
PHP  25. Composer\Autoload\includeFile() C:\xampp\htdocs\MagentoMG\vendor\composer\ClassLoader.php:322 
 
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Handler\Rule\SerializedData.php on line 36 
 
Call Stack: 
    0.0005     122848   1. {main}() C:\xampp\htdocs\MagentoMG\bin\magento:0 
    3.3313   27139608   2. Symfony\Component\Console\Application->run() C:\xampp\htdocs\MagentoMG\bin\magento:23 
    3.3340   27169152   3. Magento\Framework\Console\Cli->doRun() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Application.php:126 
    3.3340   27169280   4. Symfony\Component\Console\Application->doRun() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Console\Cli.php:96 
    3.3349   27169704   5. Symfony\Component\Console\Application->doRunCommand() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Application.php:195 
    3.3349   27169912   6. Symfony\Component\Console\Command\Command->run() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Application.php:874 
    3.3405   27173952   7. Migration\Console\MigrateDataCommand->execute() C:\xampp\htdocs\MagentoMG\vendor\symfony\console\Symfony\Component\Console\Command\Command.php:257 
    3.3405   27174040   8. Migration\Mode\Data->run() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Console\MigrateDataCommand.php:51 
  113.6809   36687184   9. Migration\Mode\Data->runData() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Mode\Data.php:68 
  113.6809   36687240  10. Migration\Mode\AbstractMode->runStage() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Mode\Data.php:116 
  113.6836   36687944  11. Migration\Step\Map\Data->perform() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Mode\AbstractMode.php:73 
 1974.6012  116637776  12. Migration\Step\Map\Data->getRecordTransformer() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Step\Map\Data.php:142 
 1974.6018  116638632  13. Migration\RecordTransformer->init() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Step\Map\Data.php:199 
 1974.6018  116638680  14. Migration\RecordTransformer->initHandlerManager() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\RecordTransformer.php:82 
 1974.6048  116641232  15. Migration\Handler\Manager->initHandler() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\RecordTransformer.php:102 
 1974.6048  116641232  16. Magento\Framework\ObjectManager\ObjectManager->create() C:\xampp\htdocs\MagentoMG\vendor\magento\data-migration-tool\src\Migration\Handler\Manager.php:52 
 1974.6048  116641392  17. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\ObjectManager.php:57 
 1974.6048  116641392  18. Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:70 
 1974.6048  116641392  19. Magento\Framework\Interception\Config\Config->hasPlugins() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Interception\ObjectManager\Config\Developer.php:61 
 1974.6048  116641392  20. Magento\Framework\Interception\Config\Config->_inheritInterception() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Interception\Config\Config.php:176 
 1974.6049  116641992  21. Magento\Framework\ObjectManager\Relations\Runtime->has() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\Interception\Config\Config.php:153 
 1974.6049  116642024  22. class_exists() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Relations\Runtime.php:38 
 1974.6049  116642240  23. spl_autoload_call() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Relations\Runtime.php:38 
 1974.6049  116642288  24. Composer\Autoload\ClassLoader->loadClass() C:\xampp\htdocs\MagentoMG\vendor\magento\framework\ObjectManager\Relations\Runtime.php:38 
 1974.6079  116642448  25. Composer\Autoload\includeFile() \Magento\vendor\composer\ClassLoader.php:322
