### ISSUE TITLE
Custom Handler

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#223]
Hi,

I am writing my own handle() function to handle a case to transform some data which extends \Migration\Handler\AbstractHandler

Can you confirm if $recordToHandle in handle() function is regarding the magento 1 database or the magento 2 database? And vice versa - oppositeRecord

I need to read the original magento 1 record, then copy the data to m2 table which has a different name and a different structure.

According to my own debugging they are the same:

```
    /**
     * {@inheritdoc}
     */
    public function handle(Record $recordToHandle, Record $oppositeRecord)
    {
        echo "record to handle" . PHP_EOL;

        print_r($recordToHandle->getData());

        echo "opposite record" . PHP_EOL;

        print_r($oppositeRecord->getData());
```

How do I access the magento 1 fields for the table row?

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 
$recordToHandle will be Magento 1 record if a handler tag is placed withing `<source><field_rules>`  scope

**Comment by craigcarnell** [comment]
@victor-v-rad 

In my magento 1 database table I have several fields.
In the magento 2 database table several of those fields have been turned in to a single field called additional_data which is an array serialiazed.

So in my map.xml, I have added:

```
<transform>
                <field>realex_transaction.additional_data</field>
                <handler class="\VaxLtd\Migration\Handler\Realex\AdditionalData">
                    <param name="fields" value="merchantid,account,authcode,pasref,cvnresult,batchid,card_issuer_bank,card_issuer_country,tss_result,timetaken,authtimetaken"/>
                </handler>
            </transform>
```

in my source part of map.xml I have added:

```
<!-- ignore unused fields in realex -->
            <ignore>
                <field>vax_realex.hash</field>
            </ignore>

            <ignore>
                <field>vax_realex.form_key</field>
            </ignore>

            <ignore>
                <field>vax_realex.pas_uuid</field>
            </ignore>

            <!-- ignore fields to trigger move -->
            <ignore>
                <field>vax_realex.merchantid</field>
            </ignore>
            <ignore>
                <field>vax_realex.account</field>
            </ignore>
            <ignore>
                <field>vax_realex.authcode</field>
            </ignore>
            <ignore>
                <field>vax_realex.pasref</field>
            </ignore>
            <ignore>
                <field>vax_realex.cvnresult</field>
            </ignore>
            <ignore>
                <field>vax_realex.batchid</field>
            </ignore>
            <ignore>
                <field>vax_realex.card_issuer_bank</field>
            </ignore>
            <ignore>
                <field>vax_realex.card_issuer_country</field>
            </ignore>
            <ignore>
                <field>vax_realex.tss_result</field>
            </ignore>
            <ignore>
                <field>vax_realex.timetaken</field>
            </ignore>
            <ignore>
                <field>vax_realex.authtimetaken</field>
            </ignore>
```

Otherwise I get an error from the migration tool. Where am I going wrong? Do I need to move those old fields to transform_fields?

**Comment by victor-v-rad** [comment]
In case you have a completely different structure in your Magento 2 it might be better to make a custom Step. If you just renamed your table from `vax_realex` to `realex_transaction` then use `<rename>` tag for that. Look at \Migration\RecordTransformer::transform() method for better understanding. It is applied for every record migrated from source in Map step

**Comment by craigcarnell** [comment]
@victor-v-rad do I just insert a new step into config.xml?

like so under steps mode="data":

```
<step title="RealexTransactions Step">
<data>VaxLt\Migration\Step\RealexTransaction\Data</data>
</step>
```

Which data step should it go after? I presume it loads them in that order in the xml?

**Comment by victor-v-rad** [comment]
> like so under steps mode="data":

Yes

> I presume it loads them in that order in the xml?

Yes, steps are run in the order as they are in config.xml

**Comment by craigcarnell** [comment]
@victor-v-rad It works, thank you 👍
