### ISSUE TITLE
Data Migration Tool 2.0.11 missing

### ISSUE THREAD

**Issue by Dogbombs** [magento/data-migration-tool#224]
Having wrangled Composer into functioning on this strange server I've been landed with at work, I'm unable to start the migration to Magento 2 as...

> Problem 1
> The requested package magento/data-migration-tool 2.0.11 exists as magento/data-migration-tool[2.0.0, 2.0.2, 2.0.5, 2.0.7, 2.1.0, 2.1.1, 2.1.2, 2.1.3] but these are rejected by your constraint.

At least there isn't a Problem 2!

**Comment by victor-v-rad** [comment]
Hi @Dogbombs 

Currently the tool officially supports only the latest 2.1 development branch of Magento and you can try it on your 2.0 branch by installing from [GitHub repository](https://github.com/magento/data-migration-tool) rather than composer package.

**Comment by Dogbombs** [comment]
Okay, thanks.  I'll give that a go.  Some weirdness in server configuration
stopped me from installing 2.1...

**Comment by MagePsycho** [comment]
I was also looking for DMT 2.0.11 as I don't want to use Magento EE 2.1.x due to buggy content-staging feature.
I was supposing that DMT tool is available as per Magento 2 version.
