### ISSUE TITLE
migration fail  Notice: Undefined offset: 1 in data-migration-tool/src/Migration/Step/Eav/Data.php on line 266

### ISSUE THREAD

**Issue by fventurini** [magento/data-migration-tool#227]
[Exception]
  Notice: Undefined offset: 1 in /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 266

Tried every bulk_size in config.xml
what else can I try?

thanks
Francesco

```
root@devshopmiracle:/var/www/html/bin# ./magento --reset -vvv migrate:data ../vendor/magento/data-migration-tool/etc/ce-to-ce/1.8.0.0/config.xml
Reset the current position of migration to start from the beginning

[2017-01-26 18:25:56][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
[2017-01-26 18:26:18][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:18][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:18][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:28][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:28][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:28][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:28][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:29][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:29][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:29][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:29][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: 1 sec
[2017-01-26 18:26:32][INFO][mode: data][stage: data migration][step: EAV Step]: started
42% [============>---------------] Remaining Time: 1 sec


  [Exception]
  Notice: Undefined offset: 1 in /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 266



Exception trace:
 () at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:266
 Migration\Step\Eav\Data->migrateAttributeSetsAndGroups() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:164
 Migration\Step\Eav\Data->perform() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:73
 Migration\Mode\AbstractMode->runStage() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:116
 Migration\Mode\Data->runData() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:68
 Migration\Mode\Data->run() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23


migrate:data [-r|--reset] config
```

**Comment by victor-v-rad** [comment]
Hi @fventurini 

This #209 report looks quite similar. I assume you got the error because you disabled `<integrity>Migration\Step\DataIntegrity\Integrity</integrity>` in your config.xml and not resolved "Orphan records" in your Magento 1 DB

**Comment by fventurini** [comment]
You are right. I have to take db backup first of every data migration for eventual restore.
Now I am trying with fresh new mag2.1 and going to resolve furter problems.
Thanks

**Comment by nareshphp1** [comment]
Facing the same issue as

 [Exception]
  Notice: Undefined offset: 1 in /home/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291



Exception trace:
 () at /home/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /home/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:291
 Migration\Step\Eav\Data->migrateAttributeSetsAndGroups() at /home/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:189
 Migration\Step\Eav\Data->perform() at /home/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:73
 Migration\Mode\AbstractMode->runStage() at /home/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:116
 Migration\Mode\Data->runData() at /home/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:68
 Migration\Mode\Data->run() at /home/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /home/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /home/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /home/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/bin/magento:23

**Comment by fwolfst** [comment]
This happens when you re-try a migration (i.e. because the first attempt failed). I am yet searching for a solution to "reset" the db, as @victor-v-rad suggested. For me, I do not want to start with a fresh 2.x db because we already did quite some configuration.
**Insight 1** Changing the prefix in `map-eav.xml` did change the error message to "offset 19" :)

**Comment by jafar247commerce** [comment]
@fwolfst ,
Any fixes found? I am also facing the same issue

**Comment by terms999** [comment]
any update on this issue? I am facing the same.

**Comment by jafar247commerce** [comment]
@terms999 , no, still i didn't get any solution for this, one possible way is, need to restore the database then start migration again, it may help you, for me its resloved

**Comment by pjayramkumar** [comment]
I face this issue when i see "Class not found /Migration/Handler/EavAttribute/ConvertConfigurableAttribute" error during the migration.

To solve this i created the file and get the source from git repo of data migration tool 2.2 version

after that you need to import the fresh copy of database in destination site.

flush the cache and run the migration command from start.

**Comment by jloreto** [comment]
Greetings, I had a similar error but on line 492,
always use reset `migrate: data -r`
  and when it reaches this point the databases have already been modified. I had my backup and towards restoration.

I went to the line and ignored the Notice Exception with @

```
                $record['attribute_group_id'] = @$this->mapAttributeGroupIdsSourceDest[$record['attribute_group_id']];
                if($record['attribute_group_id']!==FALSE) {
```


Then all fine work

Regarding, need to restore the database then start migration again, I think that here https://oyenetwork.com/articles/data-migration-to-magento2-case-study/ worked differently, they did things like:

```
- 'INSERT INTO% s (% s) VALUES% s',
+ 'INSERT IGNORE INTO% s (% s) VALUES% s',

```
