### ISSUE TITLE
Delta migration does not work

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/data-migration-tool#228]
Hi @victor-v-rad,

We migrated successfully from 1.9.0.1 to 2.1.2

After a while we wanted to have the new orders, customers etc into the Magento 2 but after running migrate:delta no new data was found. We did get some warnings:
<img width="870" alt="image 2017-01-27 at 2 24 26 pm" src="https://cloud.githubusercontent.com/assets/17834386/22372396/bb4369d8-e49c-11e6-87c7-c1e517f28253.png">

In the old database mage_m2 tables are there. Any idea why it is not working?

**Comment by victor-v-rad** [comment]
Hi @PascalBrouwers 

It could be in case you created (for testing purposes) new entities (orders/customers ... ) in Magento 2 after "data migration" but before "delta migration".

**Comment by PascalBrouwers** [comment]
Create no new customers after data migration. Though we did create 1 new product and a few new orders. Do I need to delete those?
If you want I can send the db's and the configuration.

**Comment by victor-v-rad** [comment]
It is better to make a fresh start by restoring your Magento 2 DB to its initial state

**Comment by PascalBrouwers** [comment]
I removed the extra products and orders that where added an ran the delta migration again, but got the same result. How does the delta migration work? Isn't there always a mismatch in entities because the M1 database has more entities?

**Comment by PascalBrouwers** [comment]
I ended up with doing a fresh install of Magento 2 and tried to retain the data that was made by using data upgrade scripts.

**Comment by victor-v-rad** [comment]
So have this worked out? The issue can be closed?

**Comment by PascalBrouwers** [comment]
Well, my question remains unanswered. Can you use the tool, make changes in data on M2 and then do a delta migration?

**Comment by victor-v-rad** [comment]
The tool was made to migrate to fresh installed Magento 2 otherwise issues can occur

**Comment by PascalBrouwers** [comment]
ah ok

**Comment by dfelton** [comment]
@PascalBrouwers To your question: "Well, my question remains unanswered. Can you use the tool, make changes in data on M2 and then do a delta migration?"

In my experience this depends on the nature of the changes on M2 database which you wish to perform prior to the delta migrations. 

The deltas, do not track **every** change on the M1 database. For example you can go ahead and make all the changes you like to store configuration, as there is no Deltas for that. 

The deltas are intended for (going from memory here) changes mostly regarding Customer accounts, Sales Orders, and Catalog Inventory Stock changes. 

This means you can make _most_ the changes you want to other areas of the M2 database without causing issues in your Deltas. Changes may include revisions to your Product Categories, Products themselves --again, the Deltas do track changes in inventory, so excluding that. I also do not recommend deleting products that were migrated, as the delta may blow up when attempting to update the inventory for deleted product(s) -- CMS Pages, Static Blocks.

**Comment by jeffb1a5** [comment]
checkout the last few comments on this thread:
https://github.com/magento/data-migration-tool/issues/316

a magerun command to retro-actively populate the m2_cl tables in the M1 installation;
