### ISSUE TITLE
Wrong php version detected when installing the Data Migration Tool in ssh. MultiPHP envirornment of WHM / cpanel

### ISSUE THREAD

**Issue by neko-in-space** [magento/data-migration-tool#229]
Not sure if this is Magento or Data Migration Tool issue.... but I can't install the DMT on MultiPHP environment.

## Preconditions

1. Magento CE 2.1.3 without sample data is installed.
2. MultiPHP envirornment in WHM / cpanel
3. PHP 7.0.14 (however, the default server's php is v.5.5.38)

## Steps to reproduce

1. Create an account on a server with php 5.5.38
2. Apply php v.7.0.14 to the account using MultiPHP Manager in cPanel.
3. Install Magento 2.1.3
4. Start installing Data Migration Tool in ssh

## Expected result

It should detect the correct php v.7.0.14 and install the Data Migration Tool.

## Actual result

It detects the default server's php v.5.5.38 and exits the install. `php -v` detects the correct v.7.0.14 though.

![wrong-php](https://cloud.githubusercontent.com/assets/25376344/22445827/3f854478-e7ae-11e6-8220-cbb4fb9f220f.png)

Any advice? Can the DMT be installed manually? How to install dependencies manually?

Thanks.

**Comment by victor-v-rad** [comment]
Hi @neko-in-space 

The tool cannot be run independently of Magento 2 codebase. See [its system requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) and minimal PHP version. I suppose composer could be run with PHP version you need by tweaking some of the environment variables in linux

**Comment by neko-in-space** [comment]
Thank you for the reply, victor-v-rad!
I have figured out that it's not Magento and not the Data Migration Tool that is checking php version but the Composer! The solution is forcing Composer to ignore requirements with `--ignore-platform-reqs` option. Like so:

```
composer config repositories.magento composer https://repo.magento.com
composer require magento/data-migration-tool:<version> --ignore-platform-reqs
```

**Comment by victor-v-rad** [comment]
Glad to know you solved the issue!
