### ISSUE TITLE
how to transfer eav_attribute frontend_input?

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#231]
I have one called blfa_file and it needs to. be media_image.

I can't find in any xml where to do this?

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 

You can add new handler into map-eav.xml for eav_attribute.frontend_input field

**Comment by craigcarnell** [comment]
@victor-v-rad do I need to do this in source or destination? there is an existing one in source.

**Comment by victor-v-rad** [comment]
Both are possible. But most handlers are in 'source' scope

**Comment by craigcarnell** [comment]
@victor-v-rad well for some reason my setup wont read map-eav.xml

It keeps falling back to map-eav.xml.dist.

This is my config.xml setting:

```
<eav_map_file>etc/ee-to-ee/map-eav.xml</eav_map_file>
```

**Comment by victor-v-rad** [comment]
map-eav.xml works fine in my env
