### ISSUE TITLE
[ERROR]: Source documents are not mapped: core_directory_storage,core_file_storage

### ISSUE THREAD

**Issue by VignaPranav** [magento/data-migration-tool#232]
Hi,
I am using this data-migration-tool, getting below error,
[ERROR]: Source documents are not mapped: core_directory_storage,core_file_storage

By default in map.xml the document, "core_directory_storage,core_file_storage" is renamed to "media_storage_directory_storage, media_storage_file_storage".
Since it's already maped , why I am getting this error. 

Note: I am migrating datas from magento1.13.1.0 to magento 2.1.0

**Comment by victor-v-rad** [comment]
Hi @VignaPranav 

Therese tables are created when you decide to store you media files in DB. Following the instructions from the official guide should help: ["Media files stored in the database"](http://devdocs.magento.com/guides/v2.1/migration/migration-manually.html)

**Comment by VignaPranav** [comment]
Hi@victor-v-rad,
Thanks, got the solution

**Comment by VignaPranav** [comment]
Another one issue I am facing,
While migrating I am getting the issue like,
 [PDOException]
  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Can you suggest me the solution for it

**Comment by victor-v-rad** [comment]
Try to increase max_allowed_packet in your Mysql conf. By the way it is better to create a new issue report then discussing several in one thread.

**Comment by VignaPranav** [comment]
I have raised as another issue, https://github.com/magento/data-migration-tool/issues/233
