### ISSUE TITLE
[PDOException] SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by VignaPranav** [magento/data-migration-tool#233]
Hi,
I am using this data-migration-tool, getting below error,
[PDOException]
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Note: I am migrating datas from magento1.13.1.0 to magento 2.1.0

**Comment by victor-v-rad** [comment]
Hi,

Hare is a [great article](https://dev.mysql.com/doc/refman/5.7/en/gone-away.html) about this issue. Try to leverage limit options in your mysql config. Like increasing max_allowed_packet
