### ISSUE TITLE
 [Exception]   Notice: Undefined offset: 1 in vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 209

### ISSUE THREAD

**Issue by VignaPranav** [magento/data-migration-tool#234]
Hi,
I am using this data-migration-tool, getting below error,
[Exception]   Notice: Undefined offset: 1 in vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 209

Note: I am migrating datas from magento1.13.1.0 to magento 2.1.0

I have searched for solution all has suggested to start the migration again with fresh M2 database.
Could you please suggest me the solution

**Comment by victor-v-rad** [comment]
duplicate #235
