### ISSUE TITLE
Magento 2.1.4 Launched without updated data-migration-tool

### ISSUE THREAD

**Issue by jmonschke** [magento/data-migration-tool#239]
According to the documentation here: http://devdocs.magento.com/guides/v2.1/migration/migration-tool-install.html the data-migration-tool should be on the exact same version to the patch version that Magento 2 proper is on.

As a result, for sites with Magento 2.1.4, we are unable to migrate data from Magento 1.X

**Comment by victor-v-rad** [comment]
Release of the tool will come soon after Magento

**Comment by craigcarnell** [comment]
```
  Problem 1
    - The requested package magento/data-migration-tool 2.1.4 exists as magento/data-migration-tool[2.1.3, 2.0.0, 2.0.2, 2.0.5, 2.0.7, 2.1.0, 2.1.1, 2.1.2] but these are rejected by your constraint.

```

How long till it's available on packagist?

**Comment by craigcarnell** [comment]
nevermind, its out now! :)
