### ISSUE TITLE
Showing message "Migration completed", But NO settings/data migrated

### ISSUE THREAD

**Issue by anil-suthar** [magento/data-migration-tool#240]
I'm migrating ce 1.9.2.1 to ce 2.1.3.
Did all correct settings in `config.xml` at `\vendor\magento\data-migration-tool\etc\ce-to-ce\1.9.2.1\config.xml`.
Run commands for settings and data both. Both the times it says Migration completed BUT no settings/data migrated

Followed all settings from : http://devdocs.magento.com/guides/v2.1/migration/migration-tool-preconditions.html

![untitled-1](https://cloud.githubusercontent.com/assets/3518141/22773700/7f239edc-eec9-11e6-849e-5185e24ee0c5.png)

**Comment by victor-v-rad** [comment]
Hi @anil-suthar 

Take a look at sample [config.xml.dist](https://github.com/magento/data-migration-tool/blob/master/etc/ce-to-ce/1.9.2.1/config.xml.dist). Just like it, your config should consist of "Steps" which the tool is run. But it is empty according to your run log.
