### ISSUE TITLE
Exception\LocalizedException  Key must not exceed 32 bytes.

### ISSUE THREAD

**Issue by michael-hxx** [magento/data-migration-tool#241]
Hi

i got an error after starting the data migration cli tool. I cant find any imformation maybe someone already got that error and could help me.

    [Magento\Framework\Exception\LocalizedException]
    Key must not exceed 32 bytes.

I changed my encryption key but that dont fixed the error. Mcrypt is enabled and Magento is Up to date (2.1.4) I want to migrate from 1.9.3.2 and i have already set up my configuration and mappings.

michael

**Comment by victor-v-rad** [comment]
Hi @michael-hxx 

Make sure your crypt_key in config.xml is not exceed 32 symbols.

**Comment by michael-hxx** [comment]
Hi @victor-v-rad 
i had to cut the old encrypt key and the new one to 32 signs.
my old encrypt key has got 52 signs but only the first 32 signs were used by mcrypt.
