### ISSUE TITLE
Incompatibility in data. Source document: eav_attribute. 

### ISSUE THREAD

**Issue by milossh** [magento/data-migration-tool#243]
This is the error I'm getting while trying to migrate from 1.9.0.1 to 2.1.4, ce-to-ce:

Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=237 cannot contain empty field value

That attribute is the text attribute, and is not set as unique at all. Is there a way to ignore it?

**Comment by victor-v-rad** [comment]
Hi @milossh 

You can ignore it  etc/ce-to-ce/eav-attribute-groups.xml file by adding new item to frontend_input_empty_allowed group

**Comment by milossh** [comment]
Is it safe to do so?

**Comment by victor-v-rad** [comment]
It will not prevent the attribute from migration but allow the tool to migrate with empty value in frontend_input filed

**Comment by daschenbrener** [comment]
What would be the correct syntax to do this? Im a little lost what to type to do this.

Thanks

**Comment by victor-v-rad** [comment]
Just add new item to etc/ce-to-ce/eav-attribute-groups.xml into frontend_input_empty_allowed group if you really need to have empty value in frontend_input field after migration

**Comment by friimaind** [comment]
Sorry but I have the same problem and cannot find a way to ignore this check.

On file /vendor/magento/data-migration-tool/etc/ce-to-ce/eav-attribute-groups.xml

I tried:

>         <attribute type="frontend_input">attribute_id</attribute>

or 

>        <attribute type="eav_attribute">attribute_id</attribute>

but I always receive the same error:

>[2017-05-31 16:29:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=608 cannot contain empty field value

**Comment by Sarvesh-A** [comment]
Hello @friimaind , Did you solve the issue? I am facing the same.

**Comment by friimaind** [comment]
@Sarvesh-A I abandoned and used the simple import/export. Migrating Magento 1.6 with a lot of custom modules with data-migration-tool was a nightmare, sorry.

**Comment by Sarvesh-A** [comment]
@friimaind Thanks for your feedback but I got the solution. The issue was I needed to assign `frontend_input` to particular `attribute_id` like text or varchar etc depends on your attribute. It was null so that's why was getting this error. :)

**Comment by friimaind** [comment]
Thank you @Sarvesh-A , your tip could helps other users!

**Comment by saisudham** [comment]
Error:
Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=425 cannot contain empty field value

Here attribute is is_locked (having 425 as attribute_id in eav_attribute table for entity=1 i.e, customer) so i added the below line for type ="customer" in eav-attribute-groups.xml

File Path:
/vendor/magento/data-migration-tool/etc/ce-to-ce/eav-attribute-groups.xml

Added line:

  <attribute type="customer">is_locked</attribute>
     
This solved my issue and able to migrate successfully

**Comment by asadrbk** [comment]
@friimaind 
I am late to this, if if anyone need to know how to add attribute to "frontend_input_empty_allowed" group: Follow this.
` <group name="frontend_input_empty_allowed">
		<attribute>frontend_input</attribute>
 </group>
`
You just need to add line: `<attribute>frontend_input</attribute>` the parent tag for group name is already there.

**Comment by udhayakumard10** [comment]
Hi @victor-v-rad ,

`php bin/magento migrate:data -r vendor/magento/data-migration-tool/etc/opensource-to-opensource/isha-migration/1.9.1.1/config.xml`

i just run the command on putty,
[https://ibb.co/nCG03ZF](https://ibb.co/nCG03ZF)

Im using magento 1.9.1.1 into magento 2.3.0 version migration setup

In magento 1.9.1.1 below attributes created as same magento 2.3.0, but i have same error 

foomanconnectvend_id		
foomanconnectvend_in_process	
foomanconnectvend_parent_id	 	
foomanconnectvend_supplier	 
foomanconnectvend_supply_code	
foomanconnectvend_type

Please help with this.

**Comment by udhayakumard10** [comment]
Hi @victor-v-rad ,

Any updates I mentioned issues ??

**Comment by victor-v-rad** [comment]
Hi @daschenbrener 
Did you add these attributes into eav-attribute-groups.xml?

**Comment by udhayakumard10** [comment]
thanks for updates,

Its working fine .

**Comment by MustafaBaltee** [comment]
hi i have similar issue ..
I am still stuck my error is
`[2020-02-26 13:31:21][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: source_model. Error: Class eav/entity_attribute_source_custom is not mapped in record attribute_id=563
`
and i tried to rename the class using class-map.xml but then it generate another error
invalid map file.

I want this attribute and its data in magento 2 .. 
If some one has resolve such issue please guide.
@victor-v-rad please have a look

**Comment by nawawishkid** [comment]
> Sorry but I have the same problem and cannot find a way to ignore this check.
> 
> On file /vendor/magento/data-migration-tool/etc/ce-to-ce/eav-attribute-groups.xml
> 
> I tried:
> 
> > ```
> >     <attribute type="frontend_input">attribute_id</attribute>
> > ```
> 
> or
> 
> > ```
> >    <attribute type="eav_attribute">attribute_id</attribute>
> > ```
> 
> but I always receive the same error:
> 
> > [2017-05-31 16:29:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=608 cannot contain empty field value

For those who have no idea where the `type` field of the `attribute` node comes from or what should be the value of the node like me. I found the solution!  

The `type` field of the `attribute` node comes from the `entity_type_code` field of the `eav_entity_type` table in database. And the node value is neither `frontend_input` nor `frontend_model` but the value of the `attribute_code` field of the `eav_attribute` table which the migration tool output the record ID in the error log. For example, `Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=608 cannot contain empty field value` the record ID is `608`.

And here is the SQL code to get `attribute`'s `type` and value from the Magento 1 database:

```sql
select
    eet.entity_type_code as AttributeType, 
    ea.attribute_code as AttributeValue 
from eav_attribute ea
join eav_entity_type eet on eet.entity_type_id = ea.entity_type_id 
where ea.attribute_id in (<comma_separated_record_id_list>);
```

Let's say I got errors like:

```shell
[2022-01-03 05:02:48][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=134 cannot contain empty field value
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=135 cannot contain empty field value
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_input. Error: Attribute with attribute_id=136 cannot contain empty field value
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class Amasty_Customerattr_Model_Rewrite_Eav_Entity_Attribute_Frontend_Default is not mapped in record attribute_id=148
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class Amasty_Customerattr_Model_Rewrite_Eav_Entity_Attribute_Frontend_Default is not mapped in record attribute_id=149
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class Amasty_Customerattr_Model_Rewrite_Eav_Entity_Attribute_Frontend_Default is not mapped in record attribute_id=150
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class Amasty_Customerattr_Model_Rewrite_Eav_Entity_Attribute_Frontend_Default is not mapped in record attribute_id=161
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class Amasty_Customerattr_Model_Rewrite_Eav_Entity_Attribute_Frontend_Default is not mapped in record attribute_id=163
[2022-01-03 05:02:48][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class Amasty_Customerattr_Model_Rewrite_Eav_Entity_Attribute_Frontend_Default is not mapped in record attribute_id=164
```
I logged in to my Magento 1 database server and perform this query:

```sql
select
    eet.entity_type_code as AttributeType, 
    ea.attribute_code as AttributeValue 
from eav_attribute ea
join eav_entity_type eet on eet.entity_type_id = ea.entity_type_id 
where ea.attribute_id in (134,135,136,148,149,150,161,163,164);
```

I'll get the result like:

```shell
+---------------+--------------------------------+
| AttributeType | AttributeValue                 |
+---------------+--------------------------------+
| order         | magecomp_surcharge_amount      |
| order         | base_magecomp_surcharge_amount |
| order         | magecomp_surcharge_description |
| customer      | phone_no                       |
| customer      | line_id                        |
| customer      | pharmcyshop_name               |
| customer      | date                           |
| customer      | code_customer                  |
| customer      | address_regis_pu               |
+---------------+--------------------------------+
9 rows in set (0.00 sec)
```

And use those values in the `eav-attribute-groups.xml` like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<groups xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="urn:magento:module:Magento_DataMigrationTool:etc/groups.xsd">
    <group name="ignore">
        <!-- Custom ignores -->
        <attribute type="customer">phone_no</attribute>
        <attribute type="customer">line_id</attribute>
        <attribute type="customer">pharmcyshop_name</attribute>
        <attribute type="customer">date</attribute>
        <attribute type="customer">code_customer</attribute>
        <attribute type="customer">address_regis_pu</attribute>
        <!-- End of custom ignores -->
        <!-- Existing nodes below -->
    </group>
    <group name="frontend_input_empty_allowed">
        <!-- Custom allowed -->
        <attribute type="order">magecomp_surcharge_amount</attribute>
        <attribute type="order">base_magecomp_surcharge_amount</attribute>
        <attribute type="order">magecomp_surcharge_description</attribute>
        <!-- End of custom allowed -->
        <!-- Existing nodes below -->
    </group>
</groups>
```

And now all the errors are gone!

---

**Bonus!**

Copy-pasting manually is time-consuming so I wrote a JavaScript code to transform the SQL result table to the XML nodes:

```javascript
function sqlTableStringToXmlNodes(sqlTableString) {
  return sqlTableString
    .match(/[a-zA-Z0-9\-_]+/g)
    .reduce((result, item, idx, arr) => {
      if (idx % 2 === 1) {
        result.push([arr[idx - 1], item])
      }
      return result
    }, [])
    .reduce((str, [key, value]) => {
      str += `<attribute type="${key}">${value}</attribute>`
      return str
    }, '')
}
```

Use it in your favorite browser console like this:

![image](https://user-images.githubusercontent.com/71911303/147903743-686db5b7-8291-42c4-9b9e-6fbc7be74378.png)

Copy that XML string output and paste it into your `eav-attribute-groups.xml` file!
