### ISSUE TITLE
Add Documentation to run the unit test

### ISSUE THREAD

**Issue by larsroettig** [magento/data-migration-tool#244]
I find a bug but would like fix this but i cant because you cant run the test in a single mode. 
If you try composer' install  

The error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/framework could not be found in any version, there may be a typo in the package name.

**Comment by victor-v-rad** [comment]
Hi @larsroettig 

I guess you are trying to install the tool as standalone app but it should be installed as part of Magento 2. This [guide](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-install.html) should help
