### ISSUE TITLE
Url Rewrites cannot migrate

### ISSUE THREAD

**Issue by larsroettig** [magento/data-migration-tool#248]
The Option **auto_resolve_urlrewrite_duplicates option= 1** is not working if you try to migrate many URL rewrites. I must cleanup the rewrite table. But I can not rebuild the rewrites. Add some config to regenerate the URL Rewrites by Migration.

**Comment by victor-v-rad** [comment]
Hi @larsroettig 
auto_resolve_urlrewrite_duplicates option is for EE. Because CE does not have issues with URL duplication as I understand.

**Comment by larsroettig** [comment]
@victor-v-rad  I try to migrate from EE1.14.2 to EE2.1.5 and cant migrate.

**Comment by victor-v-rad** [comment]
>The Option auto_resolve_urlrewrite_duplicates option= 1 is not working if you try to migrate many URL rewrites.

Does it show any errors?

**Comment by larsroettig** [comment]
Duplicate Rewrite for ..../.... can migrate i cant send you the the full error because confidentiality agreement
