### ISSUE TITLE
Problem migrating large dataset 1.7.0.2 to 2.1.4

### ISSUE THREAD

**Issue by Jo-Anne4WDT** [magento/data-migration-tool#252]
I'm trying to migrate a substantial dataset ( about 9GB ) from 1.7.0.2 to 2.1.4. After setting/modifying the required config.xml, map.xml, and class-map.xm I keep stranding at the following error 

  - Error while sending QUERY packet. PID=2227 in Mysql.php line 170 : $statement->execute($bind);

I am not sure, but I was under the impression it has to do with setting(s) in mysql, which I've changed to 
SET GLOBAL  `max_allowed_packet`=335544320;
Alas, this wasn't the solution.

Anyone who can tell me what I might do differently?

**Comment by victor-v-rad** [comment]
Hi @Jo-Anne4WDT 
Increasing in MySQL max_allowed_packet to 1Gb  as well as in PHP memory_limit = -1 should help

**Comment by Jo-Anne4WDT** [comment]
Thanks Victor, this solved the error with sending QUERY.

Now I've 'just' a whole lot of "Mismatch of entities" to solve. Any idea how I can create an easy/luminous solution?

**Comment by victor-v-rad** [comment]
This [guide](http://devdocs.magento.com/guides/v2.1/migration/migration-troubleshooting.html) should help

**Comment by Jo-Anne4WDT** [comment]
Again thank you Victor. It is a guide I must've missed or overlooked.
