### ISSUE TITLE
 Client password

### ISSUE THREAD

**Issue by carloshernan007** [magento/data-migration-tool#253]
Hi, I try to  do migration of Magento 1.7.0.2 to Magento 2.1.5 in this moment  is possible the migration of all information but I have one problem with the customer account the emails is correct and the password is equal in the two stores 
In magento 1.7 =  278e55f34adb3bcd0c2efc87c119af7c:m2
In magento 2.1.5 = 278e55f34adb3bcd0c2efc87c119af7c:m2:0

In the vendor/magento/data-migration-tool/etc/ce-to-ce/1.7.0.2/config.xml
<upgrade_customer_password_hash>1</upgrade_customer_password_hash>

I can not log in with user data

**Comment by victor-v-rad** [comment]
Hi @carloshernan007 

I have just migrated 1.7.0.2 to 2.1.5. The hashes are:
In magento 1.7.0.2 = 0c891d5c2a6ec5f35c18fb3c816786a6:z6
In magento 2.1.5 = 0c891d5c2a6ec5f35c18fb3c816786a6:z6:0

Log in works fine in my case. Please let me know if you find the solution for your problem or additional info.

**Comment by carloshernan007** [comment]
Hi, thanks for your help I check the process for customer login in the frontend in Magento 2.1.5 in the file vendor/magento/module-customer/Controller/Account/LoginPost.php  in line number 137 the method  !$this->formKeyValidator->validate($this->getRequest())

if ($this->session->isLoggedIn() || !$this->formKeyValidator->validate($this->getRequest())) {
    /** @var \Magento\Framework\Controller\Result\Redirect $resultRedirect */
    $resultRedirect = $this->resultRedirectFactory->create();
    $resultRedirect->setPath('*/*/');
    return $resultRedirect;
}

The form login send  form_key = "qE9Ioc1lOJW7RIpo" and the validater  $this->_formKey->getFormKey() = "qN0vyh8CPMWVmCWG"  the keys are diferent the method response all time false; 

`<input name="form_key" type="hidden" value="qN0vyh8CPMWVmCWG">`

I think this is my problem

**Comment by carloshernan007** [comment]
I have solution for the problem in chorme not work good when in the core_config_data  base_url is localhost  is necesary change the "web/unsecure/base_url"  to my IP example 192.168.1.10 and after php ./bin/magento cache:flush

It works now

**Comment by victor-v-rad** [comment]
Glad to know you solved this issue
