### ISSUE TITLE
Add possibility to deactivate the Progressbar for Task runner. 

### ISSUE THREAD

**Issue by larsroettig** [magento/data-migration-tool#255]
As Developer I would like deactivate the Progressbar for my Taskrunner Jenkins /Gitlab CI. For a Job automatization is the progressbar notrellay helpfull or correct in the logfile build history.

**Comment by victor-v-rad** [comment]
Hi @larsroettig 

You can run the tool with -vv parameter. This it means only errors to show

**Comment by larsroettig** [comment]
@victor-v-rad Thank you I will add this Information in documentation
