### ISSUE TITLE
Help with migratiom

### ISSUE THREAD

**Issue by josecoelho509** [magento/data-migration-tool#256]
Hi, 
Can someone please help me work on the map files to set up the migration? Thank you in advance.

**Comment by victor-v-rad** [comment]
Hi @josecoelho509 

There is a good [guide for migration Magento Stores](http://devdocs.magento.com/guides/v2.1/migration/bk-migration-guide.html) as a starting point.

**Comment by josecoelho509** [comment]
Thanks a lot for the answer, I tried, and I was able to configure the config file, the problem is configuring the map files.

Thanks again.

**Comment by victor-v-rad** [comment]
[This section](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-internal-spec.html#map-step) describes map file structure. 
[This one](http://devdocs.magento.com/guides/v2.1/migration/migration-troubleshooting.html), how to deal with errors migration tool throws.

**Comment by josecoelho509** [comment]
Thanks for the answer, I will read the indicated manuals again and try, only one question if you can answer, can I install the modules I want or is it ideal to migrate to a clean database? Thank you.

**Comment by victor-v-rad** [comment]
>can I install the modules I want or is it ideal to migrate to a clean database?

1.  
If the same module installed in your Magento 1 store and available for Magento 2 then installation is recommended because data of the module will be transferred to new store. 
2. 
If it is new module for your store you still can install it before migration but you need to add <ignore> tags of tables of the module
