### ISSUE TITLE
run migrate:data command, get attribute error on macOS

### ISSUE THREAD

**Issue by broros** [magento/data-migration-tool#257]
I want to migrate from 1.9.2.2 to 2.1.4, When I run migrate:data I get some errors, any way to fix this?

`[2017-03-06 17:00:42][ERROR]: Source documents are not mapped: paybox_question_number,strikeiron_tax_rate`

if I add ignore in map.xml I still get the error because "paybox_question_number,strikeiron_tax_rate" only exists in magento 1.6.2.0 and I upgraded to 1.9.2.2 some time ago

```
  <ignore>
              <document>paybox_question_number</document>
          </ignore>
          <ignore>
              <document>strikeiron_tax_rate</document>
          </ignore>
```

**Comment by victor-v-rad** [comment]
Hi @broros 

Make sure you changed default path in <map_file> option in your config.xml

**Comment by broros** [comment]
that worked but now it seems to be stuck at Log Step

`[stage: data migration][step: Log Step]: started`

**Comment by victor-v-rad** [comment]
It could be due to large data in logs
