### ISSUE TITLE
Migration from Magento 1.x EE to Magento 2.1.x CE

### ISSUE THREAD

**Issue by atishgoswami** [magento/data-migration-tool#258]
Hello Team,

We have a project on Magento 1.14.3.1 EE and we would like to migrate it to Magento 2.1.5 CE to test out the performance improvement the Magento 2.1.x version has to offer.

Currently we see there are only 3 migration flows available:

1.  Magento 1.x CE - Magento 2.x CE
2.  Magento 1.x EE - Magento 2.x EE
3.  Magento 1.x CE - Magento 2.x EE

We were wondering if **Magento 1.x EE - Magento 2.x CE** is possible with this tool. If yes, is there any configuration we need adjust for this to work ?

Regards,
Atish

**Comment by victor-v-rad** [comment]
There is no official support of such migration. As a starting point add all integrity check differences into your map file and exclude EE steps ("Custom Customer Attributes Step", "SalesOrder Step", "VisualMerchandiser Step") from config.xml. List of what else to do will go on. The tool is quite agile. Reading [the official documentation](http://devdocs.magento.com/guides/v2.1/migration/bk-migration-guide.html) will help to understand it better.

**Comment by pawan** [comment]
@atishgoswami how you managed this ? I also need to migrate from 1.14.2.2 to 2.3.3
