### ISSUE TITLE
Duplicate entry "reques path" although different store_id

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool#26]
I don't now why I can't migrate url_rewrite table with same "request path" value but different store_id.
I think this is a bug of this tool.
Do you have any idea?
![screenshot_2](https://cloud.githubusercontent.com/assets/16131502/11861246/ea3bb222-a4b0-11e5-87f7-520ccc00978f.png)

**Comment by bh-ref** [comment]
I am just now encountering a similar problem.

The problem on your Magento 1 database seems to be that it returns more than one row for the following SQL query:
`SELECT <your magento 1 database>.core_url_rewrite WHERE request_path='plugins.html' AND store_id=9;`

As you can see with the command `SHOW CREATE TABLE <your magento 1 database>.core_url_rewrite;`, the combination of the columns `request_path` and `store_id`have to be unique.

Maybe you can delete the duplicate entry? I do not know if it is wise, though.

**Comment by bh-ref** [comment]
If you want to know how many duplicates you have, run this:

```sql
SELECT request_path, store_id, COUNT(*) as count
FROM <your magento 1 database>.core_url_rewrite
GROUP BY request_path, store_id
HAVING COUNT(*) > 1;
```

**Comment by Vincenkt** [comment]
Hi 
I have solved this issue.
However, I'm facing a problem in Order grid step.
![screenshot_3](https://cloud.githubusercontent.com/assets/16131502/11865781/e9902484-a4d8-11e5-8adc-ad43ecd43198.png)

**Comment by bh-ref** [comment]
I don't know what the problem could be, unfortunately.

May I ask how you solved your first problem?

**Comment by Vincenkt** [comment]
I have removed duplicate records and the issue has been solved.

**Comment by bh-ref** [comment]
Alright, the I think I will do the same, at least for the test migration. Thank you.

**Comment by Vincenkt** [comment]
Do you have any idea with my second issue?

**Comment by bh-ref** [comment]
https://github.com/magento/data-migration-tool-ce/issues/16 mentions a similar problem, I think. Maybe it helps?

If no, you may want to begin to debug, probably the `perform()` method inside vendor/magento/data-migration-tool/src/Migration/Step/OrderGrids/Volume.php

**Comment by craigcarnell** [comment]
@bh-ref I have the same issue.

However, your query given above returns nothing on m1 DB (changed to enterprise_url_rewrite)

The data migration tool will fail on upright-vacuum-cleaners/swift-upright which exists for store 22 and store 4 etc. However they are unique as it appends the store id??

**Comment by bh-ref** [comment]
@craigcarnell I never encountered the case where a duplicate was automatically resolved like it seems to be the case in your log. However, I had another problem with URL Rewrite step. It turned out, that the affected rewrite had like some fields missing (NULL) whereas other rewrite did not have NULLs in the same fields (columns).

Maybe you can look up your affected rewrites in your DB and check with other rewrites which where successful to detect a difference/error?

**Comment by hws47a** [comment]
After upgrade migration tool to 2.0.2 I still have related issue:

>   [PDOException]                                                                                                                      
>   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'female/edits-1' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'

for data in source db ![](https://www.dropbox.com/s/iq8o3e5d80pb0da/Screenshot%202016-02-12%2021.41.47.png?dl=1)

**Comment by craigcarnell** [comment]
I am trying migration tool 2.0.2 and I have this issue:

```
[PDOException]                                                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'upright-vacuum-cleaners/swift-upright-22' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'
```

In my magento 1 db in enterprise_url_rewrite:

SELECT * FROM enterprise_url_rewrite WHERE request_path LIKE '%upright-vacuum-cleaners/swift-upright%' AND store_id=22;

![screen shot 2016-02-12 at 14 53 47](https://cloud.githubusercontent.com/assets/1188869/13010165/707f53b6-d198-11e5-97a1-33e38d3d644f.png)

**Comment by craigcarnell** [comment]
Also:

```
[PDOException]                                                                                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'upright-vacuum-cleaners/turboforce-upright-4' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'
```

When there is only 2:

```
29552106	upright-vacuum-cleaners/turboforce-upright	catalog/category/view/id/55	1	facbb8dc01a1cd1f5278eff3399cdc82	upright-vacuum-cleaners/turboforce-upright	1	51	22	2
29552201	upright-vacuum-cleaners/turboforce-upright	catalog/category/view/id/55	1	d6c5bada7a19d8a2c4216f53821bc987	upright-vacuum-cleaners/turboforce-upright	1	51	4	2
```

**Comment by cchamplin** [comment]
It looks like in #32cba04 the duplicate resolution what changed to only modify paths with a "." in them. Not sure why this change was added, but it seems to completely break duplicate resolution for many paths.

**Comment by cchamplin** [comment]
Additionally duplicates are queried and pulled by priority, but when the resolution occurs the record that is inserted into the database that does NOT have its request_path modified doesn't get the target_path or redirect_type for the highest priority duplicate.

**Comment by craigcarnell** [comment]
Any updates on this Magento???

**Comment by ilol** [comment]
@viktor-v-rad can you help?

**Comment by victor-v-rad** [comment]
I suggest #81 is the same. I have created internal issue to process this case

**Comment by craigcarnell** [comment]
@ilol Any updates on this issue? This is the last issue preventing me from handing over a decent M1 database -> M2

**Comment by digitalredefned** [comment]
I'm also experiencing this issue.  1.9.0.1 to 2.0.7 migration.  Only 1 instance of the combination that is throwing the error:
 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'adobe-1' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'

**Comment by craigcarnell** [comment]
@ilol I still get this issue with 2.1

**Comment by ilol** [comment]
will fix this in the next sprint (MAGETWO-52505)

**Comment by ygrigoriev** [comment]
@craigcarnell, we carrently work on this issue. Could you please provide your `core_url_rewrite` table?

**Comment by craigcarnell** [comment]
@ygrigoriev do you have an e-mail address or some how to send you this data?

**Comment by victor-v-rad** [comment]
Here https://github.com/victor-v-rad you can find my email.
