### ISSUE TITLE
[ERROR]: Incorrect value: Magento\Bundle\Model\Product\Attribute\Source\Shipment\Type in: eav_attribute.source_model for attribute_code=shipment_type

### ISSUE THREAD

**Issue by crashcreative** [magento/data-migration-tool#260]
I'm migrating data from magento 1.9.2.1 to magento 2.0.2, when it gets to step EAV..I 'm getting the following error:

[ERROR]: Incorrect value: Magento\Bundle\Model\Product\Attribute\Source\Shipment\Type in: eav_attribute.source_model for attribute_code=shipment_type

I double checked the values in the old and new.. they match exactly..I tried to ignore and didn't work for this in the class-map.xml Any Ideas on this?

**Comment by victor-v-rad** [comment]
Hi @crashcreative 

Probably the class Magento\Bundle\Model\Product\Attribute\Source\Shipment\Type does not exist in your Magento 2 codebase. Please be informed that all the bugfix and improvements are done in the latest stable version of Magento 2. So it would be better to use Magento 2.1.5 and the Data Migration Tool 2.1.5

**Comment by batmaninkl** [comment]
Hi having this same issue with Magento 2.1.7. Any advice? 

Ive tried manually putting the file Type.php and but to no avail.
