### ISSUE TITLE
Error occurred during "Setup Trigger" step 

### ISSUE THREAD

**Issue by pankajbhope** [magento/data-migration-tool#261]
[2017-03-17 11:04:07][INFO][mode: data][stage: setup triggers][step: Stage]: started
32% [=========>------------------] Remaining Time: 19 secs

                                                                               
  [Zend_Db_Statement_Exception]                                                
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near ';                                   
  END;                                                                         
  INSERT INTO m2_cl_sales_flat_shipment_track (`entity_id`, `operation`) V' a  
  t line 3, query was: CREATE TRIGGER codisto_sales_flat_shipment_track_updat  
  e AFTER UPDATE ON sales_flat_shipment_track FOR EACH ROW                     
  BEGIN                                                                        
  IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'codis  
  to_order_change') AND EXISTS(SELECT 1 FROM `sales_flat_order` WHERE entity_  
  id = NEW.order_id AND COALESCE(codisto_orderid, '') != '') THEN INSERT INTO  
   `codisto_order_change` SET order_id = NEW.order_id, stamp = UTC_TIMESTAMP(  
  ) ON DUPLICATE KEY UPDATE order_id = order_id, stamp = UTC_TIMESTAMP(); IF;  
  END;                                                                         
  INSERT INTO m2_cl_sales_flat_shipment_track (`entity_id`, `operation`) VALU  
  ES (NEW.entity_id, 'UPDATE')ON DUPLICATE KEY UPDATE operation = 'UPDATE';    
  END                                                                                     
                                                                               
  [PDOException]                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near ';                                   
  END;                                                                         
  INSERT INTO m2_cl_sales_flat_shipment_track (`entity_id`, `operation`) V' a  
  t line 3

**Comment by victor-v-rad** [comment]
@pankajbhope I apologize for the late reply. 

It is a part of "delta" mode. See [Migrate changes doc](http://devdocs.magento.com/guides/v2.1/migration/migration-migrate-delta.html) 
\Migration\App\SetupDeltaLog is run to setup triggers for specific tables. And I assume there are conflicts with existing ones from extensions. Though the data migration tool should properly recognize such cases (see [the code](https://github.com/magento/data-migration-tool/blob/2.1.5/src/Migration/ResourceModel/Adapter/Mysql.php#L397)) there are could be exceptions. You showed the error message but it seems truncated by github. Please use 
```
error message
```
Github Markdown to show the message again
