### ISSUE TITLE
Record structure does not equal Collection structure

### ISSUE THREAD

**Issue by jcloudsnetwork** [magento/data-migration-tool#262]
Hi,

I migrated from Magento 1.9.2.2 to 2.0.7 and right after "Tier Price Step", I get the error.

100% [============================] Remaining Time: 1 sec 
[2017-03-22 08:32:29][INFO][mode: data][stage: data migration][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec 
[2017-03-22 08:32:29][ERROR]: Record structure does not equal Collection structure

What is the error about?

Thanks

**Comment by victor-v-rad** [comment]
Hi @jcloudsnetwork 

Supposedly your table catalog_product_entity_tier_price has columns created by some extension. There is a possibility to ignore such column in the latest version of Data Migration Tool. Please try using the latest version 2.1.5

**Comment by jcloudsnetwork** [comment]
Hi @victor-v-rad 

I need to upgrade my magento to 2.1.5 in order to use latest version of data migration tool?

Thanks

**Comment by victor-v-rad** [comment]
Yes

**Comment by jcloudsnetwork** [comment]
@victor-v-rad 

Without upgrade no solutions? Some module I'm using now not support 2.1.5.....

**Comment by victor-v-rad** [comment]
You can debug \Migration\Step\TierPrice\Data class to find the exact point of the issue

**Comment by jcloudsnetwork** [comment]
@victor-v-rad 

Noted. thanks for help.
