### ISSUE TITLE
magento migrate:data fails if a table name contains a `.`

### ISSUE THREAD

**Issue by markbiek** [magento/data-migration-tool#265]
At some point during the bin/magento migrate:data process, the script does a SHOW CREATE TABLE <table-name> on each table.

The script attempts to quote the table name in a way that fails if the table name contains a ..

For example, a table named myco_documents_16.01 will generate the following SQL

SHOW CREATE TABLE `myco_documents_16`.`01`
which fails with a Base table or view does not exist PDO exception.

**Comment by victor-v-rad** [comment]
Hi @markbiek 

As you can see from this [post](http://stackoverflow.com/questions/776123/does-mysql-allows-to-create-database-with-dot), having dots in table names is not recommended practice. I did manage to reproduce this issue but it derives from Zend Framework in \Zend_Db_Adapter_Abstract::_quoteIdentifierAs() method. You can see the code
```
$ident = explode('.', $ident);
```
 of this method. It actually causes the error you describe. Possible solution could be renaming your tables with underscore instead dots.
