### ISSUE TITLE
Error : Source table does not exist

### ISSUE THREAD

**Issue by yogendrabmishra** [magento/data-migration-tool#266]
Hi, 

I am doing the data migration and fixed all issues except below one : 
Source table does not exist: catalog_category_entity_url_key
Source table does not exist: catalog_product_entity_url_key

I tried to look around and tried to put ignore in map.xml but that didn't help. Please help me to fix the error. I am using 2.1.5 data migration tool. All table are configured in map.xml file but still I am getting the error. Pls help.
---Yogi---

**Comment by victor-v-rad** [comment]
Hi @yogendrabmishra 

Probably your Magento 1 is Enterprise Edition. If so, starting from 1.13.0.0 these tables are part of URLRewite feature.

**Comment by yogendrabmishra** [comment]
Yes Victor, I am using the Enterprise, so does it means I must add these tables before I continue migration and I can't skip these tables? I am on EE1.14.2.4.  
--Yogi--

**Comment by victor-v-rad** [comment]
This is very odd. It looks like your store runs on Community Edition. You can try changing your config.xml with
```
        <step title="Url Rewrite Step">
            <integrity>Migration\Step\UrlRewrite\Version191to2000</integrity>
            <data>Migration\Step\UrlRewrite\Version191to2000</data>
            <volume>Migration\Step\UrlRewrite\Version191to2000</volume>
        </step>
```
instead of your
```
        <step title="Url Rewrite Step">
            <integrity>Migration\Step\UrlRewrite\Version11410to2000</integrity>
            <data>Migration\Step\UrlRewrite\Version11410to2000</data>
            <volume>Migration\Step\UrlRewrite\Version11410to2000</volume>
        </step>
```

**Comment by yogendrabmishra** [comment]
Hi Victor, 

I tried using your configuration above and commented out the section and replaced with 191 configuration, but still it's looking for the enterprise tables : 

[2017-04-03 11:29:50][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
14% [====>-----------------------] Remaining Time: 1 sec
28% [========>-------------------] Remaining Time: 1 sect: enterprise_url_rewrite
42% [============>---------------] Remaining Time: 1 sect: catalog_category_entity_url_key
57% [================>-----------] Remaining Time: 1 sect: catalog_product_entity_url_key
100% [============================] Remaining Time: 1 sec: enterprise_url_rewrite_redirect

--Yogi--

**Comment by victor-v-rad** [comment]
Please recheck you use the config.xml you chaged

**Comment by yogendrabmishra** [comment]
I am using this config.xml : 

php bin/magento migrate:data vendor/magento/data-migration-tool/etc/ee-to-ee/1.14.2.4/config.xml

do I need to use the community config you mean but I am sure that we are on EE 1.14.2.4.

--Yogi--
