### ISSUE TITLE
Test directory is inconstant 

### ISSUE THREAD

**Issue by mikeymike** [magento/data-migration-tool#268]
Generally M2 modules conform to a pretty rigid structure (albeit not enforced in any way) and one part of this is the test directory. 

All modules have them defined as `Test` and by calling it `tests` here you're causing the di compile command to compile the tests too. 

Here's the line that makes it skip the `Test` directory https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php#L228-L230

Note that you want actually see any errors under normal conditions but because we've replaced the ancient version of PHPUnit used by Magento2 with PHPUnit 6 we've also lost the `PHPUnit_Framework_TestCase` class so the DI compile errors for us. 

It's clear anyway that tests shouldn't be compiled so I think we should rename the directory to conform 😄

**Comment by victor-v-rad** [comment]
Hi @mikeymike 

Thank you for posting this issue with good details. Internal ticket MAGETWO-67324 to solve it.

**Comment by mikeymike** [comment]
No problem @victor-v-rad .... I'd submit a PR but I'm unsure of the testing procedure for the package. Do the tests run through a core Magento test suite ?

**Comment by victor-v-rad** [comment]
The tool is independent from Magento 2 in regards to tests. The right solution is unclear for now because the tool is not an ordinary module of Magento 2. Its directory structure more like any other libs in vendor directory 
![dirstructure](https://cloud.githubusercontent.com/assets/106504/24895200/cd88e96c-1e97-11e7-9e04-129bfe6fa046.jpg)

**Comment by mikeymike** [comment]
Understood, I'm familiar with how this is generally done within community packages although I'm unsure of why this wouldn't be seen as an ordinary module of Magento 2? Is there any other context this would be run in other than being a module ? 

Either way do you think the better solution is to change the check inside Magento ? It should be a relatively simple fix with no real impact on anything else afaik.

**Comment by victor-v-rad** [comment]
You could just delete 'tests' folder if not used.

**Comment by mikeymike** [comment]
Yup, we're doing it on a post install script with composer. Thanks though 👍

**Comment by mikeymike** [comment]
https://github.com/magento/magento2/pull/9210

This looks like it's solved just awaiting release 👍 🎉
