### ISSUE TITLE
ignore all not mapped fields and Documents

### ISSUE THREAD

**Issue by SasiKiranK** [magento/data-migration-tool#269]
Hi Team

We have 100's of fields and documents to ignore. Most helpful if we can bypass this through coding. 
I found this functions isFieldIgnored,isDocumentIgnored(),

But not sure to how to ignore all the not mapped fields and Documents.

**Comment by victor-v-rad** [comment]
Hi @SasiKiranK 

You can remove integrity checks in your config.xml in case you do not need the data from these tables and fields.
