### ISSUE TITLE
Problem in Order grid step

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool#27]
I have a problem when migrate order grid.
![screenshot_3](https://cloud.githubusercontent.com/assets/16131502/11865923/01dd377e-a4da-11e5-9c08-cadf0cd2695a.png)

**Comment by victor-v-rad** [comment]
It can occur when migration is running on live store. Some new order can be placed during the migration. In that case use [migration of incremental changes](http://devdocs.magento.com/guides/v2.0/migration/migration-migrate-delta.html)

Try to compare the table sales_flat_order_grid from Magento 1 and sales_order_grid from Magento 2. Some records may be missing

**Comment by ilol** [comment]
@Vincenkt thank you for request. If you got an desired answer can you please close the issue?

**Comment by Siyadev9** [comment]
Hi, I'm having a problem with the Order grids step.

![image](https://user-images.githubusercontent.com/29921007/27865600-8673a7bc-6193-11e7-8678-5bc82db50d7f.png)
