### ISSUE TITLE
Source documents are not mapped: merchandiser_category_values And Destination documents are not mapped: visual_merchandiser_rule

### ISSUE THREAD

**Issue by yogendrabmishra** [magento/data-migration-tool#272]
Hi Team,

I am using the Data Migration tool 2.1.5 for my EE1.14.2.4. I have stuck with this error : 
[2017-04-13 12:40:20][ERROR]: Source documents are not mapped: merchandiser_category_values
[2017-04-13 12:40:20][ERROR]: Destination documents are not mapped: visual_merchandiser_rule
When I see the map.xml.dist (I am using map.xml) I could see below code in source and destination node respectively:
 <ignore>
                <document>merchandiser_category_values</document>
            </ignore>
and 
<ignore>
                <document>visual_merchandiser_rule</document>
            </ignore>
After that I can see in visual_merchandiser_map.xml.dist file in this code under source node : 
<document_rules>
            <rename>
                <document>merchandiser_category_values</document>
                <to>visual_merchandiser_rule</to>
            </rename>
        </document_rules>
I can pass through this error by commenting the merchandiser block in config.xml but still I didn't get why are we using this module, as first we are trying to skip the tables and in other dist file renaming the document. Could you please help to understand this error and tell me the solution without leaving out this module. 

Kind regards,
Yogi

**Comment by victor-v-rad** [comment]
These tables are marked as ignored in map.xml because Visual Merchandiser has dedicated "VisualMerchandiser Step". This step use visual_merchandiser_map.xml.dist file for transferring data.
