### ISSUE TITLE
Migration from 1.6.2 to 2.1.5: integrity check fails

### ISSUE THREAD

**Issue by fwolfst** [magento/data-migration-tool#274]
I got the same error as in #174 

    [2017-04-17 08:46:19][ERROR]: Destination documents are not mapped: catalog_category_product_cl,catalog_product_attribute_cl,catalog_product_category_cl,catalog_product_price_cl,cataloginventory_stock_cl,catalogrule_product_cl,catalogrule_rule_cl,catalogsearch_fulltext_cl,customer_dummy_cl,design_config_dummy_cl

Do I understand correctly that I can only migrate a vanilla (non indexed) installation? The particular 2.1.5. shop has already received minor work and i thought now it would be time to import/migrate the old data, but it fails with the same migration-configuration that worked in a vanilla shop.

For now I will try to ignore the respective documents in map.xm but somehow I doubt that thats the correct approach.

**Comment by fwolfst** [comment]
:( as far as I understand, now shop is broken (missing attributes and stuff). How would one correctly handle the situation?

**Comment by victor-v-rad** [comment]
Hi @fwolfst 

These tables are created as soon as you set Indexer to work in "Update by Schedule" mode. It is not a problem to have it ignored in map.xml. Internal MAGETWO-67534 to have this by default. I will also add a note to the [Migration Guide](http://devdocs.magento.com/guides/v2.1/migration/bk-migration-guide.html) that Magento 2 needs to be clean (without modification and adding any entities. Such as products, categories, attributes) before migration.

**Comment by fwolfst** [comment]
thanks. selfhealing-powers activated!
