### ISSUE TITLE
Attribute Sets Migration_

### ISSUE THREAD

**Issue by snoroozi** [magento/data-migration-tool#275]
When I migrated my data all of my migrated attributes were renamed Migration_someattributeset. All were appended with Migration_

**Comment by victor-v-rad** [comment]
Hi @snoroozi 

Yes, it was done in order to avoid conflicts with names of attribute sets and attribute groups of Magento 1 and Magento 2. You can remove this prefix if you will

**Comment by snoroozi** [comment]
Remove after migration manually or is there a way before?  We have about 50
attribute Sets.

**Comment by victor-v-rad** [comment]
Look into map-eav.xml.dist. \Migration\Handler\AddPrefix handler does it. You can try removing it to test if it works for you.

**Comment by snoroozi** [comment]
Thank you.

**Comment by yogeshsyscraft** [comment]
@victor-v-rad  Will it effect any functionality if we are renaming migrated attribute in magento 2 ? hope for reply soon

**Comment by snoroozi** [comment]
If you have a staging, I suggest leave as is, and then backup your staging
and test there first.

We did have one set back from altering attribute sets directly in the
database and had to roll back to earlier that week a backup we'd made.
