### ISSUE TITLE
[ERROR]: Integrity check failed due to "core_config_data" document does not exist in the destination resource

### ISSUE THREAD

**Issue by SudheerKota** [magento/data-migration-tool#276]
HI All,
While we performing data migration using magento data-migation-tool 2.1.5 from 1.6.2.0 to 2.1.5 we were getting this error. Could anyone Help us to solve this issue?

Thanks
SudheerKota

**Comment by victor-v-rad** [comment]
Please check out if the table core_config_data exits in your Magento 2 DB

**Comment by batmaninkl** [comment]
im having the same issue. was there a solution to this?
