### ISSUE TITLE
Images are Not displaying in Website after migartion

### ISSUE THREAD

**Issue by SudheerKota** [magento/data-migration-tool#277]
HI,
I have done the migration in local system .Its all happened good.After the migration i was manually moved the medail files from magento 1.x to Magento 2.x in Pub/Media.But the Images are not displaying in new dashboard.I have tried by clearing the cache in Magento Admin ,but No result.Could any one help me out to solve this?

Have a look at below screenshot

![mg_migration](https://cloud.githubusercontent.com/assets/18481535/25266761/f53159cc-268f-11e7-9d1b-1acca01b952e.PNG)
Thanks
SudheerKota

**Comment by victor-v-rad** [comment]
There is "Flush Catalog Images Cache" button in the Admin Panel > Cache Management .

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-66781 to investigate this issue

**Comment by kerlama** [comment]
Hi,

I have almost the same issue, but with product thumbnail images. Once migration is finished, only thumbnail images are not visible, in catalog. 

I played around and noticed if you go to product and manage images, select thumbnail, untick box to be hidden on product page, save product, tick it again and save, image will be shown. 

It can be pain in the a** to repeat these steps on 1k products.

**Comment by hostep** [comment]
@kerlama: what you are experiencing is a new bug introduced in Magento 2.1.6, which is reported over here: https://github.com/magento/magento2/issues/9498

@SudheerKota, you are probably also using Magento 2.1.6 so you should run `bin/magento catalog:images:resize` after the migration, see https://github.com/magento/magento2/issues/9275 or https://github.com/magento/magento2/issues/9276

**Comment by victor-v-rad** [comment]
Thank you @hostep for the clarifications!

**Comment by SanderJP** [comment]
@hostep not entirely, @kerlama is talking about the fact that the Data Migration Tool by default ticks the box 'Hide from Product Page.' on the product images, which I just found out as well. I corrected this by changing all 1's in the disabled column to 0 in `catalog_product_entity_media_gallery_value`. This does not help if some of your images are intentionally hidden though.

**Comment by sharjeelz** [comment]
If you have migrated from magento 1.x to 2.x the images that you marked excluded in magento 1 will be hidden in magento 2
