### ISSUE TITLE
Attribute vat_id does not exist in the type customer_address

### ISSUE THREAD

**Issue by S-Mikhail** [magento/data-migration-tool#280]
Hi there,
I'm trying to migrate Magento 1.8.1.0 to 2.1.6. when i run data migration, i get the following error:

> [2017-04-22 20:28:55][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
[2017-04-22 20:28:56][INFO][mode: data][stage: integrity check][step: EAV Step]: started
[2017-04-22 20:28:56][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
**_[2017-04-22 20:28:56][ERROR]: Attribute vat_id does not exist in the type customer_address_**
[2017-04-22 20:28:56][INFO][mode: data][stage: integrity check][step: Map Step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: Log Step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
[2017-04-22 20:28:58][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started

I checked the table **eav_attribute** and found that the value **vat_id** already exist... any suggestions?
i already found this post [https://github.com/magento/data-migration-tool/issues/230](url) but he didn't have the attribute, not like me
Thanks in advance

**Comment by victor-v-rad** [comment]
Hi @S-Mikhail 

This is strange. Make sure your vat_id attribute relates to customer_address entity type. Also I would suggest migrating with Data Migration Tool 2.1.5 instead of 2.1.6 to check if issue exists on the previous version of the tool

**Comment by S-Mikhail** [comment]
I removed magento 2.1.6, installed 2.1.5 and used data migration 2.1.5 as you advised, but the problem still persist. so i tried `eav_attribute.entity_type_id from` '8' to '2' to match `customer_address_entity.entity_type_id` and it worked

**Comment by victor-v-rad** [comment]
Could you please show on a screenshot the data from eav_entity_type table. I seems EAV step did something wrong

**Comment by S-Mikhail** [comment]
yes sure, here you go, 
[1](http://prnt.sc/f109wg)
[2](http://prnt.sc/f10a68)

**Comment by S-Mikhail** [comment]
so what do u think? is there a problem with the table?

**Comment by victor-v-rad** [comment]
I am surprised you did not find the similar problems with other attributes which should have the same issue. The reason of the issue is not clear. What I could suggest is you to send me db dump of the tables:
eav_attribute_group
eav_attribute_set
eav_attribute
eav_entity_attribute
catalog_eav_attribute
customer_eav_attribute
eav_entity_type
These tables are processed in the EAV step. I will try to migrate and reproduce your case. You can email me (find email address in my profile https://github.com/victor-v-rad)

**Comment by S-Mikhail** [comment]
I just emailed you the tables you requested, thanks a lot for your time and effort

**Comment by victor-v-rad** [comment]
Hi @S-Mikhail 
I've got your email. For some reason your vat_id attribute has entity_type_id = '8' but should be '2'. So you did it right when changed it to '2'

**Comment by S-Mikhail** [comment]
Thanks for your quick response. I got the following error message when i change the entity_type_id to 2
```
[Exception]
  Notice: Undefined offset: 19 in /path/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 253
```
the following is from the Data.php with line 253 in bold
```
            if ($documentName == 'eav_attribute_set') {
                foreach ($this->initialData->getAttributeSets('dest') as $record) {
                    $record['attribute_set_id'] = null;
                    **$record['entity_type_id'] = $this->mapEntityTypeIdsDestOldNew[$record['entity_type_id']];**
                    $destinationRecord = $this->factory->create(
                        [
                            'document' => $destinationDocument,
                            'data' => $record
                        ]
                    );
                    $recordsToSave->addRecord($destinationRecord);
                }
            }
```
I think it's still related to entity_type_id

**Comment by victor-v-rad** [comment]
Try adding new record
```
INSERT INTO `eav_attribute` (`entity_type_id`, `attribute_code`, `attribute_model`, `backend_model`, `backend_type`, `backend_table`, `frontend_model`, `frontend_input`, `frontend_label`, `frontend_class`, `source_model`, `is_required`, `is_user_defined`, `default_value`, `is_unique`, `note`) VALUES
	(2, 'vat_id', NULL, NULL, 'varchar', NULL, NULL, 'text', 'VAT number', NULL, NULL, 0, 0, NULL, 0, NULL)
```

**Comment by S-Mikhail** [comment]
#1062 - Duplicate entry '2-vat_id' for key 'UNQ_EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE'
