### ISSUE TITLE
configurable product special price not showing

### ISSUE THREAD

**Issue by bijugit** [magento/data-migration-tool#281]
Hi,

We have working with magneto data migration, our  m1 version is : 1.9.3.2 and migrating to m2 version 2.1.5.

We have getting the issue in configurable product special price and tier price.

Please give your valid feedback as soon as possible.

Regards,

**Comment by victor-v-rad** [comment]
Hi @bijugit 

Please give more details about the issue. Does it appear on migrated configurable products? Are there any errors you see?

**Comment by bijugit** [comment]
Hi,

Thanks for you quick reply,

Our migration process  
migrate:settings --reset vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.3.2/config.xml and migrate:data --reset vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.3.2/config.xml (http://i.prntscr.com/a4ae9f6d7853412398adda7c03c7631e.png)
successfully completed, but  special price, group price and Tier Price details not working.
please refer this screen shot for m1 (http://i.prntscr.com/53f65dcf46f44f1581b01930e6d00ed0.png)
this is for m2 site ( http://i.prntscr.com/23cfce7e21954d58aeebdef46de32d8a.png ) ( http://i.prntscr.com/e416d706898647c5a1d769c6413e5ee2.png )

Please give valid reply as soon as possible.

Regards,

**Comment by victor-v-rad** [comment]
Group price functionality was removed in Magento 2 in favor of Tier price. So the tool converts all Group price into Tier price in \Migration\Step\TierPrice\Data class. Also it is strange your Group Price attribute migrated to M2 because it shouldn't happen. See eav-attribute-groups.xml.dist 
```
    <group name="ignore">
        <attribute type="catalog_product">msrp_enabled</attribute>
        <attribute type="catalog_product">group_price</attribute>
    </group>
```
So maybe something wrong with our Group Price attribute. Does it have group_price code in eav_attribute table?

**Comment by bijugit** [comment]
Hi,
Thanks for your reply.

Why the special price and tier price not showing for configurable product?
is there any configuration change need to implement?

please give valid feedback as soon as possible

Regards,

**Comment by victor-v-rad** [comment]
Special price is shown on your pic http://i.prntscr.com/23cfce7e21954d58aeebdef46de32d8a.png

**Comment by bijugit** [comment]
Hi,
Sorry for the late reply.

Special price and tier price issue only config parent product, please check this screen shot for m1 & m2 
For M1 , http://i.prntscr.com/aaf09721d3264466afccdf7fd9a6aa7a.png
For M2 , http://i.prntscr.com/54b2d904b7d44d40917a79ae3f680f0e.png

Also found some other issue regarding to attribute set name, 
For M1, attribute set name shows like ("Default")
For M2, attribute set name shows like ("Migration_Default", "Default"), just like ("http://i.prntscr.com/9029fa16a45948e695688ab2070e6a3a.png").

Can we retain same name of the attribute set in after migration? is this possible, please give the valid step.

Regards,

**Comment by bijugit** [comment]
Hi,

Please give your valid reply as soon as possible.

Is this Special price and tier price issue only for configurable main product, right?

Can we retain same name of the attribute set in m2 after migration?

Regards,

**Comment by victor-v-rad** [comment]
Hi @bijugit if you open migrated simple product that is an option for your configurable product you will see special and tier prices in "Advanced Pricing". And yes you wont see "Advanced Pricing" on the parent (configurable product)

**Comment by bijugit** [comment]
Hi,

Thanks for your quick reply,

We have checked the special and tier prices in "Advanced Pricing" of configurable simple product, it show blank (http://i.prntscr.com/ada68f39361f4af5a020c539a84ea472.png).

For attribute set ,Can we retain same name of the attribute set in m2 after migration?

Regards,

**Comment by victor-v-rad** [comment]
> it show blank

It is a pity, in my migrated configurable products everything looks fine 

> Can we retain same name

Yes. Try to delete _Migration prefix

**Comment by wcladesh** [comment]
Hi @bijugit ,
How you resolved that problem, I have the same issue as you described?

"We have checked the special and tier prices in "Advanced Pricing" of configurable simple product, it show blank (http://i.prntscr.com/ada68f39361f4af5a020c539a84ea472.png)."

Please give me solution.

**Comment by RonvanBreukelen** [comment]
Hello @bijugit,

I also still have this problem when migrating from magento 1.9.2 to 2.2.6. The special prices in the magento 2.2.6 site are all empty in configurable simple products.

Does someone has a solution yet?

**Comment by odeland** [comment]
Did anyone find a solution here? It would seem that special prices that are set on individual simple product of a configurable product are not migrated.

**Comment by Rutvee123** [comment]
Have any update on this? Facing same issue
