### ISSUE TITLE
Settings migration leaves admin/url/custom pointing to Magento 1 site

### ISSUE THREAD

**Issue by bobdavison** [magento/data-migration-tool#285]
Settings migration leaves admin/url/custom pointing to Magento 1 site resulting in a 404 page not found when attempting to access the admin page.

Removing the admin/url/custom path from core_config_data works so I guess that adding an ignore section to settings.xml.dist would fix this.

**Comment by victor-v-rad** [comment]
Thank you @bobdavison for reporting this issue. Internal ticket MAGETWO-68784 to fix it
