### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by snoroozi** [magento/data-migration-tool#286]
Attributes in M1 that come from modules with attribute_code in eav_attribute that don't exist in M2 are getting created in M2.  I would expect that by default that these would come up as unmatched during the integrity check, but they don't.

Do I need to manually ignore these approximately 600 attributes?  

Please advise.

**Comment by victor-v-rad** [comment]
Hi @snoroozi 

> I would expect that by default that these would come up as unmatched during the integrity check

Usually, attributes that are created manually in Magento 1 store are also needed in Magento 2 store. So they are migrated by default. But there are attributes created by Magento 1 extensions. For these are better to find corresponding extensions ported for Magento 2 in the [Marketplace](https://marketplace.magento.com/) and install it before migration.
