### ISSUE TITLE
Clarification regarding Data migration.

### ISSUE THREAD

**Issue by karthi5053** [magento/data-migration-tool#291]
Hi Team,

I'm about to start my data migration process from magento EE 1.4 to magento 2.1 Cloud Edition.
Is this data migration tool can migrate magento EE 1.4 to **magento cloud edition**?
Awaiting for your reply.

Thanks in advance.

**Comment by victor-v-rad** [comment]
I believe it can migrate. Since the cloud edition has additional modules probably you will get integrity check errors that your destination documents (read as tables) are not mapped. <ignore> them in your map.xml file in <destination> scope
