### ISSUE TITLE
No such entity

### ISSUE THREAD

**Issue by kerlama** [magento/data-migration-tool#293]
Hi,
after migration from 1.8.1.0 to 2.1.6 every time I want to save category, I get: No such entity.
Product save is working fine, while categories not. Also, I noticed that if I want to save product programmatically, it will also throw error: No such entity.

Any hints ?

**Comment by victor-v-rad** [comment]
You can set M2 into [developer mode](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html) to see stack backtrace of the error. Also look into magento_root/var/log dir for the detailed errors
