### ISSUE TITLE
Data MIgration Issue

### ISSUE THREAD

**Issue by karthi5053** [magento/data-migration-tool#294]
Hi Team,

We have magento 1.13 EE database with all tables prefixed with "xxxx_" , we have configured prefix in config.xml " <source_prefix>xxxx_</source_prefix>".

We are using data migration tool 2.1.4 and during data migration we got the following error. Seems the migration tool is missing the prefix in the sql query.

Reset the current position of migration to start from the beginning

[2017-05-09 14:12:37][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
45% [============>---------------] Remaining Time: 1 sec

 [Zend_Db_Statement_Exception]                                                                                                                 
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'src_db.core_store' doesn't exist, query was: SELECT DISTINCT  `child`.`store  
  _id` FROM `xxxx_eav_attribute_label` AS `child`                                                                                           
   LEFT JOIN `core_store` AS `parent` ON child.store_id = parent.store_id WHERE (child.store_id IS NOT NULL) AND (parent.store_id IS NULL)                                                                                                          
  [PDOException]                                                                                    
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'src_db.core_store' doesn't exist

**Comment by victor-v-rad** [comment]
Hi @karthi5053 

I checked this scenario on my staging server and it worked fine.
Please check your Magento 1 db > eav_attribute_label > foreign key FK_PRFXEAV_ATTRIBUTE_LABEL_STORE_ID_PRFXCORE_STORE_STORE_ID must have reference table xxx_core_store. But it seems there is just core_store. 
Also I suggest you to run `php bin/magento cache:flush` command to flush DDL cache

**Comment by karthi5053** [comment]
Hi Victor,

Thanks for your reply.
Is it advisable to ignore Integrity check in Data Integrity Step during data migration and delta?
i.e
By removing 
<step title="Data Integrity Step"><integrity>XXX/xxx/xxx/</integrity></step> in step mode "data".

Awaiting for your reply.

Regards,
Karthi kumar.

**Comment by victor-v-rad** [comment]
[here is](devdocs.magento.com/guides/v2.1/migration/migration-troubleshooting.html) you can find advise about orphan records if needed

**Comment by karthi5053** [comment]
Hi Victor,

Url not working.It goes to 404 page.

Regards,
Karthi Kumar.

**Comment by victor-v-rad** [comment]
http://devdocs.magento.com/guides/v2.1/migration/migration-troubleshooting.html

**Comment by karthi5053** [comment]
HI Victor,

According to the Data Migration document, to ignore tables we need to add the tables and fields to the ignore list in map.xml. But there are other xml files like **map-sales.xml.dist, map-customer.xml.dist** which also has the fields added to the ignore list. 

Our question 
 1. For ignoring tables and fields, is map.xml alone is sufficient or do we need to add the fields to the other xml files as well?

2. From the above question could you please explain how the below works?

We also noticed that map.xml has the following code added.
  `<ignore><document>customer_entity</document></ignore>` 

and map-customer.xml.dist has the following code added.
`<ignore><field>customer_entity.entity_type_id</field></ignore>`

3. Also we dont want some core magento tables to be migrated. Is it advisable to add core `magento` tables to the ignore list in map.xml?
