### ISSUE TITLE
No category titles, customer details

### ISSUE THREAD

**Issue by Dogbombs** [magento/data-migration-tool#295]
This migration is getting there!  Working from 1.9.2.4 to 2.1.6.

Unfortunately the first migration didn't take any of the store information, I had to create that manually.  Second full migration has taken all order details, all product details _but_:

* No category titles - other information such as product association to category is correct
* No customer details - While we've got their orders, we've none of the other information at all.  I suspect this means they wouldn't be able to log in and download their past purchases.

Everything else is looking good!

**Comment by victor-v-rad** [comment]
Having no category titles and no customer details after migration can be due to some customization (installed extensions) in your Magento 1 store. I have migrated vanilla stores many times from 1.9.2.4 and encountered no such issues so far.

**Comment by Dogbombs** [comment]
Okay, I'll try disabling all the extensions and then migrating.  Had to be
something like that, thanks.
