### ISSUE TITLE
Magento Data Migration Tool Configuration

### ISSUE THREAD

**Issue by rg-srini** [magento/data-migration-tool#297]
Hi,

We have to do data-migration using the magento data-migration tool from EE 1.13 to EE 2.1.4. 
We follow the docuement given below. 
http://devdocs.magento.com/guides/v2.1/migration/migration-migrate.html

We understand the command to run the migration is as given below 
bin/magento migrate:<mode> [-r|--reset] {<path to config.xml>}

As per this doc, We need to do the configurations on vendor/data-migration-tool/etc/ee-to-ee/1.13.0.0/config.xml and on the primary mapping file vendor/data-migration-tool/etc/ee-to-ee/1.13.0.0/map.xml.dist

So for instance, the typical command will be,
php magento migrate:data -r /path/to/magento/vendor/magento/data-migration-tool/etc/ee-to-ee/1.13.0.0/config.xml

However, in our git repositary the vendor directory is ignored. 
So we can not push our configurations and mapping to the vendor dir as the vendor dir is not tracked. 
We also do not have any write access on vendor folder to make changes manually on the server.

Please advice how to proceed.

Regards,
Srini

**Comment by victor-v-rad** [comment]
Hi @rg-srini 

Try to change `<map_file>` option value inside your config.xml

**Comment by rg-srini** [comment]
Hi Victor,

Thanks for your feedback. Will try.
I have noted the same question on other ticket as well.
https://github.com/magento/data-migration-tool/issues/220

Thanks,
Srini
