### ISSUE TITLE
crypt_key error 

### ISSUE THREAD

**Issue by patrickouc** [magento/data-migration-tool#300]
hello,

From the wrong point of view, is crypt_key problem, but I have modified the config.xml.

Are there any other considerations?

![e1](https://cloud.githubusercontent.com/assets/4326820/26089541/3ce49658-3a31-11e7-9463-5a068e7d7ee2.png)
![e2](https://cloud.githubusercontent.com/assets/4326820/26089546/42b61a7a-3a31-11e7-8377-22ec204210ea.png)

**Comment by victor-v-rad** [comment]
Hi @patrickouc 

I see several `<options>` tag in your config.xml. It might be the cause
