### ISSUE TITLE
I was getting base table missing error

### ISSUE THREAD

**Issue by dmj331** [magento/data-migration-tool#305]
I was installing a memento 2 site on my local server and got this error

[ERROR] exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'chocolatework.admin_user' doesn't exist' in C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('DESCRIBE `admin...', Array) #5 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('DESCRIBE `admin...', Array) #6 

![image](https://cloud.githubusercontent.com/assets/6643332/26330196/cdb94264-3f18-11e7-967e-73098458f0e2.png)

Can anyone help to take a look?

**Comment by victor-v-rad** [comment]
Hi @dmj331 

It was during Magento 2 installation. So not the issue of this project Data Migration Tool. On the [Magento 2 github](https://github.com/magento/magento2/issues) someone could have encountered such an issue. You can search there.

**Comment by dmj331** [comment]
thank you
