### ISSUE TITLE
 Table 'customer_entity' doesn't exist

### ISSUE THREAD

**Issue by Croxarens** [magento/data-migration-tool#306]
Hi,

I'm getting the following errors when I migrate and the destination database has a prefix

```
[Zend_Db_Statement_Exception]                                                                                                           
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbtest.customer_entity' doesn't exist, query was: DESCRIBE `customer_entity`  
```

```
  [PDOException]                                                                                   
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbtest.customer_entity' doesn't exist 
```

It looks like it's ignoring the prefix.
Without prefix the migration is working with no problem.

**Comment by victor-v-rad** [comment]
Hi @Croxarens 

Try adding 
```$destinationDocName = $this->destination->addDocumentPrefix($destinationDocName);``` 
into the beginning of \Migration\Step\Customer\Helper::getFieldsWithDefaultValues() [Here](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Customer/Helper.php#L253)

**Comment by victor-v-rad** [comment]
internal ticket to fix MAGETWO-69465

**Comment by Croxarens** [comment]
@victor-v-rad I'll try as soon as I'll complete the delta migration (see issue [#307](https://github.com/magento/data-migration-tool/issues/307))

**Comment by sduif** [comment]
Had the same error when migrating to a fresh install with a prefix. Can confirm that adding `$destinationDocName = $this->destination->addDocumentPrefix($destinationDocName);` did the trick and fixed the issue.

**Comment by iphigenie** [comment]
confirming just for completeness that the commit fixes the issue

**Comment by victor-v-rad** [comment]
Fixed
