### ISSUE TITLE
Delta Migration goes in loop

### ISSUE THREAD

**Issue by Croxarens** [magento/data-migration-tool#307]
I'm running the delta migration with the following command : 

`$ php bin/magento migrate:delta vendor/magento/data-migration-tool/etc/ce-to-ee/1.9.3.0/config.xml -vvv`

and this is the output :

> [2017-05-25 14:22:11][INFO][mode: delta][stage: delta delivering][step: Customer Attributes Step]: started
> [2017-05-25 14:22:11][INFO][mode: delta][stage: volume check][step: Customer Attributes Step]: started
> 100% [============================] Remaining Time: 1 sec
> [2017-05-25 14:22:11][WARNING]: Mismatch of entities in the document: customer_entity
> [2017-05-25 14:22:11][WARNING]: Mismatch of entities in the document: customer_entity_varchar
> [2017-05-25 14:22:11][WARNING]: Mismatch of entities in the document: customer_address_entity
> [2017-05-25 14:22:11][WARNING]: Volume Check failed
> [2017-05-25 14:22:11][INFO][mode: delta][stage: delta delivering][step: Map Step]: started
> [2017-05-25 14:22:12][INFO][mode: delta][stage: volume check][step: Map Step]: started
> 
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: adminnotification_inbox
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_entity
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_entity_datetime
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_entity_decimal
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_entity_int
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_entity_text
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_entity_varchar
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_category_product
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_compare_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_datetime
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_decimal
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_int
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_media_gallery
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_media_gallery_value
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_text
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_entity_varchar
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_link
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_link_attribute_decimal
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_link_attribute_int
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_relation
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: catalog_product_website
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: cataloginventory_stock_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: search_query
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: cms_block
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: cms_block_store
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: cms_page
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: cms_page_store
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: session
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_coupon_aggregated
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_coupon_aggregated_updated
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: eav_attribute_option
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: eav_attribute_option_value
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: newsletter_subscriber
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: oauth_nonce
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: product_alert_stock
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: report_compared_product_index
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: report_event
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: report_viewed_product_index
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_bestsellers_aggregated_daily
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_bestsellers_aggregated_monthly
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_bestsellers_aggregated_yearly
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_invoice
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_invoice_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_address
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_payment
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_status_history
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: quote
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: quote_address
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: quote_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: quote_item_option
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: quote_payment
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: quote_shipping_rate
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipment
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipment_comment
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipment_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipment_track
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_invoiced_aggregated
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_invoiced_aggregated_order
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_aggregated_created
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_aggregated_updated
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_tax
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_tax_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_payment_transaction
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipping_aggregated
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipping_aggregated_order
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_coupon
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_coupon_usage
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_customer
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_customer_group
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_label
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_product_attribute
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: salesrule_website
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: tax_order_aggregated_created
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: tax_order_aggregated_updated
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: wishlist
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: wishlist_item
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: wishlist_item_option
> [2017-05-25 14:22:41][WARNING]: Volume Check failed
> [2017-05-25 14:22:41][INFO][mode: delta][stage: delta delivering][step: Log Step]: started
> [2017-05-25 14:22:41][INFO][mode: delta][stage: volume check][step: Log Step]: started
> 
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: customer_visitor
> [2017-05-25 14:22:41][WARNING]: Volume Check failed
> [2017-05-25 14:22:41][INFO][mode: delta][stage: delta delivering][step: OrderGrids Step]: started
> [2017-05-25 14:22:41][INFO][mode: delta][stage: volume check][step: OrderGrids Step]: started
> 
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_order_grid
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_invoice_grid
> [2017-05-25 14:22:41][WARNING]: Mismatch of entities in the document: sales_shipment_grid
> [2017-05-25 14:22:41][WARNING]: Volume Check failed
> [2017-05-25 14:22:41][INFO][mode: delta][stage: delta delivering][step: SalesIncrement Step]: started
> [2017-05-25 14:22:41][INFO][mode: delta][stage: volume check][step: SalesIncrement Step]: started
> 
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-25 14:22:41][WARNING]: Mismatch in last increment id of order entity
> [2017-05-25 14:22:41][WARNING]: Mismatch in last increment id of invoice entity
> [2017-05-25 14:22:41][WARNING]: Mismatch in last increment id of shipment entity
> [2017-05-25 14:22:41][WARNING]: Volume Check failed
> [2017-05-25 14:22:41][INFO][mode: delta][stage: volume check][step: SalesIncrement Step]: Migration completed successfully
> [2017-05-25 14:22:41][INFO][mode: delta][stage: volume check][step: SalesIncrement Step]: Automatic restart in 5 sec. Use CTRL-C to abort
> [2017-05-25 14:22:46][INFO][mode: delta][stage: delta delivering][step: Customer Attributes Step]: started
> [2017-05-25 14:22:46][INFO][mode: delta][stage: volume check][step: Customer Attributes Step]: started
> 
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-25 14:22:47][WARNING]: Mismatch of entities in the document: customer_entity
> [2017-05-25 14:22:47][WARNING]: Mismatch of entities in the document: customer_entity_varchar
> [2017-05-25 14:22:47][WARNING]: Mismatch of entities in the document: customer_address_entity
> [2017-05-25 14:22:47][WARNING]: Volume Check failed
> [2017-05-25 14:22:47][INFO][mode: delta][stage: delta delivering][step: Map Step]: started
> [2017-05-25 14:22:47][INFO][mode: delta][stage: volume check][step: Map Step]: started

(sorry for the long output)

I didn't find any info on what '_Volume Check failed_' exactly means, and what I notice is that the output seems a loop as it's outputting all the time the same warnings.

**Comment by victor-v-rad** [comment]
Hi @Croxarens 

'delta' mode continues in a loop until CTRL-C is pressed. [The doc](http://devdocs.magento.com/guides/v2.1/migration/migration-migrate-delta.html). Warnings you see e.g.
```
[2017-05-25 14:22:47][WARNING]: Mismatch of entities in the document: customer_entity
```
means number of records in M1 and M2 of customer_entity are not equal. Check this table in both DB for the differences. Maybe you added some customer to your M2 in order to test the store

**Comment by Croxarens** [comment]
Hi @victor-v-rad ,

I checked the M2 DB and the last record in each of the following tables 

- _customer_entity_
- _customer_entity_varchar_
-  _customer_address_entity_ 

is in the M1 DB, just it's not the last one.

Table structures between M1 and M2 is different for those tables, but I don't think is a problem from the moment the settings and data migration was fine.

**Comment by Croxarens** [comment]
Is it correct that all the **m2_cl_** tables are empty?

**Comment by victor-v-rad** [comment]
the tool empty these tables as soon as delta records are delivered to M2 store

**Comment by Croxarens** [comment]
Hey @victor-v-rad ,

I tried with a vanilla installation and still getting the same error when I run the delta migration.

> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_invoiced_aggregated

> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_invoiced_aggregated_order
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_order_aggregated_created
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_order_aggregated_updated
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_order_tax
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_order_tax_item
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_payment_transaction
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_shipping_aggregated
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_shipping_aggregated_order
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_coupon
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_coupon_usage
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_customer
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_customer_group
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_label
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_product_attribute
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: salesrule_website
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: tax_order_aggregated_created
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: tax_order_aggregated_updated
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: wishlist
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: wishlist_item
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: wishlist_item_option
> [2017-05-30 11:12:57][WARNING]: Volume Check failed
> [2017-05-30 11:12:57][INFO][mode: delta][stage: delta delivering][step: Log Step]: started
> [2017-05-30 11:12:57][INFO][mode: delta][stage: volume check][step: Log Step]: started
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: customer_visitor
> [2017-05-30 11:12:57][WARNING]: Volume Check failed
> [2017-05-30 11:12:57][INFO][mode: delta][stage: delta delivering][step: OrderGrids Step]: started
> [2017-05-30 11:12:57][INFO][mode: delta][stage: volume check][step: OrderGrids Step]: started
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_order_grid
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_invoice_grid
> [2017-05-30 11:12:57][WARNING]: Mismatch of entities in the document: sales_shipment_grid
> [2017-05-30 11:12:57][WARNING]: Volume Check failed
> [2017-05-30 11:12:57][INFO][mode: delta][stage: delta delivering][step: SalesIncrement Step]: started
> [2017-05-30 11:12:57][INFO][mode: delta][stage: volume check][step: SalesIncrement Step]: started
> 100% [============================] Remaining Time: 1 sec 
> [2017-05-30 11:12:57][WARNING]: Mismatch in last increment id of order entity
> [2017-05-30 11:12:57][WARNING]: Mismatch in last increment id of invoice entity
> [2017-05-30 11:12:57][WARNING]: Mismatch in last increment id of shipment entity
> [2017-05-30 11:12:57][WARNING]: Volume Check failed
> [2017-05-30 11:12:57][INFO][mode: delta][stage: volume check][step: SalesIncrement Step]: Migration completed successfully
> [2017-05-30 11:12:57][INFO][mode: delta][stage: volume check][step: SalesIncrement Step]: Automatic restart in 5 sec. Use CTRL-C to abort


Am I doing something wrong?
M2 installation, setting migration, data migration, reindex database, clear cache and delta migration.

**Comment by rg-srini** [comment]
@Croxarens - Did you get this issue sorted out. We also facing the same issue (#316).

**Comment by Croxarens** [comment]
Hi @rg-srini ,

No, unfortunately we still working on it with no success..

I'll keep this issue updated in case we found something..

**Comment by victor-v-rad** [comment]
@Croxarens see the last comments in 316. Might help

**Comment by Croxarens** [comment]
@victor-v-rad thanks!
