### ISSUE TITLE
Version dependency should be reflected in composer.json

### ISSUE THREAD

**Issue by fooman** [magento/data-migration-tool#308]
The instructions state:

> The versions of both the migration tool and the Magento 2 code must be identical

it would be great to have this reflected in the `composer.json` dependencies to prevent the wrong version being installed/used.

To state differently if I run `composer require magento/data-migration-tool` the version constraints should take care and only allow the correct version to get installed.

**Comment by victor-v-rad** [comment]
In most cases not so critical for the patch versions. On the contrary, minor version of the tool and Magento 2 should be the same. It is because of much changes usually done to Magento 2 and the tool likely wont work.

**Comment by fooman** [comment]
Not sure that I understand @victor-v-rad. Aligning on the patch version is not a problem with composer. So for example
   
   "name": "magento/data-migration-tool",
    "version": "2.1.6",
    "require": {
        "magento/product-community-edition": "2.1.6"
    }

would mean that version 2.1.6 of the data migration tool can only be installed when the dependency product community edition is also installed at version 2.1.6.

**Comment by victor-v-rad** [comment]
I adjusted a bit my initial comment. Anyway, thank you for the proposal. Though it might be better not to strict versions of the tool and Magento in composer and give some freedom to choose.

**Comment by fooman** [comment]
@victor-v-rad I am afraid you are adding more confusion right now. Are you saying any patch version 2.1.x of the data-migration-tool will work with any patch version 2.1.y of Magento core?

If that is the case the following can be added to the composer.json file:

```
"name": "magento/data-migration-tool",
"version": "2.1.5",
"require": {
    "magento/product-community-edition": "2.1.*"
}
```

```
"name": "magento/data-migration-tool",
"version": "2.1.6",
"require": {
    "magento/product-community-edition": "2.1.*"
}
```
This comment here

>Though it might be better not to strict versions of the tool and Magento in composer and give some freedom for user to choose.

To me contradicts the readme and devdocs - so maybe those need to be amended?

Or if you are talking about forward compatibility you could do something like this:

```
"name": "magento/data-migration-tool",
"version": "2.1.5",
"require": {
    "magento/product-community-edition": "~2.1.5"
}
```
which allows you to install version 2.1.5 of the data-migration-tool into Magento 2.1.5 and Magento 2.1.6, etc but not into Magento 2.2.x.
