### ISSUE TITLE
Duplicate URL rewrites - false positive?

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#31]
This is throwing errors but I check my DB and I don't have duplicates, it seems to be ignoring after the slash:

```
There are duplicates in URL rewrites: Request path: vcc-08-competition Store ID: 1 Target path: competitions/index/index/id/vcc-08-competition Request path: vcc-08-competition Store ID: 1 Target path: cms/page/view/page_id/124
```

However if I check my database for request path I only have:

```
vcc-08-competition/submit 
vcc-08-competition/success
vcc-08-competition/enter
vcc-08-competition
```

So it think vcc-08-competition is duplicate, because it's not 

Setting auto_resolve_urlrewrite_duplicates to 1 in config.xml seems to resolve the integrity check, Will know more when I can actually complete migration to the next stage.

**Comment by hws47a** [comment]
After upgrade migration tool to 2.0.2 still have related issue:

>   [PDOException]                                                                                                                      
>   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'female/edits-1' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'

for data in source db ![](https://www.dropbox.com/s/iq8o3e5d80pb0da/Screenshot%202016-02-12%2021.41.47.png?dl=1)
