### ISSUE TITLE
How to create custom step

### ISSUE THREAD

**Issue by diazwatson** [magento/data-migration-tool#311]
Is there documentation related or could you guys point in the right direction of how to create custom steps?

Let say I have table A in M1 and I need to move that table to M2 performing some modifications to the data but I don't want to use Map Step for it.

Wouldn't it make much more sense to just write a small step for it? 

Thanks in advance.

**Comment by victor-v-rad** [comment]
Hi @diazwatson 

[Technical Specification](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-internal-spec.html) may give you some insights. Сreating your own steps is easy thing. Open your config.xml and you will see how it is done. Also your classes must implements StageInterface

**Comment by diazwatson** [comment]
Hi @victor-v-rad
I managed to create a custom step looking at the steps already defined inside `src\Migration\Step\*` thanks anyway.

But I didn't know about the technical specification docs. I will have a look.
