### ISSUE TITLE
How can I migrate magento ee 1.x version to magento 2.x CE version?

### ISSUE THREAD

**Issue by prdptom** [magento/data-migration-tool#315]
Right now what I have done is migrate magento 1.x EE to Magento 1.9.1.0 CE version and then migrate it to magento 2.1.5. The migration from EE to 1.9 CE works perfectly but when I use migration tool, a lot of error are thrown and when I add tables to ignore in map files, the migration process completes but customers are not migrated to 2.1.5.

Is there any other way to complete migration without errors.

**Comment by victor-v-rad** [comment]
Hi @prdptom 

Do you see any records in customer_entity and customer_address_entity tables of the migrated store?

**Comment by prdptom** [comment]
@victor-v-rad 

Thanks for the reply. I just checked and saw the entries are there inside the database. However in customer_entity table as well as in customer_address_entity, the field increment_id is NULL which is probably why it is not shown in admin.

How can I have values inside incremental id?

**Comment by victor-v-rad** [comment]
>  the field increment_id is NULL

It will be NULL even if creating a new customer on an empty Magento 2 instance. So it seems OK. I would suggest running cleaning cache, reindexing and run cron
`php bin/magento cache:flush && php bin/magento indexer:reindex && php bin/magento cron:run && php bin/magento cron:run`

**Comment by prdptom** [comment]
@victor-v-rad 

I executed all the commands but still the increment_id column has null value. I checked the database and found that the A_I (auto increment) is not given to the column. 

Will making those columns A_I before starting migration would help it?

**Comment by prdptom** [comment]
@victor-v-rad 

I did that and now the customer page in admin shows 'No such entity'  . Tried to solve it but it has been futile so far.
I ran this code in mysql
```
SET FOREIGN_KEY_CHECKS=0;
UPDATE `store` SET store_id = 0 WHERE code='admin';
UPDATE `store_group` SET group_id = 0 WHERE name='Default';
UPDATE `store_website` SET website_id = 0 WHERE code='admin';
UPDATE `customer_group` SET customer_group_id = 0 WHERE customer_group_code='NOT LOGGED IN';
SET FOREIGN_KEY_CHECKS=1;
```
0 rows were affected. 
What could cause this error?
