### ISSUE TITLE
Ignore categories in data migration.

### ISSUE THREAD

**Issue by karthi5053** [magento/data-migration-tool#318]
Hi Victor,

Is it possible to ignore categories during data migration?

Regards,
Karthi Kumar.

**Comment by victor-v-rad** [comment]
Though the tool does not provide such feature out of the box, you can 
- add a new step in the tool which 
-- calls \Migration\ResourceModel\Adapter\Mysql::setForeignKeyChecks(1) 
-- deletes the migrated categories
- delete the categories manually after migration
