### ISSUE TITLE
Is it possible to delta only specific information

### ISSUE THREAD

**Issue by aaronware** [magento/data-migration-tool#319]
Wondering if it's possible to define steps to only include customer related information (orders, invoices, account creation, rewards points EE, etc).

Yet ignore any other changes that have been made been v1 and v2 after an an initial migration has been done.

**Comment by victor-v-rad** [comment]
This is what exactly delta is responsible for. To catch all the actions made in FrontStore and order processing in Admin Panel. Please refer to [Migration Guide](http://devdocs.magento.com/guides/v2.1/migration/bk-migration-guide.html) for the details.

**Comment by aaronware** [comment]
@victor-v-rad thanks for the high level. But I guess I was being more specific. I read through the guide but it wasn't all that specific either. I guess my question was can I pick and choose which data to delta against and ignore everything else. In a related Question #318 our new setup has different categories than the old one so we don't want to migrate those, or products because we have already done it and change attributes etc. The only thing we are really interested in is customer data, orders etc.

**Comment by victor-v-rad** [comment]
@aaronware you can find the list of M1 tables are processed by delta in deltalog.xml.dist

**Comment by diazwatson** [comment]
@victor-v-rad Looking at deltalog.xml.dist I can see no cms content is processed by the delta step.
Can you confirm this?
