### ISSUE TITLE
Customer details not updating after data migration.

### ISSUE THREAD

**Issue by karthi5053** [magento/data-migration-tool#323]
Hi Victor,

We have successfully migrated data from Magento 1.4.0 EE to Magento 2.1.4 EE.
Upon updating custom customer attribute from admin or frontend, the migrated data of custom customer attribute disappeared.
We are not able to update custom customer attribute both from frontend and admin.

Regards,
Karthi kumar

**Comment by victor-v-rad** [comment]
Hi @karthi5053 
The latest Data Migration Tool 2.1.7 should contain the fix. You can use it with your Magento 2.1.4 EE if you do not want to use Magento 2.1.7

**Comment by rg-srini** [comment]
@victor-v-rad : We are in the delta phase and we realized this issue only now.  Is it okay to upgrade the migration tool via composer now and run delta  command with this 2.1.7?

Or should we try the migration with the new tool 2.1.7 from the beginning? Our client is giving up confidence now on the migration tool and worrying on the process. 

Is there an easy fix to correct on the DB directly?

**Comment by victor-v-rad** [comment]
@karthi5053 @rg-srini 
You can try to fix it manually. The main idea is to change in migrated DB eav_entity_type.default_attribute_set_id field values of customer and customer_address entity types. So that they will contain ids of attribute sets from Magento 1. Probably right now these ids point to Magento 2 attribute sets. To find the right ids open migrated eav_attribute_set table and find attribute set with "Migration_" prefix. These one are from Magento 1. Flush cache and recheck saving a customer.

**Comment by rg-srini** [comment]
Thanks for the quick response. Will try out.

**Comment by rg-srini** [comment]
Forgot to ask. Will this affect our future delta updates?

**Comment by victor-v-rad** [comment]
> Forgot to ask. Will this affect our future delta updates?

No, it should not. 

One more thing you should do. Look at this commit bfee89d . Before the fix, all migrated records from eav_attribute_group table obtained  **0** for default_id field. I removed this operation from xml as part of the fix. So in migrated store you should restore default_id values just like it is in your Magento 1.

**Comment by karthi5053** [comment]
Hi Victor,

We are trying out the proposed solution, meanwhile a small doubt.
Our client has planned to upgrade magento EE version from 2.1.4 to 2.1.7.
Do we need to upgrade Data migration tool from 2.1.4 to 2.1.7 or we can continue with 2.1.4 for delta updates.

Regards,
Karthi Kumar.

**Comment by victor-v-rad** [comment]
I do not see any problems if you continue with the tool 2.1.4 for delta updates

**Comment by karthi5053** [comment]
@victor-v-rad Thanks for the quick response.

**Comment by rg-srini** [comment]
@victor-v-rad : Thanks for the fix suggested. That has worked. We updated the attribute_set_id and it worked.

**Comment by victor-v-rad** [comment]
Glad to know it helped )

**Comment by imrandotftr** [comment]
Hi Victor,

We have successfully migrated data from Magento 1.13.0.2 EE to Magento 2.3.4 EE cloud version.
We are not able to update custom customer attribute both from frontend and admin.

Regards,
Imran Ansari

**Comment by victor-v-rad** [comment]
Hi @imrandotftr 

Please use the latest Magento 2.3.5 and DMT 2.3.5 it has a lot of changes into migrated EAV and the issue you have should be fixed there

**Comment by ArpitTiwari9555** [comment]
Hi @victor-v-rad 

We have used Magento 2.3.5 and DMT 2.3.5 .The new customer attributes which we are creating are working now but the migrated attributes are not working even after my migration completed properly without giving issue in the attributes step. The attributes are migrated but not saving the data the attributes are showing on the admin and frontend too but not saving any data to the database.

Regards,
Arpit Tiwari

**Comment by vimal-ranosys** [comment]
Hi @victor-v-rad 

Can you please advise on same issue as metioned by Arpit?
