### ISSUE TITLE
Migrating from 1.9.2.0 to Magento 2.1.7: attributeSetId no such entity

### ISSUE THREAD

**Issue by Mgrennes** [magento/data-migration-tool#324]
I was able to successfully migration from 1.9.2.0 to 2.1.7, but there's only one problem, I have no AttributeSets (even the default attributeSet is missing). This mean that I can't add new products, nor edit them. 

This is the message that I got when the migration completed:
`[2017-07-01 19:17:22][WARNING]: Mismatch of entities in the document: report_event
[2017-07-01 19:17:22][WARNING]: Mismatch of entities in the document: report_viewed_product_index
[2017-07-01 19:17:22][WARNING]: Volume Check failed
`

This is the log that get generated when I try to add or edit a product. Even adding a new product will fail since there is no default attributeSet.

`a:4:{i:0;s:38:"No such entity with attributeSetId = 4";i:1;s:9397:"#0 /home/website/dev.website.com/public_html/vendor/magento/module-eav/Model/Attribute/GroupRepository.php(116): Mage
nto\Framework\Exception\NoSuchEntityException::singleField('attributeSetId', 4)
#1 /home/website/dev.website.com/public_html/vendor/magento/module-catalog/Model/ProductAttributeGroupRepository.php(57): Magento\Eav\Model\Attribute\GroupRepository->getList(Object(Ma
gento\Framework\Api\SearchCriteria))
#2 /home/website/dev.website.com/public_html/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(426): Magento\Catalog\Model\ProductAttributeGroupRepository->ge
tList(Object(Magento\Framework\Api\SearchCriteria))
#3 /home/website/dev.website.com/public_html/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Eav.php(241): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Eav
->getGroups()
#4 /home/website/dev.website.com/public_html/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(68): Magento\Catalog\Ui\DataProvider\Product\Form\Modifi
er\Eav->modifyMeta(Array)
#5 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(269): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMet
a()
#6 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('produc
t_form', Array, false)
#7 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('product_for
m', NULL, Array)
#8 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(
Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#9 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Fra
mework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#10 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\R
eader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#11 /home/website/dev.website.com/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#12 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#13 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#14 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#15 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#16 /home/website/dev.website.com/public_html/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#17 /home/website/dev.website.com/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#18 /home/website/dev.website.com/public_html/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#19 /home/website/dev.website.com/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_
Catalog...')
#20 /home/website/dev.website.com/public_html/vendor/magento/module-catalog/Controller/Adminhtml/Product/NewAction.php(85): Magento\Backend\Model\View\Result\Page\Interceptor->setActiv
eMenu('Magento_Catalog...')
#21 /home/website/dev.website.com/public_html/var/generation/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Ne
wAction->execute()
#22 /home/website/dev.website.com/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->execute()
#23 /home/website/dev.website.com/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Requ
est\Http))
#24 /home/website/dev.website.com/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Reque
st\Http))
#25 /home/website/dev.website.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callPare
nt('dispatch', Array)
#26 /home/website/dev.website.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', '
dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Array, 'adminAuthentica...')
#27 /home/website/dev.website.com/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Int
erception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/website/dev.website.com/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento
\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/website/dev.website.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...',
'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Array, 'adminMassaction...')
#30 /home/website/dev.website.com/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor-
>Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/website/dev.website.com/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento
\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/website/dev.website.com/public_html/var/generation/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Ne
wAction\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /home/website/dev.website.com/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->dispatch(Object(`

Thanks for helping :)

**Comment by victor-v-rad** [comment]
Hi @Mgrennes 

Are there any records in migrated eav_attribute_set table?

**Comment by Mgrennes** [comment]
Hi @victor-v-rad,

Let me do the migration once more, since I deleted the old database. I'll report once I have done so.

Many thanks :)

**Comment by Mgrennes** [comment]
Hi @victor-v-rad,
I was able to successfully migrate ALL data with a newly installed database. I did the exact same install and this time, it worked.

I had to make sure that I update these files:
/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.0/config.xml
/vendor/magento/data-migration-tool/etc/ce-to-ce/class-map.xml.dist
/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.0/map.xml.dist

Thanks for getting back to me :)

Marc,
