### ISSUE TITLE
Migrating settings & data creates duplicate websites and stores

### ISSUE THREAD

**Issue by OZZlE** [magento/data-migration-tool#328]
Magento CE 1.9.1.1 to 2.1.7

Before:
![image](https://user-images.githubusercontent.com/893783/27909128-808fc5da-624f-11e7-892c-0179112ea4b0.png)
After:
![image](https://user-images.githubusercontent.com/893783/27909155-953a8d8a-624f-11e7-8602-e6084f22d8e3.png)

Command: `sudo -H -u www-data php bin/magento migrate:setting --reset app/migration/1.9.1.1/config-dev-m1-local.xml && echo ; sudo -H -u www-data php bin/magento migrate:data app/migration/1.9.1.1/config-dev-m1-local.xml && echo`

map.xml (changes from .dist)
```
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../map.xsd">
    <source>
        <document_rules>
++            <ignore>
++                <document>core_config_data</document>
++            </ignore>
```
map-eav.xml
```
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../map.xsd">
    <source>
        <document_rules>
++            <ignore>
++                <document>core_config_data</document>
++            </ignore>
```

**Comment by OZZlE** [comment]
Or is it a UX problem that it looks like duplicates because they have two storeviews?

**Comment by OZZlE** [comment]
Seems like it's only confusing design in M2..

**Comment by sb-rustam** [comment]
Hi @ OZZlE,

I was so excited when I saw your post, you noted that you multiple websites under one Magento 1.x core. It seems like it was related (similar) to our data migration process.  Here is our overall data migration plan:

Currently we are in process of migrating our Magento 1.14.3.8 websites into Magento 2.2.3 platform. We have 3 running websites under one Magento 1.x instance, each website has it’s own customers, products and orders. The plan was to migrate and launch these websites in phase approach (one by one). For example:

Website-1 will be launched in May 
Website-2 will be launched in August 
Website-3 will be launched in December

So we will run the data migration tool to migrate everything at once and after that it will be a multi-month migration with deltas, 3-4 months gap between each website launch time, about 1 year to launch all of these websites in Magento2 and terminate Magento 1.x instance.

The current Magento 1.14.3.8 instance will be running until all of these websites will be migrated over to Magento 2.x.x. For example, once the website-1 will be launched in Magento2 the website-2 and 3 will still be running on Magento 1.14.3.8 instance and so on. This Magento 1.14.3.8 instance will be stopped once all of these 3 websites will be moved/launched in Magento 2.

I was wondering if I can run Magento data migration tool prior to launching the website-1, which should migrate the following data for all of these 3 websites, at once:

- stores/websites settings 
- the main data (like customers, orders, products and etc.)

and I want to keep running the delta migration until all 3 of these websites will be launched in Magento2.

Would you please advise me if this would be possible? If this approach doesn't work, then would you please provide more info regarding to potential issues or any workarounds?

Thank you in advance,
Rustam.

**Comment by OZZlE** [comment]
@sb-rustam Sounds like a bad idea.. The migration tool is quite simple. It maps M1 order ID's with M2 order ID. So as soon as you have occupied an ID in M2, for example the first website to golive gets new orders and the old M1 site gets new order both with the same ID; Then you will not be able to run the delta migration.

Check other issues I have created. But this is NOT a support channel, it's for reporting bugs! You have to do your own work yourself.
