### ISSUE TITLE
Migrate settings ERROR PDO 

### ISSUE THREAD

**Issue by cdpi404** [magento/data-migration-tool#331]
Hello when i'm trying to execute the command line :  php bin/magento migrate:settings -r vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.3/config.xml

I always have those error : 

[Zend_Db_Adapter_Exception]
  SQLSTATE[HY000] [2002] Connection refused

  [PDOException]
  SQLSTATE[HY000] [2002] Connection refused

Anyone have a solution for this problem ? i've tested in a local magento 2 and now i'm on a VPS

my php.ini form phpinfo.php is here : /etc/php/7.0/apache2/php.ini
and in the grep command : /etc/php/7.0/cli/php.ini

**Comment by victor-v-rad** [comment]
Hi @cdpi404 
Try to connect with the same login/password/host by 'mysql' command from the host where the tool is installed

**Comment by cdpi404** [comment]
The tool is on my VPS and i can connect to mysql, but there is still this problem, perhaps it's not the host but the one that I want to migrate ?

**Comment by hostep** [comment]
Just FYI, ran into the same problem, only on localhost, I was using '127.0.0.1' as host instead of 'localhost', using '127.0.0.1' gives this problem. Not sure if this is helpful for @cdpi404.
