### ISSUE TITLE
store view  switcher not visible on page header

### ISSUE THREAD

**Issue by bilalusean** [magento/data-migration-tool#332]
I migrated data from **1.9.3.3CE** to **2.1.7EE**, 

The problem is **store view  switcher** not visible on page header, by default **magento luma** display **store view switcher drop down** on page header.

When I check  in **Admin -> Stores -> All Stores**, It have five store views.

I hope there is no settings to enable/disable store view switcher so I think it must be a bug in **data-migration-tool**

could you please suggest to how to solve this issue?

**Comment by victor-v-rad** [comment]
I have tried migration from 1.9.2.1 CE to 2.1.7 EE and got no problem with store view switcher on Lumia theme. Cleaning cache and reindexing might help
