### ISSUE TITLE
Magento order_id Error

### ISSUE THREAD

**Issue by prdptom** [magento/data-migration-tool#333]
Hello,

I have magento 2.1.5 installation which was migrated from magento 1.9.1

When a customer who had ordered in the previous version, place an order in the magento 2.1.5 site, the order_id is assigned as the same order id of the last order which was placed in older website instead of the value from sequence_order_1 and the details are not updated in magento 2.1.5.

Paymenis made without any issue but since the database already has order_id, no order is saved.

**Comment by victor-v-rad** [comment]
Tried to produce your issue. But the second order which was placed on migrated store got order_id = 2 and the last record in sequence_order_1 table is 2 also
