### ISSUE TITLE
Document has ambiguous configuration

### ISSUE THREAD

**Issue by msyhr** [magento/data-migration-tool#334]
Attempting to migrate an existing M1 extension to M2 extensions tables. I've re-named the table to match the m2 extension and ignored the columns that I no longer need. However one column is needed, but has been renamed in the m2 version. Below is my xml that does not work. Is this incorrect?
```xml
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../map.xsd">
    <source>
        <document_rules>
        	<rename>
                <document>aw_points_summary</document>
                <to>aw_rp_points_summary</to>              
            </rename>
        </document_rules>
        <field_rules>
        	<move>
                <field>aw_points_summary.points_for_subscription_granted</field>
                <to>aw_rp_points_summary.is_awarded_for_newsletter_signup</to>
            </move>
        </field_rules>
    </source>
</map>
```
The command line tool returns this error:

`[ERROR]: Document has ambiguous configuration: aw_points_summary`

**Comment by simonrl** [comment]
Having the same error: move data to a new table, and rename columns at the same time.

1.9.2.4 -> 2.3.5 opensource-to-commerce

My setup is pretty similar to the one posted.

How did you solve this?

**Edit 1**: it should work exactly like this, according to the docs: https://devdocs.magento.com/guides/v2.3/migration/extend-the-tool.html

**Edit 2**: it was my mistake, i had the document ignored using a wildcard and thus didn't find it. Sorry.
