### ISSUE TITLE
[Exception]   Notice: Undefined offset: 4 in /home/m2demo/www/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 563

### ISSUE THREAD

**Issue by pmoreno1980** [magento/data-migration-tool#336]
PLease help!

workin in my migration from 1.9.2.1 to 2.1.7 and after work with "ignore" documents and fields i run this command php7 bin/magento migrate:data vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.1/config.xml and i get this error:

[Exception]
  Notice: Undefined offset: 4 in /home/m2demo/www/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 563

 the line is:  $attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode]

please can you help me with this, i was reading a lot of documentation but i can;t find the specific problem,

what means the "4" in Undefined offset: 4?

please let me know

**Comment by victor-v-rad** [comment]
Hi @pmoreno1980 

As a workaround you can try to remove/comment these two lines [523](https://github.com/magento/data-migration-tool/blob/2.1.7/src/Migration/Step/Eav/Data.php#L523) and [524](https://github.com/magento/data-migration-tool/blob/2.1.7/src/Migration/Step/Eav/Data.php#L524) after migration in admin panel move manually attribute 'price' into 'product-details' group and 'shipment_type' into 'bundle-items' group in the all attribute sets

**Comment by pmoreno1980** [comment]
thanks @victor-v-rad  i will try that and i will let you know.
