### ISSUE TITLE
delta migration - migrate products and catagories

### ISSUE THREAD

**Issue by MoMannn** [magento/data-migration-tool#337]
I know there is no way to migrate this currently but is there plan to incorporate this? or can anyone tell me in what way should I start if I would like to implement this myself?

**Comment by victor-v-rad** [comment]
Start to examine deltalog.xml and how 'delta' mode works

**Comment by gritdigital-mibu** [comment]
Hi @victor-v-rad,
Any chance you could elaborate on how to do this? I'm struggling to do the same thing and I see quite a few others online looking for a similar solution. Your time and efforts will be greatly appreciated!
Regards,

**Comment by victor-v-rad** [comment]
@gritdigital-mibu 
Though it is not supported out of the box but still can be done to my believe. 
rad_victor my skype
