### ISSUE TITLE
Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist

### ISSUE THREAD

**Issue by ashvinimarwal** [magento/data-migration-tool#338]
i have migrated magento data from 1.9.x to fresh magento 2.1.7 and now when i save new product it ive the following error
Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist
/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php
Kindly see the screenshot.
![28332101-1f778c4e-6c11-11e7-95c9-45bc656df73f](https://user-images.githubusercontent.com/5154042/28565426-d942ac02-7149-11e7-90d0-df2b6026b845.JPG)

Please help

**Comment by victor-v-rad** [comment]
Strange enough. The latest data migration tool should have converted "catalog/product_attribute_backend_media" M1 class name to empty string. Find this M1 class name in class-map.xml.dist. Also you can remove Magento\Catalog\Model\Product\Attribute\Backend\Media manually in your migrated Magento 2 store in eav_attribute, catalog_eav_attribute, customer_eav_attribute, eav_entity_type tables

**Comment by ashvinimarwal** [comment]
Thanks a lot @victor-v-rad , Now i can see products on frontend with images but now i'm getting new error while saving any product in backend.
See screenshot
![image](https://user-images.githubusercontent.com/5154042/28577880-9adf0362-7175-11e7-9824-0aec74920131.png)

**Comment by victor-v-rad** [comment]
Make sure you are using the latest version of the tool by checking out mage2_root/vendor/magento/data-migration-tool/composer.json file. There you should see "version": "2.1.7"

**Comment by ashvinimarwal** [comment]
Hello @victor-v-rad ,

I follwed the following setup to do the migration from magento 1.9.x to magento 2.0.7
**Steps**
1.Created the backup of magento live site as  /www/m1_live/
2.Installed the fresh copy of magento 2 on local as /www/m2_root/
3.Download the migration tool and extract that in magento 1 site as
 /www/m1_live/magento2_data_migration-0.1.25
4.Open the the path on browser as 127.0.0.1/m1_live/magento2_data_migration-0.1.25
and submitted the both database details
5.Followed the Next on each step.

I did this right ?

I have inserted new row for same attribute id(Media Gallery) in catalog_eav_attritbues table and now facing following issue on front end of some categories.

1 exception(s):
Exception #0 (ReflectionException): Class NULL does not exist

Exception #0 (ReflectionException): Class NULL does not exist
#0 /home/coolkidz/public_html/beta/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('NULL')
#1 /home/coolkidz/public_html/beta/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('NULL')
#2 /home/coolkidz/public_html/beta/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('NULL')
#3 /home/coolkidz/public_html/beta/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('NULL', Array)
#4 /home/coolkidz/public_html/beta/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('NULL', Array)
#5 /home/coolkidz/public_html/beta/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(498): Magento\Framework\Validator\UniversalFactory->create('NULL')
#6 /home/coolkidz/public_html/beta/var/generation/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php(1103): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getBackend()
#7 /home/coolkidz/public_html/beta/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(621): Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getBackend()
#8 /home/coolkidz/public_html/beta/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(505): Magento\Eav\Model\Entity\AbstractEntity->walkAttributes('backend/afterLo...', Array, NULL)

**Comment by victor-v-rad** [comment]
Following the official [Migration Guide](http://devdocs.magento.com/guides/v2.1/migration/bk-migration-guide.html) would be best.

**Comment by ashvinimarwal** [comment]
so i have to start it again ?

**Comment by ashvinimarwal** [comment]
so i have to start it again ?
any way to fix current site ?

**Comment by ashvinimarwal** [comment]
Thank you @victor-v-rad ,Issue is fixed now.
