### ISSUE TITLE
Missing input price on admin after migration

### ISSUE THREAD

**Issue by yosefkurniawan** [magento/data-migration-tool#339]
Hi, I have a problem on migration from CE 1.9.0.1 to CE 2.1.7. 
All data looks migrated successfully, such a categories, products, attribute & attribute set, customer, etc.
However I got problem with price input. It is missing from manage product page. It is happening on all attribute set, even on default M2 attribute set. But if I look on product grid on admin > products > catalog, the prices are there. Every product has price. Price seems successfully migrated but it is weird that the input price is missing from product management page.
Kindly help. any suggestion?

**Comment by victor-v-rad** [comment]
Hi @yosefkurniawan 

The tool moves 'price' attribute from 'Prices' attribute group of Magento 1 to 'Product Details' attribute group of Magento 2 in this [code line](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/Eav/Data.php#L523). So maybe it did not happen for some reason

**Comment by yosefkurniawan** [comment]
Hi @victor-v-rad 

In admin > store > attributes > attribute set > [my migrated attribute set from m1], I can see that the price has been moved to 'Product Details' attribute group. But somehow price input is missing when I try to edit or create product even with attribute set 'Default' which is the default one from Magento 2.

**Comment by victor-v-rad** [comment]
Price attribute shows without any problem on the clean (without extensions) Magento. Please share your findings if you resolved the issue
