### ISSUE TITLE
Migration_ Prefixed headings

### ISSUE THREAD

**Issue by LekeFly** [magento/data-migration-tool#34]
Why is this happening?

<img width="527" alt="screen shot 2015-12-30 at 01 31 28" src="https://cloud.githubusercontent.com/assets/219316/12044628/22ba81ee-ae95-11e5-9df7-7982f73011ed.png">

**Comment by craigcarnell** [comment]
@LekeFly Same issue here

**Comment by quangdog** [comment]
Same issue here.

**Comment by victor-v-rad** [comment]
It is because Magento 2 has its own attribute set that can't be easily merged with attribute set of Magento 1. You can remove this 'Migration_' prefix in admin panel of Magento 2 after migration.

**Comment by quangdog** [comment]
"1. You can remove this 'Migration_' prefix in admin panel of Magento 2 after migration." - can you be more specific?  Where/how do I make this change in the admin panel?

**Comment by quangdog** [comment]
Nevermind - I found it: Stores --> Attribute Set.

**Comment by ilol** [comment]
@LekeFly if you got an answer, please close the issue

**Comment by vcortez** [comment]
Does this affect Groups as this was prefixed as well?

**Comment by victor-v-rad** [comment]
You can rename Groups just like Attribute Sets. This issue with "Migrated_" prefix is planned to fix.

**Comment by fballiano** [comment]
Hi @victor-v-rad, is there a possibility to have an option to "overwrite" previous attribute sets/groups instead of having to manually change all of them to remove the "migration" prefix?

**Comment by victor-v-rad** [comment]
Hi @fballiano. There is https://github.com/magento/data-migration-tool/issues/627 to implement such behavior. The tool is open source and everyone is welcome to do contribution to improve it
