### ISSUE TITLE
after migration always store_id=0 while update product price from admin

### ISSUE THREAD

**Issue by bilalusean** [magento/data-migration-tool#342]
We migrated Magento 1.9.3.3 CE to Magento 2.1.7 EE. After migration, I have one weird issue.

I have two stores **English**(store_id=1), **French**(store_id=4). If I update the product price under **store_id=1** or **store_id=4**, It will always update the price of **default store(store_id=0)**.

Below controller trigger, while click save button

    http://host/admin/catalog/product/save/id/157/type/simple/store/1/set/12/key/5ecc5689598345dea76766a4c313be487ff26210431713bece6f1ea194e555f6/back/edit

product initialised from builder `vendor/magento/module-catalog/Controller/Adminhtml/Product/Builder.php`

    $product->setStoreId($request->getParam('store', 0));

`$request->getParam('store', 0)` it returns store=1 so here store_id set correctly but somehow it update only store_id=0 only.

Also tried like change the below line in

    vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php

From

    $product->save();

To

    $product->setStoreId(1);
    $product->save();

but still it is only update the price of **store_id=0**.

In the same controller `vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php` I tried like

    var_dump($product); //vardump1
    $product->save();
    var_dump($product); //vardump2

**vardump1**  :  In var_dump data, it correctly set price what I'm set in admin
**vardump2**  :  In var_dump data, it is not correctly set price 

>Note: price update only the problem, If I change the product name, It correctly update name as per the right store.

I'm trying to reproduce the issues in fresh magento install with sample data but can't so I think it may be bug in data migration tool.

**Comment by victor-v-rad** [comment]
Hi @bilalusean 

If you have Price setup in global scope Magento will save for store = 0 anyway. But after changing scope  per Website (in Configuration > Catalog > Price) you can save price for store > 0

**Comment by bilalusean** [comment]
OMG! thank you so much, it fixed!
