### ISSUE TITLE
Notice: Undefined offset: 44 in /vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on l   ine 563

### ISSUE THREAD

**Issue by Hobbit78** [magento/data-migration-tool#345]
Hi,

I'm trying to migrate my CE 1.9.0.1 database to 2.1.7.
Somehow i'm getting this error:

`Notice: Undefined offset: 44 in /vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on l   ine 563`

I run:
`bin/magento migrate:data -r vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.0.1/config.xml`

How to solve this problem?

**Comment by victor-v-rad** [comment]
Hi @Hobbit78 

Try to follow this advice https://github.com/magento/data-migration-tool/issues/301#issuecomment-304619179 and write back if it helped.

**Comment by Hobbit78** [comment]
Hi victor-v-rad,

Your mentioned advise [https://github.com/magento/data-migration-tool/issues/301#issuecomment-304619179](url) worked like a charm.
But need to to run migration on a fresh database after commenting out the mentioned lines.

Thanks for the help!

**Comment by cparadigm** [comment]
@Hobbit78 The link is now 404.

**Comment by LucasMaliszewski** [comment]
@Hobbit78 The link is now 404. Any chance I could trouble you for an update?
