### ISSUE TITLE
completed the data migration but the data is not migrated. Do I need to migrate the extentions to get all the data in the new magento 2.0.0 from 1.9.2.4

### ISSUE THREAD

**Issue by chiju** [magento/data-migration-tool#346]

**Comment by victor-v-rad** [comment]
We advice using the latest version of the tool. Currently it is 2.1.8 with the same version of Magento 2.1.8
Take a look at [Data Migration Guide](http://devdocs.magento.com/guides/v2.1/migration/bk-migration-guide.html). It contains many of the answers you would have.
