### ISSUE TITLE
Error thrown by delta command

### ISSUE THREAD

**Issue by rajansahota** [magento/data-migration-tool#348]
Source  Magento1 version 1.6.2.0   
Destination Magento2 version 2.1.7                                                                                                                                                                                 
Command : php bin/magento migrate:delta --reset vendor/magento/data-migration-tool/etc/ce-to-ce/1.6.2.0/config.xml

  [Zend_Db_Statement_Exception]                                                                                                                                                     
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'operation' in 'where clause', query was: SELECT `mgnt_sales_flat_order_2`.* FROM `mgnt_sales_flat_order`                  
   INNER JOIN `mgnt_sales_flat_order` AS `mgnt_sales_flat_order_2` ON mgnt_sales_flat_order.entity_id = mgnt_sales_flat_order.entity_id WHERE (`operation` in ('INSERT', 'UPDATE')  
  ) LIMIT 649                                                                                                                                                                       
                   
![screen shot 2017-08-14 at 2 47 30 pm](https://user-images.githubusercontent.com/5188276/29265713-acd31ef2-80ff-11e7-9b1a-df6ccda7a70f.png)

@victor-v-rad 
need your help, please help me.

**Comment by victor-v-rad** [comment]
Do you have another table for orders mgnt_sales_flat_order_2, apart from the main mgnt_sales_flat_order?

**Comment by rajansahota** [comment]
Hi @victor-v-rad , 
No, there is not any  mgnt_sales_flat_order_2 table.

**Comment by victor-v-rad** [comment]
Did you changed deltalog.xml.dist file?

**Comment by rajansahota** [comment]
@victor-v-rad 
No , I am not changed any thing in this file, just renamed deltalog.xml.dist to deltalog.xml

**Comment by rajansahota** [comment]
@victor-v-rad
any update? please advice.

**Comment by victor-v-rad** [comment]
>I have removed m2_cl hard coded prefix
>please advice

Most likely because of your amendments to the code of the tool

**Comment by rajansahota** [comment]
@victor-v-rad 

I want run delta command on products and category.
Do you have any advice and solution.
