### ISSUE TITLE
Migration from 1.9 to 2.1.7 wysiwyg product description formatting gone

### ISSUE THREAD

**Issue by KojoSlayer** [magento/data-migration-tool#349]
Product descriptions have lost all of the wysiwyg editor formatting (Bullet points,paragraphs, bold etc). The products still have listed stars next to the bullet points e.g:

```
* bullet one
* bullet two
* bullet three
```

Preconditions

Magento 1.9.1.0 migration to 2.1.7
PHP Version 7
Steps to reproduce

Run data migration tool on new 2.1.7 install from site with product description formatting
Check product descriptions after successful migration
Expected result

All formatting like bold and paragraphs to show on the product descriptions.
Actual result

Product descriptions show as blocks of text no formatting or bullet points etc apart from * character where bullet points were.
Hopefully I haven't just missed something here, no idea whats going on with it.

**Comment by victor-v-rad** [comment]
Just migrated to 2.1.8 . See the screenshot 
![1502971728806](https://user-images.githubusercontent.com/106504/29411621-50c0671c-835e-11e7-87d1-07b57b423cc9.jpg)

**Comment by wcladesh** [comment]
Hello @victor-v-rad ,
I have the same problem, In admin its display fine but on front-end, it's not working fine and bullets are just display as content.

Please check in your front-end you will definitely find the bug.

Also Please add any solution if you found the issue.

**Comment by sumeetmobiwebtech** [comment]
@KojoSlayer @wcladesh 
anyone got the solution ?
i am also facing same issues,my short and long description is missing HTML tags

**Comment by victor-v-rad** [comment]
Make sure it is not PageBuilder feature of Magento 2 which can cause it
