### ISSUE TITLE
Class adminhtml/catalog_product_helper_form_config does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer

### ISSUE THREAD

**Issue by diazwatson** [magento/data-migration-tool#351]
When migrating from Magento EE 1.14.2.3 to Magento EE 2.1.8 I got this message:

```
Class adminhtml/catalog_product_helper_form_config does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=110
Class adminhtml/catalog_product_helper_form_config does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=134
```
Those two attributes are:
- gift_message_available
- gift_wrapping_available

Looking at those attributes in M2 I can see that the class being used as `frontend_input_render` for both is `Magento\GiftWrapping\Block\Adminhtml\Product\Helper\Form\Config`

Is this the right class?
Can someone confirm this?
If so, why `adminhtml/catalog_product_helper_form_config` is not mentioned in `class-map.xml.dist`?

**Comment by victor-v-rad** [comment]
Thank you @diazwatson for sharing this fix. I believe it occurs for those who updated to 1.14.2.3 from previous versions. Because if I install Magento EE 1.14.2.3 these attributes get 
```
giftmessage/adminhtml_product_helper_form_config
enterprise_giftwrapping/adminhtml_product_helper_form_config
```
in frontend_input_renderer field and they are covered in class-map.xml.dist
Anyway, internal issue MAGETWO-71810 to fix your scenario.

**Comment by diazwatson** [comment]
Indeed, according to my repo, last update seems to be in:

`app/code/core/Mage/GiftMessage/sql/giftmessage_setup/mysql4-upgrade-0.7.3-0.7.4.php`

and

`app/code/core/Enterprise/GiftWrapping/sql/enterprise_giftwrapping_setup/mysql4-upgrade-1.10.0.0.4-1.10.0.0.5.php`
