### ISSUE TITLE
Data Migration tool to Magento EE 2.2

### ISSUE THREAD

**Issue by ngandara-summa** [magento/data-migration-tool#357]
Hi, today I started migrating from magento 1 EE 1.14.2.3 to magento 2 EE 2.2 and I found that the M2 EE 2.2 migration tool is not yet available. I would like to know when it will be available. Thank you.

**Comment by victor-v-rad** [comment]
release of the tool happens soon after release of the Magento 2

**Comment by FreekVandeursen** [comment]
Is there no Release Candidate for the data migration tool? For those of use who are currently testing / developing with the new 2.2 RC from Magento?

**Comment by victor-v-rad** [comment]
There is no such RC for the tool but this [branch](https://github.com/magento-panda/data-migration-tool/tree/MAGETWO-65087) is for 2.2 and it is in development
