### ISSUE TITLE
[ERROR]: "crypt_key" option is not defined the configuration

### ISSUE THREAD

**Issue by Bikermanirl** [magento/data-migration-tool#358]
Data migration is failing with the error 

 php bin/magento migrate:settings /home/user-name/public_html/v2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.6.0.0/config.xml

[2017-09-12 08:22:48][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
[2017-09-12 08:22:48][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
[2017-09-12 08:22:48][INFO][mode: settings][stage: data migration][step: Settings Step]: started
19% [=====>----------------------] Remaining Time: 1 sec
[2017-09-12 08:22:48][ERROR]: "crypt_key" option is not defined the configuration.

The local.xml is located at 
/home/user-name/public_html/app/etc/local.xml (permisions for the file are 644)

and has the following entry 

 ```
<crypt>
            <key><![CDATA[adfabde1a4e1533ec61eae16e58abb66]]></key>
        </crypt>
```

Crypt_key is specified under options in config.xml:

```
<options>

    <crypt_key>adfabde1a4e1533ec61eae16e58abb66</crypt_key>
        <map_file>etc/ce-to-ce/1.6.0.0/map.xml.dist</map_file>
        <eav_map_file>etc/ce-to-ce/map-eav.xml.dist</eav_map_file>
        <eav_document_groups_file>etc/ce-to-ce/eav-document-groups.xml.dist</eav_document_groups_file>
        <eav_attribute_groups_file>etc/ce-to-ce/eav-attribute-groups.xml.dist</eav_attribute_groups_file>
        <log_map_file>etc/ce-to-ce/map-log.xml.dist</log_map_file>
        <log_document_groups_file>etc/ce-to-ce/log-document-groups.xml.dist</log_document_groups_file>
        <settings_map_file>etc/ce-to-ce/settings.xml.dist</settings_map_file>
        <customer_map_file>etc/ce-to-ce/1.6.0.0/map-customer.xml.dist</customer_map_file>
        <customer_document_groups_file>etc/ce-to-ce/customer-document-groups.xml.dist</customer_document_groups_file>
        <customer_attribute_groups_file>etc/ce-to-ce/1.6.0.0/customer-attribute-groups.xml.dist</customer_attribute_groups_file>
        <delta_document_groups_file>etc/ce-to-ce/1.6.0.0/deltalog.xml.dist</delta_document_groups_file>
        <order_grids_document_groups_file>etc/ce-to-ce/order-grids-document-groups.xml.dist</order_grids_document_groups_file>
        <map_document_groups>etc/ce-to-ce/map-document-groups.xml.dist</map_document_groups>
        <class_map>etc/ce-to-ce/class-map.xml.dist</class_map>
        <tier_price_map_file>etc/ce-to-ce/map-tier-price.xml.dist</tier_price_map_file>
        <!--
        In case bulk_size=0 it will be auto-detected for every document.
        -->
        <bulk_size>0</bulk_size>
```
Is this an issue with the tool or is there something wrong with my configuration

**Comment by victor-v-rad** [comment]
Hi @Bikermanirl 
Sorry for the late reply. From the first glance your config is correct. I've rechecked this option in my instance and it works well.

**Comment by Bikermanirl** [comment]
I got it to work by deleting the line  <crypt_key /> at the bottom of the options
