### ISSUE TITLE
how to install data migration tool

### ISSUE THREAD

**Issue by rapolumadhu34** [magento/data-migration-tool#363]
i'm downloaded this zip file, and uploaded in my project cpanel root folder, next what i'm doing i don't understand. anyone please help me

**Comment by rapolumadhu34** [comment]
![image](https://user-images.githubusercontent.com/32007894/30589321-a61ed8ac-9d57-11e7-8f33-d4cacf9e2f33.png)

**Comment by victor-v-rad** [comment]
[Install Data Migration Tool](http://devdocs.magento.com/guides/v2.1/migration/migration-tool-install.html)

**Comment by rapolumadhu34** [comment]
without commands we need installation. i'm already downloading magento 2.1.9 ce
installation is done.

**Comment by rapolumadhu34** [comment]
next this migration tool also downloaded, and we place the root folder after what i do.

**Comment by rapolumadhu34** [comment]
![image](https://user-images.githubusercontent.com/32007894/30742876-e2ee8ce2-9fb8-11e7-835e-bda5c02be9ce.png)

**Comment by rapolumadhu34** [comment]
how to fix this issue, my magento ver 1.9.3.2   migrate ver is magento 2.1.9     data migration tool ver also 2.1.9
