### ISSUE TITLE
how to fix this issue 

### ISSUE THREAD

**Issue by rapolumadhu34** [magento/data-migration-tool#364]
![image](https://user-images.githubusercontent.com/32007894/30743565-de1f6396-9fbb-11e7-8fa1-108be2ffc318.png)

**Comment by rapolumadhu34** [comment]
my magento ver is 1.9.3.2 migrate ver is 2.1.9 data-migration-tool ver is 2.1.9

**Comment by victor-v-rad** [comment]
Hi @rapolumadhu34 

As a workaround you can try to remove/comment these two lines [523](https://github.com/magento/data-migration-tool/blob/2.1.7/src/Migration/Step/Eav/Data.php#L523) and [524](https://github.com/magento/data-migration-tool/blob/2.1.7/src/Migration/Step/Eav/Data.php#L524) after migration in admin panel move manually attribute 'price' into 'product-details' group and 'shipment_type' into 'bundle-items' group in the all attribute sets

**Comment by victor-v-rad** [comment]
#336 duplicate
