### ISSUE TITLE
Magento 2 - update & data migration from 1.9.2.0 to 2.1.9 - can't edit category

### ISSUE THREAD

**Issue by mrABR** [magento/data-migration-tool#369]
I have a Magento 1.9.2.0 that's filled with categories, users, sales, products, etc. I also have a Magento 2.1.3 that is a fresh install. I've used the Data Migration Tool from Magento to import every content of the old version into the new.

First, I've updated Magento 2.1.3 -> 2.1.9. All good so far. Then, I installed Data Import Tools, configured the connection, ran the migration and it successfully imported everything from 1.9.2.0 to the new 2.1.9. All good so far.

What happens next is whenever I create a category, it creates without a name. I can't change its name nor Anchor, but I can change its position and add/remove products to it. Going on the admin panel to make these changes, it says it was updated successfully, but it wasnt. I've ruled out cache issue and what it appears to be (as I was playing around with catalog_category_entity_varchar) is that somehow, whenever I create a category, it doesn't insert into this table their attributes and values.

All other tables, like sales, customer, products, are working as expected.

Any ideas or solutions? I've gone to the length of trying chmod 777 to every single file (just in case it was a permission issue) without success.

http://devdocs.magento.com/guides/v2.0/migration/migration-tool-internal-spec.html

**Comment by victor-v-rad** [comment]
Were there any errors from Data Migration Tool when you migrated your Magento 1?

**Comment by mrABR** [comment]
It did, I had to place some ignores, as described below.

on ignore document in destination (map.xml)
magestore_bannerslider_banner
magestore_bannerslider_report
magestore_bannerslider_slider
magestore_bannerslider_value

on ignore document_rules in source (same file)

core_file_storage	      		   
lof_slider_banner
mksresponsivebannerslider
permission_block
permission_variable

Thought maybe some of these tables , such as permission_block and permission_variable, but my thinking is: does the migration change anything in the destination database or just adapts the content information from one database to another by knowing where to place it? Or maybe these permission_block and variable contain information about admin permissions? Weird thing is that I can create everything but the issue only applies to categories.

Thanks in advance and sorry for the trouble
