### ISSUE TITLE
No products in categories after run

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#37]
catalog_category_flat_store_3, catalog_category_entity all contain products, catalog_category_product contains products in categories, catalog_product_flat_3 contains products but none are visible

I did a full re-index?

Most of my url_rewrites are empty.. probably the cause?

How do I re-run the url_rewrite indexer?

**Comment by kokoc** [comment]
URL rewrite indexer was removed in Magento 2. Please check URLs manually using web ui.

**Comment by craigcarnell** [comment]
@kokoc Thanks I found that. However, I am still not seeing any products in categories at all (front end only)

**Comment by craigcarnell** [comment]
I can confirm it is related to https://github.com/magento/data-migration-tool-ce/issues/39

The catalog category joins with catalog search by creating a temporary table. The contents of catalogsearch_fulltext_scope3 are empty.

By creating a new product in the admin it will add to catalogsearch_fulltext_scope(ID) tables

So if you are using the data migration tool this table never gets filled?

**Comment by craigcarnell** [comment]
https://github.com/magento/magento2/issues/2750

**Comment by craigcarnell** [comment]
Fixed, looks like index was always set to working due to segfault with php7 and never ran again

**Comment by craigcarnell** [comment]
Now I have products again, there prices are 0 and the names are missing
