### ISSUE TITLE
magento 2. 2

### ISSUE THREAD

**Issue by Amex68** [magento/data-migration-tool#370]
I was wondering whether Data Migration Tool 2.2.0 will be available for us any time soon?

**Comment by victor-v-rad** [comment]
Yes it will be available soon

**Comment by victor-v-rad** [comment]
Available from now

**Comment by AbdulKadir-Agoliya** [comment]
I am attempting to migrate from 1.9.3.6 to 2.2.0 Opensource to opensource using the data migration tool.
using command : php bin/magento migrate:data /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml

start migration setting and there is one error source docuement is
Source fields are not mapped. Document: core_website. Fields: mf_guid,created_at,updated_at
i added ignore field statement

core_website.mf_guid 
core_website.updated_at
core_website.created_at

in map-stores.xml

php bin/magento migrate:data -r /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml

Expected result

1.error should remove
2. migration process to next step or proceed further

Actual result

1 . [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'field list'

**Comment by victor-v-rad** [comment]
`core_website` table is migrated in setting mode 
```
php bin/magento migrate:settings path/to/config.xml
```
it is strange you get this in `data` mode. Because in `data` mode `core_website` table is ignored in map.xml.dist file

**Comment by AbdulKadir-Agoliya** [comment]
sorry my mistake its setting not data

php bin/magento migrate:setting -r /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml

**Comment by victor-v-rad** [comment]
could you run migration with `-vvv` param to see full backtrace?

**Comment by AbdulKadir-Agoliya** [comment]
it give me this
Exception trace:
 () at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 PDOStatement->execute() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 Migration\ResourceModel\Adapter\Mysql->insertMultiple() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:137
 Migration\ResourceModel\Adapter\Mysql->insertRecords() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php:46
 Migration\ResourceModel\Destination->saveRecords() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Step/Settings/Data.php:137
 Migration\Step\Settings\Data->perform() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:73
 Migration\Mode\AbstractMode->runStage() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Mode/Settings.php:70
 Migration\Mode\Settings->runData() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Mode/Settings.php:34
 Migration\Mode\Settings->run() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:51
 Migration\Console\MigrateSettingsCommand->execute() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Application.php:875
 Symfony\Component\Console\Application->doRunCommand() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Application.php:204
 Symfony\Component\Console\Application->doRun() at /home/mazelivingco/public_html/mag2/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at /home/mazelivingco/public_html/mag2/bin/magento:23

migrate:settings [-r|--reset] [-a|--auto] [--] <config>

**Comment by victor-v-rad** [comment]
Seems error is caused in Migration/Step/Settings/Data.php which works with `core_config_data` table. (Not core_website) Try to find `created_at` in Magento 1 `core_config_data` table

**Comment by AbdulKadir-Agoliya** [comment]
yes core_config_data  has also these three column
created_at , updated_at ,mf_guid  

But i got these error for mapping 

Source fields are not mapped. Document: core_website. Fields: mf_guid,created_at,updated_at
i added ignore field statement

core_website.mf_guid
core_website.updated_at
core_website.created_at

in map-stores.xml

Then after errror  shows me
 [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'field list'

**Comment by AbdulKadir-Agoliya** [comment]
can you please help me on that what to do ?

**Comment by victor-v-rad** [comment]
#378 duplicate

**Comment by AbdulKadir-Agoliya** [comment]
php bin/magento migrate:setting /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml


Display no error explanation : 

php bin/magento migrate:data --reset /public_html/mag2/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml
Reset the current position of migration to start from the beginning

[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:35][INFO][mode: data][stage: data migration][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:36][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:36][INFO][mode: data][stage: data migration][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:59][INFO][mode: data][stage: volume check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:59][INFO][mode: data][stage: data migration][step: Map Step]: started
38% [==========>-----------------] Remaining Time: 3 mins
                                                                                               
  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' 



Please Advice me How to solve this its around 3 days i am trying to migrate to Magento2.2.0

**Comment by charmming** [comment]
Please i have been having trouble migrating data from magento 1x to magento 2x, after installing the tool and configure,  tried running the bellow code

/opt/lampp/htdocs/magento# php bin/magento migrate:settings -r -a -vvv /opt/lampp/htdocs/magento/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.1.0/config.xml
and keep giving me the bellow error

![erroroo](https://user-images.githubusercontent.com/24452316/32717964-dcdd16cc-c85b-11e7-89fd-04a8f1db8939.jpg)

please any help cos i have searched and searched for help but couldn't get...
