### ISSUE TITLE
Magento 2.2 redirect to localhost

### ISSUE THREAD

**Issue by Volle83** [magento/data-migration-tool#372]
Hi,

after finishing the data-migration (from 1.9.2.4 (CE) to 2.2.0) the Shop redirects always to http://localhost/<language>?SID=xxx - where can I change this? 

BR
Volker

**Comment by victor-v-rad** [comment]
Checkout your Magento 2 core_config_data table, record with `web/unsecure/base_url` path

**Comment by victor-v-rad** [comment]
I assume you have installed your Magento 2 shop with localhost as url

**Comment by victor-v-rad** [comment]
There are also several records you can check
```
web/secure/base_url
web/unsecure/base_link_url
web/secure/base_link_url
```

**Comment by kovalevandrew** [comment]
Same problem updated from 2.1.7 to 2.2 redirect to localhost
Used this fix https://github.com/romainruaud/magento2/commit/468eaeeb54956f9972fca27e271304f9263aafd9
it helps but cant access to admin 404

**Comment by kovalevandrew** [comment]
> web/secure/base_url
web/unsecure/base_link_url
web/secure/base_link_url

Solution:
set base_url in core_config_data table like domain not {{base_url}}

**Comment by Volle83** [comment]
It was a clean / new installation without any config or login before migration. I have checked the core_config_data table, there are all 4 rows missing:
`web/unsecure/base_url`
`web/secure/base_url`
`web/unsecure/base_link_url`
`web/secure/base_link_url`

Do I also need to add this rows in the table?
`web/unsecure/base_skin_url`
`web/unsecure/base_media_url`
(also as secure)

After adding the 4 rows the shop comes up to the right page 👍

**Comment by victor-v-rad** [comment]
Hi @Volle83 
After migration, your `web/unsecure/base_url` should not get value of your Magento 1 shop and but remain the initial value. I still do not get what conditions should be for redirect to http://localhost/ 
I guess it is problem of Magento 2.2.0 and not Data Migration Tool

**Comment by narangkishore98** [comment]
I am still unable to figure this out.
