### ISSUE TITLE
How can i use time zone handler for order purchase time ? 

### ISSUE THREAD

**Issue by meezin** [magento/data-migration-tool#373]
### Preconditions

1. Magento 1.9.1.0 (Time zone : UTC -5)
2. Magento 2.1.9 (Time zone : UTC -5)

### Steps to reproduce

1. After migration, the purchase time for an order have a difference the real order purchase time
2. 
3. 

### Expected result

1. If an order was placed on M1 at 1pm, the purchase time on M2 also should be stamped as 1pm 

### Actual result

1. [Screenshot, logs]
When it comes to same order, In M1, it seems like this : 

![image](https://user-images.githubusercontent.com/18614465/31147842-0b2edb0a-a859-11e7-90de-ce2071965f87.png)

In M2, 

![image](https://user-images.githubusercontent.com/18614465/31147740-cee3bd96-a858-11e7-99b4-9e8f81001632.png)

 

but it stamped as like original time + 5 hours, which it is a difference time from general UTC time 

###The question is how can i use time zone handler for order purchase time? The only thins i can see on migration document is about created time of customer. 
http://devdocs.magento.com/guides/v2.0/migration/migration-migrate-follow-up.html

**Comment by victor-v-rad** [comment]
You can try 
```
          <transform>
              <field>sales_flat_order.created_at</field>
              <handler class="\Migration\Handler\Timezone">
                  <param name="offset" value="-5" />
              </handler>
          </transform>
```

**Comment by meezin** [comment]
@victor-v-rad Which map file?

**Comment by meezin** [comment]
@victor-v-rad you know, purchase time on invoice grid and shipment grid was affected. Do i need to use handler for only `sales_flat_order.created_at` ? Thanks

**Comment by victor-v-rad** [comment]
sales_invoice.created_at 
sales_invoice_grid.created_at 
sales_shipment.created_at 
sales_shipment_grid.created_at 

on `<destination>`

**Comment by meezin** [comment]
That's work Thanks

**Comment by shurui91** [comment]
I wonder do we need to do anything extra in order to modify the time related to credit memos? Thanks! @victor-v-rad
