### ISSUE TITLE
Magento 2.2.0 :: unserialize(): Error at offset 374 of 388 bytes in /ma     gento/data-migration-tool/src/Migration/Handler/SerializeToJson/ConvertWithConditions.php on line 62

### ISSUE THREAD

**Issue by mritu19** [magento/data-migration-tool#374]
Hi,
I would like to share with you that during migrating data from Mganeto1 to Magento2.2.0, getting the below error.

[Exception]                                                                                                                 
  Notice: unserialize(): Error at offset 374 of 388 bytes in /ma     gento/data-migration-tool/src/Migration/Handler/SerializeToJson/ConvertWithConditions.php on line 62

Can you please help us regarding the same. Any solution  ?

**Comment by victor-v-rad** [comment]
Hi @mritu19 
At first glance some of serialized data from 
```
sales_flat_quote_item_option
enterprise_giftregistry_item_option
wishlist_item_option
```
tables is broken. You can try to ignore it by adding `gnoreBrokenData` parameter in your map file to existing `<transform>` tag. Like
```
            <transform>
                <field>sales_flat_quote_item_option.value</field>
                <handler class="\Migration\Handler\SerializeToJson\ConvertWithConditions">
                    <param name="conditionalField" value="code" />
                    <param name="conditionalFieldValuesPattern" value="/(parameters)|(info_buyRequest)|(attributes)|(bundle_option_ids)|(bundle_selection_ids)|(bundle_selection_attributes)/" />
                    <param name="gnoreBrokenData" value="true" />
                </handler>
            </transform>
```
But it would be better to find what data causes this issue. You can do it by yourself by debugging \Migration\Handler\SerializeToJson\ConvertWithConditions class or send data of these tables or whole DB to me (find my email in [my profile](https://github.com/victor-v-rad))

**Comment by mritu19** [comment]
Hi @victor-v-rad

Thanks for your quick reply.
I would like to share with you that i have added the tags as suggested, but still I am getting the same issue.
Also, Can you please suggest me, how can be debug the code in the \Migration\Handler\SerializeToJson\ConvertWithConditions  class.

 Is it by using var_dump/print_r of below line 

"   $unserializeData = $this->ignoreBrokenData ? @unserialize($value) : unserialize($value);
        $value = false === $unserializeData ? json_encode([]) : json_encode($unserializeData); "

However, I have found the below data under migration-tool-progress.lock 

"
a:17:{s:38:"Migration\Step\DataIntegrity\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:28:"Migration\Step\Eav\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:33:"Migration\Step\Customer\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:28:"Migration\Step\Map\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:42:"Migration\Step\UrlRewrite\Version191to2000";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:28:"Migration\Step\Log\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:32:"Migration\Step\Ratings\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:43:"Migration\Step\ConfigurablePrices\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:35:"Migration\Step\OrderGrids\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:34:"Migration\Step\TierPrice\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:39:"Migration\Step\SalesIncrement\Integrity";a:1:{s:15:"integrity check";a:1:{s:6:"result";b:1;}}s:27:"Migration\App\SetupDeltaLog";a:1:{s:14:"setup triggers";a:1:{s:6:"result";b:1;}}s:23:"Migration\Step\Eav\Data";a:1:{s:14:"data migration";a:1:{s:6:"result";b:1;}}s:25:"Migration\Step\Eav\Volume";a:1:{s:12:"volume check";a:1:{s:6:"result";b:1;}}s:28:"Migration\Step\Customer\Data";a:1:{s:14:"data migration";a:1:{s:6:"result";b:1;}}s:30:"Migration\Step\Customer\Volume";a:1:{s:12:"volume check";a:1:{s:6:"result";b:1;}}s:23:"Migration\Step\Map\Data";a:1:{s:3:"run";a:1:{s:7:"process";a:153:{i:0;s:23:"adminnotification_inbox";i:1;s:11:"captcha_log";i:2;s:23:"catalog_category_entity";i:3;s:32:"catalog_category_entity_datetime";i:4;s:31:"catalog_category_entity_decimal";i:5;s:27:"catalog_category_entity_int";i:6;s:28:"catalog_category_entity_text";i:7;s:31:"catalog_category_entity_varchar";i:8;s:24:"catalog_category_product";i:9;s:30:"catalog_category_product_index";i:10;s:20:"catalog_compare_item";i:11;s:29:"catalog_product_bundle_option";i:12;s:35:"catalog_product_bundle_option_value";i:13;s:32:"catalog_product_bundle_selection";i:14;s:38:"catalog_product_bundle_selection_price";i:15;s:22:"catalog_product_entity";i:16;s:31:"catalog_product_entity_datetime";i:17;s:30:"catalog_product_entity_decimal";i:18;s:30:"catalog_product_entity_gallery";i:19;s:26:"catalog_product_entity_int";i:20;s:36:"catalog_product_entity_media_gallery";i:21;s:42:"catalog_product_entity_media_gallery_value";i:22;s:27:"catalog_product_entity_text";i:23;s:30:"catalog_product_entity_varchar";i:24;s:20:"catalog_product_link";i:25;s:30:"catalog_product_link_attribute";i:26;s:38:"catalog_product_link_attribute_decimal";i:27;s:34:"catalog_product_link_attribute_int";i:28;s:38:"catalog_product_link_attribute_varchar";i:29;s:25:"catalog_product_link_type";i:30;s:22:"catalog_product_option";i:31;s:28:"catalog_product_option_price";i:32;s:28:"catalog_product_option_title";i:33;s:33:"catalog_product_option_type_price";i:34;s:33:"catalog_product_option_type_title";i:35;s:33:"catalog_product_option_type_value";i:36;s:24:"catalog_product_relation";i:37;s:31:"catalog_product_super_attribute";i:38;s:37:"catalog_product_super_attribute_label";i:39;s:26:"catalog_product_super_link";i:40;s:23:"catalog_product_website";i:41;s:22:"cataloginventory_stock";i:42;s:27:"cataloginventory_stock_item";i:43;s:11:"catalogrule";i:44;s:26:"catalogrule_customer_group";i:45;s:25:"catalogrule_group_website";i:46;s:19:"catalogrule_product";i:47;s:25:"catalogrule_product_price";i:48;s:19:"catalogrule_website";i:49;s:19:"catalogsearch_query";i:50;s:18:"checkout_agreement";i:51;s:24:"checkout_agreement_store";i:52;s:9:"cms_block";i:53;s:15:"cms_block_store";i:54;s:8:"cms_page";i:55;s:14:"cms_page_store";i:56;s:19:"core_email_template";i:57;s:12:"core_session";i:58;s:14:"core_translate";i:59;s:13:"core_variable";i:60;s:19:"core_variable_value";i:61;s:17:"coupon_aggregated";i:62;s:23:"coupon_aggregated_order";i:63;s:25:"coupon_aggregated_updated";i:64;s:30:"customer_eav_attribute_website";i:65;s:23:"customer_form_attribute";i:66;s:14:"customer_group";i:67;s:13:"design_change";i:68;s:17:"directory_country";i:69;s:24:"directory_country_format";i:70;s:24:"directory_country_region";i:71;s:29:"directory_country_region_name";i:72;s:23:"directory_currency_rate";i:73;s:17:"downloadable_link";i:74;s:23:"downloadable_link_price";i:75;s:27:"downloadable_link_purchased";i:76;s:32:"downloadable_link_purchased_item";i:77;s:23:"downloadable_link_title";i:78;s:19:"downloadable_sample";i:79;s:25:"downloadable_sample_title";i:80;s:19:"eav_attribute_label";i:81;s:20:"eav_attribute_option";i:82;s:26:"eav_attribute_option_value";i:83;s:10:"eav_entity";i:84;s:19:"eav_entity_datetime";i:85;s:18:"eav_entity_decimal";i:86;s:14:"eav_entity_int";i:87;s:16:"eav_entity_store";i:88;s:15:"eav_entity_text";i:89;s:18:"eav_entity_varchar";i:90;s:16:"eav_form_element";i:91;s:17:"eav_form_fieldset";i:92;s:23:"eav_form_fieldset_label";i:93;s:13:"eav_form_type";i:94;s:20:"eav_form_type_entity";i:95;s:12:"gift_message";i:96;s:23:"importexport_importdata";i:97;s:18:"newsletter_problem";i:98;s:16:"newsletter_queue";i:99;s:21:"newsletter_queue_link";i:100;s:27:"newsletter_queue_store_link";i:101;s:21:"newsletter_subscriber";i:102;s:19:"newsletter_template";i:103;s:14:"oauth_consumer";i:104;s:11:"oauth_nonce";i:105;s:11:"oauth_token";i:106;s:11:"paypal_cert";i:107;s:26:"paypal_payment_transaction";i:108;s:24:"paypal_settlement_report";i:109;s:28:"paypal_settlement_report_row";i:110;s:18:"persistent_session";i:111;s:19:"product_alert_price";i:112;s:19:"product_alert_stock";i:113;s:6:"rating";i:114;s:13:"rating_entity";i:115;s:13:"rating_option";i:116;s:18:"rating_option_vote";i:117;s:29:"rating_option_vote_aggregated";i:118;s:12:"rating_store";i:119;s:12:"rating_title";i:120;s:29:"report_compared_product_index";i:121;s:12:"report_event";i:122;s:18:"report_event_types";i:123;s:38:"report_viewed_product_aggregated_daily";i:124;s:40:"report_viewed_product_aggregated_monthly";i:125;s:39:"report_viewed_product_aggregated_yearly";i:126;s:27:"report_viewed_product_index";i:127;s:6:"review";i:128;s:13:"review_detail";i:129;s:13:"review_entity";i:130;s:21:"review_entity_summary";i:131;s:13:"review_status";i:132;s:12:"review_store";i:133;s:34:"sales_bestsellers_aggregated_daily";i:134;s:36:"sales_bestsellers_aggregated_monthly";i:135;s:35:"sales_bestsellers_aggregated_yearly";i:136;s:23:"sales_billing_agreement";i:137;s:29:"sales_billing_agreement_order";i:138;s:21:"sales_flat_creditmemo";i:139;s:29:"sales_flat_creditmemo_comment";i:140;s:26:"sales_flat_creditmemo_item";i:141;s:18:"sales_flat_invoice";i:142;s:26:"sales_flat_invoice_comment";i:143;s:23:"sales_flat_invoice_item";i:144;s:16:"sales_flat_order";i:145;s:24:"sales_flat_order_address";i:146;s:21:"sales_flat_order_item";i:147;s:24:"sales_flat_order_payment";i:148;s:31:"sales_flat_order_status_history";i:149;s:16:"sales_flat_quote";i:150;s:24:"sales_flat_quote_address";i:151;s:29:"sales_flat_quote_address_item";i:152;s:21:"sales_flat_quote_item";}}}}

"

Also, there is no any data under below table 
enterprise_giftregistry_item_option
wishlist_item_option

**Comment by victor-v-rad** [comment]
Try make $this->ignoreBrokenData always true in \Migration\Handler\SerializeToJson\ConvertWithConditions class

**Comment by victor-v-rad** [comment]
`migration-tool-progress.lock`  does not relate to your issue

**Comment by mritu19** [comment]
Below is the code in \Migration\Handler\SerializeToJson\ConvertWithConditions class


    public function __construct($conditionalField, $conditionalFieldValuesPattern, $ignoreBrokenData = false)
    {
        $this->conditionalField = $conditionalField;
        $this->conditionalFieldValuesPattern = $conditionalFieldValuesPattern;
        $this->ignoreBrokenData = $ignoreBrokenData;
    }

  
    public function handle(Record $recordToHandle, Record $oppositeRecord)
    {
        $this->validate($recordToHandle);
        $value = $recordToHandle->getValue($this->field);
        if (null !== $value) {
            if ($this->shouldProcessField($recordToHandle->getData()[$this->conditionalField])) {
                $unserializeData = $this->ignoreBrokenData ? @unserialize($value) : unserialize($value); //line 62
                $value = false === $unserializeData ? json_encode([]) : json_encode($unserializeData);
            }
        }
        $recordToHandle->setValue($this->field, $value);
    }

--should change the "  $ignoreBrokenData = false" to "$ignoreBrokenData = true" in below function 

public function __construct($conditionalField, $conditionalFieldValuesPattern, $ignoreBrokenData = false) "
    { }

please suggest.
Thanks

**Comment by mritu19** [comment]
Hi @victor-v-rad 
Thanks for your quick reply.

As suggested, I have added below line in  \Migration\Handler\SerializeToJson\ConvertWithConditions class

// $this->ignoreBrokenData = $ignoreBrokenData;
 $this->ignoreBrokenData = true;

Thereafter, I am successfully able to complete the data migration in magento2.2.0
However, I have noticed that there are something mismatched with original data which is below:
---  lifetime sales is mismatched from the Magento1 
---Average orders is also mismatched (minor differences)

Apart from that I am also not able to see any Product and Orders. But I am able to see all category lists and category's assigned product count under category. 

When I clicked to see the Products and orders then ajax-loader spinning infinite. Even, I have also noticed that after installing/setup magento2.2.0 thereafter still I am not able to see the Products and orders but ajax-loader spinning for infinite

you can check screenshot for your reference.

![image](https://user-images.githubusercontent.com/32297749/31214163-a3f90c10-a9c7-11e7-9633-26b1df4e764f.png)

Can you please help us regarding the same. Any solution ?

**Comment by victor-v-rad** [comment]
try `php bin/magento cache:flush && php bin/magento indexer:reindex`

**Comment by mritu19** [comment]
Hi @victor-v-rad 
Thanks for your quick reply.

As suggested, I have flushed cache and run the re-indexing command... But from last 2 hours re indexing is not completed yet. below is the screenshot for your reference :: 

![image](https://user-images.githubusercontent.com/32297749/31218805-0c77c11c-a9d9-11e7-9a4b-fe6e6c89ceb2.png)

I have also seen in admin panel that there are still some re-indexing is pending which is below, you can check screenshot below ::

![image](https://user-images.githubusercontent.com/32297749/31218897-533380a0-a9d9-11e7-9db8-22efa0c75c9c.png)

Apart from that I have seen that customer grid re-indexing is completed, in that case I could able to see customer data. but unfortunately , customer data is also not coming under customer grid, ajax-loader spinning infinite.

Can you please help us regarding the same. Any solution ?

**Comment by mritu19** [comment]
Hi @victor-v-rad 

After completion of Data Migration in M2.2.0, I have flushed cache and run the re-indexing command. Except one "catalog_product_price" all re indexing is completed.

But still No any Data is coming under  customers, products, orders, pages and static blocks in admin Grid. Only ajax-loader spinning infinite.

Like below screenshot ::

![image](https://user-images.githubusercontent.com/32297749/31227042-04052142-a9f6-11e7-92ee-0a18a5255549.png)

However, under "Marketing tab > Email templates, URL Rewrites etc." data is coming under grid.

I have noticed that "404 not found for pub/static/version1507091218/adminhtml/Magento/backend/en_US/js-translation.json" file in console.

Should i run the static content deploy command ?

Can you please help us regarding the same. Any solution ?

**Comment by mritu19** [comment]
Hi @victor-v-rad 

I would like to share with you that after run the command "setup:static-content:deploy" i am able to see all migrated data now in Admin panel.

Thanks for your support.

**Comment by hammockvienna** [comment]
@victor-v-rad 
`Try make $this->ignoreBrokenData always true in \Migration\Handler\SerializeToJson\ConvertWithConditions class`

I guess this is a short term solution. It will ignore the broken data and proceed. We have the exact same issue like mritu19 but with the core_config_data table. If we ignore the brokendata then the core_config_data values are only migrated partly. In Magento 2.1.7 everything was migrated in Magento 2.2.0 have have that issue during migration.

Whats the best thing in order to identify the problematic records?
" $unserializeData = $this->ignoreBrokenData ? @unserialize($value) : unserialize($value);
$value = false === $unserializeData ? json_encode([]) : json_encode($unserializeData); "

@mritu19 are you sure having all old data in magento 2.2.0 ? i guess you might be missing something.
