### ISSUE TITLE
Magento 2.2.0 : Data MIgration Tool map.xml fiile not ignoring any field or document

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#375]
Hello Guys ,

I am Unable to Ignore Fields and Document or do Mapping in , Data migration Tool  2.2.0 , i have Changed config.xml file  From 

<map_file>etc/opensource-to-opensource/1.9.3.2/map.xml.dist</map_file>
to 
<map_file>etc/opensource-to-opensource/1.9.3.2/map.xml</map_file>

But No Effect , Please Help  ITS URGENT

Thanks in Advance

**Comment by victor-v-rad** [comment]
Make sure you use config.xml which contain your new map filename. Also you can use `-a` option to make the tool disregard Integrity check errors [Docs](http://devdocs.magento.com/guides/v2.2/migration/migration-migrate-data.html)

**Comment by yogeshsyscraft** [comment]
Yes i am sure , that my config.xml contain New Map file name , also i used -a but with this its giving WARNING in Yellow Color , and without - a its Giving Error in red Color,

**Comment by victor-v-rad** [comment]
>  its giving WARNING 
So if you want use <ignore> in map file the `-a` option just does the same. 
I've just tried custom mapping with new map file and it works in my environment

**Comment by yogeshsyscraft** [comment]
Please Find below image with Error and code as you said me to use same map file , 
![error](https://user-images.githubusercontent.com/32513730/31175512-1bc8eac6-a92d-11e7-8eea-58c4ef7833cc.png)

**Comment by yogeshsyscraft** [comment]
Please Find below image with Error and code as you said me to use same map file ,

![error](https://user-images.githubusercontent.com/32513730/31175726-cb456e48-a92d-11e7-81d8-d913cad4cda9.png)

**Comment by yogeshsyscraft** [comment]
can u please suggest me anything  ???

**Comment by victor-v-rad** [comment]
map.xml file used for `data` migration. But your error is in `settings` mode. Use map-stores.xml.dist for your needs

**Comment by yogeshsyscraft** [comment]
its Working .. Thank You so much dear @victor-v-rad
