### ISSUE TITLE
magento 2.2.0 : Admin page redirecting to Production site 

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#376]
Hello Team ,

I have completed migration from Magento 1.9.3.2 to Magento 2.2.0 After This i found data in magento 2 frontend but after being redirect to Production site whenever Click on CHECKOUT page and Also ADMIN login is redirecting me to production site , please suggest .

Thanks

**Comment by victor-v-rad** [comment]
Try `php bin/magento cache:flush && php bin/magento indexer:reindex`

**Comment by yogeshsyscraft** [comment]
Hello Victor ,

Thanks for your quick response , as i have already tried these steps , as well i also tried deploy , but still same redirection to my production site whenever i hit URL for Login page of frontend or i go to Admin panel or i got to cart , Checkout page , i am being redirected to Production site , 
please Suggest something to get rid of this issue .

Thanks 
Yogesh

**Comment by victor-v-rad** [comment]
Check out your Magento 2 core_config_data table for records with
```
web/unsecure/base_url
web/secure/base_url
web/unsecure/base_link_url
web/secure/base_link_url
```
in `path` field. Are these look ok?

**Comment by yogeshsyscraft** [comment]
i found these two records
web/unsecure/base_url
web/secure/base_url 

these record are not in my core_config_data table 
web/unsecure/base_link_url
web/secure/base_link_url

**Comment by yogeshsyscraft** [comment]
please suggest anything  ??

**Comment by victor-v-rad** [comment]
Look at #372 It might contain solution

**Comment by yogeshsyscraft** [comment]
thanks dear
