### ISSUE TITLE
MAGENTO 2.2.0 : :The configuration parameter \"formElement\" is a required for \"is_quotation\" field.

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#380]
Hello @victor-v-rad ,

After successfully Migrating in Magento 2.2.0  i am Having this issue when i edit any Product , Please suggest Something ,

`The configuration parameter \"formElement\" is a required for \"is_quotation\" field.`

Thanks 
Yogesh

**Comment by yogeshsyscraft** [comment]
Please suggest something Its **URGENT**

**Comment by victor-v-rad** [comment]
At this point it is hard to suggest something useful due lack of information. I can try to migrate your DB on my environment to reproduce it

**Comment by yogeshsyscraft** [comment]
thanks for reply dear,  as i have fixed this issue by deleting that Attribute From DB ,

once again Thanks A lot

**Comment by hussja** [comment]
We have a quote ext on M1. possibly that.
