### ISSUE TITLE
After migration, CSS/JS file only for a few category aren't loaded properly. 

### ISSUE THREAD

**Issue by meezin** [magento/data-migration-tool#381]
Hi, There.

I just checked my migration works well.
By the way, i can see a weird issue on our home page.

My devwebsite url is http://dev.kbethos.com/
And the url under this issue http://dev.kbethos.com/blanks-classics.html
Resources on other url except this seems to be loaded well without problem.

What is the issue of it?
I have tried migration work over and over again. It still happens

**Comment by victor-v-rad** [comment]
Look at source code of the page in Chrome browser
view-source:http://dev.kbethos.com/blanks-classics.html
you will see it not complete
