### ISSUE TITLE
After Migration Orders Records doesn't match with Magento 1.9.3.2 

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#386]
Hello Guyx 

Please help me , i have completed process of migration but when i match data of 1.9.3.2 with 2.2.0 , i found data doesn't Matched , please suggested me why this happened ,

Many Thanks

**Comment by yogeshsyscraft** [comment]
@victor-v-rad  Please help me Sir

**Comment by victor-v-rad** [comment]
@yogeshsyscraft 
Try this fix https://github.com/magento/data-migration-tool/pull/267/commits/e1963d7c7159719d7def5f92d1e1f9c586da508e

**Comment by victor-v-rad** [comment]
@yogeshsyscraft 
try this fix https://github.com/magento-panda/data-migration-tool/commit/5fc6ff3c5c89aea88e8843c55fdafc9cf3bd6f3b

**Comment by victor-v-rad** [comment]
and this
https://github.com/magento-panda/data-migration-tool/commit/1d3226c833be529c288ffa951658577669855541

**Comment by yogeshsyscraft** [comment]
Thanks @victor-v-rad  ,
