### ISSUE TITLE
Magento2.2.0 :: After Data Migration, Child categories Product not coming in frontend and configurable price is not editable

### ISSUE THREAD

**Issue by mritu19** [magento/data-migration-tool#387]
Hi @victor-v-rad 

I am working on M2.2.0 and have successfully migrated M1.9.1.0 data. But Unfortunately I have the same Problem, I am not able to see any product under category. However, I am able to search the all migrated products and respected product detail page.

Preconditions

Magento 2.2.0

**Steps to reproduce**

Products is already assigned to categories and subcategories (After data migration from M1).

check screenshot below ::

![all-category-and-products](https://user-images.githubusercontent.com/32297749/31387723-06bcf9e0-ade9-11e7-8f5c-dd1a5b35625b.PNG)

Also Configurable product price is displaying in  product Grid 

check screenshot below ::

![configurable-product-priceall](https://user-images.githubusercontent.com/32297749/31387483-3c1479ca-ade8-11e7-8337-60958225a149.PNG)

But that price is not coming when I open any configurable product and see the price. 
Check below

![configurable-product-price-not-editable](https://user-images.githubusercontent.com/32297749/31387577-83a99fae-ade8-11e7-8f7c-bdd7e5d62acc.PNG)

Visit category page on front end

**Expected result**

See grid of all products in the category

Actual result
No any product is coming.

I have around 84.5K products and the product is configurable and simple.

[Note: I have tried to save some products and have added "Default Category" under category mapping. thereafter i am able to see those products in respected category in Frontend. but it is not feasible to save 84.5k Products manually again one by one.

I Have also followed several necessary steps which is suggested under community support (Like cache flush, reindexing, isRangingNeeded()->false). But still products is not coming.

Can you please help me regarding the same. Any solution ?

**Comment by fballiano** [comment]
Did you find any solution? I also have no products shown on the frontend (although prices are editable for me).

Thanks!

**Comment by sarjangautam** [comment]
I had similar issue (products not showing in front) but was resolved after reindexing. I have to reset indexes and run them again. 

php bin/magento indexer:reset
php bin/magento indexer:reindex

Do not forget to clear the cache after that.
