### ISSUE TITLE
mcrypt error - Trying to install Data Migration Tool 2.2.0

### ISSUE THREAD

**Issue by C1oudmedia** [magento/data-migration-tool#388]
SSH (using Putty)
access root folder
composer config repositories.magento composer https://repo.magento.com
composer require magento/data-migration-tool:2.2.0

all going well then:

Problem 1
    - magento/framework 101.0.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for magento/framework (locked at 101.0.0) -> satisfiable by magento/framework[101.0.0].

Using PHP 7.1.10, but have tried with 7.0.8 througfh to current version - all results the same
Ubuntu 16.04.2 LTS‬
Magento version 2.2.0

mcrypt is installed

been round most websites with similar issues and lots of contradictions, tried most but cannot get it to work

**Comment by ihor-sviziev** [comment]
@C1oudmedia just make sure that mctypt is availabe with php -m | grep mcrypt. It might be available for web server, but not available to cli.
