### ISSUE TITLE
migration from 1.8 to 2.2

### ISSUE THREAD

**Issue by keanass** [magento/data-migration-tool#395]
vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169 

everything done like you said but the problem still. please give a solution or information to correct that.

**Comment by victor-v-rad** [comment]
Do you mean this issue ?
```
Array to string conversion in /var/www/html/magento220/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169
```
and this fix 
https://github.com/magento-panda/data-migration-tool/commit/1d3226c833be529c288ffa951658577669855541
have not fixed your case?
