### ISSUE TITLE
Migrating Store Views form Magento 1.9.1 to Magento 2.2 

### ISSUE THREAD

**Issue by expertalex** [magento/data-migration-tool#396]
Hello. 

I'm trying to migrate all products form magento 1.9.1 to magento 2.2 but only one store view is migrated.
How can I migrate al store view & the corresponding translations for each product?

Thanks

**Comment by victor-v-rad** [comment]
Hi,
Probably you have not migrated `settings` first

**Comment by expertalex** [comment]
Hello Victor.
I follow the instructions line by line!!!
1st: bin/magento migrate:settings -r {<path to config.xml>}
2nd: bin/magento migrate:data -r -a {<path to config.xml>} 

Also before the migration I included some attributes in customer-attribute-groups.xml and some clases in class-map.xsd to be ignored to avoid errors .

P.S. I also tried to roll back magento after failures.

**Comment by victor-v-rad** [comment]
Clarification sent to the client through email

**Comment by dwianbigi** [comment]
Hi @expertalex ,
Could you please give me the conclusion about your issue? Because I need to migrate from single store view only
Thank you

**Comment by nadeskats** [comment]
> Hi,
> Probably you have not migrated `settings` first

Thank you! @victor-v-rad
