### ISSUE TITLE
Data migration - "super product attributes configuration" price values for options VS actual product price

### ISSUE THREAD

**Issue by gritdigital-mibu** [magento/data-migration-tool#398]
Hi there,

After migrating products from Magento CE 1.8.0.0 to CE 2.1.8 I've noticed a difference in the pricing.

![2017-10-25 16_06_34-cast iron gutter drop end socket 65mm outlet _ manage products _ catalog _ magen](https://user-images.githubusercontent.com/11611416/32041012-90507266-ba2a-11e7-93a3-1eb4a38b1046.png)

Magento 2 shows the prices as £21.80 and £24.44 but in Magento 1 they show as £21.80 and £28.94.
I don't know which of the two should be considered the "true" price - can you please advise?

Kind regards,
Mike

**Comment by victor-v-rad** [comment]
Hi @gritdigital-mibu 

This post
http://blog.mag-manager.com/2016/10/magento-2-configurable-product-price.html
about how prices were changed for configurable product in Magento 2

**Comment by gritdigital-mibu** [comment]
@victor-v-rad 

Thank you Victor - this was exactly what I was looking for.
To confirm, the behaviour I'm seeing is correct/intended? 

Kind regards,
Mike

**Comment by victor-v-rad** [comment]
The right answer should the price of a configurable product option displayed in Store Front of Magento 1 and Magento 2. Thus if you open this configurable product in Magento 1 Store Front then the option 115mm should be £24.44. In Magento 2 pricing of configurable product was made more simple.

**Comment by 12417580** [comment]
HI @victor-v-rad 

I used the migration tool to move from magento 1 to magento 2.2.5

The configurable products lose the main product price, and only the price of associated price is considered. For example 

![correct](https://user-images.githubusercontent.com/37321978/44388106-9e8da700-a56a-11e8-83e9-687d7a050214.PNG)

The price here is right, this is the main product price. But when I go in this product, I see this

![not](https://user-images.githubusercontent.com/37321978/44388193-d4329000-a56a-11e8-8694-e57dedfa9a09.PNG)

I don't see the main product price here.

And here is a screenshot of the associated products

![price](https://user-images.githubusercontent.com/37321978/44388272-0d6b0000-a56b-11e8-8946-75bbdf50e36c.PNG)

The price $64 is for the case, which comes as an add on for the main product.

In magento  1, when someone selects the case they see the price $1509 + $64

But in Magento 2, it comes up just as $64

Please help me with this

Thanks,
Farhan Saeed
