### ISSUE TITLE
Category images data not migrating

### ISSUE THREAD

**Issue by anil-suthar** [magento/data-migration-tool#399]
I have migrated **M1.9 to M2.2.0** successfully without any error.
Moved media directory to M2 (without .htaccess)
Did Clear/Flush cache, Content Deploy etc...

**Expected Result**
Product and Category Images should be shown at admin and frontend

**Actual Result**
I can see the product images BUT **category Images are not showing** at admin or at frontend

![cat-images](https://user-images.githubusercontent.com/3518141/32052100-c676361a-ba74-11e7-959b-508544c86491.jpg)

**Comment by victor-v-rad** [comment]
Hi @anil-suthar 
Category Thumbnail image from M1 is not the Category Image from M2

![1509025021552](https://user-images.githubusercontent.com/106504/32055955-fa66b9bc-ba6b-11e7-8b1a-00e47a4d64fe.jpg)
![1502971728806](https://user-images.githubusercontent.com/106504/32055960-fe0228d6-ba6b-11e7-8e4d-abd58efd5212.jpg)

**Comment by anil-suthar** [comment]
Thanks for reply,
I have many categories with "Image" and "Thumbnail Image" both set at M1 But they are not showing any image for any Category for M2.
I'll try again, and let you know, thanks

**Comment by sumeet-mis** [comment]
@anil-suthar 
did you solve this ?
i am also getting this issue all are migrated but category images(or name) is not migrated from M1 to M2.

or anyone there how to solve this ?
