### ISSUE TITLE
Version11410to2000 - temporaryTable

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#400]
Hi,

My class extends Version11410to2000, which used the variable tableName which was previously a protected variable. The latest data migration tool changes this to a private variable called temporaryTable.

Could you change this back to a protected variable so my class extend works?

https://github.com/magento/data-migration-tool/blob/715cef2c8c84e77e24d984917425d519733bb2c7/src/Migration/Step/UrlRewrite/Version11410to2000.php#L24

thanks

**Comment by victor-v-rad** [comment]
Hi,
Internal ticket MAGETWO-82867. Will be published in the next release

**Comment by craigcarnell** [comment]
@victor-v-rad this is now fixed, thanks :+1:
