### ISSUE TITLE
Serialized values are not converted to JSON on migration to 2.2.x

### ISSUE THREAD

**Issue by renttek** [magento/data-migration-tool#401]
### Preconditions
1. Setup a fresh Magento >= 2.2.0 (PHP 7.1.10)
2. Install data migration tool via composer
2. Create configuration for data migration tool

### Steps to reproduce
1. Migrate data from M1 to M2

### Expected result
1. All serialized values, migrated in the DB should be usable by M2

### Actual result
1. Migrated data is still serialized and not converted to json

I think, the migration-tool should run the conversion from serialized to json again, after migrating the data OR even convert the data directly on migration

**Comment by victor-v-rad** [comment]
Hi @renttek 

I guess this is the fix https://github.com/magento-panda/data-migration-tool/commit/c7d4d8521dfafe25e343cf8ae6c561712bbfc4d2
It will be published in the next release

**Comment by jphat** [comment]
Patch seems to work as tested on Magento 2.2.0, Community Edition
Thanks.

**Comment by renttek** [comment]
hey @victor-v-rad, that's awesome!
Thanks for the link to the patch!

**Comment by UberthemeTeam** [comment]
hi @renttek, we see you're using Magento migration tool at the moment. In any case that you might want to take a look at other migration tools like our [UB Data Migration Pro](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/), please take a look. In our latest update release Pro ver3.1.1 for Magento CE 2.2.0, the serialized values are fully converted to JSON (some of our users have been using this version, and successfully ported all serialized values to M2).

**_PS._** We're biased when referring our migration tool here, yet just want to leave a message in case you're interested in.

**Comment by grablor** [comment]
Hi @victor-v-rad , your solution worked for me. Thanks a lot.
Issue:
Migrated from Magento 1.9.1.1 to 2.2.0
Add to cart button missing on product page after migration.
on category list page if clicked Add to cart button it gives following error "We can't add this item to your shopping cart right now."
After following [YOUR SOLUTION](https://github.com/magento-panda/data-migration-tool/commit/c7d4d8521dfafe25e343cf8ae6c561712bbfc4d2) my issue resolved.

Thank you,
Pratik

**Comment by victor-v-rad** [comment]
@grablor 
glad it helped )

**Comment by es11support** [comment]
@victor-v-rad

So, if we previously imported our settings without applying this patch, can we simply apply the patch to "settings.xml" and re-import **ONLY** the settings using the following command:

bin/magento migrate:settings -r /path-to-magento/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.2/config.xml

**Comment by mfsi-subhras** [comment]
Faced the same issue after migrating store from 1.9.0.1 to 2.2.
Patch helped.
@victor-v-rad. Thank you :)

**Comment by nguyetnguyen** [comment]
Hi @victor-v-rad,
I got this problem on migrating data from Magento ee 1.13.0.2 to 2.2.3. 
Here are the errors
`
←[0;33m[2018-04-06 10:18:05][WARNING]: Could not unserialize data of enterprise_logging_event_changes.result_data with record id 35617←[0m
←[0;33m[2018-04-06 10:18:05][WARNING]:  ←[0m
←[0;33m[2018-04-06 10:18:05][WARNING]: Could not unserialize data of enterprise_logging_event_changes.result_data with record id 38301←[0m
`
I checked code as [https://github.com/magento-panda/data-migration-tool/commit/c7d4d8521dfafe25e343cf8ae6c561712bbfc4d2](your guide) on my settings.xml.dist. It is already updated. 
Here is the code on settings.xml.dist
`        <transform>
            <path>cataloginventory/item_options/min_sale_qty</path>
            <handler class="\Migration\Handler\SerializeToJson">
                <param name="suppressWarning" value="true"/>
            </handler>
        </transform>
        <transform>
            <path>currency/options/customsymbol</path>
            <handler class="\Migration\Handler\SerializeToJson"/>
        </transform>
`
Could you help? Thanks!
