### ISSUE TITLE
Design configuration (2.2.0) does not save After Migration From 1.9.3.2

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#402]
Hello @victor-v-rad  I am facing this issue after migration , please have a look and Help me , 

**Preconditions**

1. Magento 2.2
2. After Migration From 1.9.3.2

**Steps to reproduce**

1. Login to Admin got to Content->Design -> Configration
2. Select Any Store and click edit action
3. Do any changes -> Click of Save

**Expected result**

Changes should be saved and refresh page .

**Actual result**

`404 error: Page not found.`

![issue](https://user-images.githubusercontent.com/32513730/32158190-86743746-bd6d-11e7-8355-0ac96c6bb67d.png)

**Comment by victor-v-rad** [comment]
Hi
I will be able to check it after vacation.

**Comment by victor-v-rad** [comment]
Tried it but had no luck reproducing

**Comment by yogeshsyscraft** [comment]
Hello @victor-v-rad  , Thanks For trying , i have solved the issue , 


Thanks Once again
