### ISSUE TITLE
After Migration from 1.9.3.2 to M2.2.0 Ajax stops working

### ISSUE THREAD

**Issue by KooTjoo** [magento/data-migration-tool#403]
I use
PHP 7.0.
CentOS Linux 7.4
Plesk Onyx Server
MySQL Mariadb 10.1

I did a Clean Installation of M2.2.0
Added 1 product to test things
Ajax Cart and other Ajax Features (layered navigation) work as expected.
Reinstalled clean installation
Used Migration Tool to migrate form 1.9.3.2 to 2.2.0. No errors reported.

Result
Products, Customers etc show up like they should
After migration all Ajax functionality stopped working

I Tried:
Reindex, Chache Clean, Comile, Deploy etc.
Checked and compared settings of clean installation and migrated site. No issues found

Also tested this on M2.1.9 but same result.

**Comment by victor-v-rad** [comment]
Try to install extensions (Ajax Cart and other Ajax Features) after migration

**Comment by KooTjoo** [comment]
Hi,

Thanks for the answer, but that doesn't help. I tried that.

Basic installation of M2.2 without migration has a working Ajax Add To Cart. As soon as I migrate (it is multistore), then it stops working. It must be something the migration causes. Any further info would be great.

Thanks
KooTjoo

**Comment by gouravsyscraft** [comment]
Can you check on browser console and let me know, what error message are showing when you are trying to add product on card.
