### ISSUE TITLE
Fatal error on data migration tool

### ISSUE THREAD

**Issue by bhagdave** [magento/data-migration-tool#405]
We are attempting to do a data migration from 1.9.0.1 to 2.2.0 and are getting the following fatal error.
[2017-11-06 15:06:11][DEBUG][mode: data][stage: data migration][step: Map Step][table: catalog_product_entity_varchar]: migrating
50% [==============>-------------] Remaining Time: 18 minsPHP Fatal error:  Uncaught Error: Call to a member function getStructure() on boolean in /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/ResourceModel/AbstractResource.php:199
Stack trace:
#0 /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php(33): Migration\ResourceModel\AbstractResource->getPageSize('catalog_product...')
#1 /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/Step/Map/Data.php(175): Migration\ResourceModel\Destination->saveRecords('catalog_product...', Object(Migration\ResourceModel\Record\Collection), false)
#2 /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php(73): Migration\Step\Map\Data->perform()
#3 /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(122): Migration\Mode\AbstractMode->runStage(Object(Migration\Step\Map\Data), 'Map Step', 'data migration')
#4 /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php(69): Migration\Mode\Dat in /var/www/MagentoE/vendor/magento/data-migration-tool/src/Migration/ResourceModel/AbstractResource.php on line 199

**Comment by victor-v-rad** [comment]
It might be some problem with DDL cache or something. See #251 had a similar problem and resolved it. Most likely your catalog_product_entity_varchar exists but when the tool calls \Magento\Framework\DB\Adapter\Pdo\Mysql::describeTable function for the table it return empty array.

**Comment by bhagdave** [comment]
Cool, will give that a try.

**Comment by victor-v-rad** [comment]
I had no problems with migrating from remote DB. Not sure exactly why it happens. You can test remote migration before doing live migration

**Comment by bhagdave** [comment]
Just to confirm this is still an issue and fails every time when connecting to an RDS instance.  Disabling the DDL cache has no impact on the result.

**Comment by florincyberion** [comment]
The default pagesize in the tool is 50k. That can be quite much from some mysql servers. Setting bulk_size in config.xml to a more reasoable number seems to resolve the issue.(for me it worked with 1000)
