### ISSUE TITLE
Want To Migrate Only Product from 1.9.3.2 to 2.2.0

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#406]
Hii @victor-v-rad  

After migration my products are deleted by mistake and want to migrate only Products , i have tried data migration with "-a " attribute , but products not migrated , can you tell me from which step Products migrate .

Thanks 
Yogesh

**Comment by victor-v-rad** [comment]
As for now there is no standard way to migrate only products, order, categories, etc. Clear Magento2 DB and migrate whole store again.

**Comment by yogeshsyscraft** [comment]
@victor-v-rad  if i migrate whole store , than all configurations that i have setup and added extensions and installed theme , etc etc all will be overwrite . it will waste lot of time . is there any hope  ??

**Comment by victor-v-rad** [comment]
Not sure which way is faster

**Comment by victor-v-rad** [comment]
I have not done such experiments yet. But you can try migrate only products in this way: 

1 backup your Magento 2 DB
2 in your tool > config.xml leave only "Map Step" and "ConfigurablePrices step" for mode="data". Like this
```
    <steps mode="data">
        <step title="Map Step">
            <integrity>Migration\Step\Map\Integrity</integrity>
            <data>Migration\Step\Map\Data</data>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="ConfigurablePrices step">
            <integrity>Migration\Step\ConfigurablePrices\Integrity</integrity>
            <data>Migration\Step\ConfigurablePrices\Data</data>
            <volume>Migration\Step\ConfigurablePrices\Volume</volume>
        </step>
    </steps>
```
3 instead of [$sourceDocuments = $this->source->getDocumentList();](https://github.com/magento/data-migration-tool/blob/2.2.0/src/Migration/Step/Map/Data.php#L131) paste the next code
```
$sourceDocuments =
    [
        'catalog_product_bundle_option',
        'catalog_product_bundle_option_value',
        'catalog_product_bundle_price_index',
        'catalog_product_bundle_selection',
        'catalog_product_bundle_selection_price',
        'catalog_product_bundle_stock_index',
        'catalog_product_enabled_index',
        'catalog_product_entity',
        'catalog_product_entity_datetime',
        'catalog_product_entity_decimal',
        'catalog_product_entity_gallery',
        'catalog_product_entity_group_price',
        'catalog_product_entity_int',
        'catalog_product_entity_media_gallery',
        'catalog_product_entity_media_gallery_value',
        'catalog_product_entity_text',
        'catalog_product_entity_tier_price',
        'catalog_product_entity_varchar',
        'catalog_product_flat_1',
        'catalog_product_flat_2',
        'catalog_product_link',
        'catalog_product_link_attribute',
        'catalog_product_link_attribute_decimal',
        'catalog_product_link_attribute_int',
        'catalog_product_link_attribute_varchar',
        'catalog_product_link_type',
        'catalog_product_option',
        'catalog_product_option_price',
        'catalog_product_option_title',
        'catalog_product_option_type_price',
        'catalog_product_option_type_title',
        'catalog_product_option_type_value',
        'catalog_product_relation',
        'catalog_product_super_attribute',
        'catalog_product_super_attribute_label',
        'catalog_product_super_attribute_pricing',
        'catalog_product_super_link',
        'catalog_product_website',        
    ]
```
4 migrate data with `--reset`

I am not sure if it will work but that I would do first

**Comment by victor-v-rad** [comment]
If you deleted relations of products with categories then add catalog_category_product your your $sourceDocuments

**Comment by yogeshsyscraft** [comment]
@victor-v-rad  

> If you deleted relations of products with categories then add catalog_category_product your your $sourceDocuments

I have Just selected All Products and clicked on Delete In "Mass Action" Dropdown . now please suggest me should i have to add  "catalog_category_product  " in $sourceDocuments ?

**Comment by victor-v-rad** [comment]
yes add catalog_category_product

**Comment by yogeshsyscraft** [comment]
Wow ! Products migrated ..
Thank you so much @victor-v-rad .  :+1:

**Comment by yogeshsyscraft** [comment]
@victor-v-rad  , products come in admin and database , but they are not appearing in fronted and Search , 
i have tried 

> indexing
> deploy
> setup Upgrade 
> cache  clean 

but no effect , please suggest something

**Comment by victor-v-rad** [comment]
Do you see them assigned to categories in Admin Panel?

**Comment by yogeshsyscraft** [comment]
Yes , they are Assigned , also when i open categories and they Show Number of Assigned products .

**Comment by victor-v-rad** [comment]
catalog_category_product_index* tables are responsible for showing products on the StoreFront. Do they empty?

**Comment by victor-v-rad** [comment]
Do you use flat tables for categories and products? if so turn them off/on then reindex

**Comment by yogeshsyscraft** [comment]
catalog_category_product_index ,  catalog_category_product_index_replica , catalog_category_product_index_tmp 

obove tables ahs lot of data , acros 24369 row are in table .

**Comment by yogeshsyscraft** [comment]
Also i off flat tables for categories and products , and re index , but no effect

**Comment by gouravsyscraft** [comment]
@victor-v-rad  

> catalog_category_product_index* tables are responsible for showing products on the StoreFront. Do they empty?

Victor responsible product have data and this is also associate with its own categories, We found the reason that quantity field are showing blank means this is not migrated?
IS this possible that quantity field not migrated by any reason?
I am waiting for your responce @victor-v-rad

**Comment by victor-v-rad** [comment]
Good hint! 
There are two more tables need to migrate cataloginventory_stock and cataloginventory_stock_item.
Add it to $sourceDocuments as you did it previously and migrate.

**Comment by dekiakbar** [comment]
hello @victor-v-rad , can you give me more detail about migrating from M1 1.9.2.4 to M 2.2.x, but only the product and the category, not all data, and where is the file that content "$sourceDocuments = $this->source->getDocumentList();"
thanks

**Comment by victor-v-rad** [comment]
Hi @dekiakbar the tool migrate all data at once and does not have such function as partial migration natively. But I believe it is possible to migrate only catalog (have not tried yet) if you know now which tables need to exclude from migration. Please look into similar issue reports and learn how the tool works

**Comment by jafar247commerce** [comment]
@yogeshsyscraft , can you share how you able to migrate only products?
I migrated customers and orders only successfully. Looking for how can we migrate only products. If you have done it please share the details.

**Comment by teamcenobite** [comment]
> @yogeshsyscraft , can you share how you able to migrate only products?
> I migrated customers and orders only successfully. Looking for how can we migrate only products. If you have done it please share the details.

@jafar247commerce can you provide config.xml and map.xml examples of how you were able to successfully migrate customers and orders only?

**Comment by Tantuss** [comment]
It is also possible to use n98-magerun to make a db dump which contains no customers, no sales etc.
For example:
n98-magerun db:dump --strip="@development"

Then use this DB for your migration.

**Comment by hafizumer907** [comment]
I have also need migrate only products mean complete catalog(products assigned with categories also), what should i do with custom product attributes?

Can anyone help me please @victor-v-rad  @yogeshsyscraft @jafar247commerce

**Comment by mhafizumer** [comment]
> I have not done such experiments yet. But you can try migrate only products in this way:
> 
> 1 backup your Magento 2 DB
> 2 in your tool > config.xml leave only "Map Step" and "ConfigurablePrices step" for mode="data". Like this
> 
> ```
>     <steps mode="data">
>         <step title="Map Step">
>             <data>Migration\Step\Map\Data</data>
>         </step>
>         <step title="ConfigurablePrices step">
>             <data>Migration\Step\ConfigurablePrices\Data</data>
>         </step>
>     </steps>
> ```
> 
> 3 instead of [$sourceDocuments = $this->source->getDocumentList();](https://github.com/magento/data-migration-tool/blob/2.2.0/src/Migration/Step/Map/Data.php#L131) paste the next code
> 
> ```
> $sourceDocuments =
>     [
>         'catalog_product_bundle_option',
>         'catalog_product_bundle_option_value',
>         'catalog_product_bundle_price_index',
>         'catalog_product_bundle_selection',
>         'catalog_product_bundle_selection_price',
>         'catalog_product_bundle_stock_index',
>         'catalog_product_enabled_index',
>         'catalog_product_entity',
>         'catalog_product_entity_datetime',
>         'catalog_product_entity_decimal',
>         'catalog_product_entity_gallery',
>         'catalog_product_entity_group_price',
>         'catalog_product_entity_int',
>         'catalog_product_entity_media_gallery',
>         'catalog_product_entity_media_gallery_value',
>         'catalog_product_entity_text',
>         'catalog_product_entity_tier_price',
>         'catalog_product_entity_varchar',
>         'catalog_product_link',
>         'catalog_product_link_attribute',
>         'catalog_product_link_attribute_decimal',
>         'catalog_product_link_attribute_int',
>         'catalog_product_link_attribute_varchar',
>         'catalog_product_link_type',
>         'catalog_product_option',
>         'catalog_product_option_price',
>         'catalog_product_option_title',
>         'catalog_product_option_type_price',
>         'catalog_product_option_type_title',
>         'catalog_product_option_type_value',
>         'catalog_product_relation',
>         'catalog_product_website',        
>     ]
> ```
> 
> 4 migrate data with `--reset`
> 
> I am not sure if it will work but that I would do first

Hi, I am try to migrate catalog only(products and category) @victor-v-rad  it migrate all above mention tables But my eav_attribute table is empty. how can we eav_attributes are also migrate?
