### ISSUE TITLE
Data Migration Tool for Magento 2.2.1 and 2.1.10

### ISSUE THREAD

**Issue by lewisje** [magento/data-migration-tool#407]
When version 2.2.1 of the tool is released, will it also work on 2.1.10, or will a separate 2.1.10 version of the tool be released for the new minor release of Magento?

**Comment by victor-v-rad** [comment]
The tool 2.2.1 will be released shortly. Magento 2.2.x is the only branch which the tool supports

**Comment by ihor-sviziev** [comment]
@victor-v-rad why don't you support 2.1.10 anymore?

**Comment by victor-v-rad** [comment]
It is not up to me. But most likely previously released tool 2.1.9 will work on Magento 2.1.10 just fine. If someone needs fixes from 2.2.x branch than he can back-port it manually.
