### ISSUE TITLE
Deltalog for <table_name> is not installed

### ISSUE THREAD

**Issue by sarow471** [magento/data-migration-tool#409]
Hello,

I'm getting these errors when migrating the updates by using "Delta" (bin/magento migrate:delta /var/www/webroot/ROOT/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.0.1/config.xml)

My current version of Magento is 2.2, as per some previous issues related to this one I found m2_cl tables in database but there are only 6 tables and for others it's showing me the exception "Deltalog for <table_name> is not installed". Please suggest me with the appropriate solution for this.

**Comment by victor-v-rad** [comment]
The tables that are monitored for delta changes listed in deltalog.xml.dist file. If the not existed tables are among of them then you can either remove entries from deltalog.xml.dist or rerun deltalog installation. To install deltalog tables again without migrating data, 
1 remove all steps from `<steps mode="data">` in your config.xml 
2 backup your magento2root/var/migration-tool-progress.lock
3 run `migrate:data` with --reset parameter. After you should see
```
INFO][mode: data][stage: setup triggers][step: Stage]: started
[INFO][mode: data][stage: setup triggers][step: Stage]: Migration completed
```
4 restore migration-tool-progress.lock
5 look into your M1 DB for m2_cl_* tables that were not exist previously

**Comment by sarow471** [comment]
Thanks for your response. Removing of entries from deltalog.xml.dist file was not working for me but the second method was working fine. But the data was not updated on the database. I'm getting number of mismatch warnings, please check the screenshot attached.
![screenshot-delta](https://user-images.githubusercontent.com/6189224/32697784-5390f980-c7be-11e7-9709-fda04b266e5e.png)

**Comment by victor-v-rad** [comment]
Depending on your situation you can either restart migration all over again with reassurance that all the necessary deltalog tables are installed or read this issue #316 . The guys used the custom script
