### ISSUE TITLE
After Magento 1.9.1 -> 2.2.1 , product were migrated well but they doesn't seem appear on frontend

### ISSUE THREAD

**Issue by meezin** [magento/data-migration-tool#411]
The test site is 

dev.kbethos.com 

This is my migrated website and you can see the product in back-end but it doesn't appear on frontend.
How can i do that? 

![image](https://user-images.githubusercontent.com/18614465/32730841-49768224-c856-11e7-8a98-810535588543.png)
![image](https://user-images.githubusercontent.com/18614465/32730851-54355654-c856-11e7-8b25-05d8498a3167.png)

After that, price re-index time take horribly too much!

Thank you

Mary Kim 
[data-migration-tool.zip](https://github.com/magento/data-migration-tool/files/1467207/data-migration-tool.zip)

**Comment by maurixxxx** [comment]
I have the same problem after migration from 1.7.2 to 2.2.1. In my frontend the category show the number of product in it but  no product showing. I tried adding some new product manually and they don't show in frontend.

**Comment by victor-v-rad** [comment]
I would suggest rechecking products in Admin Panel. Open it to see if attributes like  Enable Product  Stock Status are ok

**Comment by maurixxxx** [comment]
Thanks, i checked and everything is ok.  I don't think the problem is due to the migration tool otherwise  the product added manually should be visible, isn't?

**Comment by victor-v-rad** [comment]
@maurixxxx as you can see from dev.kbethos.com @meezin made his StoreFront work somehow

**Comment by meezin** [comment]
@victor-v-rad that issue had kept so i downgraded my magento version to 2.1.9

**Comment by victor-v-rad** [comment]
You can send me a link to your DB dump of Magento 1 and I will try to migrate it on my environment to reproduce the issue.

**Comment by meezin** [comment]
I sent email due to big size dump file

**Comment by victor-v-rad** [comment]
@meezin @maurixxxx have you copied media folder from Magento 1 to Magento 2?

**Comment by victor-v-rad** [comment]
One more thing. Magento 2 has improved [xml layout architecture](http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/layouts/layout-overview.html) Thus xml layout from Magento 1 is not compatible with Magento 2. So after migration, change your CMS Pages > Layout Update XML to the format that Magento 2 understand

**Comment by victor-v-rad** [comment]
Use above recommendations to fix your issue with the Fronted not showing products

**Comment by maurixxxx** [comment]
i solved it coping the media folder, thanks.
