### ISSUE TITLE
Data-Migration-Tool Error

### ISSUE THREAD

**Issue by pollom** [magento/data-migration-tool#413]
Hello,

I'm getting the following error when I try to run the migration tool:

[2017-11-16 18:01:36][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-11-16 18:01:36][WARNING]: Source documents are not mapped: core_store,core_store_group,core_website
[2017-11-16 18:01:36][WARNING]: Destination documents are not mapped: store,store_group,store_website
[2017-11-16 18:01:36][INFO][mode: settings][stage: data migration][step: Settings Step]: started

  [Zend_Db_Statement_Exception]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mmnc_old.core_config_data' doesn't exi
  st, query was: SELECT COUNT(*) FROM `core_config_data`

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mmnc_old.core_config_data' doesn't exi
  st

I noticed that the prefix mgt_ isn't being prepended to the table name from the source.  What does this mean?

Thanks.

**Comment by victor-v-rad** [comment]
It seems like source and destination DBs are swapped in config.xml
And use
```
        <source_prefix />
        <dest_prefix />
```
from config.xml if your Magento DB uses prefix

**Comment by pollom** [comment]
Hi Victor,

I was able to fix that error by dropping the prefixes on the tables in the source database.

Mike

**Comment by victor-v-rad** [comment]
This error happens when M1 or M2 use prefix in tables name. Please add your prefix in config.xml file in tags
```
<source_prefix />
<dest_prefix />
```
