### ISSUE TITLE
[SQLSTATE 2300] Integrite Constraint Violation

### ISSUE THREAD

**Issue by pollom** [magento/data-migration-tool#414]
Hello,

I keep getting the error below, even when I revert back to the initial state of the db in magento 2.2.1 :

![image](https://user-images.githubusercontent.com/7291890/32964256-36dbe3d0-cb98-11e7-96ff-5b6a1099f58e.png)

Can anyone help me with this error?

Thanks.

**Comment by victor-v-rad** [comment]
Hi @pollom 

Every customer_entity table in M1 and M2 have UNQ_CUSTOMER_ENTITY_EMAIL_WEBSITE_ID unique index. But seems the index is dropped in your M1 customer_entity table for some reason. Have you solved your issue?

**Comment by pollom** [comment]
Hi Victor,

Thanks for your reply.  I was able to fix that error, but now I'm getting another error that I can't figure out.

The error is: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Defined' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'  

I appreciate your help.

Mike

**Comment by victor-v-rad** [comment]
it is because of the second attempt of migration to the already migrated data. Reinstall magento 2 or restore the DB from a dump

**Comment by pollom** [comment]
When I reinstall magento 2 do I need to drop, and recreate, the database for magento 2?

**Comment by pollom** [comment]
Hi Victor,

I reinstalled magento 2 and ran magento migrate:data ... But I'm getting the error I had before:

[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '20mc92@isdschoolsmail.org-1' for key
   'CUSTOMER_ENTITY_EMAIL_WEBSITE_ID'

Mike

**Comment by pollom** [comment]
The index is there but it isn't unique.  I modified the index to make it unique, and am, now, getting that error in the database.

**Comment by pollom** [comment]
I fixed the Integrity constraint error.

Now I'm getting the following error:

[Exception]
  Warning: Error while sending QUERY packet. PID=3226 in /var/www/vhosts/migration.makemynewspaper.com/vendor/magento/data-migrati
  on-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169

Mike

**Comment by pollom** [comment]
Hi Victor,

The above error seems to have vanished mysteriously, and, now, I am getting  the following error:

[PDOException]
  SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes

Mike

**Comment by victor-v-rad** [comment]
try to set max_allowed_packet = 1024M in my.conf of MySQL

**Comment by pollom** [comment]
Hi Victor,

I made the change you suggested in mariadb-server.cnf but am still getting the error:

[PDOException]
  SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes

Mike

**Comment by pollom** [comment]
Your suggestion worked.  I forgot to restart the database server.  But now I am getting these warnings

Could not unserialize data of table_name.value with record id xxxxx

Mike

**Comment by pollom** [comment]
Does the stage below take a long time?  It seems to be taking a long time.

[2017-11-21 14:41:24][INFO][mode: data][stage: data migration][step: Log Step]: started
0% [>---------------------------] Remaining Time: < 1 sec

**Comment by diazwatson** [comment]
@pollom An easy way around the 
```
[PDOException]
SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' 
```
message is to define the bulk size so the tool does not auto detect it.

Maybe something like 
`<bulk_size>100</bulk_size>`

Yes it is going to take longer but it won't crash

**Comment by iwkse** [comment]
> Hi Victor,
> 
> Thanks for your reply. I was able to fix that error, but now I'm getting another error that I can't figure out.

Hi, I'm getting the same error, how did you fix it?
