### ISSUE TITLE
Why display out of stock option doesn't apply to grouped/configurable product after migration ?

### ISSUE THREAD

**Issue by meezin** [magento/data-migration-tool#415]
Hi! 
In magento2 default, if associated products are out of stock and display out of stock setting as NO, grouped/configurable product shouldn't be shown on frontend. 

My environment is 1.9.1.0 -> 2.1.9 and the grouped/configurable product whose simple products are out of stock still appear on frontend. How can i handle that?

**Comment by victor-v-rad** [comment]
Can't reproduce such scenario. Thought I used the latest magento and the tool 2.2.1
