### ISSUE TITLE
Duplicated attribute_group_name and attribute_set_name Migration_

### ISSUE THREAD

**Issue by diazwatson** [magento/data-migration-tool#416]
I know the purpose of the prefix _Migration__ is to avoid conflicts between M1 and M2 for `attribute_group_name` and `attribute_set_name`.

I also read that after migration we can remove these prefixes from admin but, how can we do this? We can't!

I mean it is not just the prefixes, the `attribute_group_name` and `attribute_set_name` are actually duplicated so it won't be possible to rename.

Also some attributes are attached to the M1 one and some others are attached to the M2 one so we cannot delete any of those.

Am I missing something in here?

**Comment by victor-v-rad** [comment]
What if after migration in Admin Panel add prefix M2_ to native Magento 2 attribute sets and groups and remove Migration_ prefix

**Comment by diazwatson** [comment]
That is a bit ugly isn't?

**Comment by victor-v-rad** [comment]
Agree. That is why MAGETWO-52479 was created. It is about rewriting EAV step in the way that attribute sets and groups from M1 were not copied with Migration_ prefix but merged with attribute sets and groups from M2.

**Comment by diazwatson** [comment]
@victor-v-rad ticket MAGETWO-52479 available for people outside Magento to work with?

**Comment by victor-v-rad** [comment]
Hi @diazwatson 

Just created #627 You can drug it into In progress column if you plan to work on it.

**Comment by diazwatson** [comment]
Great Victor, I'll have a look as soon as I get a chance if nobody else has
done before.
