### ISSUE TITLE
Post migration problems

### ISSUE THREAD

**Issue by pollom** [magento/data-migration-tool#417]
Hello,

After the migration completed I received the following warnings:

[2017-11-23 17:25:02][WARNING]: Could not unserialize data of sales_flat_quote_item_option.value with record id XXXXX

I didn't migrate the settings since that seemed to interfere with the Admin Panel; the Admin Panel wouldn't display in the browser.  The Panel displays if I bypass the settings migration.

And the site displays but with the wrong style sheets and images.  Some of the links are also broken.

Here is the link below:

http://migration.makemynewspaper.com

**Comment by victor-v-rad** [comment]
Hi @pollom 

What the versions of magento and the tool do you use?
Can you show record data from sales_flat_quote_item_option table that causes `Could not unserialize` error?

**Comment by pollom** [comment]
Hi Victor,

We are using Magento 2.2.1.  And I thought I was using the same version of the tool.  I downloaded the tool from the Magento site as an archive(*.tar.gz), and unzipped it in the appropriate directory.  Should I haved used Composer?

For some reason I don't see those records which is odd.  So, I have no idea what's going on.

Mike

**Comment by victor-v-rad** [comment]
You can read the [Migration Guide](http://devdocs.magento.com/guides/v2.2/migration/bk-migration-guide.html). There are instructions how to install and use the tool

**Comment by pollom** [comment]
I read the Migration Guide and followed it to a tee, but I am still having problems.  The main problem is that the css and js files are not being applied correctly.  I checked the Apache rewrites and all that and everything looks okay.  The information for the site shows up but not the way it is supposed to.

In the old version 1.7.0.2 the css, and js, files are located in the following directory:
skin/frontend/mmnc_package/mmnc_default/css/

There is no directory like that in the new version of Magento (Magento 2.2.1).  So, do I need to move these files manually, and, if so, then where in the new version do I do this?  And how do I go about doing this?

Thanks,
Mike

**Comment by pollom** [comment]
... also the links on the main page are broken; they're not working.

**Comment by victor-v-rad** [comment]
the Data Migration Tool migrates only data. Details about custom PHP code / CSS / JS on [this page](http://devdocs.magento.com/guides/v2.2/migration/bk-migration-guide.html)
