### ISSUE TITLE
Customer created_at

### ISSUE THREAD

**Issue by kerlama** [magento/data-migration-tool#419]
Hi,

I have migrated data from 1.9.1.1 to 2.1.9 and spotted that created_at for customers are wrong.

For example, on M1 one customer have created_at = 2017-07-12 19:04:38 but when migrated this value changed to: 2017-12-07 19:04:38

Its on the same server.

Thanks

**Comment by victor-v-rad** [comment]
It seems the date format to display it different 2017-07-12 vs 2017-12-07 month and day are switched . But it it the same date

**Comment by kerlama** [comment]
Well, in customer grid it is showing as December 07 2017 ...

**Comment by kerlama** [comment]
So, anyone has this issue too ?
