### ISSUE TITLE
Delta does not migrate new customers

### ISSUE THREAD

**Issue by dwirt** [magento/data-migration-tool#422]
### Preconditions
1. from Magento 1.9.1.0 to Magento 2.2.1

### Steps to reproduce
1. run migration:data
2. create new customer in m1 shop (frontend or admin, doesn't matter)
3. run migration:delta

### Expected result
1. new customers are in M2 DB

### Actual result
1. new customers are not in M2 DB

changed data of existing customers is migrated, but no new customers are created. Orders, invoices, shipping, etc. work fine, even on the same delta execution.

**Comment by victor-v-rad** [comment]
Maybe not all DB triggers and log tables were been setup. For example check out if m2_cl_sales_flat_order table and trg_sales_flat_order_after_* triggers exist in Magento 1 DB

**Comment by dwirt** [comment]
The `m2_cl_sales_flat_order` table exists (though currently empty) as well as the triggers `trg_sales_flat_order_after_delete`, `trg_sales_flat_order_after_insert` and `trg_sales_flat_order_after_update`.

**Comment by victor-v-rad** [comment]
Check when you create a new order in M1 if the table m2_cl_sales_flat_order gets its id

**Comment by dwirt** [comment]
I just realized that the customer was in the DB, just not in the admin panel. It was just a index and cache issue. Sorry
