### ISSUE TITLE
Only orders are not getting migrated

### ISSUE THREAD

**Issue by PrithweemaD** [magento/data-migration-tool#427]
I want to migrate only orders from Magento 1.9.3.2 to Magento 2.1.7.
Each time it fails, I uninstall the set up & re-install it. But its still getting same error.
[2017-12-15 07:29:49][WARNING]: Mismatch of entities in the document: sales_order_grid
[2017-12-15 07:29:49][WARNING]: Mismatch of entities in the document: sales_invoice_grid
[2017-12-15 07:29:49][WARNING]: Mismatch of entities in the document: sales_shipment_grid
[2017-12-15 07:29:49][WARNING]: Mismatch of entities in the document: sales_creditmemo_grid
[2017-12-15 07:29:49][WARNING]: Volume Check failed
Please help me out. I am stuck here for more than a week.

Is it possible to migrate only orders without any customers in the database?

**Comment by victor-v-rad** [comment]
The tool migrates all data by default. However it might be possible to migrate only orders if tweak the tool to migrate only tables related to orders. For example 
```
sales_flat_order
sales_flat_order_address
sales_flat_order_grid
sales_flat_order_item
sales_flat_order_payment
sales_flat_order_status_history
sales_flat_shipment
sales_flat_shipment_comment
sales_flat_shipment_grid
sales_flat_shipment_item
sales_flat_shipment_track
sales_flat_invoice
sales_flat_invoice_comment
sales_flat_invoice_grid
sales_flat_invoice_item
sales_billing_agreement
sales_billing_agreement_order
sales_flat_creditmemo
sales_flat_creditmemo_comment
sales_flat_creditmemo_grid
sales_flat_creditmemo_item
sales_order_status
sales_order_status_label
sales_order_status_state
sales_order_tax
sales_order_tax_item
sales_payment_transaction
```

**Comment by PrithweemaD** [comment]
Hi @victor-v-rad ,

Have tried everything. This is how my map.xml file looks like,

<?xml version="1.0" encoding="UTF-8"?>

<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../map.xsd">
    <source>
        <document_rules>
            <ignore>
                <document>catalog_category*</document>
            </ignore>
            <ignore>
                <document>catalog_compare*</document>
            </ignore>
            <ignore>
                <document>catalog_eav_attribute</document>
            </ignore>
            <ignore>
                <document>cataloginventory_stock*</document>
            </ignore>
            <ignore>
                <document>catalog_product_*</document>
            </ignore>
            <ignore>
                <document>core_*</document>
            </ignore>
            <ignore>
                <document>cms_*</document>
            </ignore>

            <rename>
                <document>sales_flat_order_grid</document>
                <to>sales_order_grid</to>
            </rename>
            <rename>
                <document>sales_flat_invoice_grid</document>
                <to>sales_invoice_grid</to>
            </rename>
            <rename>
                <document>sales_flat_creditmemo_grid</document>
                <to>sales_creditmemo_grid</to>
            </rename>
            <rename>
                <document>sales_flat_shipment_grid</document>
                <to>sales_shipment_grid</to>
            </rename>

            <rename>
                <document>m2_cl_sales_flat_order_grid</document>
                <to>m2_cl_sales_order_grid</to>
            </rename>
            <rename>
                <document>m2_cl_sales_flat_invoice_grid</document>
                <to>m2_cl_sales_invoice_grid</to>
            </rename>
            <rename>
                <document>m2_cl_sales_flat_creditmemo_grid</document>
                <to>m2_cl_sales_creditmemo_grid</to>
            </rename>
            <rename>
                <document>m2_cl_sales_flat_shipment_grid</document>
                <to>m2_cl_sales_shipment_grid</to>
            </rename>
        </document_rules>
        <field_rules>
            <move>
                <field>sales_flat_creditmemo_grid.grand_total</field>
                <to>sales_creditmemo_grid.order_base_grand_total</to>
            </move>
             
            <ignore>
                <field>sales_flat_invoice_grid.base_grand_total</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.store_to_order_rate</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.base_to_order_rate</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.store_to_base_rate</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.base_to_global_rate</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.creditmemo_status</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.invoice_id</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.store_currency_code</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.order_currency_code</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.base_currency_code</field>
            </ignore>
            <ignore>
                <field>sales_flat_creditmemo_grid.global_currency_code</field>
            </ignore>
        </field_rules>
    </source>
    <destination>
        <document_rules>
            <ignore>
                <document>catalog_category*</document>
            </ignore>
            <ignore>
                <document>catalog_compare*</document>
            </ignore>
            <ignore>
                <document>catalog_eav_attribute</document>
            </ignore>
            <ignore>
                <document>cataloginventory_stock*</document>
            </ignore>
            <ignore>
                <document>catalog_product_*</document>
            </ignore>
            <ignore>
                <document>core_*</document>
            </ignore>
            <ignore>
                <document>cms_*</document>
            </ignore>
        </document_rules>
        <field_rules>
            <ignore>
                <field>sales_order_grid.billing_address</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.shipping_address</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.shipping_information</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.customer_email</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.customer_group</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.subtotal</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.shipping_and_handling</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.customer_name</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.payment_method</field>
            </ignore>
            <ignore>
                <field>sales_order_grid.total_refunded</field>
            </ignore>

            <ignore>
                <field>sales_invoice_grid.store_name</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.customer_name</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.customer_email</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.customer_group_id</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.payment_method</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.billing_address</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.shipping_address</field>
            </ignore>
             <ignore>
                <field>sales_invoice_grid.shipping_information</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.subtotal</field>
            </ignore>
            <ignore>
                <field>sales_invoice_grid.shipping_and_handling</field>
            </ignore>

            <ignore>
                <field>sales_shipment_grid.customer_name</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.order_status</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.billing_address</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.shipping_address</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.billing_name</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.shipping_name</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.customer_email</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.customer_group_id</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.payment_method</field>
            </ignore>
            <ignore>
                <field>sales_shipment_grid.shipping_information</field>
            </ignore>

            <ignore>
                <field>sales_creditmemo_grid.billing_address</field>
            </ignore>
            <ignore>
                <field>sales_creditmemo_grid.shipping_address</field>
            </ignore>
            <ignore>
                <field>sales_creditmemo_grid.customer_group_id</field>
            </ignore>
            <ignore>
                <field>sales_creditmemo_grid.order_status</field>
            </ignore>
            <ignore>
                <field>sales_creditmemo_grid.customer_name</field>
            </ignore>
            <ignore>
                <field>sales_creditmemo_grid.customer_email</field>
            </ignore>
             <ignore>
                <field>sales_creditmemo_grid.payment_method</field>
            </ignore>
             <ignore>
                <field>sales_creditmemo_grid.shipping_information</field>
            </ignore>
             <ignore>
                <field>sales_creditmemo_grid.subtotal</field>
            </ignore>
             <ignore>
                <field>sales_creditmemo_grid.shipping_and_handling</field>
            </ignore>
             <ignore>
                <field>sales_creditmemo_grid.adjustment_positive</field>
            </ignore>
            <ignore>
                <field>sales_creditmemo_grid.adjustment_negative</field>
            </ignore>
            
            <ignore>
                <field>eav_attribute_group.attribute_group_code</field>
            </ignore>
            <ignore>
                <field>eav_attribute_group.tab_group_code</field>
            </ignore>
        </field_rules>
    </destination>
</map>


Please suggest me if I am doing wrong.

**Comment by victor-v-rad** [comment]
The error `Mismatch of entities in the document: sales_order_grid` means order count more on Magento 1 then on Magento 2 or vice versa

**Comment by bedroomathletics** [comment]
We are also having a similar issue where order count on magento 1 is higher than magento 2. How do we fix this, Delta isn't working correctly, can't we just migrate data for ORDERS only from the beginning to override as such?

**Comment by dnesdeveloper** [comment]
Has anybody found the solution for the above-mentioned issue?

**Comment by jimains** [comment]
I have the same issue, is there a known solution for this? It seems pretty integral to any data migration

**Comment by jimains** [comment]
I have the same issue, is there a known solution for this? It seems pretty integral to any data migration

**Comment by daweedco** [comment]
Hello same issue here , and the table m2_cl_sales_order_grid is populated , but the data wont transfer
