### ISSUE TITLE
Integrity constraint violation upgrading from magento 2.1.4 -> 2.2.2 

### ISSUE THREAD

**Issue by mmiller1** [magento/data-migration-tool#429]
When running `magento setup:upgrade` it fails with the following error:
```
Upgrading data.. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-0-0-0' for key 'PRIMARY', query was: INSERT INTO `salesrule_product_attribute` () VALUES ()
```
looking at the database, a row is being created with all 0 values more than once in the saluesrule_product_attribute table(hence the 0-0-0-0 entry). Deleting the row, and attempting again results in the same error. Another issue in the magento github repo suggests truncating the salesrules but this is not an option as we have many custom salesrules that need to remain.

**Comment by victor-v-rad** [comment]
Hi @msm93v2 

How does it relate to Data Migration Tool?

**Comment by msm93v2** [comment]
I created the issue here based on the result of this issue. https://github.com/magento/magento2/issues/11585

I contacted magento ee support and they provided a patch that resolved this.

**Comment by victor-v-rad** [comment]
I have created new sales rule in Magento 1 but as you can see from screen shot 
![rule](https://user-images.githubusercontent.com/106504/34203252-133caf40-e583-11e7-8fe8-ea5cc87443ae.jpg)
i do not have 0-0-0-0 record. 
You can recreate a new rule with the same conditions to avoid the error

**Comment by dnsv** [comment]
@mmiller1 would you be willing to share the patch? We're also affected and can't truncate the tables.

**Comment by bpoiss** [comment]
Have you found a workaround for this bug?

**Comment by bpoiss** [comment]
What was the fix for this issue? @victor-v-rad
