### ISSUE TITLE
No Customers Visible In Admin Backend After Migration

### ISSUE THREAD

**Issue by quangdog** [magento/data-migration-tool#43]
I'm migrating from 1.7.0.2 -> 2.0.0, and the migrator runs with no errors reported in the log.  After migration, when I log into the backend of the store I see 0 customers in the admin panel. When checking the database tables, it appears that a bunch of data was not actually migrated: 

*customer_address_entity_text*: 
M1 database: 9989 rows
M2 database: 0 rows 

*customer_entity_int*:
M1 database: 23585 rows
M2 database: 8286 rows

*customer_entity_varchar*:
M1 database: 47199 rows
M2 database: 4818 rows

These are just a few examples of differences... lots of other tables have what appear to be incorrect row counts. Shouldn't they all have the same number of rows?

**Comment by quangdog** [comment]
In the interest of getting more data here, I believe the problem is related to getting EAV values mapped correctly, but I'm a bit lost trying to figure out what is not mapping right.  I have not touched the EAV mapping stuff in the migrator - just using the distribution defaults for them.

Here is a complete list of the differences in table row counts from M1 to M2 post-migration.  Some tables I expect to have different counts, others should not.

![Row Counts] (http://i.imgur.com/ith02Xi.png)

I suspect the problem is that the data from eav_attribute is not moving from M1 to M2 correctly, so all the eav tables are messed up as a result.

Help?

**Comment by gigadesign1** [comment]
A lot of attributes that were saved in the customer_entity_int and customer_entity_varchar tables in M1 are now stored in the customer_entity table in M2.
That explains why the customer_entity_int and customer_entity_varchar tables in M2 have less records than in M1.

I don't know why not all of your customer are migrated. I have the same issue migrating customers from 1.9.2.2.

**Comment by victor-v-rad** [comment]
Hi,

1
Try cleaning cache and reindexing using shell.
`php bin/magento indexer:reindex && php bin/magento cache:clean`
It should fix grid of customers in admin panel

2
Check out customer_entity table of Magento 2. It should contain migrated customers. If yes try to login on storefront by some of migrated user

**Comment by quangdog** [comment]
Sweet!  I can see my customers in the admin section now.  However, whenever I try to edit a customer record, I get this error: 

"The configuration parameter "formElement" is a required for "enable" field."

**Comment by quangdog** [comment]
Here is the full error report, in case that is useful: 

a:4:{i:0;s:75:"The configuration parameter "formElement" is a required for "enable" field.";i:1;s:9772:"#0 /var/www/miridiatech/store/vendor/magento/module-ui/Component/Form/Fieldset.php(107): Magento\Ui\Component\Form\Field->prepare()
#1 /var/www/miridiatech/store/vendor/magento/module-ui/Component/Form/Fieldset.php(77): Magento\Ui\Component\Form\Fieldset->prepareField(Array, 'enable', NULL)
#2 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/Generator/UiComponent.php(148): Magento\Ui\Component\Form\Fieldset->prepare()
#3 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Fieldset))
#4 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/Generator/UiComponent.php(126): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form))
#5 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'customer_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/miridiatech/store/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /var/www/miridiatech/store/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /var/www/miridiatech/store/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /var/www/miridiatech/store/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /var/www/miridiatech/store/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#13 /var/www/miridiatech/store/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#14 /var/www/miridiatech/store/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#15 /var/www/miridiatech/store/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#16 /var/www/miridiatech/store/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Custome...')
#17 /var/www/miridiatech/store/vendor/magento/module-customer/Controller/Adminhtml/Index/Edit.php(126): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Custome...')
#18 /var/www/miridiatech/store/var/generation/Magento/Customer/Controller/Adminhtml/Index/Edit/Interceptor.php(24): Magento\Customer\Controller\Adminhtml\Index\Edit->execute()
#19 /var/www/miridiatech/store/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->execute()
#20 /var/www/miridiatech/store/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/miridiatech/store/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#23 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->___callParent('dispatch', Array)
#24 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Array, 'adminAuthentica...')
#25 /var/www/miridiatech/store/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#28 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Array, 'designLoader')
#29 /var/www/miridiatech/store/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#32 /var/www/miridiatech/store/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Array, 'adminMassaction...')
#33 /var/www/miridiatech/store/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/miridiatech/store/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#36 /var/www/miridiatech/store/var/generation/Magento/Customer/Controller/Adminhtml/Index/Edit/Interceptor.php(39): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /var/www/miridiatech/store/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /var/www/miridiatech/store/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#40 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#41 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#42 /var/www/miridiatech/store/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#43 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /var/www/miridiatech/store/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#45 /var/www/miridiatech/store/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#46 /var/www/miridiatech/store/vendor/magento/module-store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#47 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /var/www/miridiatech/store/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#49 /var/www/miridiatech/store/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#50 /var/www/miridiatech/store/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#51 /var/www/miridiatech/store/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#52 /var/www/miridiatech/store/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#53 {main}";s:3:"url";s:48:"/store/admin_16ko83/customer/index/edit/id/9446/";s:11:"script_name";s:16:"/store/index.php";}

**Comment by victor-v-rad** [comment]
@quangdog 
I am closing the issue. Please recheck it in the latest version 2.1.1 of the tool and reopen if it is still actual
