### ISSUE TITLE
Delta migration customer group price

### ISSUE THREAD

**Issue by sarootua** [magento/data-migration-tool#432]
Добрый день, возникла необходимость мигрировать групповые цены в режиме delta. 
Шаги миграции
1. Мигрирую settings 
2. Захожу в deltalog и прописываю необходимые значения для отслеживания (цены, категории и тд и тп)
3. запускаю data - все ок, данные мигрировались
4. в м1 меняю любую сущьность (например цена на товар или категория, создаю товары) 
5. Запускаю delta - все мигрируется(дозагружается) кроме group и tier price

В map.xml документ catalog_product_entity_group_price выставлен с тегом ignore - если я убераю его - и запускаю delta в консоли выдают ошибки

HP Fatal error:  Uncaught TypeError: Argument 2 passed to Migration\Step\Map\Data::getRecordTransformer() must be an instance of Migration\ResourceModel\Document, boolean given, called in /home/admin/web/test.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Map/Delta.php on line 75 and defined in /home/admin/web/test.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Map/Data.php:191
Stack trace:
#0 /home/admin/web/test.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Map/Delta.php(75): Migration\Step\Map\Data->getRecordTransformer(Object(Migration\ResourceModel\Document), false)
#1 /home/admin/web/test.com/public_html/vendor/magento/data-migration-tool/src/Migration/App/Step/AbstractDelta.php(189): Migration\Step\Map\Delta->getRecordTransformer(Object(Migration\ResourceModel\Document), false)
#2 /home/admin/web/test.com/public_html/vendor/magento/data-migration-tool/src/Migration/App/Step/AbstractDelta.php(126): Migration\App\Step\Abst in /home/admin/web/test.com/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Map/Data.php on line 191

Подскажите, как решить проблему или каким способом в режиме delta отслеживать group price ?

**Comment by victor-v-rad** [comment]
Добрый день @sarootua 

Tier Price заменил Group Price в Magento 2. 
http://www.magetraining.com/blog/magento-2-what-has-happened-to-group-price/

Для этого тулза в "Tier Price Step" конветрит все из catalog_product_entity_group_price в catalog_product_entity_tier_price. В "Tier Price Step" нет поддержки delta, но вы это можете сделать смотрите иснтрукцию из [гайда](http://devdocs.magento.com/guides/v2.2/migration/migration-migrate-delta.html#migrate-delta-external-extensions)

**Comment by sarootua** [comment]
Спасибо за ответ, уже решил через экспорт c sql c m1 и стандартным импортом Advanced Price M2
