### ISSUE TITLE
Delta migration does not migrate changes related to enterprise gift card accounts

### ISSUE THREAD

**Issue by molsm** [magento/data-migration-tool#433]
We done full data migration testing and now testing delta migration. Gift card accounts has not been updated on magento 2.
Can not see any related `m2_cl_*` for `enterprise_giftcardaccount_*` tables.

This feature is not implemented in delta migration at all?

**Comment by victor-v-rad** [comment]
@molsm 

Seems you are right about enterprise_giftcardaccount_history table. This table is used in storefront and it should be in deltalog.xml.dist file for delta start to work. Delta tables `m2_cl_*` are setup when data is migrated, which you already done. So in order delta setup tables you can 
1. remove all steps in `data` in your config.xml. Example:
```
    <steps mode="data">
    </steps>
```
2. backup your var/migration-tool-progress.lock
3. rerun migrate:data with `--reset` option
4. restore  var/migration-tool-progress.lock
5. check that `m2_cl_enterprise_giftcardaccount_history ` tables is setup

or you can clean your M2 DB to its initial state and rerun migrate:data with `--reset` option

**Comment by molsm** [comment]
Hi @victor-v-rad ,

Thanks for info.

But what about case when on magento 1 new gift card was created after `migration:data` ?
You are migration in `deltalog.xml` only gift account history!?

Best regards,

**Comment by victor-v-rad** [comment]
By default the tool should process all operations on StoreFront and order processing in Admin Panel. But you can add in your deltalog.xml all enterprise_giftcardaccount* tables to catch by delta mode.
