### ISSUE TITLE
Clicking on product (Edit option) from ADMIN is throwing a FATAL ERROR: Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given

### ISSUE THREAD

**Issue by mrkkd2013** [magento/data-migration-tool#436]
**After data Migration to 2.2.1 from 1.9**

## Clicking on product (Edit option) from ADMIN is throwing a -----"FATAL ERROR:"

 **Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given....."**

## Preconditions

1) we migrated our project from 1.9 to 2.2.1 using data migration tool.
2) Magento 2.2.1, PHP 7.1.9, MYSQL 5.7.19
3) Cleared/clean the CACHE and run the INDEXING also.
4) Logged to ADMIN section.

## Steps to reproduce

1) Go to ADMIN
2) Navigate from Catalog --> Products 
3)  click on the displayed Products. It redirects to Product Edit page and throws the below error:-

## Actual Result

`Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php on line 212 and defined in C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php:164 Stack trace: #0 C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php(212): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('mailchimp_sync_...', NULL) #1 C:\wamp64\www\xyz\vendor\magento\module-ui\Component\Form\Field.php(84): Magento\Framework\View\Element\UiComponentFactory->create('mailchimp_sync_...', 'datetime', Array) #2 C:\wamp64\www\xyz\vendor\magento\framework\View\Layout\Generator\UiComponent.php(159): Magento\Ui\Component\Form\Field->prepare() #3 C:\wamp64\www\xyz\vendor\magento\framework\View\Layout\Generator\UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiCompon in C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php on line 164
`

## Expected Result

**- should redirect to a product details Edit page and there should not be any error.**

**Can someone please help to fix this**
**Thanks in advance**

**Comment by mrkkd2013** [comment]
@victor-v-rad Could you please guide us in this?

**Comment by victor-v-rad** [comment]
Hi @mrkkd2013 

Seems attributes from MailChimp  extension were migrated and causing the issue. Delete it if you do not use the extension in Magento 2

**Comment by mrkkd2013** [comment]
May i know how to migrate the data without migrating the extensions?

**Comment by jonbunce** [comment]
I have the same issue, with a different module installed. It is a PDF file attachment module in our Magento 1 install

**Comment by seanscott49** [comment]
I am having the same exact issue. On the stock map.xml file, this is near the top.

<ignore>
     <document>mailchimp_sync_batches</document>
</ignore>

I tried removing this and adding the table from m1 to m2 manually, and I have installed the extension ahead of time and tried again. I still get the same error. 

Still debugging.

**Comment by victor-v-rad** [comment]
to not migrate some unwanted attribute add new entry into eav-attribute-groups.xml file inside `<group name="ignore">`

**Comment by deepjoshi94** [comment]
attribute_id `video_gallery` is not there is magento 2. In my case I had to ignore that attribute.

**Comment by Jeeva-Rathinam** [comment]
@victor-v-rad @seanscott49 @mrkkd2013 @jonbunce @deepjoshi94 Anyone help to solve this issue?

**Comment by Jeeva-Rathinam** [comment]
> attribute_id `video_gallery` is not there is magento 2. In my case I had to ignore that attribute.

How can i find which attribute is the error?
