### ISSUE TITLE
1.9.2.4 CE to 2.2.2 CE Unserialize() error

### ISSUE THREAD

**Issue by blantry** [magento/data-migration-tool#437]
In the Map section we get a bunch of warnings that say:

  Could not unserialize data of sales_flat_order_item.product_options with record id 9619

Then an [Exception]
 Notice: unserialize(): Error at offset 175 of 175 bytes in /public_html/vendor/magento  
  /data-migration-tool/src/Migration/Handler/Rule/SerializedData.php on line 36

**Comment by victor-v-rad** [comment]
Hi @blantry 

By default sales_flat_order_item.product_options is processed by \Migration\Handler\SerializeToJson\SalesOrderItem class and not \Migration\Handler\Rule\SerializedData as you mentioned. You can find these handlers in your map.xml file

**Comment by blantry** [comment]
Victor,

Thank you for your response, I am not really worried so much about the warnings I wanted to include them in case they were a part of the larger issue which is the exception error that does not allow the migration to complete.  Any thoughts on what is causing the migration to end prematurely with the following error:

Then an [Exception]
Notice: unserialize(): Error at offset 175 of 175 bytes in /public_html/vendor/magento
/data-migration-tool/src/Migration/Handler/Rule/SerializedData.php on line 36

**Comment by victor-v-rad** [comment]
The problem with your sales or catalog rules. Some of these rules is broken
