### ISSUE TITLE
Class .. does not exist but mentioned in ..

### ISSUE THREAD

**Issue by Lasim** [magento/data-migration-tool#438]
Dear Magento Community,

I'm migrating from CE 1.9.1.0 to CE 2.2.1.
data-migration-tool Version: 2.2.2

I get error with text:

`[2017-12-30 17:22:56][ERROR]: Class Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=85`

I tried to ignore it in class-map.xml file. It did not help.
It looks like the attribute can not be ignored.

In my opinion this is the image of a product ;-)

Full output with -vvv:
```
2017-12-30 17:22:56][ERROR]: Class Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=85
[2017-12-30 17:22:56][INFO][mode: data][stage: volume check][step: EAV Step]: Error occurred. Rollback.
[2017-12-30 17:22:56][INFO][mode: data][stage: volume check][step: EAV Step]: EAV Step: rollback
[2017-12-30 17:22:57][INFO][mode: data][stage: volume check][step: EAV Step]: Please fix errors and run Migration Tool again
                         
  [Migration\Exception]  
  Volume Check failed    
                         

Exception trace:
 () at /opt/xxx/magento2/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:138
 Migration\Mode\Data->runVolume() at /opt/xxx/magento2/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:71
 Migration\Mode\Data->run() at /opt/xxx/magento2/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /opt/xxx/magento2/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at /opt/xxx/magento2/vendor/symfony/console/Application.php:842
 Symfony\Component\Console\Application->doRunCommand() at /opt/xxx/magento2/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /opt/xxx/magento2/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /opt/xxx/magento2/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /opt/xxx/magento2/bin/magento:23

migrate:data [-r|--reset] [-a|--auto] [--] <config>
```

Any idea?

Regards
Lasim

**Comment by victor-v-rad** [comment]
Look for the possible solution in [Migration Guide > Troubleshooting](http://devdocs.magento.com/guides/v2.2/migration/migration-troubleshooting.html)

**Comment by Lasim** [comment]
Hey Viktor,

thanks for your response.
Unfortunately, the solutions did not help.

Add class mapping using the class-map.xml.dist file -> same error.
I also successfully ignored other attributes. The one with "BaseImage" can not be ignored.

**Comment by kp-drc** [comment]
I have the same issue. Any one has solution ?

**Comment by niners52** [comment]
Same issue

**Comment by AurelienLavorel** [comment]
Same for me, you need to modify **vendor/magento/data-migration-tool/etc/opensource-to-opensource/class-map.xml**, not **vendor/magento/data-migration-tool/etc/opensource-to-opensource/class-map**.
I think it's not the expected behavior.

**Comment by kushaljindal92** [comment]
same here it is not working for me. Please let me know if anybody have solution for it

**Comment by sumeetmobiwebtech** [comment]
i am also getting same error
