### ISSUE TITLE
Reflaction error Class Migration\Handler\SerializeToJson\SalesOrderItem does not exist 

### ISSUE THREAD

**Issue by jaysmagento** [magento/data-migration-tool#439]
Hello ,
   When migrating from magento 1.9.3.7 to Magento 2.1.9   getting reflaction error .

![screenshot from 2018-01-02 15 51 58](https://user-images.githubusercontent.com/19706726/34480901-22aa4ff8-efd5-11e7-9437-72101230f310.png)

**Comment by victor-v-rad** [comment]
Hi @jaysmagento 

You can run the tool with `-vvv` option to see backtrace
