### ISSUE TITLE
Migrating customers from 1.9.2.2 to 2.0

### ISSUE THREAD

**Issue by gigadesign1** [magento/data-migration-tool#44]
I'm trying to migrate my data from Magento 1.9.2.2 to 2.0.

When I run the migration tool it 'hangs' on the Customer Attributes Step.
In the console I don't see the progress bar running nor the percentage output. It looks like this:
<img width="727" alt="schermafbeelding 2016-01-09 om 13 00 32" src="https://cloud.githubusercontent.com/assets/1337445/12215923/036e7c20-b6d1-11e5-93f6-f1dd5e126182.png">

We have two Magento 1.9.2.2 installations. One with 32K customers and one with just 80 customers. The issue happens on both databases.

I tried on two different enviroments. Both show this issue.

What could be wrong?

**Comment by victor-v-rad** [comment]
Hi,

Try running with debug verbosity (`-vvv` option in command line) and see if it helps. As example:
`php bin/magento migrate:data /var/www/magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml -vvv`

**Comment by redboxmarcins** [comment]
Did you enable password hashing? Try to switch it off in config.xml

`<upgrade_customer_password_hash>0</upgrade_customer_password_hash>`

**Comment by ilol** [comment]
@gigadesign1 did it helped? Can you please close the issue?

**Comment by victor-v-rad** [comment]
I am closing the issue. Please recheck it in the latest version of the tool and reopen if it is still actual

**Comment by dunctem** [comment]
I am having the same issue 
![image](https://user-images.githubusercontent.com/2025297/28033033-9aa0a52e-657a-11e7-9f53-532fb28dfc21.png)

And when I access all customers, it's empty. Any idea on how to migrate the customers properly?

**Comment by mdruguet** [comment]
Hello, is the migration modify userr's password or not?
