### ISSUE TITLE
Source documents and destinations documents not mapped during data migration from Magento v1.9.3.2 to v2.1.9 

### ISSUE THREAD

**Issue by routbiplab** [magento/data-migration-tool#441]
[2018-01-02 14:00:57][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
[2018-01-02 14:00:57][INFO][mode: data][stage: integrity check][step: EAV Step]: started
[2018-01-02 14:00:57][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
[2018-01-02 14:00:57][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: 1 sec
[0;31m[2018-01-02 14:01:00][ERROR]: Destination documents are not mapped: captcha_log,catalog_product_bundle_option,catalog_product_bundle_option_value,catalog_product_bundle_price_index,catalog_product_bundle_selection,catalog_product_bundle_selection_price,catalog_product_bundle_stock_index,catalog_product_index_price_bundle_idx,catalog_product_index_price_bundle_opt_idx,catalog_product_index_price_bundle_opt_tmp,catalog_product_index_price_bundle_sel_idx,catalog_product_index_price_bundle_sel_tmp,catalog_product_index_price_bundle_tmp,catalog_product_index_price_downlod_idx,catalog_product_index_price_downlod_tmp,cataloginventory_stock,cataloginventory_stock_item,cataloginventory_stock_status,cataloginventory_stock_status_idx,cataloginventory_stock_status_tmp,catalogrule,catalogrule_customer_group,catalogrule_group_website,catalogrule_product,catalogrule_product_price,catalogrule_website,checkout_agreement,checkout_agreement_store,downloadable_link,downloadable_link_price,downloadable_link_purchased,downloadable_link_purchased_item,downloadable_link_title,downloadable_sample,downloadable_sample_title,gift_message,importexport_importdata,newsletter_problem,newsletter_queue,newsletter_queue_link,newsletter_queue_store_link,newsletter_subscriber,newsletter_template,oauth_consumer,oauth_nonce,oauth_token,paypal_billing_agreement,paypal_billing_agreement_order,paypal_cert,paypal_payment_transaction,paypal_settlement_report,paypal_settlement_report_row,persistent_session,product_alert_price,product_alert_stock,quote,quote_address,quote_address_item,quote_item,quote_item_option,quote_payment,quote_shipping_rate,rating,rating_entity,rating_option,rating_option_vote,rating_option_vote_aggregated,rating_store,rating_title,report_compared_product_index,report_event,report_event_types,report_viewed_product_aggregated_daily,report_viewed_product_aggregated_monthly,report_viewed_product_aggregated_yearly,report_viewed_product_index,review,review_detail,review_entity,review_entity_summary,review_status,review_store,sales_bestsellers_aggregated_daily,sales_bestsellers_aggregated_monthly,sales_bestsellers_aggregated_yearly,sales_creditmemo,sales_creditmemo_comment,sales_creditmemo_item,sales_invoice,sales_invoice_comment,sales_invoice_item,sales_invoiced_aggregated,sales_invoiced_aggregated_order,sales_order,sales_order_address,sales_order_aggregated_created,sales_order_aggregated_updated,sales_order_item,sales_order_payment,sales_order_status,sales_order_status_history,sales_order_status_label,sales_order_status_state,sales_order_tax,sales_order_tax_item,sales_payment_transaction,sales_refunded_aggregated,sales_refunded_aggregated_order,sales_shipment,sales_shipment_comment,sales_shipment_item,sales_shipment_track,sales_shipping_aggregated,sales_shipping_aggregated_order,salesrule,salesrule_coupon,salesrule_coupon_aggregated,salesrule_coupon_aggregated_order,salesrule_coupon_aggregated_updated,salesrule_coupon_usage,salesrule_customer,salesrule_customer_group,salesrule_label,salesrule_product_attribute,salesrule_website,search_query,sendfriend_log,shipping_tablerate,sitemap,tax_calculation,tax_calculation_rate,tax_calculation_rate_title,tax_calculation_rule,tax_class,tax_order_aggregated_created,tax_order_aggregated_updated,weee_tax,widget,widget_instance,widget_instance_page,widget_instance_page_layout,wishlist,wishlist_item,wishlist_item_option[0mThere was an error in Step Map Step
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: 1 sec
[0;31m[2018-01-02 14:01:00][ERROR]: Source documents are not mapped: log_visitor[0m
[0;31m[2018-01-02 14:01:00][ERROR]: Destination documents are not mapped: customer_visitor[0mThere was an error in Step Log Step
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec
[0;31m[2018-01-02 14:01:00][ERROR]: Source documents are not mapped: catalog_product_entity_group_price[0mThere was an error in Step Tier Price Step
[2018-01-02 14:01:00][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started

  [Migration\Exception]
  Integrity Check failed

migrate:data [-r|--reset] config

**Comment by mrkkd2013** [comment]
Looks like you need to add the mapping(with ignore tags) entries in the XML
files.

For source documents and fields you have to add
in the source section and for destination documents and fields you have to
add in the document section of XML files.

**Comment by victor-v-rad** [comment]
Hi @routbiplab 

If tables in Magento DB with some custom prefix then it should be set in config.xml > `<options>` > `<source_prefix />` or `<dest_prefix />`
