### ISSUE TITLE
SalesIncrement Integrity check failure while Migrating from Magento v1.9.3.2 to v2.1.9

### ISSUE THREAD

**Issue by routbiplab** [magento/data-migration-tool#442]
[2018-01-03 06:56:10][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started

  [Migration\Exception]
  Integrity Check failed

migrate:data [-r|--reset] config

**Comment by victor-v-rad** [comment]
@routbiplab 

I see no tables or fields mentioned that conflicts. Is it the whole message?
