### ISSUE TITLE
Migrating from 1.9.2.4 to 2.2.1 | integrity constraint violation. duplicate entry

### ISSUE THREAD

**Issue by wedob13** [magento/data-migration-tool#443]
Hello, i run the tool and the end i see the products not getting migrated and i have a pdoException of

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '42-469' for key 'EAV_ENTITY_ATTRIBUTE_ATTRIBUTE_SET_ID_ATTRIBUTE_ID'

do you think the sqlerror is possible of terminating the migration and thus not completing it so thats why i cant see data migrated?

**Comment by victor-v-rad** [comment]
Hi @wedob13 

Yes EAV structure migrates at the beginning. So you do not see migrated data in M2. As for the error, it is not possible to have two the same attributes in attribute set. Look what attribute set with id 42 is and attribute with id 469

**Comment by wedob13** [comment]
@victor-v-rad  Hello victor, yes i checked this i managed to map some attributes in order not to have have conflicts and to delete the duplicate ones. Now i have a question i posted yesterday regarding the entity types. I tried searching everywhere but i got no luck unfortunately :/
