### ISSUE TITLE
Ignore entity types in EAV migration step.

### ISSUE THREAD

**Issue by wedob13** [magento/data-migration-tool#444]
I would like to ask how is it possible to ignore entity_types.

I get the typical error of class 'X' not existing but mentioned in eav_entity_types but its not attribute type.

`Class X does not exist but mentioned in: eav_entity_type.entity_model for entity_type_id=10`

so i cant use the standard <attribute type=""> to ignore it. I try using <entity type=""> tag on my own but it didn't work. Am i missing something?

Thank you in advance!

**Comment by victor-v-rad** [comment]
You can in class-map.xml.dist add something like
```
    <rename>
        <from>extentionname/class_name_of_entity_model</from>
        <to />
    </rename>

```
and migrate. Then remove useless eav_entity_type from DB

**Comment by sheshagiriAnvekar** [comment]
Where we need to add 
<rename>
        <from>extentionname/class_name_of_entity_model</from>
        <to />
    </rename>

in map.xml ? is it in source or destination ?

**Comment by sheshagiriAnvekar** [comment]
I am getting below error while migrating 1.9.0.1 to 2.3.1 

[2019-05-08 09:20:32][ERROR]: Incompatibility in data. Source document: eav_entity_type. Field: entity_model. Error: Class x/y is not mapped in record entity_type_id=9

**Comment by sheshagiriAnvekar** [comment]
Thanks  @victor-v-rad  your solution worked for me
