### ISSUE TITLE
Non-Latin Attribute Group Name Cause 1062 Duplicate Entry Error for Key 'CATALOG_CATEGORY_PRODUCT_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE'

### ISSUE THREAD

**Issue by sirkay777** [magento/data-migration-tool#445]
We have a Chinese site and we use Chinese for attribute group name.
![snip20180111_22](https://user-images.githubusercontent.com/2386695/34806602-cf27c360-f6be-11e7-91cd-fba767d282b6.png)
This error occur when migrating data:
![snip20180111_23](https://user-images.githubusercontent.com/2386695/34806618-ebca5e2e-f6be-11e7-88f7-840ac31f5a5c.png)
Because the tool cannot transform Chinese group name to group code, thus violate integrity constraint for key 'CATALOG_CATEGORY_PRODUCT_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE'

![snip20180111_19](https://user-images.githubusercontent.com/2386695/34806660-48bfb1d8-f6bf-11e7-8f0c-019c43252ccb.png)
data-migration-tool/src/Migration/Model/Eav/AttributeGroupNameToCodeMap.php

**Comment by victor-v-rad** [comment]
Hi @sirkay777 
Thank you for posting this issue. Internal ticket MAGETWO-86688 to fix it

**Comment by magenx** [comment]
is it possible to fixthis issue asap, without any ugly workarounds?
