### ISSUE TITLE
Release 2.1.10, 2.1.11 and other missing versions

### ISSUE THREAD

**Issue by Igloczek** [magento/data-migration-tool#449]
It's extremely annoying when following docs, composer is throwing errors that couldn't find package, just because the version of this tools related to the core version is not released.

http://devdocs.magento.com/guides/v2.0/migration/migration-tool-install.html

**Comment by Siyadev9** [comment]
wow! so we can't do migrations now?

**Comment by Igloczek** [comment]
@Siyadev9 If you are facing the same problem, just use 👍 to let maintainers know that more people have same problems. A comment like this is not helping anyone, you should consider removing it.

**Comment by Igloczek** [comment]
@Siyadev9 no problem, we are all frustrated when stuff like this appears, but it's just a software 😉
