### ISSUE TITLE
[ERROR]: Document has ambiguous configuration: sales_invoice

### ISSUE THREAD

**Issue by awaisaltaf** [magento/data-migration-tool#451]
I am getting this error on integrity check, while all field are managed in map.xml file. In below image green showing field which are in magento2 and red in magento 1 others are common. so both red and green indicated fields are managing in map.xml, i double checked it but getting this error.
![datamigration](https://user-images.githubusercontent.com/10347603/35567371-ae6bf4de-05e6-11e8-8126-39f627433167.png)

**Comment by victor-v-rad** [comment]
Hi @awaisaltaf 
Sorry for late reply. Is this issue still relevant? You can try to `--auto` option to workaround integrity check errors without having to change map.xml file
