### ISSUE TITLE
How to fix? element cannot be added as child to sidebar.additional and sidebar.main, because the latter doesn't exist 

### ISSUE THREAD

**Issue by cmcimport** [magento/data-migration-tool#452]
Hi, I'm receiving these errors about "element cannot be added as child to 'sidebar.additional', because the latter doesn't exist".

[2018-02-02 12:20:24] main.INFO: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'umm.sidemenu.catalog_category_view.main' element cannot be added as child to 'sidebar.main', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'sidebar_main_top_before_laynav' element cannot be added as child to 'sidebar.main', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'umm.sidemenu.catalog_category_view.additional' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'catalog.leftnav' element cannot be added as child to 'sidebar.main', because the latter doesn't exist [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'umm.sidemenu.catalog_category_view.main' tries to reorder itself towards '', but their parents are different: 'sidebar.main' and '' respectively. [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'sidebar_main_top_before_laynav' tries to reorder itself towards '', but their parents are different: 'sidebar.main' and '' respectively. [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'umm.sidemenu.catalog_category_view.additional' tries to reorder itself towards '', but their parents are different: 'sidebar.additional' and '' respectively. [] []
[2018-02-02 12:20:24] main.INFO: Broken reference: the 'catalog.leftnav' tries to reorder itself towards '', but their parents are different: 'sidebar.main' and '' respectively. [] []

Someone could guide me to fix the issue with my sidebar.main and sidebar.additional?
Thanks in advance.

##################### EDIT

I didn't saw this issue at migration until weeks of the installation, so currently my M2 is under production with this bug.
As said @victor-v-rad this errors seems not relevant with the issue.

I would try to detail the error:

At BBDD we have all the fields of our megamenu in the categories. You can writte all these fields at database manually, so you are going to see working correctly the "umm" (Universal MegaMenu) at front-end.

The problem is at backend, when you edit any category all the fields at megamenu are going to be deleted.

I have tried to uninstall I have installed the extension, and to install other similar megamenu solutions with the same result.

Without experience at M2 I though that the log file with "umm.sidemenu" was related, but I was wrong.

**Comment by victor-v-rad** [comment]
Hi @cmcimport 

Sorry for late reply. Is this issue still relevant? It could be a problem with migrated widgets or CMS Pages

**Comment by cmcimport** [comment]
No, I think that this log have not the relationship with my issue. I'm new in M2 and I'm a bit lost with the reports.

I can't save some fields at backend for my categories, these fields are from the "MegaMenu" extension included in my theme, compatible with M2.
I saw these fields in my DB and also at xml files of the extension, in fact, 2 of -maybe- 10 fields are saved correctly, the rest are missed.
Please, can you guide me in order to make a debug when I save my categories?

Can I make anything similar to print_r to check the array or... how do I proceed :/ ?, what I have followed in the official documentation of magento has not given me concrete information of the error

I think that something is wrong at database. :(
Thank you so much.

**Comment by victor-v-rad** [comment]
Probably this "MegaMenu" extension is migrated from Magento 1 to Magento 2. Try to delete them if they are not needed.

**Comment by cmcimport** [comment]
We need it or some similar because our catalog is complicated. Spare parts from different brands.
I tried to uninstall and install other similar extensions to manage the main menu with the same results, nothing to save.

I'm worried about that one day the error will be fatal.

I know that is not the right topic, but do you know some advice to be able to make a debug/backtrace in M2.2.2 in my case?

I really want to do it, also for learn how proceed.

Thank you so much!

**Comment by victor-v-rad** [comment]
Maybe some of these tools can help
https://firebearstudio.com/blog/how-to-debug-magento-2.html
https://cedcommerce.com/magento-2-extensions/developer-debug-tool

**Comment by Naturegreen** [comment]
@cmcimport hi , have you resolved problem , i have the same issue. maybe Ultimo Mega Menu caused this problem?

**Comment by cmcimport** [comment]
Hi @Naturegreen, sorry but I didn't solve it :(

**Comment by jenithagile** [comment]
HI,
 I have Same problem. please anyone help

**Comment by Celggar** [comment]
Hello,
I have the same problem too.

**Comment by Tomasz-Silpion** [comment]
Various elements try to push themselves into sidebar.additional container but that element exists only in 2columns-left page layout. For example adding paypal.partner.right.logo to sidebar.additional is defined in paypal module cms_index_index layout which would throw the info notice if homepage is set as 1column.

In my opinion that's a bug, which needs one of following action to be taken:

1) Refactor Magento\Framework\View\Layout methods not to log such info in development mode
2) Add sidebar.additional in all layouts
3) Refactor module layouts to add elements to sidebar.additional in page_layout/2columns-left.xml only.

Where last option is the best one in my opinion.

As a temporary workaround you can add:
 
```
<?xml version="1.0"?>
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <container name="sidebar.additional" label="Sidebar Additional" htmlTag="div" htmlClass="custom-content">
        <referenceBlock name="wishlist_sidebar" remove="true"/>
        <referenceBlock name="sale.reorder.sidebar" remove="true"/>
        <referenceBlock name="catalog.compare.sidebar" remove="true" />
        <referenceBlock name="paypal.partner.right.logo" remove="true" />
        <referenceBlock name="bml.right.logo" remove="true" />
    </container>
</layout>
```

as your theme Magento_Theme/page_layout/1column.xml

**Comment by jaxtheking** [comment]
Thanks @Tomasz-Silpion, your workaround seems to work for me.
Even better, the below is more concise and foolproof as one doesn't have to list all possible blocks that any module may be trying to add to the `sidebar.additional` container:

```
<?xml version="1.0"?>
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <container name="sidebar.additional" label="Sidebar Additional" htmlTag="div"/>
    <referenceContainer name="sidebar.additional" remove="true"/>
</layout>
```

**Comment by sneider86** [comment]
Thanks this workarround work for me. in Magento 2.2.6

**Comment by sneider86** [comment]
Hi, i am debuging my ecommer and now show this error.
[2018-12-10 22:40:32] main.INFO: Broken reference: the 'skip_gallery_before' tries to reorder itself towards 'product.info.media.image', but their parents are different: 'skip_gallery_before.wrapper' and 'product.info.media' respectively. [] []
please anybody can help me.

**Comment by krytenuk** [comment]
Thanks @Tomasz-Silpion your workaround also works in Magento 2.3.0

**Comment by AnthonyIp** [comment]
@krytenuk can you tell me which file did you put the code ?

**Comment by krytenuk** [comment]
@AnthonyIp app\design\frontend\Vendor\theme\Magento_Theme\page_layout\1column.xml

**Comment by AnthonyIp** [comment]
@krytenuk doesn't work for me, I made the change in `/vendor/magento/module-layered-navigation/view/frontend/page_layout/1column.xml`
Here is the content : 
`
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <move element="catalog.leftnav" destination="content.top" after="-"/>
    <container name="sidebar.additional" label="Sidebar Additional" htmlTag="div"/>
    <referenceContainer name="sidebar.additional" remove="true"/>
</layout>
`

**Comment by tim-bezhashvyly** [comment]
@victor-v-rad Why the hack this issue is silently closed?

**Comment by victor-v-rad** [comment]
@LlZARD Is the issue caused by the tool? Nobody forbid to continue conversation here.

**Comment by mertgokceimam** [comment]
@victor-v-rad yes the issue is caused by Magento's not fully correct logic implementation. As another user is suggested Magento needs to refactor how these type of errors are generated

**Comment by tim-bezhashvyly** [comment]
I believe what @victor-v-rad means and looks like he is right this is a wrong repository for this issue.

**Comment by michalbiarda** [comment]
> Thanks @Tomasz-Silpion, your workaround seems to work for me.
> Even better, the below is more concise and foolproof as one doesn't have to list all possible blocks that any module may be trying to add to the `sidebar.additional` container:
> 
> ```
> <?xml version="1.0"?>
> <layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
>     <container name="sidebar.additional" label="Sidebar Additional" htmlTag="div"/>
>     <referenceContainer name="sidebar.additional" remove="true"/>
> </layout>
> ```

@jaxtheking 2columns-left layout inherits from 1column layout, so with such change "sidebar.additional" (the real one) will be removed from all other layouts.

I suggest the following fix in custom theme:

1column.xml:
```
<?xml version="1.0"?>
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <referenceContainer name="columns">
        <container name="div.sidebar.main" htmlTag="div" htmlClass="sidebar sidebar-main" after="main">
            <container name="sidebar.main" as="sidebar_main" label="Sidebar Main"/>
        </container>
        <container name="div.sidebar.additional" htmlTag="div" htmlClass="sidebar sidebar-additional" after="div.sidebar.main">
            <container name="sidebar.additional" as="sidebar_additional" label="Sidebar Additional"/>
        </container>
    </referenceContainer>
    <referenceContainer name="div.sidebar.main" remove="true" />
    <referenceContainer name="div.sidebar.additional" remove="true" />
</layout>
```

2columns-left.xml
```
<?xml version="1.0"?>
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <referenceContainer name="div.sidebar.main" remove="false" />
    <referenceContainer name="div.sidebar.additional" remove="false" />
</layout>
```

**Comment by michalbiarda** [comment]
In case someone is looking for a fix to similar bug appearing in checkout layout, here's the resolution:

checkout.xml
```
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <referenceContainer name="columns">
        <container name="div.sidebar.main" htmlTag="div" htmlClass="sidebar sidebar-main" after="main">
            <container name="sidebar.main" as="sidebar_main" label="Sidebar Main"/>
        </container>
        <container name="div.sidebar.additional" htmlTag="div" htmlClass="sidebar sidebar-additional" after="div.sidebar.main">
            <container name="sidebar.additional" as="sidebar_additional" label="Sidebar Additional"/>
        </container>
    </referenceContainer>
    <referenceContainer name="div.sidebar.main" remove="true" />
    <referenceContainer name="div.sidebar.additional" remove="true" />
    <container name="header.container" as="header_container" label="Page Header Container" htmlTag="header" htmlClass="page-header" before="main.content"/>
    <container name="page.top" as="page_top" label="After Page Header" after="header.container"/>
    <container name="footer-container" as="footer" before="before.body.end" label="Page Footer Container" htmlTag="footer" htmlClass="page-footer"/>
    <referenceContainer name="header.container" remove="true" />
    <referenceContainer name="page.top" remove="true" />
    <referenceContainer name="footer-container" remove="true" />
</layout>
```
