### ISSUE TITLE
[Migration\Exception] Volume Check failed - Url Rewrite Step - Magento 1.7.0.2 -> 2.2.2

### ISSUE THREAD

**Issue by HannanAkbar** [magento/data-migration-tool#453]
```
[2018-02-04 02:31:06][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
100% [============================] Remaining Time: < 1 sec
[2018-02-04 02:31:31][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Error occurred. Rollback.
[2018-02-04 02:31:31][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Url Rewrite Step: rollback
[2018-02-04 02:31:31][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Please fix errors and run Migration Tool again


  [Migration\Exception]
  Volume Check failed
```
**Stack Trace**
```
Exception trace:
 () at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:138
 Migration\Mode\Data->runVolume() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:71
 Migration\Mode\Data->run() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /opt/bitnami/apps/magento/htdocs/bin/magento:23
```

**Comment by HannanAkbar** [comment]
I also tried wiping the DB and starting the process from start, but got the same error.

**Comment by HannanAkbar** [comment]
I temporarily modified the code to skip the error and go to the next step.

`[Magento Root]/vendor/magento/data-migration-tool/src/Migration/Step/UrlRewrite/Version191to2000.php`

Add this line `$result = true;` before the `return` statement inside the `volume()` function on line **249**.

**Comment by victor-v-rad** [comment]
Hi @HannanAkbar 

Did URL rewrites migrate properly? The only thing that their number is not right.

**Comment by chmoelders** [comment]
I run into the same issue.

The error caused by a duplicate in my source table `cms_page`. 
More specific `cms_page.identifier` *no-route* exists two times for different languages but only one CMS_Page was migrated.

I've deleted one *no-route* page and everything works fine.

**Comment by priceguru1** [comment]
I run into same issue.

In source database, there was two cms pages with same identifier. Please check and if its duplicate page with same identifier then delete one cms page and run migration data again.

**Comment by liushu2000** [comment]
> I run into the same issue.
> 
> The error caused by a duplicate in my source table `cms_page`.
> More specific `cms_page.identifier` _no-route_ exists two times for different languages but only one CMS_Page was migrated.
> 
> I've deleted one _no-route_ page and everything works fine.

Thanks, I got the same issue, fixed using your solution, thanks

**Comment by cljk** [comment]
> I run into the same issue.
> 
> The error caused by a duplicate in my source table `cms_page`.
> More specific `cms_page.identifier` _no-route_ exists two times for different languages but only one CMS_Page was migrated.
> 
> I've deleted one _no-route_ page and everything works fine.

Was the reason in my case too. But I had several pages in a bilingual setup with same `identifier`.
Looked for it with

```
select * from cms_page p1, cms_page p2 where p1.identifier = p2.identifier and p1.page_id != p2.page_id;
```

**Comment by abkrim** [comment]
In mi case are several duplicates.

```
SELECT  identifier, COUNT(identifier) FROM databses.cms_page GROUP BY identifier HAVING COUNT(identifier) > 1;
'home', '3'
'newsletter', '2'
'no-route', '4'
```
More info:
Home is because there're 3 shop (multishop)


There is no other explanation or solution?
