### ISSUE TITLE
Customizable Options are not showing on frontend 2.2.2

### ISSUE THREAD

**Issue by heyepic** [magento/data-migration-tool#457]
### Preconditions

1. Import catalog from Magento 1.9 to 2.2.2

### Steps to reproduce

1. Visit product with custom options on front-end.

### Expected result

1. Visitor can choose custom options if they exist. 

### Actual result

1. Options do not appear.

**If you visit the product in the backend and then just click "Save", this fixes it. The problem is we have have almost 3,000 products. Is there a way to bulk do this fast?**

**Comment by victor-v-rad** [comment]
Did you use Data Migration Tool to transfer data of Magento 1? Because the custom options work fine after  I migrated a store with the tool
