### ISSUE TITLE
Unable to Create An Account after migrating data from magento 1.7.0.2 to magento 2.1.8

### ISSUE THREAD

**Issue by tousif12** [magento/data-migration-tool#458]
hi ,
I migrated data of Customers and Sales from 1.7.0.2 to 2.1.8 . But after that when I try to sign up for a new customer it says 
**enter customer email or id** .  And on checkout as well new registration is not appearing. 
I followed this blog to migrate 
[](https://www.pinpointdesigns.co.uk/migrating-data-from-magento-1-to-magento-2-using-the-data-migration-tool/)

My map.xml.dist  and config.xml file is as follow
https://gist.github.com/tousif12/466d097e0c4400b607a619196d31308e#file-config-xml

**Comment by victor-v-rad** [comment]
Hi @tousif12 

Since 2.1.8 the tool has released many new versions. It is preferable to use the latest stable 2.2.2 . It contains a lot of bugfixes

**Comment by tousif12** [comment]
@victor-v-rad   I am on Magento 2.1.8  so On magento 2.1.8 I can use 2.2.2 ?  and Its a know bug on 2.1.8 tool ?

**Comment by victor-v-rad** [comment]
the tool 2.2.2 is not compatible with magento 2.1.8
