### ISSUE TITLE
Data migration Class error

### ISSUE THREAD

**Issue by kp-drc** [magento/data-migration-tool#459]
I tried to migrate data from Magento 1.9.2.2 to Magento 2.2.2 for testing using data migration version 2.2.2.  But I am getting below error in migration process.

[2018-02-14 11:45:37][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2018-02-14 11:45:37][ERROR]: Class Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=74
[2018-02-14 12:26:56][INFO][mode: data][stage: volume check][step: EAV Step]: Error occurred. Rollback.
[2018-02-14 12:26:56][INFO][mode: data][stage: volume check][step: EAV Step]: EAV Step: rollback
[2018-02-14 12:26:56][INFO][mode: data][stage: volume check][step: EAV Step]: Please fix errors and run Migration Tool again
                         
  [Migration\Exception]  
  Volume Check failed    

I already tried after adding below in **class-map.xml.dist** but it didn't work.

    <rename>
        <from>Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage</from>
        <to />
    </rename>

**Comment by victor-v-rad** [comment]
Hi @kp-drc 

`<from>` should contain class name in M1 style (e.g. `adminhtml/catalog_product_helper_form_config`)

**Comment by kp-drc** [comment]
Thanks for reply. So for Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage which M1 style class I should use ?

**Comment by kp-drc** [comment]
I tried both `adminhtml/catalog_product_helper_form_baseimage` and `adminhtml/catalog_product_helper_form_base_image` but it didn't work.

**Comment by victor-v-rad** [comment]
What value catalog_eav_attribute.frontend_input_renderer has with attribute_id=74?

**Comment by kp-drc** [comment]
It is `image` attribute in M1 table.

**Comment by kp-drc** [comment]
And `frontend_input_renderer` for attribute_id 74 is empty in table `catalog_eav_attribute`

**Comment by kp-drc** [comment]
Any hint @victor-v-rad  ?

**Comment by kp-drc** [comment]
@victor-v-rad  `frontend_input_renderer` for attribute_id 74 is empty in table `catalog_eav_attribute` in M1.
It is `image` attribute in M1 table.

**Comment by victor-v-rad** [comment]
If frontend_input_renderer was empty for attribute_id 74 then you would not get the error

**Comment by kp-drc** [comment]
@victor-v-rad  Yes. I double checked. It is empty there in M1 database. So what can be the solution now ?

**Comment by bobdavison** [comment]
BaseImage was a Magento 2 class in version 2.0 but was later removed.
The install scripts still set the frontend_input_renderer to this BaseImage but then upgrade scripts set it to null.

@kp-drc have you run `magento setup:upgrade`?  
This should remove the reference to BaseImage in the catalog_eav_attribute table.

If not, the results of the following 2 queries on your M2 database might be interesting:

select * from setup_module where module='Magento_Catalog';
select attribute_id from catalog_eav_attribute where frontend_input_renderer='Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage';

**Comment by kp-drc** [comment]
@bobdavison @victor-v-rad  I already tried it but didn't work.
