### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'entity_model' cannot be null

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#460]
Hi @victor-v-rad , @balex13 , @ygrigoriev @RuslanKostiv1 @slamking @magento-team  I am getting in below issue when migrating from 1.9.0.1 to 2.2 . 

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'entity_model' cannot be null
`

after going to table **eav_entity_type** i found entity_model column value is blank in 3 rows , please have a look below snap shot .
![tabl](https://user-images.githubusercontent.com/32513730/36206461-77c2847e-11b8-11e8-9862-bbbebd227958.png)

When i deleted rows which has blank value , its creating another error of Offset 3 required .
Please suggest something . 

Thanks 
Yogesh

**Comment by yogeshsyscraft** [comment]
any Help @victor-v-rad  ???

**Comment by victor-v-rad** [comment]
Hi @yogeshsyscraft 

I assume your eav_entity_type.entity_model filed allows NULL value. But normally NULL is not allowed for this field. So the solution is simple to set empty string as value of this filed

**Comment by yogeshsyscraft** [comment]
Hi @victor-v-rad  Thanks For reply . 
Can  you please tell me how to do this , i have tried it manually from Db but got error .

Many Thanks

**Comment by yogeshsyscraft** [comment]
@victor-v-rad  Can you please give me some solution . as i  am sure you can give me solution .

**Comment by victor-v-rad** [comment]
Here is the instructions https://stackoverflow.com/questions/13014836/update-cell-to-be-empty-mysql-php

**Comment by Siyadev9** [comment]
@yogeshsyscraft did this help?

**Comment by yogeshsyscraft** [comment]
@Siyadev9  You are right , above process is not working , what i have done  , i have setup  new magento 1 Store , than export all required data from magento 1 Old to magento 1.9 new fresh , than start migrating process from fresh magento 1.9  to magento 2 . and it was working very well .

**Comment by MrCodeFreak** [comment]
@yogeshsyscraft what process did you use to move your old data to the new fresh Magento 1.9 site?

**Comment by yogeshsyscraft** [comment]
@MrCodeFreak  Import/export process
