### ISSUE TITLE
Virtual type does not exist but mentioned in

### ISSUE THREAD

**Issue by bobdavison** [magento/data-migration-tool#461]
Magento 2.2.1, Migration Tool 2.2.1

I am getting the following error:
`ERROR: Class Simplyhops\ProductAdmin\Model\Config\Source\Variety does not exist but mentioned in: eav_attribute.source_model for attribute_id=257`

I have looked at the [Migration Troubleshooting](http://devdocs.magento.com/guides/v2.2/migration/migration-troubleshooting.html#class-does-not-exist-but-mentioned) page and suggestions in issue #144.

This error is related to a new attribute in my Magento 2 code, it is not migrated but the migration tool seems to move it to a new attribute id and the volume check attempts to validate it.  The class does not exists as it is a virtual type configured in my di.xml.

I have tried adding the effected attribute into the ignore section of eav-attribute-groups.xml and adding an empty class map to class-map.xml but to no avail.

**Comment by bobdavison** [comment]
I have got round this by providing a custom Migration\Step\Eav\Volume sub-class via config.xml that changes  [line 153](https://github.com/magento/data-migration-tool/blob/a6d0154f33aabbdc609f515723568b54e160772c/src/Migration/Step/Eav/Volume.php#L153) to also check if the ObjectManager can create an instance of the type.

It is not a great solution as it instantiates the objects rather than just checking that  they are valid but it works for now.

**Comment by kp-drc** [comment]
@bobdavison  I am also getting similar error below. Can you please help to fix it ?

Class Magento\Catalog\Block\Adminhtml\Product\Helper\Form\BaseImage does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=74

**Comment by bobdavison** [comment]
@kp-drc your problem is unrelated, the BaseImage class does not exist as it was removed from Magento between versions 2.0 and 2.1

You could set the offending frontend_input_renderer to null in the catalog_eav_attribute table but you should consider upgrading to a newer release of Magento 2.

**Comment by kp-drc** [comment]
@bobdavison  I am using Magento 2.2.2. It is already latest.

**Comment by bobdavison** [comment]
@kp-drc your problem is unrelated to this issue and you already have your own issue open.  If I can help I will comment on your issue.

**Comment by victor-v-rad** [comment]
Hi @bobdavison 

Thank you for posting this issue. Internal ticket MAGETWO-87959 to fix it
