### ISSUE TITLE
Magento 1.9.2.4 -> 2.2.2 serious issue - url rewrites stopped working

### ISSUE THREAD

**Issue by caww** [magento/data-migration-tool#462]
Hi
I did full migration and there was No errors at all in command line

But attributes set from old site was migrated with this name:
Migration_default

But now we expirience trouble:
-When we go to edit any old (migrated product) and change URL - nothing happend - rewrites not added even if I keep checkbox checked (create redirection from old url)
-When i create new product and using any of attributes set then all is working fine

Please help to find way 
We have 700+ products and re-create all seems too hard
====
indexer:reindex --- did many times -- nothing changed

**Comment by molsm** [comment]
Hello @caww attributes set "Migration" prefix is expected behaviour. Data migration tool do that for a reason. You can easily re-name it from admin.

About url rewrites...hard to tell...

**Comment by victor-v-rad** [comment]
Hi @caww 

Internal ticket MAGETWO-87957 to fix this issue. I tried to change attribute set to 'Default' but did not work.

**Comment by caww** [comment]
Hi @victor-v-rad 
Exists plans to fix this bug? I mean in roadmap

**Comment by victor-v-rad** [comment]
The issue was fixed in #541
