### ISSUE TITLE
magento 1.9.2.4 to magento2 migration

### ISSUE THREAD

**Issue by bijugit** [magento/data-migration-tool#463]
Hi,

We want migrate only customer and sales order details. what are the map files enable in config.xml file 

Regards,
Biju

**Comment by victor-v-rad** [comment]
Hi @bijugit 

there are several similar tickets #337 #427 #326 #406

**Comment by bijugit** [comment]
Hi,
when i was using this command "php bin/magento migrate:data -r /vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml"

it gives some warning " Could not unserialize data of sales_flat_order_item.product_options with record id 206", please refer this screen shot ( http://prntscr.com/ifjrw8 ).

we have to migrate data from 1.9.2.4 to 2.2.2

is there any fix for this?


Regards,
Biju.

**Comment by kp-drc** [comment]
@victor-v-rad  I am getting similar error for sales qoute options table.

**Comment by victor-v-rad** [comment]
What data these records have in sales_flat_order_item.product_options ?

**Comment by premalathappts** [comment]
Dear Team,

While migrating the data from magento 1.9.0.1 to magento 2.2.4 i faced the same issues you have mentioned above.

I checked the solution you have shared but map.xml is configured correctly.
<transform>
                <field>sales_flat_order_item.product_options</field>
                <handler class="\Migration\Handler\SerializeToJson\SalesOrderItem"/>
            </transform>

[2018-08-16 07:01:26][WARNING]: Could not unserialize data of sales_flat_order_item.product_options with record id 6290

How can i solve this error?
