### ISSUE TITLE
Need to Update Renaming Products , Customer , Order , from the date of last last Data Migration .

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/data-migration-tool#464]
Hi @victor-v-rad  ,

We want to migrate renaming data From last Migrate , as In Delta document define that delta Migrate will do  
`data that customers added via storefront (created orders, reviews, changes in customer profiles, etc.)`

but now i want to migrate Products and categories changes too , Is there any way . 

Thanks

**Comment by victor-v-rad** [comment]
Similar questions already have been posted.
