### ISSUE TITLE
New attribute options do not survive migration

### ISSUE THREAD

**Issue by bobdavison** [magento/data-migration-tool#465]
Magento 2.2.1, Migration 2.2.1

I have new M2 module which creates new product attributes, some of which have options.
I create a clean M2 database and run `setup:upgrade`
The new options exist in the eav_attribute_option and eav_attribute_option_value tables.
I run migration.
The new attributes are still there but the options have disappeared from the option tables.

Is there something I can put in any mapping file to prevent this?

**Comment by victor-v-rad** [comment]
Hi @bobdavison 

The solution can be installing the extension after `migrate:data`

**Comment by bobdavison** [comment]
@victor-v-rad yes, in this instance I could do it that way and probably will.

I still think that it is a bug in the migration code.  Do you agree?

**Comment by victor-v-rad** [comment]
In most cases the tool overwrites data in Magento 2. 
From the [Migration Guide](http://devdocs.magento.com/guides/v2.3/migration/migration-tool-preconditions.html) 

>We do not recommend creating new entities (products, categories, attributes, etc.) in your Magento 2 store before migration because the Data Migration Tool **overwrites** such new entities with the old ones from Magento 1.

**Comment by bobdavison** [comment]
Ah, I missed that.  I had planned to set up lots in M2 before running migration so I will have to change our plans.

Thanks for letting me know.
