### ISSUE TITLE
Order Not Migrating:: Mismatch of entities in the document: sales_order_grid

### ISSUE THREAD

**Issue by gouravsyscraft** [magento/data-migration-tool#467]
Hello Team,

I have migrated the magneto 1.9.0.1 to magento 2.2 all data... bu when after some time i need to migrate only order and customer then i done below step.

1) First remove all customer and order with below query.
Truncate Order****

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `gift_message`;
TRUNCATE TABLE `quote`;
TRUNCATE TABLE `quote_address`;
TRUNCATE TABLE `quote_address_item`;
TRUNCATE TABLE `quote_id_mask`;
TRUNCATE TABLE `quote_item`;
TRUNCATE TABLE `quote_item_option`;
TRUNCATE TABLE `quote_payment`;
TRUNCATE TABLE `quote_shipping_rate`;
TRUNCATE TABLE `reporting_orders`;
TRUNCATE TABLE `sales_bestsellers_aggregated_daily`;
TRUNCATE TABLE `sales_bestsellers_aggregated_monthly`;
TRUNCATE TABLE `sales_bestsellers_aggregated_yearly`;
TRUNCATE TABLE `sales_creditmemo`;
TRUNCATE TABLE `sales_creditmemo_comment`;
TRUNCATE TABLE `sales_creditmemo_grid`;
TRUNCATE TABLE `sales_creditmemo_item`;
TRUNCATE TABLE `sales_invoice`;
TRUNCATE TABLE `sales_invoiced_aggregated`;
TRUNCATE TABLE `sales_invoiced_aggregated_order`;
TRUNCATE TABLE `sales_invoice_comment`;
TRUNCATE TABLE `sales_invoice_grid`;
TRUNCATE TABLE `sales_invoice_item`;
TRUNCATE TABLE `sales_order`;
TRUNCATE TABLE `sales_order_address`;
TRUNCATE TABLE `sales_order_aggregated_created`;
TRUNCATE TABLE `sales_order_aggregated_updated`;
TRUNCATE TABLE `sales_order_grid`;
TRUNCATE TABLE `sales_order_item`;
TRUNCATE TABLE `sales_order_payment`;
TRUNCATE TABLE `sales_order_status_history`;
TRUNCATE TABLE `sales_order_tax`;
TRUNCATE TABLE `sales_order_tax_item`;
TRUNCATE TABLE `sales_payment_transaction`;
TRUNCATE TABLE `sales_refunded_aggregated`;
TRUNCATE TABLE `sales_refunded_aggregated_order`;
TRUNCATE TABLE `sales_shipment`;
TRUNCATE TABLE `sales_shipment_comment`;
TRUNCATE TABLE `sales_shipment_grid`;
TRUNCATE TABLE `sales_shipment_item`;
TRUNCATE TABLE `sales_shipment_track`;
TRUNCATE TABLE `sales_shipping_aggregated`;
TRUNCATE TABLE `sales_shipping_aggregated_order`;
TRUNCATE TABLE `tax_order_aggregated_created`;
TRUNCATE TABLE `tax_order_aggregated_updated`;
SET FOREIGN_KEY_CHECKS=1;

**Truncate Customer**

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `customer_address_entity`;
TRUNCATE TABLE `customer_address_entity_datetime`;
TRUNCATE TABLE `customer_address_entity_decimal`;
TRUNCATE TABLE `customer_address_entity_int`;
TRUNCATE TABLE `customer_address_entity_text`;
TRUNCATE TABLE `customer_address_entity_varchar`;
TRUNCATE TABLE `customer_entity`;
TRUNCATE TABLE `customer_entity_datetime`;
TRUNCATE TABLE `customer_entity_decimal`;
TRUNCATE TABLE `customer_entity_int`;
TRUNCATE TABLE `customer_entity_text`;
TRUNCATE TABLE `customer_entity_varchar`;
TRUNCATE TABLE `customer_grid_flat`;
TRUNCATE TABLE `customer_log`;
TRUNCATE TABLE `customer_log`;
TRUNCATE TABLE `customer_visitor`;
TRUNCATE TABLE `persistent_session`;
TRUNCATE TABLE `wishlist`;
TRUNCATE TABLE `wishlist_item`;
TRUNCATE TABLE `wishlist_item_option`;
SET FOREIGN_KEY_CHECKS=1;

**Then i only keep below step for Data step in config.xml.**

 <steps mode="data">
      <step title="Customer Attributes Step">
           <integrity>Migration\Step\Customer\Integrity</integrity>
           <data>Migration\Step\Customer\Data</data>
           <volume>Migration\Step\Customer\Volume</volume>
       </step>

       <step title="Map Step">
           <integrity>Migration\Step\Map\Integrity</integrity>
           <data>Migration\Step\Map\Data</data>
           <volume>Migration\Step\Map\Volume</volume>
       </step>
       <step title="OrderGrids Step">
           <integrity>Migration\Step\OrderGrids\Integrity</integrity>
           <data>Migration\Step\OrderGrids\Data</data>
           <volume>Migration\Step\OrderGrids\Volume</volume>
       </step>
       <step title="SalesIncrement Step">
           <integrity>Migration\Step\SalesIncrement\Integrity</integrity>
           <data>Migration\Step\SalesIncrement\Data</data>
           <volume>Migration\Step\SalesIncrement\Volume</volume>
       </step>
    </steps>

And run Migrate:data command, So now customer migrated successfully but order not migrating.. I am getting below error.

**[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_order_grid
[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_invoice_grid
[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_shipment_grid
[2018-02-19 06:42:21][WARNING]: Mismatch of entities in the document: sales_creditmemo_grid**

Please help me solve this.

**Comment by knsenthil** [comment]
I am also facing the same issue.. any solution for this problem

**Comment by jammy-git** [comment]
Same problem here too.

**Comment by epiblue** [comment]
I'm also having this issue with 1.9.3.6 to 2.2.6 migration. Help would be appreciated!!

**Comment by mavinBharathi** [comment]
I am getting the same issue with 1.9.0.1 to 2.3.1..Please provide solution...

**Comment by victor-v-rad** [comment]
Hi @mavinBharathi Please compare number of records in sales_order and sales_order_grid tables. Are they equal ? You can do reindex in Magneto 2 and it should add missing records into sales_order_grid

**Comment by sheba17** [comment]
Hi I am of the user who is having the same issue. My magento 2 version is 2.3.3 and Magento 1 version is 1.9.3.1.
I am getting the same issue. Refer link: 
![image](https://user-images.githubusercontent.com/38135560/71984547-14251080-324f-11ea-8d4b-56a0f86fa43c.png)

Please help me out on this.

**Comment by victor-v-rad** [comment]
Hi @sheba17 You can disregard these massages if you do reindex. It will fill grid tables with needed data

**Comment by sheba17** [comment]
But I can see my all sales tables empty so how I can reindex data. Can you please help me why sales data are not migrated?

**Comment by RonakParmar** [comment]
I am also getting same error while migrating sales data from Magento 1.9.1.0 to Magento 2.3.2.
sales_order and sales_order_grid in M2, these two tables are blank. 

Can any one help on this issue? 

Thank you.

**Comment by ruipns** [comment]
Hey,

I had the exact same problem, I spent dome days just with trial and error and I managed to do it.

So I separated the customers from the orders and it worked like this.

**Import Customers:**

Truncate all customers just like @gouravsyscraft did.
In config.xml
`<steps mode="data">
        <step title="Customer Attributes Step">
            <integrity>Migration\Step\Customer\Integrity</integrity>
            <data>Migration\Step\Customer\Data</data>
            <volume>Migration\Step\Customer\Volume</volume>
        </step>
    </steps>
<steps mode="delta">
        <step title="Customer Attributes Step">
            <delta>Migration\Step\Customer\Delta</delta>
            <volume>Migration\Step\Customer\Volume</volume>
        </step>
        <step title="Map Step">
            <delta>Migration\Step\Map\Delta</delta>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="OrderGrids Step">
            <delta>Migration\Step\OrderGrids\Delta</delta>
            <volume>Migration\Step\OrderGrids\Volume</volume>
        </step>
    </steps>`

In map.xml
` `

`            `

Comment this ones.

Run migration:data and all customers should be in database.
If they don't appear in admin panel run 
php -d memory_limit=2G bin/magento indexer:reindex
And all should be good for the customers.

Note: If you can't login with the imported users truncate customer_entity_varchar after the migration.

**Import Orders:**

Here it gave the most problems but as for the customers truncate all orders like above but truncate catalog_product_entity_media_gallery_value_to_entity and catalog_product_entity_media_gallery_value too.

Then in config.xml:
`<steps mode="data">
            <step title="Data Integrity Step">
                <integrity>Migration\Step\DataIntegrity\Integrity</integrity>
            </step>
               <step title="Map Step">
                <integrity>Migration\Step\Map\Integrity</integrity>
                <data>Migration\Step\Map\Data</data>
                <volume>Migration\Step\Map\Volume</volume>
            </step>
               <step title="OrderGrids Step">
                <integrity>Migration\Step\OrderGrids\Integrity</integrity>
                <data>Migration\Step\OrderGrids\Data</data>
                <volume>Migration\Step\OrderGrids\Volume</volume>
            </step>
            <step title="SalesIncrement Step">
                <integrity>Migration\Step\SalesIncrement\Integrity</integrity>
                <data>Migration\Step\SalesIncrement\Data</data>
                <volume>Migration\Step\SalesIncrement\Volume</volume>
            </step>
        </steps>
  <steps mode="delta">
        <step title="Map Step">
            <delta>Migration\Step\Map\Delta</delta>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="SalesIncrement Step">
            <delta>Migration\Step\SalesIncrement\Delta</delta>
            <volume>Migration\Step\SalesIncrement\Volume</volume>
        </step>
        <step title="OrderGrids Step">
            <delta>Migration\Step\OrderGrids\Delta</delta>
            <volume>Migration\Step\OrderGrids\Volume</volume>
        </step>
</steps>`

map.xml:
`            `

`            `

Comment this. You might want to add to ignore some more tables like cms_*, eav, etc it depends of your needs. I had a lot of problems with most tables so the best way is having a pre-migration database and the same one after the migration so you can compare (sometimes it just changes the keys and keep the rows so don't just look at that like I did in the beginning xD), so if you find some data that should not be imported try to find which table it is in and add that table name to ignore in map.
Then run migration:data it will probably give some warnings too or maybe not, either way check if all orders are already imported.
If not run migration:data again. (might need to truncate gallery tables again)

Might not be the best way but worked for me. If you need help I can try to help.
Hope this helps someone :D

**Comment by Eddcapone** [comment]
This is the formatted version of rulpns answer. Credits to him.
---------------

Hey,

I had the exact same problem, I spent dome days just with trial and error and I managed to do it.

So I separated the customers from the orders and it worked like this.

Import Customers:

## Truncate all customers just like @gouravsyscraft did.

## config.xml
```
<steps mode="data">
    <step title="Customer Attributes Step">
        <integrity>Migration\Step\Customer\Integrity</integrity>
        <data>Migration\Step\Customer\Data</data>
        <volume>Migration\Step\Customer\Volume</volume>
    </step>
</steps>
<steps mode="delta">
    <step title="Customer Attributes Step">
        <delta>Migration\Step\Customer\Delta</delta>
        <volume>Migration\Step\Customer\Volume</volume>
    </step>
    <step title="Map Step">
        <delta>Migration\Step\Map\Delta</delta>
        <volume>Migration\Step\Map\Volume</volume>
    </step>
    <step title="OrderGrids Step">
        <delta>Migration\Step\OrderGrids\Delta</delta>
        <volume>Migration\Step\OrderGrids\Volume</volume>
    </step>
</steps>
```

## map.xml

```
<!--<ignore>
    <document>customer_entity</document>
</ignore> 
<ignore>
    <document>customer_entity_datetime</document>
</ignore> 
<ignore> 
    <document>customer_entity_decimal</document>
</ignore>-->

<!--<ignore>
    <document>customer_grid_flat</document>
</ignore>-->
```


Comment this ones.

Run `migration:data` and all customers should be in database.

If they don't appear in admin panel run:

`php -d memory_limit=2G bin/magento indexer:reindex`

And all should be good for the customers.

Note: If you can't login with the imported users truncate customer_entity_varchar after the migration.

## Import Orders:

Here it gave the most problems but as for the customers truncate all orders like above but truncate these two too:

**catalog_product_entity_media_gallery_value_to_entity**
**catalog_product_entity_media_gallery_value**

Then in **config.xml:**

```
<steps mode="data">
    <step title="Data Integrity Step"> 
        <integrity>Migration\Step\DataIntegrity\Integrity</integrity>
    </step>
    <step title="Map Step">
        <integrity>Migration\Step\Map\Integrity</integrity>
        <data>Migration\Step\Map\Data</data>
        <volume>Migration\Step\Map\Volume</volume>
    </step>
    <step title="OrderGrids Step">
        <integrity>Migration\Step\OrderGrids\Integrity</integrity>
        <data>Migration\Step\OrderGrids\Data</data>
        <volume>Migration\Step\OrderGrids\Volume</volume>
    </step>
    <step title="SalesIncrement Step">
        <integrity>Migration\Step\SalesIncrement\Integrity</integrity>
        <data>Migration\Step\SalesIncrement\Data</data>
        <volume>Migration\Step\SalesIncrement\Volume</volume>
    </step>
</steps>
<steps mode="delta">
    <step title="Map Step">
        <delta>Migration\Step\Map\Delta</delta>
        <volume>Migration\Step\Map\Volume</volume>
    </step>
    <step title="SalesIncrement Step">
        <delta>Migration\Step\SalesIncrement\Delta</delta>
        <volume>Migration\Step\SalesIncrement\Volume</volume>
    </step>
    <step title="OrderGrids Step">
        <delta>Migration\Step\OrderGrids\Delta</delta>
        <volume>Migration\Step\OrderGrids\Volume</volume>
    </step>
</steps>
```


**map.xml:**

```
<!--<ignore>
    <document>sales_creditmemo_grid</document>
</ignore>
<ignore>
    <document>sales_invoice_grid</document>
</ignore>
<ignore>
    <document>sales_order_grid</document>
</ignore>
<ignore>
    <document>sales_shipment_grid</document> 
</ignore>-->

<!--
<ignore>
    <document>sales_flat_creditmemo_grid</document></ignore>
<ignore>
    <document>sales_flat_invoice_grid</document></ignore>
<ignore>
    <document>sales_flat_order_grid</document>
</ignore>
<ignore>
    <document>sales_flat_shipment_grid</document>
</ignore>
<ignore>
    <document>customer_entity</document> </ignore>
<ignore>
    <document>customer_entity_datetime</document>
</ignore>
<ignore>
    <document>customer_entity_decimal</document> 
</ignore>-->
```

Comment this. You might want to add to ignore some more tables like cms_*, eav, etc it depends of your needs. 
I had a lot of problems with most tables so the best way is having a pre-migration database and the same one after the migration so you can compare (sometimes it just changes the keys and keep the rows so don't just look at that like I did in the beginning xD), so if you find some data that should not be imported try to find which table it is in and add that table name to ignore in map.

Then run `migration:data` it will probably give some warnings too or maybe not, either way check if all orders are already imported.
If not run migration:data again. (might need to truncate gallery tables again)

Might not be the best way but worked for me. If you need help I can try to help.
Hope this helps someone :D
