### ISSUE TITLE
Completely lacking delta migration of products & categories

### ISSUE THREAD

**Issue by peterjaap** [magento/data-migration-tool#469]
This is a huge problem for us. Development of an M2 shop takes months and we can't ask the client to not update their product catalog in the meantime. We need a delta migration for products & categories, otherwise this whole tool is useless.

**Comment by piotrekkaminski** [comment]
@peterjaap we have delta migration http://devdocs.magento.com/guides/v2.3/migration/migration-migrate-delta.html - did you try it and it did not work for you? cc @victor-v-rad

**Comment by peterjaap** [comment]
New products are added, yes. But changes to existing products and attributes are not.

**Comment by peterjaap** [comment]
Actually, new products aren't added either. These are the m2_cl_ tables that are created in M1, no `catalog_product_` tables in here;

```
m2_cl_catalog_compare_item
m2_cl_cataloginventory_stock_item
m2_cl_customer_address_entity
m2_cl_customer_address_entity_datetime
m2_cl_customer_address_entity_decimal
m2_cl_customer_address_entity_int
m2_cl_customer_address_entity_text
m2_cl_customer_address_entity_varchar
m2_cl_customer_entity
m2_cl_customer_entity_datetime
m2_cl_customer_entity_decimal
m2_cl_customer_entity_int
m2_cl_customer_entity_text
m2_cl_customer_entity_varchar
m2_cl_downloadable_link_purchased
m2_cl_downloadable_link_purchased_item
m2_cl_eav_entity_store
m2_cl_gift_message
m2_cl_log_visitor
m2_cl_newsletter_subscriber
m2_cl_rating_option_vote
m2_cl_rating_option_vote_aggregated
m2_cl_report_compared_product_index
m2_cl_report_event
m2_cl_report_viewed_product_index
m2_cl_review
m2_cl_review_detail
m2_cl_review_entity_summary
m2_cl_review_store
m2_cl_sales_flat_creditmemo
m2_cl_sales_flat_creditmemo_grid
m2_cl_sales_flat_creditmemo_item
m2_cl_sales_flat_invoice
m2_cl_sales_flat_invoice_grid
m2_cl_sales_flat_invoice_item
m2_cl_sales_flat_order
m2_cl_sales_flat_order_address
m2_cl_sales_flat_order_grid
m2_cl_sales_flat_order_item
m2_cl_sales_flat_order_payment
m2_cl_sales_flat_order_status_history
m2_cl_sales_flat_quote
m2_cl_sales_flat_quote_address
m2_cl_sales_flat_quote_address_item
m2_cl_sales_flat_quote_item
m2_cl_sales_flat_quote_item_option
m2_cl_sales_flat_quote_payment
m2_cl_sales_flat_quote_shipping_rate
m2_cl_sales_flat_shipment
m2_cl_sales_flat_shipment_grid
m2_cl_sales_flat_shipment_item
m2_cl_sales_flat_shipment_track
m2_cl_sales_order_tax
m2_cl_sales_order_tax_item
m2_cl_wishlist
m2_cl_wishlist_item
m2_cl_wishlist_item_option
```

**Comment by victor-v-rad** [comment]
Hi @peterjaap @piotrekkaminski 

Partially it is possible for the tool to track tables of products & categories if you add these tables into deltalog.xml.dist file before starting migration. For example tables of products 
```
       'catalog_product_entity',
        'catalog_product_entity_datetime',
        'catalog_product_entity_decimal',
        'catalog_product_entity_gallery',
        'catalog_product_entity_group_price',
        'catalog_product_entity_int',
        ... and so on
```
are part of Map step and because it has support of delta mode (src/Migration/Step/Map/Delta.php) these tables **will** be tracked. But `ConfigurablePrices` step, for example, does not support delta mode and table `catalog_product_super_attribute_pricing` cannot be added to deltalog.xml.dist. If a store does not use configurable products then it is not a problem.

**Comment by victor-v-rad** [comment]
@peterjaap is it possible to develop M2 store before starting migration? Or store data from M1 is required for developing M2 store?

**Comment by frilogg** [comment]
I have the same problem, not possible to have a good development of M2 Store  when there is lack of  migration of products & categories

**Comment by victor-v-rad** [comment]
The feature will be implemented in MAGETWO-88440 story

**Comment by peterjaap** [comment]
@victor-v-rad where can we track progress on that story?

**Comment by victor-v-rad** [comment]
2..3-develop branch

**Comment by victor-v-rad** [comment]
The story was implemented and released with 2.3.3 version

**Comment by PascalBrouwers** [comment]
That commit https://github.com/magento/data-migration-tool/commit/9bcdcd211f1e754b61b4c104cd6f0099b89c7c72 only does the Url Rewrite Step

**Comment by PascalBrouwers** [comment]
I see the tables where added to deltalog.xml.dst here: https://github.com/magento/data-migration-tool/commit/79a8bf8f4f51cfdaa6b8cd419098166ebb36280c
