### ISSUE TITLE
[Migration\Exception] - Integrity Check failed 1.9.0.1 -> CE 2.0.0

### ISSUE THREAD

**Issue by vcpawate** [magento/data-migration-tool#47]
Hello All,
 
I am trying to port existing magento 1.9.0.1 to Magento 2.0. I was able to run ./magento migrate:settings (mode) , but when I executed data mode, there were errors
 
[ERROR]: Source documents are missing or not mapped: amazon_log_api,amazon_log_exception
 
I have added ignore fields to the file map.xml present in <root folder>vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.0.1/map.xml
 
Below is the example I have added,
 
<ignore>
<field>amazon_log_api.log_id</field>
</ignore>
<ignore>
<field>amazon_log_api.host</field>
</ignore>
 
Even though after making all above mentioned modification, I can see error which says it could not map database
I have followed suggestions from this post, but It did not help
https://github.com/magento/data-migration-tool-ce/issues/19
 
Please let me know how to proceed further by adding, particualy, where to add ignore fields,
I have added all fields in each table, it would be nice if there is a option to just mention table and all its column would be automatically ignored.
 
Also, if there are any issues, please let me know, As I am a beginner, please explain me in detail as it would really help me to understand, Appreciate your help, I have tried for a week and was frustrated as I could not find more information,
 
Looking forward for your response,

**Comment by victor-v-rad** [comment]
Hi,

Try to add the xml code 
```
<ignore>
    <document>amazon_log_api</document>
</ignore>
<ignore>
    <document>amazon_log_exception</document>
</ignore>
```
into `<source><document_rules>` scope of your map.xml

**Comment by vcpawate** [comment]
Appreciate your quick response,

I tried adding to <field> and <document> scope but I am getting same error,

I am sure how to debug further,
Any help would be appreciated

Thanks

**Comment by victor-v-rad** [comment]
In your config.xml check `<options><map_file>` tag. It should point to your map.xml file. Instead of map.xml.dist

**Comment by vcpawate** [comment]
I have modified  map_file and it was pointing to map.xml.dist, I made it to poin to map.xml in location 
s/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.0.1/

But Still I am getting this error:
 Source documents are missing or not mapped: 
amazon_log_api,amazon_log_exception,amazon_log_feed,amazon_log_iopn,amazon_log_report,

Please find my map.xml file attached,

[map.txt](https://github.com/magento/data-migration-tool-ce/files/87245/map.txt)

**Comment by andidhouse** [comment]
You can use "*" in the syntax if this helps you - for example to ignore all documents starting with "amazon" just try the following:
<ignore>
    <document>amazon*</document>
</ignore>

**Comment by victor-v-rad** [comment]
The xml
```xml
<ignore>
    <document>amazon_log_api</document>
</ignore>
```
in `<source><document_rules>` scope makes migration tool to ignore the hole table with its member fields.

Use asterisk symbol `*` to ignore a group of tables. Example:
```xml
<ignore>
    <document>amazon_log_*</document>
</ignore>
```
As suggested @andidhouse

**Comment by vcpawate** [comment]
Thanks for your input, All your suggestions worked like a charm, I managed to go further, but I am facing other issue which I tried to search web, and many forums but there was no help,

Please let me know how should I proceed to solve this issue,

Please find the output

bitnami@ip-172-31-30-220:/opt/bitnami/apps/magento/htdocs/bin$ php magento migrate:data -r  /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.0.1/config.xml
Reset the current position of migration to start from the beginning

[2016-01-12 22:12:15][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:15][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:16][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:19][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: 1 sec
[2016-01-12 22:12:21][INFO][mode: data][stage: data migration][step: EAV Step]: started
28% [========>-------------------] Remaining Time: 1 sec


  [ErrorException]
  Undefined offset: 1



migrate:data [-r|--reset] config

**Comment by victor-v-rad** [comment]
Try to run the migration with -vvv option like this:
php bin/magento migrate:data /var/www/magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.0.1/config.xml -vvv
it should show the trace of the error

**Comment by vcpawate** [comment]
[2016-01-13 15:15:16][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:16][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:16][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:20][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: 1 sec
[2016-01-13 15:15:21][INFO][mode: data][stage: data migration][step: EAV Step]: started
28% [========>-------------------] Remaining Time: 1 sec


  [ErrorException]
  Undefined offset: 1



Exception trace:
 () at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:186
 Composer\Util\ErrorHandler::handle() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:186
 Migration\Step\Eav\Data->migrateAttributeSetsAndGroups() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:138
 Migration\Step\Eav\Data->perform() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:73
 Migration\Mode\AbstractMode->runStage() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:116
 Migration\Mode\Data->runData() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:68
 Migration\Mode\Data->run() at /opt/bitnami/apps/magento/htdocs/var/generation/Migration/Mode/Data/Proxy.php:95
 Migration\Mode\Data\Proxy->run() at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /opt/bitnami/apps/magento/htdocs/lib/internal/Magento/Framework/Console/Cli.php:49
 Magento\Framework\Console\Cli->doRun() at /opt/bitnami/apps/magento/htdocs/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /opt/bitnami/apps/magento/htdocs/bin/magento:25


migrate:data [-r|--reset] config


at /opt/bitnami/apps/magento/htdocs/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:186, following code is there


 if ($documentName == 'eav_attribute_group') {
                foreach ($this->initialData->getAttributeGroups('dest') as $record) {
*LINE NUMBER: 186:*                    $oldAttributeSet = $this->initialData->getAttributeSets('dest')[$record['attribute_set_id']];
                    $newAttributeSet = $this->newAttributeSets[
                        $oldAttributeSet['entity_type_id'] . '-' . $oldAttributeSet['attribute_set_name']
                    ];
                    $record['attribute_set_id'] = $newAttributeSet['attribute_set_id'];
                    $record['attribute_group_id'] = null;
                    $destinationRecord = $this->factory->create(
                        [
                            'document' => $destinationDocument,
                            'data' => $record
                        ]
                    );
                    $recordsToSave->addRecord($destinationRecord);
                }
            }

**Comment by vcpawate** [comment]
I would appreciate if you can help me with the issue I am facing,

**Comment by vcpawate** [comment]
Please help

**Comment by davidaholm** [comment]
I have the same issue

**Comment by Vikram0811** [comment]
@vcpawate @davidaholm are you guys able  to resolve the above issue. I am facing the same issue saying 
```
ErrorException]
Undefined offset: 1
```
P.S I do not see any catalog, customers or order data imported in Mage 2

Kindly Help !

**Comment by vcpawate** [comment]
david, Vikram0811, Issue not yet resolved at my end,I spent countless hours trying to solve the issue but could not and I could not get any help. Waiting for one version to get released or someone could help to resolve the isse

**Comment by davidaholm** [comment]
I got it working, it involved removing all the items in my catalog that had attributes and attribute sets.

**Comment by vcpawate** [comment]
thanks for the update, but I have 2000 products which has attributes and
attribute sets.It would be difficult to list them again,
Do you think attributes and attribute sets. have to be removed?

**Comment by davidaholm** [comment]
for me, it was easier to do so, for you you will need to map them individually and create the homes for them in your migration DB, that being said, so worth it.

**Comment by Vikram0811** [comment]
@davidaholm if `it involved removing all the items in my catalog that had attributes and attribute sets` then what did you really imported to Mage 2 ? every prod will be having attributes assigned. Can we remove the attribute and its sets from Mage 1.X and then do the migration ? Will that be helpful ? Even if its successful how do we migrate or map attributes later ?

**Comment by davidaholm** [comment]
VIkram, mapping involves editing the config files
eav-attribute-groups.xml.dist

**Comment by Got-iT-Inc** [comment]
Before I started the migration, but after I setup magento, I made a backup of the database (in my case, magento2). When I got this error message I erased the "magento2" database and then restored the backup I had. This got rid of my error. I'm pretty sure it's from getting partially through a migration and having it fail

**Comment by amitsamtani** [comment]
Has anybody figured out how to debug this offset error? I am getting Undefined offset: 6. I tried debugging to see what it was. Here is the output. What would I be looking for here. @davidaholm mentions that he removed all products with Attribute Sets. Is there a way to change all products to use the Default attribute sets? I don't need any of the information in the custom attribute sets. Here is the stack trace:

devvtec@dev.techandhouse.com [~/public_html]# ./bin/magento migrate:settings vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml -vvv

[2016-08-02 12:52:37][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
[2016-08-02 12:52:37][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
[2016-08-02 12:52:37][INFO][mode: settings][stage: data migration][step: Settings Step]: started
[2016-08-02 12:52:37][INFO][mode: settings][stage: data migration][step: Stores Step]: started
[2016-08-02 12:52:37][INFO][mode: settings][stage: volume check][step: Stores Step]: started
[2016-08-02 12:52:37][INFO][mode: settings][stage: volume check][step: Stores Step]: Migration completeddevvtec@dev.techandhouse.com [~/public_html]# ./bin/magento migratedevvtec@dev.techandhouse.com [~/public_html]# ./bin/magento migrate:data vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml -vvv

[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: EAV Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: Map Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: Log Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: integrity check][step: PostProcessing Step]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: setup triggers][step: Stage]: started
[2016-08-02 12:53:12][INFO][mode: data][stage: data migration][step: EAV Step]: started
57% [================>-----------] Remaining Time: 1 secarray(32) {
  [4]=>
  array(1) {
    ["product-details"]=>
    string(1) "4"
  }
  [27]=>
  array(1) {
    ["product-details"]=>
    string(2) "35"
  }
  [31]=>
  array(1) {
    ["product-details"]=>
    string(2) "55"
  }
  [33]=>
  array(1) {
    ["product-details"]=>
    string(2) "65"
  }
  [34]=>
  array(1) {
    ["product-details"]=>
    string(2) "70"
  }
  [35]=>
  array(1) {
    ["product-details"]=>
    string(2) "75"
  }
  [36]=>
  array(1) {
    ["product-details"]=>
    string(2) "80"
  }
  [37]=>
  array(1) {
    ["product-details"]=>
    string(2) "85"
  }
  [38]=>
  array(1) {
    ["product-details"]=>
    string(2) "90"
  }
  [41]=>
  array(1) {
    ["product-details"]=>
    string(3) "105"
  }
  [44]=>
  array(1) {
    ["product-details"]=>
    string(3) "136"
  }
  [45]=>
  array(1) {
    ["product-details"]=>
    string(3) "141"
  }
  [48]=>
  array(1) {
    ["product-details"]=>
    string(3) "163"
  }
  [58]=>
  array(1) {
    ["product-details"]=>
    string(3) "221"
  }
  [59]=>
  array(1) {
    ["product-details"]=>
    string(3) "257"
  }
  [61]=>
  array(1) {
    ["product-details"]=>
    string(3) "272"
  }
  [68]=>
  array(1) {
    ["product-details"]=>
    string(3) "364"
  }
  [81]=>
  array(1) {
    ["product-details"]=>
    string(3) "531"
  }
  [82]=>
  array(1) {
    ["product-details"]=>
    string(3) "540"
  }
  [83]=>
  array(1) {
    ["product-details"]=>
    string(3) "613"
  }
  [84]=>
  array(1) {
    ["product-details"]=>
    string(3) "624"
  }
  [85]=>
  array(1) {
    ["product-details"]=>
    string(3) "635"
  }
  [86]=>
  array(1) {
    ["product-details"]=>
    string(3) "655"
  }
  [87]=>
  array(1) {
    ["product-details"]=>
    string(3) "666"
  }
  [88]=>
  array(1) {
    ["product-details"]=>
    string(3) "677"
  }
  [89]=>
  array(1) {
    ["product-details"]=>
    string(3) "687"
  }
  [90]=>
  array(1) {
    ["product-details"]=>
    string(3) "697"
  }
  [91]=>
  array(1) {
    ["product-details"]=>
    string(3) "707"
  }
  [93]=>
  array(1) {
    ["product-details"]=>
    string(3) "728"
  }
  [94]=>
  array(1) {
    ["product-details"]=>
    string(3) "739"
  }
  [95]=>
  array(1) {
    ["product-details"]=>
    string(3) "749"
  }
  [99]=>
  array(1) {
    ["product-details"]=>
    string(3) "759"
  }
}

attribute id: 126
attribute id['attribute code']: price
get value: 6



                                                                                                                                           
  [Exception]                                                                                                                              
  Notice: Undefined offset: 6 in /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 442  
                                                                                                                                           


Exception trace:
 () at /home/devvtec/public_html/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:442
 Migration\Step\Eav\Data->moveAttributeToGroup() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:400
 Migration\Step\Eav\Data->moveAttributes() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:386
 Migration\Step\Eav\Data->migrateEntityAttributes() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:163
 Migration\Step\Eav\Data->perform() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:73
 Migration\Mode\AbstractMode->runStage() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:116
 Migration\Mode\Data->runData() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:68
 Migration\Mode\Data->run() at /home/devvtec/public_html/var/generation/Migration/Mode/Data/Proxy.php:95
 Migration\Mode\Data\Proxy->run() at /home/devvtec/public_html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /home/devvtec/public_html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /home/devvtec/public_html/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/devvtec/public_html/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/devvtec/public_html/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /home/devvtec/public_html/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/devvtec/public_html/bin/magento:23


migrate:data [-r|--reset] config


devvtec@dev.techandhouse.com [~/public_html]#

**Comment by amitsamtani** [comment]
I have been able to complete the Migration. Since I don't really care about the other attribute sets (used them when Magento first came out, but don't really use them any more, I don't mind all my items being part of the default attribute set). 

I changed the following code as follows. Sorry about the bad pasting job of code:

`if(!isset($attributeSetGroups[$record->getValue('attribute_set_id')])):
					$asg = 4; //4 = Default Attribute set in my case
				else:
					$asg = $attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode];
				endif;`
				
				`$record->setValue(
                    'attribute_group_id',
                    $asg //$attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode]
                );`

Not sure if this is recommended but works for now. Going to keep an eye on this issue to see if there is a better way to do this.

**Comment by victor-v-rad** [comment]
EAV step has been modified significantly. Please follow up the the upcoming release

**Comment by amitsamtani** [comment]
Hi Victor, do you know if the upcoming release is coming soon or its still going to take time?

**Comment by victor-v-rad** [comment]
The release of the tool goes shortly after release of Magento 2

**Comment by victor-v-rad** [comment]
I am closing the issue. Please recheck it in the latest version of the tool and reopen if it is still actual
