### ISSUE TITLE
Customer Grid table doesnt update when creating test orders on delta installation

### ISSUE THREAD

**Issue by royandre** [magento/data-migration-tool#472]
When running delta migration, and creating test orders on the delta installation, the admin table 
 customer_grid_flat is not updated.

Test orders created on the delta installation gets automatically wiped during running a new delta migration, which is fine. However, when new orders then are created on the delta install, the first ones gets the customers form the previous test orders attached to them.

Not sure it is "by the rule" to create test orders on delta installs, but that certainly is an important step to verify everything works as expected.

**Comment by victor-v-rad** [comment]
as far I know `customer_grid_flat` table in Magento 2 will be filled when you run Customer Grid indexer
