### ISSUE TITLE
Tool Stalls for me

### ISSUE THREAD

**Issue by niners52** [magento/data-migration-tool#473]
I am trying to migrate a database from 1.9.3.1 ce to 2.2.2 ee using the data migration tool. I have done a migration before on a different site and had to deal with errors but I am not getting any errors. When it gets to this step-

[INFO][mode: data][stage: data migration][step: Map Step]: started 13%

it stalls. It happened yesterday so I restored the database and started over and it happened at exactly 13% again. I let it run for 12 hours to make sure it had enough time. Our store has about 5k customers, 25k items, and 15k orders so I don't think it is too big. Any ideas? Which log can I check? How can I get more information?

**Comment by victor-v-rad** [comment]
Hi @niners52 

You can run migration with `-vvv` option to debug the process of migration. It will show migration per tables. So you will know on which table it is stalled

**Comment by niners52** [comment]
Hello,
I ran it with that command and it stalled on catalog_product_entity_varchar table. I am now running it localhost to localhost and that table passed through just fine. My concern going forward through development is how will I run the delta if I do it localhost to localhost

**Comment by bhagdave** [comment]
I think this is related to https://github.com/magento/data-migration-tool/issues/251 and https://github.com/magento/data-migration-tool/issues/405.  Mine eventually crashes with an error.  I have yet to get the tool to run against a remote database on an AWS RDS instance,
