### ISSUE TITLE
Skip product data migration 

### ISSUE THREAD

**Issue by molsm** [magento/data-migration-tool#479]
**Question**

How we can skip product data migration?

Any reference would be helpfull

Thanks.

**Comment by victor-v-rad** [comment]
Hi @molsm 
You can delete it in Magento 2 admin panel after migration. Or use Magento 2 API for automatically deleting

**Comment by molsm** [comment]
@victor-v-rad Thanks.

So there is no clean way how we can manage skip product data migration during "data migration tool" run? Of course we can ignore several tables through xml, but this could lead to issues with data integrity (problems would appear after migration on running magento store)!?

So you suggest keep current behaviour and just delete products after migration?

Best regards,

**Comment by victor-v-rad** [comment]
yes

**Comment by goutamfulcrum** [comment]
Someone got solution for skipping product/category import?
