### ISSUE TITLE
Configurable Products without simples M1 CE 1.9.3.1  to M2 CE 2.2.3

### ISSUE THREAD

**Issue by kemexyz** [magento/data-migration-tool#480]
**Preconditions**
PHP 7.0.25
MYSQL 5.7.21-0ubuntu0.16.04.1
Magento1 1.9.3.1
Magento2 2.2.3 

Magento 1 with configurable product with simples, 3 filled super attribute tables

**Steps to reproduce**
Migrate from 1.9.3.1 to 2.2.3
Start data migration:
bin/magento migrate:data vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.1/config.xml

**Expected result**
Configurable products have simples and are shown on frontend with selectable options

**Actual Results**
Configurable products do not have any simples in backend, 3 super attribute tables are empty. No options on frontend.

I already reinstalled Magento 2.2.3 and migrated data again, nothing changed – same behavior.

**Comment by victor-v-rad** [comment]
Hi @kemexyz 

The only table that is ignored for transferring data in map.xml file is `catalog_product_super_attribute_pricing`

**Comment by kemexyz** [comment]
Hello,

I'm very sorry. My m1 DB was not empty or anything but it had some errors.
A new import of the M1 DB and updating data migration to 2.2.3 solved the issue.

I'm unable to say  what the real issue with the M1 DB was, but there were no errors shown during migration.
