### ISSUE TITLE
"php_network_getaddresses: getaddrinfo failed" in data migration

### ISSUE THREAD

**Issue by rveronese** [magento/data-migration-tool#484]
Dear all,

I'm currently using the Data Migration Tool to migrate from Magento CE 1.7.0.2 to 2.2.3. I have successfully run the settings migration, but i get the following error trying to execute the data migration right after

>   [Zend_Db_Adapter_Exception]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

>  [PDOException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

> [PDOException]
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known 

It seems like it can't resolve the DB address but i can't understand why since the settings migration is executed successfully.

Any help is appreciated, thanks in advance

**Comment by victor-v-rad** [comment]
Hi @rveronese 

use -vvv option to see backtrance. It might shed some light on the root cause

**Comment by rveronese** [comment]
Hi @victor-v-rad 

First of all, many thanks for your reply.
It seems like the problem is in establishing the connection to the DB. My MySQL instances are running on AWS RDS.

Here is the exception backtrace

` [Zend_Db_Adapter_Exception]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known


Exception trace:
 () at /var/app/current/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:144
 Zend_Db_Adapter_Pdo_Abstract->_connect() at /var/app/current/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php:111
 Zend_Db_Adapter_Pdo_Mysql->_connect() at /var/app/current/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:398
 Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() at /var/app/current/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:460
 Zend_Db_Adapter_Abstract->query() at /var/app/current/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
 Zend_Db_Adapter_Pdo_Abstract->query() at /var/app/current/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:517
 Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /var/app/current/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:580
 Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /var/app/current/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:737
 Zend_Db_Adapter_Abstract->fetchAll() at /var/app/current/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php:21
 Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll() at /var/app/current/vendor/magento/framework/Data/Collection/AbstractDb.php:774
 Magento\Framework\Data\Collection\AbstractDb->_fetchAll() at /var/app/current/vendor/magento/framework/Data/Collection/AbstractDb.php:670
 Magento\Framework\Data\Collection\AbstractDb->getData() at /var/app/current/vendor/magento/framework/Data/Collection/AbstractDb.php:574
 Magento\Framework\Data\Collection\AbstractDb->loadWithFilter() at /var/app/current/vendor/magento/framework/Data/Collection/AbstractDb.php:559
 Magento\Framework\Data\Collection\AbstractDb->load() at /var/app/current/vendor/magento/framework/Data/Collection.php:831
 Magento\Framework\Data\Collection->getIterator() at /var/app/current/vendor/magento/module-config/App/Config/Source/RuntimeConfigSource.php:82
 Magento\Config\App\Config\Source\RuntimeConfigSource->loadConfig() at /var/app/current/vendor/magento/module-config/App/Config/Source/RuntimeConfigSource.php:62
 Magento\Config\App\Config\Source\RuntimeConfigSource->get() at /var/app/current/vendor/magento/framework/App/Config/ConfigSourceAggregated.php:40
 Magento\Framework\App\Config\ConfigSourceAggregated->get() at /var/app/current/vendor/magento/module-config/App/Config/Type/System/Reader.php:60
 Magento\Config\App\Config\Type\System\Reader->read() at /var/app/current/generated/code/Magento/Config/App/Config/Type/System/Reader/Proxy.php:95
 Magento\Config\App\Config\Type\System\Reader\Proxy->read() at /var/app/current/vendor/magento/module-config/App/Config/Type/System.php:292
 Magento\Config\App\Config\Type\System->readData() at /var/app/current/vendor/magento/module-config/App/Config/Type/System.php:191
 Magento\Config\App\Config\Type\System->loadDefaultScopeData() at /var/app/current/vendor/magento/module-config/App/Config/Type/System.php:152
 Magento\Config\App\Config\Type\System->get() at /var/app/current/vendor/magento/framework/App/Config.php:131
 Magento\Framework\App\Config->get() at /var/app/current/vendor/magento/framework/App/Config.php:80
 Magento\Framework\App\Config->getValue() at /var/app/current/vendor/magento/framework/Filter/Translit.php:409
 Magento\Framework\Filter\Translit->__construct() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/app/current/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/app/current/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/app/current/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:144
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:230
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/app/current/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/app/current/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/App/Step/StageFactory.php:43
 Migration\App\Step\StageFactory->create() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/App/Mode/StepList.php:55
 Migration\App\Mode\StepList->Migration\App\Mode\{closure}() at n/a:n/a
 array_walk_recursive() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/App/Mode/StepList.php:57
 Migration\App\Mode\StepList->createInstances() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/App/Mode/StepList.php:67
 Migration\App\Mode\StepList->getSteps() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:88
 Migration\Mode\Data->runIntegrity() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:62
 Migration\Mode\Data->run() at /var/app/current/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /var/app/current/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at /var/app/current/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /var/app/current/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /var/app/current/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /var/app/current/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/app/current/bin/magento:23`

I'm a bit confused about why it can't connect to DB, also considering the fact that the settings migration run properly. Both DB instances accept inbound traffic on port 3306.

**Comment by victor-v-rad** [comment]
you can share your config.xml (remove sensitive data)

**Comment by rveronese** [comment]
here it is
[config.txt](https://github.com/magento/data-migration-tool/files/1841606/config.txt)

Thank you again for your interest.

**Comment by victor-v-rad** [comment]
the file seems ok
