### ISSUE TITLE
Migrating from 1.9.2.3 to 2.2.3 - migrate issue when source and destination are on different servers

### ISSUE THREAD

**Issue by cliveyg** [magento/data-migration-tool#486]
Hi,

I'm getting errors when trying to run the data migration tool. The source and destination servers are on different IP addresses. I changed config.xml to resemble below: 
```
    <source>
        <database host="xx.xx.xx.xx" name="magento1_db" user="mag1user" pass="xxxxxx"/>
    </source>
    <destination>
        <database host="localhost" name="magento2_db" user="mag2user" pass="xxxxxx"/>
    </destination>
```
When I run the command `magento migrate:settings -r /path/to/config.xml`

I get the following error: 

  ```
[Zend_Db_Adapter_Exception]                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'mag1user'@'yyy.yy.yyy.yy' (using password: NO)

```
Where yyy.yy.yyy.yy is the IP address of the destination server (which isn't even specified in config.xml). I've granted remote privileges to both users on both servers and  I've checked using the mysql command line that the servers can see each other.

Why is the error message referring to user 1 on ip address 2??
Is this a bug or have I missed a step?

Regards,
Clive

**Comment by victor-v-rad** [comment]
Correct xml attribute name is `password` not `pass`
```
    <source>
        <database host="localhost" name="magento1" user="root" password="yourpassword"/>
    </source>
    <destination>
        <database host="localhost" name="magento2" user="root" password="yourpassword"/>
    </destination>
```

**Comment by cliveyg** [comment]
Hi Victor,

Thanks for spotting that. However I'm still getting the error. Only password is now yes instead of no. 

```
  [Zend_Db_Adapter_Exception]                                                                          
  SQLSTATE[HY000] [1045] Access denied for user 'user1'@'yyy.yy.yyy.yyy' (using password: YES) 
```

Where yyy.yy.yyy.yyy is the destination server. I just don't understand why the script tries user1@destination_server. Like I said I can see and logon to destination server from the source server using `mysql -u user1 -h 'yyy.yy.yyy.yyy -p` and I can logon to the destination server from the source server using `mysql -u user2 -h xx.xx.xx.xx -p`.

**Comment by jammy-git** [comment]
I'm also getting exactly the same issue when migrating from 1.7.0.2 to 2.2.4.

I can log in to the source server MySQL service from the destination server, so I'm sure it's not a connection/authentication issue.

Anybody found a solution yet?

**Comment by wolfautoparts** [comment]
I have this same issue on m2.3.1. Can connect to remote host with CLI but tool is broken. Any solution yet?
