### ISSUE TITLE
Suggestion: Product Quantity and Stock information should be updated

### ISSUE THREAD

**Issue by frilogg** [magento/data-migration-tool#489]
I now understand that new products and categories are not migrated when doing the delta migrate function of the tool. As I would love this to be possible and see that other have suggested this, I would love at least to have  Product Quantity and Stock information updated, or is this reflected since the orders are migrated?

**Comment by victor-v-rad** [comment]
> Product Quantity and Stock information updated
Try to add cataloginventory_stock_item table into deltalog.xml file. After migration of `data` m2_cl_cataloginventory_stock_item table and trg_cataloginventory_stock_item_* triggers should be created to track stock information

**Comment by frilogg** [comment]
And deltalog.xml is locatet where?

**Comment by frilogg** [comment]
Hi the only file I find is deltalog.xml.dist.  Anyway... cataloginventory_stock_item goes this under the delta_map group name? and what key should I give it? ..

**Comment by victor-v-rad** [comment]
Sorry, you are right cataloginventory_stock_item already in deltalog.xml file. So it should work without any changes
