### ISSUE TITLE
a:4:{i:0;s:129:"Notice: Undefined offset: 52 - Magento Data Migration Issue 1.9.2 To 2.1.2

### ISSUE THREAD

**Issue by wajahatbashir** [magento/data-migration-tool#492]
Hi Guys, I migrated data from magento 1.9.2 to magento 2.1.2 and successfully Category step. Everything looks good and all data imported but when i go to Products->categories in admin i am facing this error.

products and categories are not showing on frontend.

![screenshot_4](https://user-images.githubusercontent.com/11786908/38293282-f9478980-37f7-11e8-8475-8740cf54e923.jpg)

In admin panel, category page (Product-> categories) throwing exception error. Error is
a:4:{i:0;s:139:"Notice: Undefined offset: 564 in [Magento_PATH]\vendor\magento\module-eav\Model\ResourceModel\ReadHandler.php on line 166";i:1;s:6536:"#0

**Comment by victor-v-rad** [comment]
Hi @wajahatbashir 

Please consider migration to the latest Magento 2.2.3 with Data Migration Tool 2.2.3. The tool got many bugfixes since 2.1.2

**Comment by wajahatbashir** [comment]
Hi @victor-v-rad 

If i'll use latest version of Magento 2.2.3, then my custom Magento theme 'll not conflict with latest version ?

**Comment by victor-v-rad** [comment]
you can try and see

**Comment by victor-v-rad** [comment]
You mean the same error on Admin > Products->categories page? Can you show the whole backtrace error?
