### ISSUE TITLE
Address information not showing proper please help

### ISSUE THREAD

**Issue by KalpeshKikani** [magento/data-migration-tool#496]
Hello
please help i have migrated site in 1.9 to 2.2.2 but address information not showing the backend & frontend so only the address template.
like this

{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}{{depend firstname}}
{{/depend}}
{{depend company}}{{var company}}
{{/depend}}
{{if street1}}{{var street1}}
{{/if}}
{{depend street2}}{{var street2}}
{{/depend}}
{{depend street3}}{{var street3}}
{{/depend}}
{{depend street4}}{{var street4}}
{{/depend}}
{{if city}}{{var city}}, {{/if}}{{if region}}{{var region}}, {{/if}}{{if postcode}}{{var postcode}}{{/if}}

{{var country}}

{{depend telephone}}T: {{var telephone}}{{/depend}}
{{depend fax}}
F: {{var fax}}{{/depend}}
{{depend vat_id}}
VAT: {{var vat_id}}{{/depend}}

If any solution so please

**Comment by victor-v-rad** [comment]
Hi @KalpeshKikani 

Duplicate #476 
Try this [solution ](https://github.com/magento/magento2/issues/5873)

**Comment by KalpeshKikani** [comment]
I have upgrade Magento version and customer address information issue solve.
