### ISSUE TITLE
Migrate only categories

### ISSUE THREAD

**Issue by salahy** [magento/data-migration-tool#497]
Hello, I am trying to migrate categories from 1.9 to 2.2, I followed the guide but still I cant set the mapping right, I find it difficult in the guide, I didn't do any database modifications in the tables (prefix,changing names of the tables) but also I don't want any other data, only categories

how I can do it ?

**Comment by victor-v-rad** [comment]
By default the tool migrates everything. To migrate some entities separately you need to remove unnecessary Steps from you config.xml and add `<ignore>` tag to all tables in map.xml file except that are relate to categories.
