### ISSUE TITLE
404 error for admin link

### ISSUE THREAD

**Issue by BabliDey** [magento/data-migration-tool#501]
I have migrated data from magento 1.9.2.3 community version to magento 2,1,8 community version. After migration the admin link showing 404 page not found error. Need to solve this.

**Comment by joridos** [comment]
Same problem here, but with enterprise to commerce.

**Comment by BabliDey** [comment]
I fixed this problem. Actually in database core_config_data table the value of default scope was wrong. After changing it with proper url it is working. But I can not see any sales data are migrated from magento 1 to magento 2.

**Comment by joridos** [comment]
Thanks @BabliDey , witch is the config that you have changed? what is the core_config_data path to that config?

**Comment by joridos** [comment]
I found the config, thanks.

**Comment by BabliDey** [comment]
Hello @joridos I changed base_url link in core_config_data table.

**Comment by victor-v-rad** [comment]
Hi
The issue was fixed in some of 2.2 releases. What is the reason using Magento 2.1 if there is new 2.2 which include more bugfixes?
