### ISSUE TITLE
Sales data are not migrated. 

### ISSUE THREAD

**Issue by BabliDey** [magento/data-migration-tool#502]
I have installed this to migrate data from magento 1.9.2.3 to magento 2.1.8. And after installing I run the migration command. The command shows migration complete.

![mg2](https://user-images.githubusercontent.com/24405051/39353632-2b3b9d9a-4a00-11e8-94b9-c5f06c0d0f7c.png)

 But after that I checked the sales data are not migrated at all.

**Comment by victor-v-rad** [comment]
Try `php bin/magento cache:flush && php bin/magento indexer:reindex`
Try the latest Data Migration Tool 2.2.4 with Magento 2.2.4
