### ISSUE TITLE
xml file is invalid - ce 1.9.0.1 to ce 2.2.2

### ISSUE THREAD

**Issue by potschntom** [magento/data-migration-tool#503]
I try to make delta migration.
I made a copy of the live database from the live server and put it on the dev server the same way I did on first full migration.
Then I change config.xml to the new databases an and run script with ./magento migrate:delta config.xml -vvv

I get this error: 
  [Migration\Exception]  
  XML file is invalid.   
                         

Exception trace:
 () at /shop/vendor/magento/data-migration-tool/src/Migration/Reader/Map.php:92
 Migration\Reader\Map->init() at /shop/vendor/magento/data-migration-tool/src/Migration/Reader/Map.php:68
 Migration\Reader\Map->__construct() at /shop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /shop/vendor/magento/framework/ObjectManager/Factory/Compiled.php:108
 Magento\Framework\ObjectManager\Factory\Compiled->create() at /shop/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /shop/vendor/magento/data-migration-tool/src/Migration/Reader/MapFactory.php:58
 Migration\Reader\MapFactory->create() at /shop/vendor/magento/data-migration-tool/src/Migration/Step/Map/Data.php:116
 Migration\Step\Map\Data->__construct() at /shop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /shop/vendor/magento/framework/ObjectManager/Factory/Compiled.php:108
 Magento\Framework\ObjectManager\Factory\Compiled->create() at /shop/vendor/magento/framework/ObjectManager/Factory/Compiled.php:150
 Magento\Framework\ObjectManager\Factory\Compiled->get() at /shop/vendor/magento/framework/ObjectManager/Factory/Compiled.php:79
 Magento\Framework\ObjectManager\Factory\Compiled->create() at /shop/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /shop/vendor/magento/data-migration-tool/src/Migration/App/Step/StageFactory.php:43
 Migration\App\Step\StageFactory->create() at /shop/vendor/magento/data-migration-tool/src/Migration/App/Mode/StepList.php:55
 Migration\App\Mode\StepList->Migration\App\Mode\{closure}() at n/a:n/a
 array_walk_recursive() at /shop/vendor/magento/data-migration-tool/src/Migration/App/Mode/StepList.php:57
 Migration\App\Mode\StepList->createInstances() at /shop/vendor/magento/data-migration-tool/src/Migration/App/Mode/StepList.php:67
 Migration\App\Mode\StepList->getSteps() at /shop/vendor/magento/data-migration-tool/src/Migration/Mode/Delta.php:86
 Migration\Mode\Delta->run() at /shop/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDeltaCommand.php:51
 Migration\Console\MigrateDeltaCommand->execute() at /shop/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at /shop/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /shop/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /shop/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /shop/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /shop/bin/magento:23

https://github.com/magento/data-migration-tool/issues/320 didn´t help me.

Thanks

**Comment by victor-v-rad** [comment]
Hi @potschntom 

You can show the content of your config.xml file (without passwords and hosts) I will try to validate it

**Comment by potschntom** [comment]
Hi @victor-v-rad 

My config.xml:

<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../config.xsd">
    <steps mode="settings">
        <step title="Settings Step">
            <integrity>Migration\Step\Settings\Integrity</integrity>
            <data>Migration\Step\Settings\Data</data>
        </step>
        <step title="Stores Step">
            <integrity>Migration\Step\Stores\Integrity</integrity>
            <data>Migration\Step\Stores\Data</data>
            <volume>Migration\Step\Stores\Volume</volume>
        </step>
    </steps>
    <steps mode="data">
        <step title="Data Integrity Step">
            <integrity>Migration\Step\DataIntegrity\Integrity</integrity>
        </step>
        <step title="EAV Step">
            <integrity>Migration\Step\Eav\Integrity</integrity>
            <data>Migration\Step\Eav\Data</data>
            <volume>Migration\Step\Eav\Volume</volume>
        </step>
        <step title="Customer Attributes Step">
            <integrity>Migration\Step\Customer\Integrity</integrity>
            <data>Migration\Step\Customer\Data</data>
            <volume>Migration\Step\Customer\Volume</volume>
        </step>
        <step title="Map Step">
            <integrity>Migration\Step\Map\Integrity</integrity>
            <data>Migration\Step\Map\Data</data>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Url Rewrite Step">
            <integrity>Migration\Step\UrlRewrite\Version191to2000</integrity>
            <data>Migration\Step\UrlRewrite\Version191to2000</data>
            <volume>Migration\Step\UrlRewrite\Version191to2000</volume>
        </step>
        <step title="Log Step">
            <integrity>Migration\Step\Log\Integrity</integrity>
            <data>Migration\Step\Log\Data</data>
            <volume>Migration\Step\Log\Volume</volume>
        </step>
        <step title="Ratings Step">
            <integrity>Migration\Step\Ratings\Integrity</integrity>
            <data>Migration\Step\Ratings\Data</data>
            <volume>Migration\Step\Ratings\Volume</volume>
        </step>
        <step title="ConfigurablePrices step">
            <integrity>Migration\Step\ConfigurablePrices\Integrity</integrity>
            <data>Migration\Step\ConfigurablePrices\Data</data>
            <volume>Migration\Step\ConfigurablePrices\Volume</volume>
        </step>
        <step title="OrderGrids Step">
            <integrity>Migration\Step\OrderGrids\Integrity</integrity>
            <data>Migration\Step\OrderGrids\Data</data>
            <volume>Migration\Step\OrderGrids\Volume</volume>
        </step>
        <step title="Tier Price Step">
            <integrity>Migration\Step\TierPrice\Integrity</integrity>
            <data>Migration\Step\TierPrice\Data</data>
            <volume>Migration\Step\TierPrice\Volume</volume>
        </step>
        <step title="SalesIncrement Step">
            <integrity>Migration\Step\SalesIncrement\Integrity</integrity>
            <data>Migration\Step\SalesIncrement\Data</data>
            <volume>Migration\Step\SalesIncrement\Volume</volume>
        </step>
        <step title="PostProcessing Step">
            <data>Migration\Step\PostProcessing\Data</data>
        </step>
    </steps>
    <steps mode="delta">
        <step title="Customer Attributes Step">
            <delta>Migration\Step\Customer\Delta</delta>
            <volume>Migration\Step\Customer\Volume</volume>
        </step>
        <step title="Map Step">
            <delta>Migration\Step\Map\Delta</delta>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Log Step">
            <delta>Migration\Step\Log\Delta</delta>
            <volume>Migration\Step\Log\Volume</volume>
        </step>
        <step title="OrderGrids Step">
            <delta>Migration\Step\OrderGrids\Delta</delta>
            <volume>Migration\Step\OrderGrids\Volume</volume>
        </step>
        <step title="SalesIncrement Step">
            <delta>Migration\Step\SalesIncrement\Delta</delta>
            <volume>Migration\Step\SalesIncrement\Volume</volume>
        </step>
    </steps>
    <source>
        <database host="localhost" name="" user="myproabr" password="" />
    </source>
    <destination>
        <database host="localhost" name="" user="" password="" />
    </destination>
    <options>
        <map_file>etc/opensource-to-opensource/1.9.0.1/map.xml.dist</map_file>
        <eav_map_file>etc/opensource-to-opensource/map-eav.xml.dist</eav_map_file>
        <eav_document_groups_file>etc/opensource-to-opensource/eav-document-groups.xml.dist</eav_document_groups_file>
        <eav_attribute_groups_file>etc/opensource-to-opensource/eav-attribute-groups.xml.dist</eav_attribute_groups_file>
        <log_map_file>etc/opensource-to-opensource/map-log.xml.dist</log_map_file>
        <log_document_groups_file>etc/opensource-to-opensource/log-document-groups.xml.dist</log_document_groups_file>
        <settings_map_file>etc/opensource-to-opensource/settings.xml.dist</settings_map_file>
        <customer_map_file>etc/opensource-to-opensource/map-customer.xml.dist</customer_map_file>
        <customer_document_groups_file>etc/opensource-to-opensource/customer-document-groups.xml.dist</customer_document_groups_file>
        <customer_attribute_groups_file>etc/opensource-to-opensource/customer-attribute-groups.xml.dist</customer_attribute_groups_file>
        <delta_document_groups_file>etc/opensource-to-opensource/deltalog.xml.dist</delta_document_groups_file>
        <order_grids_document_groups_file>etc/opensource-to-opensource/order-grids-document-groups.xml.dist</order_grids_document_groups_file>
        <map_document_groups>etc/opensource-to-opensource/map-document-groups.xml.dist</map_document_groups>
        <class_map>etc/opensource-to-opensource/class-map.xml.dist</class_map>
        <tier_price_map_file>etc/opensource-to-opensource/map-tier-price.xml.dist</tier_price_map_file>
        <stores_map_file>etc/opensource-to-opensource/map-stores.xml.dist</stores_map_file>
        
        <bulk_size>0</bulk_size>
        
        <direct_document_copy>0</direct_document_copy>
        <source_prefix>magento1</source_prefix>
        <dest_prefix />
        <auto_resolve_urlrewrite_duplicates>0</auto_resolve_urlrewrite_duplicates>
        <log_file>migration.log</log_file>
        <progress_bar_format>%percent%% [%bar%] Remaining Time: %remaining%</progress_bar_format>
        <upgrade_customer_password_hash>1</upgrade_customer_password_hash>
        <edition_migrate>opensource-to-opensource</edition_migrate>
        <edition_number>1.9.0.1</edition_number>
        <init_statements_source>SET NAMES utf8;</init_statements_source>
        <init_statements_destination>SET NAMES utf8;</init_statements_destination>
        <crypt_key></crypt_key>
    </options>
</config>

**Comment by victor-v-rad** [comment]
Also make sure your map.xml file is valid. Since the exception is from Migration/Reader/Map.php

**Comment by potschntom** [comment]
Hi @victor-v-rad 

That was the problem made copy paste and mixed </ignore> with <ignore>

Thanks
