### ISSUE TITLE
Maintaining xml files

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#505]
Hi,

When a new release of the tool comes out, I have to compare my .xml files to the .xml.dist in the new release and make any amends.

Would it not be possible for the tool to load the .dist files as well as say map-extra.xml etc.?

That way I can keep my own changes in separate files. Anything with the filename -extra would be loaded in addition?

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 

It is a good idea to extend xml files of the tool by other xml files. It could be done in a "module" approach. These modules would extend the tool functionality. So module which extend "data-migration-tool" module could have suffix in its name. So the name would be "data-migration-tool-someextension"
Internal ticket MAGETWO-91098 to implement it.
