### ISSUE TITLE
[PDOException]   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME' [Magento 2.2.3]

### ISSUE THREAD

**Issue by kamalakannanR1** [magento/data-migration-tool#507]
Hi,
I am using this data-migration-tool, getting below error,
` php bin/magento migrate:data -r vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.0.0/config.xml -vvv`
[PDOException]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

Note: Magento 1.9.00 To 2.2.3 (migration tool 2.2.3) # @victor-v-rad

**Comment by victor-v-rad** [comment]
Reinstall your Magento 2 instance from scratch

**Comment by kamalakannanR1** [comment]
Lot of Time Im Newly install But Still shown Error:
`[PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'` 

Im check my Eav_Attribute_Set table Only have 'Default' attribute names  (8 Default )

**Comment by victor-v-rad** [comment]
recheck your config.xml maybe <database> points to different Magento 2 DB

**Comment by jorgeramirezf1** [comment]
2 posible options to fix this:

- Restore your backup of your magento 2 fresh install (You need to make a db backup before migration) 
- Check the map-eav.xml.dist to verify the prefix of your magento1 attribute_sets 
                <field>eav_attribute_group.attribute_group_name</field>
                <handler class="\Migration\Handler\AddPrefix">
                    <param name="prefix" value="Migration_"/>
                </handler>
            </transform>

I hope it helps :)

**Comment by ramsampathi** [comment]
Hi @victor-v-rad,
Magento1 - 1.9.2.4
Magento2 - 2.2.6
i got the same issue like

[Exception]
Notice: Undefined offset: 1 in /home/devserve/public_html/thordsenv2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291

and

[PDOException]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

I tried with many times with new setup but it throws an same errors
please help on this.
Thanks,

**Comment by ramsampathi** [comment]
Hi @jorgeramirezf1 ,
checked your solution but i got an error like 
 [Exception]
  Notice: Undefined offset: 9 in /home/devserve/public_html/thordsenv2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291

is there any other solution..its very urgent for me please
