### ISSUE TITLE
Migrating several 1.9.x into 2.2?

### ISSUE THREAD

**Issue by danielc1234** [magento/data-migration-tool#510]
Hi, I am wondering if the data migration tool has the capability to migrate several different installs of magento 1.9 into a single install of magento 2.2? 
We are wanting to try and bring several sites under one controlling install.
Thanks

**Comment by victor-v-rad** [comment]
Hi @danielc1234 

The tool migrates from one DB of M1 into one DB of M2.  It is possible to use several different websites on one instance of M1 in one DB. In this case the tool will migrate it without problems.

**Comment by danielc1234** [comment]
Thanks @victor-v-rad  However, my question was for several M1 Databases into one M2 database. Would there be a way to accomplish this?

**Comment by victor-v-rad** [comment]
The tool migrates customers, products, categories with preserving primary keys of tables. So if you will migrate second DB over already migrated store it will overwrite with new data. However the tool is open source and you can rewrite it for your needs. Reading [Tool Technical Specification](https://devdocs.magento.com/guides/v2.3/migration/migration-tool-internal-spec.html) doc can be a good starting point
