### ISSUE TITLE
How to convert serialized data to json which also has a new name?

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#512]
In settings.xml I have this - as in M1 it is pdfinvoiceplus/variables/customer as serialized data, but in M2 it is pdfinvoiceplus/variable/customer_variables.

The data gets renamed to pdfinvoiceplus/variable/customer_variables but it is not converted to json data, what am I doing wrong?

```
<rename>
            <path>pdfinvoiceplus/variables/customer</path>
            <to>pdfinvoiceplus/variable/customer_variables</to>
        </rename>
```
and

```
<transform>
            <path>pdfinvoiceplus/variable/customer_variables</path>
            <handler class="\Migration\Handler\SerializeToJson"/>
        </transform>
```

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 

Do you see 
`Could not unserialize data of ...` 
when migrating settings?
