### ISSUE TITLE
Migrating from 1.9.1.0 => 2.2.2

### ISSUE THREAD

**Issue by bellingboe** [magento/data-migration-tool#516]
I'm working on a site upgrade for a client, and their current site has tons of data, and is on 1.9.1.0.. so I found this and followed all the instructions....

https://devdocs.magento.com/guides/v2.2/migration/migration-tool-configure.html

It says :  
``
[2018-05-24 16:09:50][INFO][mode: data][stage: setup triggers][step: Stage]: started
 1/1 [============================] 100%
[2018-05-24 16:09:50][INFO][mode: data][stage: setup triggers][step: Stage]: Migration completed
``

but on the 2.2.2 installation, it doesn't appear any of the data was imported. I even tried re-installing 2.2.2, and running the tool directly after, but still nothing.

**Comment by victor-v-rad** [comment]
HI @bellingboe 

It seems like your config.xml is missing all `steps` records so nothing is migrated. Also running the tool with `--reset` option to start from the benign will help if you previously migrated store and the tool remembered it

**Comment by bellingboe** [comment]
Oh wow, cant believe I missed that, but now I'm getting:

``
  [Migration\Exception]
  Invalid map filename: /var/www/vhosts/***/vendor/magento/data-migration-tool/
``

But all my XML paths are correct, I just double checked


	<options>

    	<crypt_key>189719e17313c4fa37498a7a9ceeeef8</crypt_key>

		<source_prefix>bb_</source_prefix>

		<settings_map_file>etc/opensource-to-opensource/1.9.1.0/settings.xml</settings_map_file>

		<map_file>etc/opensource-to-opensource/1.9.1.0/map.xml</map_file>

        <eav_map_file>etc/opensource-to-opensource/1.9.1.0/map-eav.xml</eav_map_file>

        <eav_document_groups_file>etc/opensource-to-opensource/1.9.1.0/eav-document-groups.xml</eav_document_groups_file>

        <eav_attribute_groups_file>etc/opensource-to-opensource/1.9.1.0/eav-attribute-groups.xml</eav_attribute_groups_file>

	</options>
