### ISSUE TITLE
Products do not shown after migration

### ISSUE THREAD

**Issue by Serzhik** [magento/data-migration-tool#52]
When I try to run reindex, I have error:

$ php bin/magento indexer:reindex
Customer Grid index has been rebuilt successfully in 00:00:03
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dev_autom`.`catalog_product_index_tier_price`, CONSTRAINT `CAT_PRD_IDX_TIER_PRICE_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON ), query was: INSERT INTO `catalog_product_index_tier_price` SELECT `tp`.`entity_id`, `cg`.`customer_group_id`, `cw`.`website_id`, MIN(IF(tp.website_id = 0, ROUND(tp.value * cwd.rate, 4), tp.value)) FROM `catalog_product_entity_tier_price` AS `tp`
 INNER JOIN `customer_group` AS `cg` ON tp.all_groups = 1 OR (tp.all_groups = 0 AND tp.customer_group_id = cg.customer_group_id)
 INNER JOIN `store_website` AS `cw` ON tp.website_id = 0 OR tp.website_id = cw.website_id
 INNER JOIN `catalog_product_index_website` AS `cwd` ON cw.website_id = cwd.website_id WHERE (cw.website_id != 0) GROUP BY `tp`.`entity_id`,
        `cg`.`customer_group_id`,
        `cw`.`website_id` ON DUPLICATE KEY UPDATE `min_price` = VALUES(`min_price`)
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:08

**Comment by victor-v-rad** [comment]
Hi,
I suppose some products do not transfer to Magento 2. Do you have any records in catalog_product_entity table of Magento 2?

**Comment by Serzhik** [comment]
All products from Magento 1.9.2.1 exists at `catalog_product_entity` of Magento 2

**Comment by Serzhik** [comment]
Some products changed their attribute set

**Comment by ilol** [comment]
Hey guys, what is final situation?

**Comment by Serzhik** [comment]
@ilol, I don't konow, because it was my last attempt to migrate )

**Comment by ilol** [comment]
@Serzhik try the MT after update up to 2.1.1
