### ISSUE TITLE
Data migration tool 2.2.3

### ISSUE THREAD

**Issue by VijaySankhat** [magento/data-migration-tool#524]
I am getting an error while migrating from Magento 1.9.0.1 To Magento 2.2.3.
My error log on console is 

> [2018-05-28 11:55:35][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
> [2K100% [============================] Remaining Time: < 1 sec
> [2018-05-28 11:55:35][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
> [2K100% [============================] Remaining Time: < 1 sec
> [0;33m[2018-05-28 11:55:35][WARNING]: Source documents are not mapped: core_store,core_store_group,core_website[0m
> [0;33m[2018-05-28 11:55:35][WARNING]: Destination documents are not mapped: store,store_group,store_website[0m
> [2018-05-28 11:55:35][INFO][mode: settings][stage: data migration][step: Settings Step]: started
> [2K100% [============================] Remaining Time: < 1 sec
> [2018-05-28 11:55:36][INFO][mode: settings][stage: data migration][step: Stores Step]: started
> [2K33% [=========>------------------] Remaining Time: < 1 sec

**Comment by victor-v-rad** [comment]
Store step has its own map file map-stores.xml.dist . Check if the record
`<stores_map_file>etc/opensource-to-opensource/map-stores.xml.dist</stores_map_file>`
is in you config.xml

**Comment by VijaySankhat** [comment]
Thanks for your response @victor-v-rad 
Yes I have rename it as <stores_map_file>etc/opensource-to-opensource/map-stores.xml</stores_map_file>
And the content of 
> map-stores.xml is as below.
```
<map xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../map.xsd">
    <source>
        <document_rules>
            <rename>
                <document>core_store</document>
                <to>store</to>
            </rename>
            <rename>
                <document>core_store_group</document>
                <to>store_group</to>
            </rename>
            <rename>
                <document>core_website</document>
                <to>store_website</to>
            </rename>
        </document_rules>
        <field_rules>
            <ignore>
                <field>core_website.is_staging</field>
            </ignore>
            <ignore>
                <field>core_website.master_login</field>
            </ignore>
            <ignore>
                <field>core_website.master_password</field>
            </ignore>
            <ignore>
                <field>core_website.visibility</field>
            </ignore>
        </field_rules>
    </source>
    <destination>
        <field_rules>
            <ignore>
                <field>store_group.code</field>
            </ignore>
            <transform>
                <field>store_group.code</field>
                <handler class="\Migration\Handler\StoreGroupCode" />
            </transform>
        </field_rules>
    </destination>
</map>
```

**Comment by victor-v-rad** [comment]
Your map-stores.xml is the same as original map-stores.xml.dist Anyway I've just `in/magento migrate:settings path/to/config.xml` without any problems

**Comment by VijaySankhat** [comment]
@victor-v-rad  please provide some suggestions, if you have any.

**Comment by victor-v-rad** [comment]
This error happens when M1 or M2 use prefix in tables name. Please add your prefix in config.xml file in tags
```
<source_prefix />
<dest_prefix />
```

**Comment by Eddcapone** [comment]
I have used prefix but still get the same error.

**Comment by PurushothamanKrishnamoorthy** [comment]
@victor-v-rad : This issue is generating for both 2.3.4 and 2.3.5 . It was working fine for me month, Now I'm facing the same issue. I have updated map files, config files and prefix too. Can you suggest ways to debug this issue.

And I can see these fields are already ignored by default in maps.xml but why we are getting these error?

**Comment by PurushothamanKrishnamoorthy** [comment]
@victor-v-rad : I have ignore fields in map-stores.xml, it works but I'm getting below error:. Is that a right approach ? 

![image](https://user-images.githubusercontent.com/7234860/88140194-e3b32b80-cc0e-11ea-9be0-9633d4ad92af.png)
