### ISSUE TITLE
Issue:- Incompability in data issue Source document: eav_attribute_group. Field: attribute_group_name. Error:

### ISSUE THREAD

**Issue by wakar** [magento/data-migration-tool#526]
**During Magento1.9.3.4 to Magento2.1.8 Migration Getting following issues :-** 

 Incompatibility in data. Source document: eav_attribute_group. Field: attribute_group_name. Error: The product attribute set "Default" does not contain all required attribute group names "General, Prices, Design, Images"

I've attached screenshot.

Any help will be appriciated.

Thanks in advance.

![magento-migration-issue](https://user-images.githubusercontent.com/13333191/40775893-d646473e-64e6-11e8-910d-07dc483f2abe.png)

**Comment by kishansatasiya** [comment]
I am facing same issue.
It is due to you have rename default attribute group (General, Prices, Design, Images) to something else in your magento 1 website.

What should be recommended solution without losing integrity ?

**Comment by wakar** [comment]
The same input I got from R&D, but when I checked the DB "attribute group" looks original.

Thanks, Kishan for your input.

**Comment by wakar** [comment]
After hard work, I configured DB with fresh Magento files then checked attribute group & find that "General" group was renamed as "Basic Info" after changing this to "General" my issue has been resolved.

Thanks!!!
