### ISSUE TITLE
During Data Migration Getting Access Violation Issue

### ISSUE THREAD

**Issue by wakar** [magento/data-migration-tool#528]
During data migration from Magento1 to Magento2, I'm getting the following issue:- 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';
  END;
  INSERT INTO m2_cl_cataloginventory_stock_item (`item_id`, `operation`) V' at line 3, query was: CREATE TRIGGER codisto_cataloginventory_stock_item_delete AFTER DELETE ON cataloginventory_stock
  _item FOR EACH ROW
 

Please see the screenshot for more details

![data-migration-issue](https://user-images.githubusercontent.com/13333191/40908137-7eb9294e-6803-11e8-9058-2ee5ab36aafa.png)

Please help me to resolve this issue.

Thanks!!!

**Comment by victor-v-rad** [comment]
Hi @wakar 

Recheck our MySQL account permissions

**Comment by varunfirstwire** [comment]
Hi,
I am also getting same error but on insert trigger while doing migration.
I have checked the permission of database user and getting that it has all the privileges. 
mysql> SELECT * FROM mysql.user WHERE User='miguser'\G;
*************************** 1. row ***************************
                  Host: localhost
                  User: miguser
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: N
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type:
            ssl_cipher:
           x509_issuer:
          x509_subject:
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: *9D62E34EBDE13D15810A4EBE0F***************
      password_expired: N
 password_last_changed: 2020-10-06 22:00:42
     password_lifetime: NULL
        account_locked: N
1 row in set (0.01 sec)

ERROR:
No query specified

Can you please help..

**Comment by sanaullahAhmad** [comment]
drop all the triggers.. from Magento1 database..
![image](https://github.com/magento/data-migration-tool/assets/9458235/dd94b09c-020d-4678-b5da-7cc221380b66)
