### ISSUE TITLE
After Migration+Checkout page blank(only logo is showing)

### ISSUE THREAD

**Issue by wakar** [magento/data-migration-tool#529]
I've migrated from M1.9.3.4 to M2.1.8 but when i goto checkout page(after adding product to cart) it's shows empty page, only logo is showing.

while other pages are fine.

Screenshots :- 

![checkout-page-empty](https://user-images.githubusercontent.com/13333191/40978738-9ecee77a-68f1-11e8-82fe-23314e1b9648.png)

Thanks!!!

**Comment by victor-v-rad** [comment]
I see you use IP address instead of domain name. I might be the cause
