### ISSUE TITLE
Configurable products price after migration

### ISSUE THREAD

**Issue by juandosil** [magento/data-migration-tool#530]
Hello.
I have migrated the product data without a problem from Magento 1.9.2 to Magento 2.2.4. The problem I find now in the configurable products. In some configurable product your simple products do not have the same price of the configurable product since they had no relevance in Magento 1.9. Now if I find in Magento 2 that the price is the price of the simple product. Would it be possible in the migration that the price of each simple product of a configurable product was the same price as the configurable product?

**Comment by victor-v-rad** [comment]
Hi @juandosil 

Please see the similar issue #398 can help
