### ISSUE TITLE
magento 1 to magento 2 data migration error class not found at attribute id

### ISSUE THREAD

**Issue by RasikMiyani** [magento/data-migration-tool#543]
Hello,

I am doing data migration usin magento data migration and facing some issue related to class not found.

I think there are some extension installed and model created and assigned that attribute. and same way that extension and model not found on magento2 while migrating data.

I also did R&D on this and found some help like below,
Add the attribute to the ignore group in the eav-attribute-groups.xml.dist file.

But can you please advise how we can ignore that group.

My errors:
?[0;31m[2018-06-21 05:05:06][ERROR]: Class debit/entity_customer_attribute_backend_encrypted does not exist but mentioned in: eav_attribute.backend_model for attribute_id=519?[0m
?[0;31m[2018-06-21 05:05:06][ERROR]: Class debit/entity_customer_attribute_backend_encrypted does not exist but mentioned in: eav_attribute.backend_model for attribute_id=520?[0m
?[0;31m[2018-06-21 05:05:06][ERROR]: Class metarobots/product_attribute_source_unit does not exist but mentioned in: eav_attribute.source_model for attribute_id=521?[0m
[2018-06-21 05:05:06][INFO][mode: data][stage: volume check][step: EAV Step]: Error occurred. Rollback.
[2018-06-21 05:05:06][INFO][mode: data][stage: volume check][step: EAV Step]: EAV Step: rollback
[2018-06-21 05:05:11][INFO][mode: data][stage: volume check][step: EAV Step]: Please fix errors and run Migration Tool again

Thanks for help in advance.

Thanks,

**Comment by victor-v-rad** [comment]
@RasikMiyani 

If you do **not want** to migrate these attributes, use eav-attribute-groups.xml.dist . If you **want** to migrate it add class-map.xml.dist empty map of your classes. Like 
```
    <rename>
        <from>debit/entity_customer_attribute_backend_encrypted</from>
        <to />
    </rename>
```
