### ISSUE TITLE
magento 1 to magento 2 data migration error

### ISSUE THREAD

**Issue by RasikMiyani** [magento/data-migration-tool#544]
hello,

When I  start magento 1 to magento 2 data migration that will give me a error,
that error will be show below,
 [Exception]
  Warning: PDOStatement::execute(): MySQL server has gone away in C:\xampp\ht
  docs\Magento-CE-2.2.44\vendor\magento\data-migration-tool\src\Migration\Res
  ourceModel\Adapter\Mysql.php on line 169

please Help,
Thanks in Advance
Thanks,

**Comment by RasikMiyani** [comment]
Tata will be solved

**Comment by victor-v-rad** [comment]
Hi @RasikMiyani 

Try to increase max_allowed_packet option in your my.conf

**Comment by RasikMiyani** [comment]
Thanks @victor-v-rad  ,
but thata issue solved allready

**Comment by eakenbor** [comment]
> Tata will be solved

Please how did you solve it?
