### ISSUE TITLE
PayPal standard settings for active/sandbox mode not carried across

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#545]
Hi,

This should fix it..

```
<rename>
            <path>payment/paypal_standard/active</path>
            <to>payment/wps_express/active</to>
        </rename>
        <rename>
            <path>payment/paypal_standard/sandbox_flag</path>
            <to>paypal/wpp/sandbox_flag</to>
        </rename>
```

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 
Thank you for this fix. I found `payment/paypal_wps_express/active` in my Magento 1.9.3.1 for PayPal Standard configuration. But your is `payment/paypal_standard/active`

**Comment by craigcarnell** [comment]
@victor-v-rad We are using Magento EE 1.14.3.8

Website Payments Standard, Use this solution->Yes.

This setting is: 

```
<config_path>payment/paypal_standard/active</config_path>
```

line 1724.

**Comment by victor-v-rad** [comment]
MAGETWO-93065 ticket to fix it
