### ISSUE TITLE
migration tool for magento 2.1.13?

### ISSUE THREAD

**Issue by MarcusWolschon** [magento/data-migration-tool#547]
According to
https://github.com/magento/data-migration-tool
the migration tool has to precisely match the magento2 version.
However there are only migration tools for 2.1.9 and then 2.2.0.
Nothing for Magento 2.1.10-2.1.13.

Background:
On Debian based systems magento1.x can only be installed at the same time with magento 2.1 using PHP 5.6
but not with 2.2 or 2.3 with PHP 7.x.
This is because libcurl3 and libcurl4 are conflicting due to Canonical ******* up and they are required by php5-curl and php7-curl.

**Comment by piotrekkaminski** [comment]
We release the tool to match latest versions so 2.1 development stopped when 2.2 was introduced.
Would migrating to 2.1.9 and then updating it to 2.2.5 solve the issue?

**Comment by victor-v-rad** [comment]
Yes 1.9.3.6 config should work with 1.9.3.8 database. 
Consider possibility ruining [multiple PHP versions](https://pehapkari.cz/blog/2017/03/27/multiple-php-versions-the-easy-way/) on one debian instance. Or allocate separate linux instance for Magento 2.2

**Comment by victor-v-rad** [comment]
```
 <ignore>
                <document>amazon_customer</document>
                <document>amazon_customer</document>
</ignore>
```
you actually found a bug here ) two `amazon_customer` records in xml file should not exist

**Comment by MarcusWolschon** [comment]
Multiple PHP versions don't work because both require different versions of libcurl and libcurl3+libcurl4 explicitly.
Quote:
"both libcurl3 and libcurl4 provide the "libcurl.so.4" library (libcurl3
did so for historical reasons), so both packages can't be installed at the same
time. "

Anyway, workaround works.
