### ISSUE TITLE
Error when using PHP 7

### ISSUE THREAD

**Issue by andidhouse** [magento/data-migration-tool#55]
we just tried to use php7.0.2 and get the following error when starting the data migration. Just a test with php7 but strange:

php bin/magento migrate:data -r /var/www/html/magento2/vendor/magento/data-migration-tool/etc/ce-to-ce/1.7.0.2/config.xml
PHP Fatal error:  Redefinition of parameter $logger in /var/www/html/magento2/vendor/magento/data-migration-tool/src/Migration/Step/ConfigurablePrices/Volume.php on line 45

**Comment by victor-v-rad** [comment]
Hi,

Apply this [pull request](https://github.com/magento/data-migration-tool-ce/pull/29) to fix your issue

**Comment by ilol** [comment]
@andidhouse did it help? I would like to ask you to close the issue.
Btw we process the https://github.com/magento/magento2/issues/4356.

**Comment by andidhouse** [comment]
Hi @ilol,

we did not test - sorry! We switched back to php5 version as we had many bugs in php7 and also face many problems we have to solve to migrate to m2 at the moment so we could not test php7 any further.

Many thanks for investigating #4356 - but this has nothing to do with php7 - we run php5 at the moment.

**Comment by ilol** [comment]
So, @andidhouse I am closing this issue. Thank you

**Comment by medma-infomatix** [comment]
Please run the below command.

[$ composer update](url)

I have fixed this issue by update composer.
