### ISSUE TITLE
Installation Error - Fatal Error: Out Of Memory

### ISSUE THREAD

**Issue by ROYALRandhawa** [magento/data-migration-tool#551]
Hello Everyone,
I got some issues when installing **Data Migration Tool** for **Magento 2.1.7**
Whenever I tried to install tool I got error:
```
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 370679808) (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/GenericRule.php on line 36
```
My server has memory_limit of 2048M or 2G right now. As per official docs og Magento Data Migration Tool, it just need 2G of memory but in my case something strange happening.

I also tried to install with `php -dmemory_limit=2G /usr/local/bin/composer update --prefer-dist --no-dev`
By no success........

Please help me, I need it urgent

**Some info about my site:
Magento 2.1.7
php 7.0.30
memory_limit: 2G**

**Comment by victor-v-rad** [comment]
Hi @ROYALRandhawa 
Possible solutions could be 
# to set PHP > memory_limit = -1 
# in data migration tool > config.xml <bulk_size> = 1000 or 500

**Comment by ROYALRandhawa** [comment]
@victor-v-rad  thanks for you reply

i tried with memory_limit=-1 but no success

but I am confused how I use second way **`in data migration tool > config.xml <bulk_size> = 1000 or 500`** 

I am installing data migration tool via composer and please tell me if there is a way to install tool manually without composer

**Comment by victor-v-rad** [comment]
about config.xml you can read [here](https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html)

**Comment by ROYALRandhawa** [comment]
this is not working, can you please  give another way to install Data Migration Tool.... its good if there is way to install manually

**Comment by adeptofvoltron** [comment]
@victor-v-rad is it possible to change bulk size just for one table??

**Comment by victor-v-rad** [comment]
bulk_size only for all tables. But you can change the code of the tool for the particular table

**Comment by ParagBhargav** [comment]
@victor-v-rad Here @ROYALRandhawa  is talking about to install the data migration tool. But you are talking about Migration settings. We need to increase the <bulk_size> when we try to migrate the data not when we trying to install the migration tool.
