### ISSUE TITLE
Migrate from 1.9.2.2 to 2.1.13, no commands defined in the "migrate" namespace

### ISSUE THREAD

**Issue by allblued** [magento/data-migration-tool#552]
I am trying to migrate magento from 1.9.2.2 to 2.1.13 by following the official document. However, after I set up the config.xml, and try to use the following command to start the migration:

bin/magento migrate:settings [-r|--reset] /var/www/html/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.2/config.xml

An error message jumped out said:

 [InvalidArgumentException]                                 
  There are no commands defined in the "migrate" namespace. 

Is there any way to solve this problem?

**Comment by victor-v-rad** [comment]
Probably the tool was installed incorrectly in magento 2 code base

**Comment by allblued** [comment]
Yes, I didn't successfully install the tool. I tried to use both git and repo to install the tool, but the composer command doesn't work for me with the following error message:

[xx@xx shopping]$ composer config repositories.magento composerhttps://repo.magento.com
Could not open input file: /home/xx/composer.phar
[xx@xxshopping]$ composer require magento/data-migration-tool:<version>
bash: syntax error near unexpected token `newline'
[xx@xx shopping]$

How can I add composer.phar?

**Comment by victor-v-rad** [comment]
https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx
