### ISSUE TITLE
map-tier-pricing.xml.dist references incorrect

### ISSUE THREAD

**Issue by clivewalkden** [magento/data-migration-tool#557]
Just been running the migration tool and spotted some links which needed updating for the config.xml.dist files. Below is my commit message.

Updated some references to map-tier-pricing.xml.dist in the 1.9.3.6-1.9.3.8 and 1.14.3.6-1.14.3.8 config.xml.dist files see PR #548

**Comment by victor-v-rad** [comment]
Thank you @clivewalkden for fixing it in https://github.com/magento/data-migration-tool/pull/548 
internal ticket MAGETWO-93233 to process it

**Comment by victor-v-rad** [comment]
Merged
