### ISSUE TITLE
No data appread even after successful data migration

### ISSUE THREAD

**Issue by vcpawate** [magento/data-migration-tool#56]
I am migrating magento from 1.9.0.1 to Magento 2.0.1, using Magento Data migration tool,

Data migration tool executed with no error, but I cannot see any data in magento admin backend,

I have cleared cache, reindexed. I can see data in database, but no data appeared on Magento admin panel,

Please help

**Comment by victor-v-rad** [comment]
Normally, running the next command fixes such issue:
`php bin/magento indexer:reindex && php bin/magento cache:clean`

**Comment by vcpawate** [comment]
I did executed those commands, but I still I cannot see any data on the Admin panel

**Comment by victor-v-rad** [comment]
I've just migrated 1.9.0.1 (without any extensions) to Magento 2.0.1 and I can see orders/products/customers .... in admin panel of Magento 2

**Comment by vcpawate** [comment]
I tried to do again from migration form new instance beginning and I got error Undefined offset 
With -vvv option enable it is pointing to data.php file

Could you please let me know what is the problem? I could be facing? I have a existing live website in  magento 1.9.0.1 and I am facing lot of issues, I came long way, To just let you know issues faced were,
Packed size were small in mysql ini file, Php memory size was small and I have to patch the file Version191to2000.php. After all this , I got above error, I have used bitnami distribution of magento 2 2.0.0.1

**Comment by victor-v-rad** [comment]
>I got error Undefined offset With -vvv

Please show error message with backtrace. Use [Inline Markdown](https://guides.github.com/features/mastering-markdown/) for this message.

**Comment by vcpawate** [comment]
I tried fresh installation from github this time branch 2.0 Tag 2.0.1(Earlier, I tried with Bitnami Installation) and I could not find any issue, migration was successful, 
Still I have to replace Version191to2000.php - I am not sure why this has not yet been merged?

After migration: I tried to login to backend, but  I am facing error as "file not found" when click on www.STORENAME.com/admin

No log created in var/log or in var/report

What is wrong here

**Comment by vcpawate** [comment]
tried clean and flush but still it says FILE NOT FOUND

**Comment by vcpawate** [comment]
Tried following 
 php bin/magento setup:static-content:deploy  

Also referred following link - but still facing issue
http://magento.stackexchange.com/questions/87038/magento-2-error-404-not-found-at-magento-2-admin-login-page

**Comment by vcpawate** [comment]
Just now I checked , Data migration tool has just imported 600 products(from phpmyadmin), where as my live store has 6000 products

**Comment by ilol** [comment]
Hey @vcpawate, how are you there? Did you migrate successfully?

**Comment by vcpawate** [comment]
No, I tried all different possible things, but I could not, I guess , need to wait for few more revision

**Comment by vcpawate** [comment]
Hello Oliinyk

Fine thanks, how are you doing
