### ISSUE TITLE
Unable to run migration without super privilages

### ISSUE THREAD

**Issue by eCommerceGorilla** [magento/data-migration-tool#562]
Unable to run the migration tool on a hosting account without SUPER privileges.

> [Zend_Db_Statement_Exception]                                                                                                                                                           
>   SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable  
>   ), query was: CREATE TRIGGER trg_catalog_compare_item_after_insert AFTER INSERT ON catalog_compare_item FOR EACH ROW                                                                    
>   BEGIN                                                                                                                                                                                   
>   INSERT INTO m2_cl_catalog_compare_item (`catalog_compare_item_id`, `operation`) VALUES (NEW.catalog_compare_item_id, 'INSERT')ON DUPLICATE KEY UPDATE operation = 'INSERT';             
>   END                                                                                                                                                                                     
>                                                                                                                                                                                           
> 
>                                                                                                                                                                                           
>   [PDOException]                                                                                                                                                                          
>   SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable  
>   ) 

Is there a way of getting around the necessity of SUPER privileges as it is almost never an option on a shared environment?

**Comment by victor-v-rad** [comment]
Hi @eCommerceGorilla 

1 In case you do not need to run migration in delta mode then you could switch off setup delta triggers and tables.

2 The error message gives a hint `you might want to use the less safe log_bin_trust_function_creators variable`. So try using this variable
