### ISSUE TITLE
Can't edit product or create new attribute set after migration

### ISSUE THREAD

**Issue by allblued** [magento/data-migration-tool#564]
Can't edit product or create new attribute set after migration
I used data-migration-tool to migrate my store from 1.9.2.2 to 2.1.14, but after the migration, I find I can't open "edit" page of any existing product. The following error message show up:

========================================================

> There has been an error processing your request.
> 
> The configuration parameter "formElement" is a required for "" field.
> 
> Error log record number: 1495859023951
> 
> (Yes, there is nothing in the second quote mark)

========================================================

Also, I tried to add new product, with new attribute set, but when I configured it and click "save", it shows:

========================================================

> Attribute with the same code already exists.

========================================================

In the error log, I found the following information:
======================================

> [2018-07-30 14:44:08] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/index/index/key/cc242c6131c71fd66b16260b5ad93552390d63148a2873939769751de382d700/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
> [2018-07-30 18:44:17] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/index/index/key/7c675e741f7f8463bf9cb5963069917303c44d9cbb12fe559cfa9ce92b622fe8/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
> [2018-07-30 19:08:13] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/index/index/key/7c675e741f7f8463bf9cb5963069917303c44d9cbb12fe559cfa9ce92b622fe8/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
> [2018-07-30 19:22:45] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/index/index/key/7c675e741f7f8463bf9cb5963069917303c44d9cbb12fe559cfa9ce92b622fe8/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
> [2018-07-30 19:23:15] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/cache/flushSystem/key/ce357941d6c6529e4ec5ebfe1ccbb6b3183496b7554f966f32496cdcdceed824/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
> [2018-07-30 19:23:15] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/cache/flushSystem/key/ce357941d6c6529e4ec5ebfe1ccbb6b3183496b7554f966f32496cdcdceed824/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
> [2018-07-30 19:23:15] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/cache/flushSystem/key/ce357941d6c6529e4ec5ebfe1ccbb6b3183496b7554f966f32496cdcdceed824/","invalidateInfo":{"tags":["FPC"],"mode":"matchingTag"},"is_exception":false} []
> [2018-07-30 19:23:16] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://kuohua.ca/shopping/index.php/admin_1xw3il/admin/cache/index/key/a34d8fc7097e4a12342c6aecb256d410cc150d914594a6f047bf1a5411d3ea28/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []

============================================================

Anyone knows how to solve it?

**Comment by victor-v-rad** [comment]
Hi @allblued 

If you can migrate to Magento 2.2.x you likely wont have these issues.
