### ISSUE TITLE
After Migration issue is " No such entity with email = examplemail@mail.com, websiteId = 1"

### ISSUE THREAD

**Issue by wcladesh** [magento/data-migration-tool#565]
I have Followed all recommendation and suggestion to Migrate Magento 1.9.1.0 to Magento 2.2.4. I have Installed latest fresh Magento 2.2.4 and Migrate my Old website Magento 1.9.1.0. My website is a multiple stores/website. Everything is migrated proper and working fine but when I am trying to create customer I am getting issue  " No such entity with email = examplemail@mail.com, websiteId = 1" . I have tried each and everything to debug that issue but not able to resolve that issue.

I have to make a replica of new DB and replace two tables "customer_eav_attribute" and "eav_attribute of fresh Magento2 "  then I am able to create customer successfully but new is raised in Catalog section. Category and product name are missing in the backend. So it seems this is not good to replace both tables.

Please help me to resolve " No such entity with email = examplemail@mail.com, websiteId = 1" issue.

**Comment by victor-v-rad** [comment]
Hi @wcladesh 

Look into migrated eav_attribute table and try to find `email` attribute. After migration it is better to all the changes with attributes from Admin Panel and not by changing records in DB tables

**Comment by wcladesh** [comment]
Hi @victor-v-rad ,

Thanks for your quick reply,

changes with attributes from Admin Panel is ok for product attributes but not possible for customer attribute since I am using Magento Open Source hence customer attributes (email)are not available in the admin panel.

As per your suggestions, I have resolved that issue by comparing  attribute_code "email" in Magento default and found that backend type was "varchar" after migration while it is "static" in Magento Default. After updating it is working now fine.

I was troubling that issue last 7 days and finally resolved this with your help.

One More issue I have got after the migration is that we are not able to save color attribute option in admin section while saving color attribute its throw error

**"The value of Admin must be unique."** 

 when we are removing all repeated options value and saved it then it is saving while reopening it then again the same issue appeared means duplicate option values are not deleting in actual.

please help us to resolve this issue.

Thanks Again for your help.

**Comment by victor-v-rad** [comment]
I see `email` attribute is `static` in all my M1 instances. Do not know why your one has `varchar`. Tomorrow I will look at the issue with values must be unique.

**Comment by wcladesh** [comment]
Hi @victor-v-rad, 
Thanks for your quick reply.
 you are correct all M1 instances have static values but my old website has backend_type 
varchar , the client provided us old website database and we are migrating it in M2.

Please look into the other reported issue which is a blocker at the current stage.

**Comment by victor-v-rad** [comment]
This one #566 ?

**Comment by wcladesh** [comment]
Hi @victor-v-rad,
Sorry I am not talking about the above issue as you referenced  [#566](https://github.com/magento/data-migration-tool/issues/566)

I have an issue as regarding when updating  attribute **color**  as mention above 

_One More issue I have got after the migration is that we are not able to save color attribute option in admin section while saving color attribute its throw error

"The value of Admin must be unique."

when we are removing all repeated options value and saved it then it is saving while reopening it then again the same issue appeared means duplicate option values are not deleting in actual._

**Comment by wcladesh** [comment]
Hi @victor-v-rad,
Any update?
Still, I have the same problem "The value of Admin must be unique." while deleting duplicate option values from color attribute and saving then it saved without and error but again reopening this attribute same option values exist and same issue coming again means it is not deleting option values in actual.

Please help me.

Thanks

**Comment by wcladesh** [comment]
Hi @victor-v-rad,
This issue has been resolved from our end, updating issue has been resolved.
By Set "max_input_vars" in php.ini file.
"max_input_vars" to 300000 

Thanks

**Comment by vrajeshpatel4u** [comment]
Is there any solutions for this ?
