### ISSUE TITLE
move column between tables

### ISSUE THREAD

**Issue by adeptofvoltron** [magento/data-migration-tool#566]
Hi,
wonder what is the best practice to move a column between 2 not mapped documents.

example:
in my documents rule section I got:
```
    <rename>
                <document>source_table_1</document>
                <to>destination_table_1</to>
     </rename>
    <rename>
                <document>source_table_2</document>
                <to>destination_table_2</to>
     </rename>
```

but if there is one column I want to move from `source_table_1` to `destination_table_2`, what is the best practice?

code below will not work(obviously):
```
 <move>
                <field>source_table_1.column</field>
                <to>destination_table_2.column</to>
  </move>
```
 
lets assume that in destination_table_2 table I got id column from destination_table_1 but no foreign key

**Comment by victor-v-rad** [comment]
Thank you @adeptofvoltron for describing this issue, Internal ticket MAGETWO-93986 to fix it. Probably the quickest way for you to resolve it is to write a new step with custom SQL like `\Migration\Step\Ratings\Data` and make it run in the end of migration

**Comment by adeptofvoltron** [comment]
thank you @victor-v-rad for your quick respond. If there is no other option right now...than ok. I will have to do it.
Maybe later I will make some pull request for it

**Comment by davoc** [comment]
Is there a fix for this issue yet? I assume it is impossible to do anything other than ignore fields whose names and tables do not match between m1 and m2 module eav attributes until this is resolved?

**Comment by victor-v-rad** [comment]
@davoc @adeptofvoltron 
one more way to solve it is to write new handler
```
            <transform>
                <field>destination_table_2.column</field>
                <handler class="\Migration\Handler\YourHandler"/>
            </transform>

```
which fetch data from source_table_1.column . See this example \Migration\Handler\BundleParentProduct
