### ISSUE TITLE
Question - video 

### ISSUE THREAD

**Issue by jacobabey1** [magento/data-migration-tool#569]
Hello , 
wanted to find out if there is any step by step video online ,  on how to use the magento migration tool ?
I have searched online but can't find  one .
Can some help out with a practical  video ? or share any link to one ?

**Comment by victor-v-rad** [comment]
Hi @jacobabey1 

There is a [video](https://www.youtube.com/watch?v=WS-1Jje5XSw) but it is in Russian. Auto-translate subtitles may work.

**Comment by jacobabey1** [comment]
Thank you for the information
