### ISSUE TITLE
Is it possible to use data migration tool version 2.0.0 on Magento 2.0.1 ?

### ISSUE THREAD

**Issue by lgarridoj** [magento/data-migration-tool#57]
The data migration guide says:

"Note: The versions of both the migration tool and the Magento 2 code must be identical (for example, 2.0.0). To find the version of either package, open composer.json and find the value of "version"."

However, there is no data migration tool version 2.0.1.
Can I use the version 2.0.0 on magento 2.0.1?

**Comment by ilol** [comment]
We almost ready to release 2.0.2 version. Please, follow the updates.

**Comment by ilol** [comment]
Released :)

**Comment by ilol** [comment]
@lgarridoj can you close? thanks
