### ISSUE TITLE
CE 1.9.2.2 to OS 2.2.5 errors.

### ISSUE THREAD

**Issue by maxedout** [magento/data-migration-tool#570]
Hey there Guys/Gals,

As we all know it is time to get a move on to M2, and that is what I am attempting to accomplish. I am trying to use the Migration Tool v2.2.5 and am getting a new collection of errors as per screenshot. As one can probably guess, I am not a programmer, but I am doing my best.

Any suggestions would be most helpful.

Thanks for your time

PS. I am able to connect to both databases via mysqli without any problems.

![migration-tool-2 2 5-errors](https://user-images.githubusercontent.com/5733653/43672539-326691e4-977e-11e8-9a5b-ccde08e39af7.jpg)

**Comment by victor-v-rad** [comment]
Hi @maxedout 

Changing password for connection to MySQL might help

**Comment by maxedout** [comment]
Hello there, thanks for the suggestion, it is very close.

The root of the problem was because the SOURCE DB had it's password saved in a format incompatible with PHP7, solution is to resave the password in a format compatible with PHP7. I did not do this, my hoster (Nexcess rocks) did this for me.
