### ISSUE TITLE
Volume Check Failed. Migrating data from m1 to m2

### ISSUE THREAD

**Issue by mehmetuygun** [magento/data-migration-tool#571]
1.  I am trying to migrate customers and orders from magento 1.9.3.8 to magento 2.2.5 (php 7.1)

### Steps to reproduce

1.    My config.xml file is as according.

`<steps mode="data">`
`        <step title="Customer Attributes Step">`
`                     <integrity>Migration\Step\Customer\Integrity</integrity>`
`                      <data>Migration\Step\Customer\Data</data>`
`                      <volume>Migration\Step\Customer\Volume</volume>`
`         </step>`
`         <step title="OrderGrids Step">`
`                        <integrity>Migration\Step\OrderGrids\Integrity</integrity>`
`                        <data>Migration\Step\OrderGrids\Data</data>`
`                        <volume>Migration\Step\OrderGrids\Volume</volume>`
`          </step>`
`          <step title="SalesIncrement Step">`
`                        <integrity>Migration\Step\SalesIncrement\Integrity</integrity>`
`                        <data>Migration\Step\SalesIncrement\Data</data>`
`                        <volume>Migration\Step\SalesIncrement\Volume</volume>`
`          </step>`
`          </steps>`

1.  `php bin/magento migrate:data -r -a vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.8/config.xml`

### Actual result

 ![screenshot_2](https://user-images.githubusercontent.com/4094099/43777174-ef05a9a2-9a49-11e8-9e64-b19f38906da9.png)

**Comment by victor-v-rad** [comment]
Hi @mehmetuygun 

Here several similar issues ) #559, #497, #489, #337, #427, #326, #406, #80

**Comment by dnesdeveloper** [comment]
any solution please

**Comment by dnesdeveloper** [comment]
Has anybody found the solution for the above-mentioned issue?
