### ISSUE TITLE
After migration, Grouped products want a price?

### ISSUE THREAD

**Issue by iphigenie** [magento/data-migration-tool#574]
### Preconditions

Magento 2.2.5 and Data Migration Tool 2.2.5

### Steps to reproduce

1. 1.9.x Magento site with a grouped product and associated products
1. Run migration between 1.9.x and 2.2.5
2. On 2.2.5 side, go to Admin, Store, Products
3. Edit the Grouped product
4. Try to save the grouped product

### Expected result

There should be no price field, grouped products do not have an editable or required price field, price is calculated based on associated products.

### Actual result

Editing any migrated grouped product gives an error showing the price field, empty, demanding that the field be filled.

### Additional notes

The grouped products are functioning fine on the front end, showing the normal calculated price, being added to cart.

In admin, trying to create a new grouped product of attribute set "default" (not a migrated one) also shows a price field, marked as "required" - so the admin behaviour of grouped products has been changed/overriden by the migration. 

It is as if the price attribute has been recreated, losing whatever "special" sauce triggers in admin to know to not show it on grouped products.

**Comment by victor-v-rad** [comment]
Hi @iphigenie 

Yes you are right about price field. Internal ticket MAGETWO-94160 to fix it

**Comment by karamveer-cipl** [comment]
Hi All,

We also facing same issue after migration database from 1.9 to 2.2.5 version. 

Can anyone please suggest the solution/fixes?

**Comment by wilfriedwolf** [comment]
Me too. -> 1.7.0.2 -> 2.2.6 Any news here?

**Comment by wilfriedwolf** [comment]
Hi all,

I just solved the problem and created 2 pull requests (for 2.2-develop and 2.3-develop). I hope I did everything right.
I'll create a small module to correct this issue for older versions tomorrow.

Best regards,

Willi

**Comment by iphigenie** [comment]
Hi Willi
Fantastic timing I just had a fresh M2 installed to do another stab at migration. Will give it a try :)

**Comment by wilfriedwolf** [comment]
Hi Iphigenie,

pleased to hear. I just created a Module (which is quite easy and not yet tested) so you could try out  and do the testing :)

You can get it on  [github](https://github.com/sandstein/fix-data-migration-for-grouped) ;)

Best regards,

Willi

**Comment by karamveer-cipl** [comment]
Hi wilfriedwolf,

Does your module works on Migration tool version 2.2.6. ?

**Comment by wilfriedwolf** [comment]
It should, since it just provides a plugin to a handler. It is not tested though, so just try out...

**Comment by iphigenie** [comment]
confirming that the tool in version 2.3.1 seems to avoid the problem :)

**Comment by victor-v-rad** [comment]
I rechecked migration to 2.3.1 and price field is no more in Grouped product
