### ISSUE TITLE
transform table, that do not take part in migration

### ISSUE THREAD

**Issue by adeptofvoltron** [magento/data-migration-tool#575]
### question

On destination database table I got table, that table is not taking part in migration because there is no equivalent for that table in magento 1.  However during migration process I want to transform one of the columns.
Is it possible to do it during map step - or transform in run only on mapped reccords? Do I have to write my own step at the end of migration?

**Comment by victor-v-rad** [comment]
Either `<rename>` rule for document in map file or new step

**Comment by adeptofvoltron** [comment]
rename only for destination table? without any source?

**Comment by victor-v-rad** [comment]
see my comment https://github.com/magento/data-migration-tool/issues/566#issuecomment-414225688
