### ISSUE TITLE
class-map.xml is ignored migrating from M1.9.2.4 to M2.2.5

### ISSUE THREAD

**Issue by pablobae** [magento/data-migration-tool#576]
Im trying to migrate from magento 1.9.2.4 to Magento 2.2.5. 
### Preconditions

1.  Centos 7 64
2. PHP 7.1.19

### Steps to reproduce

1. My config.xml file is the default with my databases credendials and key
2.  Run 
`php bin/magento migrate:data -ra vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml`

Getting the following class map error: 
`[2018-08-18 13:22:50][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
`
`[2018-08-18 13:22:50][ERROR]: Class Meigee_CategoriesEnhanced/category_attribute_source_block_grid does not exist but mentioned in: eav_attribute.source_model for attribute_id=132` 
`[2018-08-18 13:22:50][ERROR]: Class Meigee_CategoriesEnhanced/category_attribute_source_block_ratio does not exist but mentioned in: eav_attribute.source_model for attribute_id=134`
`...`
`[2018-08-18 13:22:50][ERROR]: Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attribute_id=145`
`[2018-08-18 13:22:50][INFO][mode: data][stage: volume check][step: EAV Step]: Error occurred. Rollback.`
`[2018-08-18 13:22:50][INFO][mode: data][stage: volume check][step: EAV Step]: EAV Step: rollback`
`[2018-08-18 13:22:51][INFO][mode: data][stage: volume check][step: EAV Step]: Please fix errors and run Migration Tool again`

 ` [Migration\Exception]
  Volume Check failed `

3. Regarding that error, add file vendor/magento/data-migration-tool/etc/opensource-to-opensource/class-map.xml  to ignore that classes:
`...
    <rename>
        <from>Meigee_CategoriesEnhanced/category_attribute_source_block_ratio</from>
        <to></to>
    </rename>
    <rename>
        <from>Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable</from>
        <to></to>
    </rename>
    <rename>
        <from>Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisablelight</from>
        <to></to>
    </rename>
    <rename>
        <from>Meigee_CategoriesEnhanced/category_attribute_source_block_labels</from>
        <to></to>
    </rename>
    <rename>
        <from>themeOptionsIndigo/attribute_source_type</from>
        <to></to>
    </rename>
    <rename>
        <from>ThemeOptionsIndigo/attribute_source_productlayout</from>
        <to></to>
    </rename>
    <rename>
        <from>ThemeOptionsIndigo/attribute_source_slider</from>
        <to></to>
    </rename>
    <rename>
        <from>ThemeOptionsIndigo/attribute_source_relatedpos</from>
        <to></to>
    </rename>
    <rename>
        <from>ThemeOptionsIndigo/attribute_source_collateral</from>
        <to></to>
    </rename>
    <rename>
        <from>ThemeOptionsIndigo/attribute_source_brandpos</from>
        <to></to>
    </rename>
    <rename>
        <from>ThemeOptionsIndigo/attribute_source_productsidebar</from>
        <to></to>
    </rename>
...`

4. Re-run  
`php bin/magento migrate:data -ra vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml`

### Expected result

1.  Detailed classes on class-map.xml ignored and go on to the next step without errors

### Actual result

1. Class map is ignored, and class errors still present:
Getting the following class map error: 
`[INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
`
`[ERROR]: Class Meigee_CategoriesEnhanced/category_attribute_source_block_grid does not exist but mentioned in: eav_attribute.source_model for attribute_id=132` 
`[ERROR]: Class Meigee_CategoriesEnhanced/category_attribute_source_block_ratio does not exist but mentioned in: eav_attribute.source_model for attribute_id=134`
`...`
`[ERROR]: Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attribute_id=145`
`[INFO][mode: data][stage: volume check][step: EAV Step]: Error occurred. Rollback.`
`[INFO][mode: data][stage: volume check][step: EAV Step]: EAV Step: rollback`
`[INFO][mode: data][stage: volume check][step: EAV Step]: Please fix errors and run Migration Tool again`

 ` [Migration\Exception]
  Volume Check failed `

**Comment by victor-v-rad** [comment]
seems you did not add Meigee_CategoriesEnhanced/category_attribute_source_block_grid to class-map.xml

**Comment by victor-v-rad** [comment]
if you do not need these attributes you also can not to transfer it to M2. 
eav-attribute-groups.xml.dist >> `<group name="ignore">`

**Comment by kostia-lev** [comment]
> seems you did not add Meigee_CategoriesEnhanced/category_attribute_source_block_grid to class-map.xml

but he added category_attribute_source_block_ratio to class-map.xml, and still sees it in the error message. Why is that? 
I have the same issue. 
It is not clear what file to use: dist or remove dist and create a new file, none of these work.

**Comment by kostia-lev** [comment]
this is my error:
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_source_categorylabel does not exist but mentioned in: eav_attribute.source_model for attribute_id=138
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_source_dropdown_type does not exist but mentioned in: eav_attribute.source_model for attribute_id=139
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_backend_grid_columns does not exist but mentioned in: eav_attribute.backend_model for attribute_id=141
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_source_dropdown_columns does not exist but mentioned in: eav_attribute.source_model for attribute_id=142
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_backend_dropdown_blocks does not exist but mentioned in: eav_attribute.backend_model for attribute_id=143
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_helper_grid_columns does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=141
[2018-11-11 21:29:49][ERROR]: Class ultramegamenu/category_attribute_helper_dropdown_blocks does not exist but mentioned in: catalog_eav_attribute.frontend_input_renderer for attribute_id=143

I renamed this is my file vendor/magento/data-migration-tool/etc/opensource-to-opensource/class-map.xml.dist to class-map.xml and added such strings:
```
<rename>
        <from>ultramegamenu/category_attribute_source_categorylabel</from>
        <to></to>
    </rename>
    <rename>
        <from>ultramegamenu/category_attribute_source_dropdown_type</from>
        <to></to>
    </rename>
    <rename>
        <from>ultramegamenu/category_attribute_backend_grid_columns</from>
        <to></to>
    </rename>
    <rename>
        <from>ultramegamenu/category_attribute_source_dropdown_columns</from>
        <to></to>
    </rename>
    <rename>
        <from>ultramegamenu/category_attribute_backend_dropdown_blocks</from>
        <to></to>
    </rename>
    <rename>
        <from>ultramegamenu/category_attribute_helper_grid_columns</from>
        <to></to>
    </rename>
    <rename>
        <from>ultramegamenu/category_attribute_helper_dropdown_blocks</from>
        <to></to>
    </rename>
```

**still have same error**

after that I tried to add these strings to vendor/magento/data-migration-tool/etc/opensource-to-opensource/eav-attribute-groups.xml.dist:
```
    <group name="ignore">
        <attribute type="catalog_product">msrp_enabled</attribute>
        <attribute type="catalog_product">group_price</attribute>
        <attribute type="catalog_category">umm_cat_label</attribute>
        <attribute type="catalog_category">umm_dd_type</attribute>
        <attribute type="catalog_category">umm_dd_proportions</attribute>
        <attribute type="catalog_category">umm_dd_columns</attribute>
        <attribute type="catalog_category">umm_dd_blocks</attribute>
    </group>
```
**still have same error**
can it be cached somehow? or it does not work at all?
1.9.3.9 -> 2.2.6

**Comment by victor-v-rad** [comment]
Hi @kostia-lev 

1
There are three class-map.xml files
etc/commerce-to-commerce/class-map.xml.dist
etc/opensource-to-opensource/class-map.xml.dist
etc/opensource-to-commerce/class-map.xml.dist
Make sure you use the right one

2
Run the tool with -vvv option to show backtrace of the error. 

3
Also try to this format of xml
```
<rename>
        <from>ultramegamenu/category_attribute_source_categorylabel</from>
        <to/>
</rename>
```
instead of
```
<rename>
        <from>ultramegamenu/category_attribute_source_categorylabel</from>
        <to></to>
</rename>
```

**Comment by MustafaBaltee** [comment]
magento 2.3.3 contain only map.xml.dist and config.xml.dist
now i want to map the class here is the error
[2020-02-25 12:31:18][ERROR]: Incompatibility in data. Source document: eav_attribute. Field: source_model. Error: Class eav/entity_attribute_source_custom is not mapped in record attribute_id=563

here is my class-map.xml code

eav/entity_attribute_source_custom
Afg\Customerattribute\Model\Customer\Attribute\Source\Useurterm

and here is ther error
Invalid map filename: /chroot/home/a44491da/developer.americanfireglass.com/pub/afgtest/vendor/magento/data-migration-tool/etc/opensource-to-opensource/class-map.x
ml

i already removed .dist form config and map.xml
i any one know the solution please comment

**Comment by helmsmantest** [comment]
Hi, probably it would be helpful for somebody.
I added the following lines 
`<transform>
                <field>eav_attribute.backend_model</field>
                <handler class="\Migration\Handler\ClassMap" />
            </transform>
            <transform>
                <field>eav_attribute.attribute_model</field>
                <handler class="\Migration\Handler\ClassMap" />
            </transform>
            <transform>
                <field>eav_attribute.frontend_model</field>
                <handler class="\Migration\Handler\ClassMap" />
            </transform>`
to my map.xml file.
