### ISSUE TITLE
Class eclipsesettings/category_attribute_source_menutype does not exist but mentioned in: eav_attribute.source_model for attribute_id

### ISSUE THREAD

**Issue by saniyazahid** [magento/data-migration-tool#577]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by victor-v-rad** [comment]
find you solution in the documentation https://devdocs.magento.com/guides/v2.3/migration/migration-troubleshooting.html
