### ISSUE TITLE
Error: Source documents are not mapped core_store but they're ignored.

### ISSUE THREAD

**Issue by austevo** [magento/data-migration-tool#580]
Hi,

I'm trying to migrate from 1.7.0.2 to 2.2.3. Both databases reside on the same box. Below is output from migration.log

    [2018-08-26 11:13:41][WARNING]: Source documents are not mapped: 
    core_store,core_store_group,core_website
    [2018-08-26 11:13:41][WARNING]: Destination documents are not mapped: 
    store,store_group,store_website

I have core_store ignored in map.xml yet it's not making any difference.

I'm invoking the below command
`~/magento/scs/bin/magento migrate:settings -r -a /var/www/magento/scs/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.7.0.2/config.xml`

Any assistance is appreciated. Thanks.

**Comment by victor-v-rad** [comment]
Seems the same in #524 . Please look at my answers. It may help

**Comment by austevo** [comment]
Thanks Victor.

**Comment by victor-v-rad** [comment]
This error happens when M1 or M2 use prefix in tables name. Please add your prefix in config.xml file in tags
```
<source_prefix />
<dest_prefix />
```
