### ISSUE TITLE
Images marked as 'exclude' were not migrated

### ISSUE THREAD

**Issue by diazwatson** [magento/data-migration-tool#584]
Guys can you think of a reason why the information that defines an images as **exclude** are not migrated from Magento 1?
![space_48_backlog_-_agile_board_-_jira](https://user-images.githubusercontent.com/1080386/45080779-90ed2b00-b0ed-11e8-8815-252cc4b65d49.jpg)

**Comment by victor-v-rad** [comment]
Hi @diazwatson 

Similar issue was fixed in 2.2.5 ef2fc02 for Magento Commerce (EE)

**Comment by diazwatson** [comment]
Hi @victor-v-rad 
Do you think is worth to create a PR to fix in the others 2.2.x as well as 2.1.x versions?

**Comment by victor-v-rad** [comment]
We have only master and develop branches but every one can cherry pick ef2fc02 for their 2.2.x

**Comment by diazwatson** [comment]
Thanks
