### ISSUE TITLE
Unable to edit issues, issues don't display after migrating from 1.7.0.4 to 2.2.3

### ISSUE THREAD

**Issue by smilisav** [magento/data-migration-tool#585]
Hi,

I migrated settings and data successfully without errors. The products all show in the admin area, however editing them fails.

On the front end, they appear within the product category count, but no products appear. I've manually created a product and it works normally.

I get an ERROR 500 when attempting to edit.

Here's the error from system.log when attempting to view:
`[2018-09-05 12:22:54] main.INFO: Broken reference: the 'product.reviews' element cannot be added as child to 'product_tabs', because the latter doesn't exist [] []`

Any help is appreciated. Thanks.

**Comment by austevo** [comment]
Just noticed that applying the 'Migration_Default' attribute set to the manually created product breaks it. I now get a 500 error when trying to edit it.

I also get an error page when I check a product and select update attributes.

**Comment by victor-v-rad** [comment]
Hi @austevo 

Applying the 'Migration_Default' attribute set to the manually created product gives me 
> A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

error. Internal ticket MAGETWO-94903 to investigate it and fix

**Comment by victor-v-rad** [comment]
The issue is no longer reproducible on Magento CE and EE. Probably it was fixed in some other fix
