### ISSUE TITLE
Wrong URL addresses for products and categories

### ISSUE THREAD

**Issue by Serzhik** [magento/data-migration-tool#59]
After data migration of two different stores on Magento 1.9.2.0 and 1.9.2.1 all products and categories URLs has extra ".html".

Example:
Before migration: site.com/product.html, site.com/category.html;
After migration: site.com/product.html.html, site.com/category.html.html;

**Comment by andidhouse** [comment]
same here after migration from 1.7.0.2...

**Comment by Serzhik** [comment]
The problem is in `url_rewrite` table.
![heidisql_2016-02-01_16-42-48](https://cloud.githubusercontent.com/assets/2320879/12720368/3442330c-c903-11e5-81b8-e64f594e572b.png)

**Comment by Serzhik** [comment]
To fix it after migration run this query at MySQL:

`UPDATE url_rewrite SET request_path = REPLACE(request_path, '.html.html', '.html') WHERE request_path LIKE '%.html.html%';
UPDATE url_rewrite SET target_path = REPLACE(target_path, '.html.html', '.html') WHERE target_path LIKE '%.html.html%';`

**Comment by andidhouse** [comment]
Yes. another way is to totally truncate the url_rewrite database. Then on save of a product or category the table is regenerated (but you must save all products and categories to achieve this). Would be nice to fix this one in the tool...

**Comment by ilol** [comment]
@Serzhik did you resolve the issue? can close?

**Comment by ilol** [comment]
Thank you @andidhouse ! We are discussind your suggestion internally

**Comment by ilol** [comment]
MAGETWO-52158
