### ISSUE TITLE
Incremental migration(want to get products,categories etc since the last time migrated data)

### ISSUE THREAD

**Issue by wakar** [magento/data-migration-tool#591]
I've already migrated from Magento1 but after completed migration, I've added some more products on Magento1 site & also some customers have been added.

So I want to include those products,categories,customers,orders etc.

For that I'm using **"Delta migration"** command :- 

`php bin/magento migrate:delta  vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.8/config.xml`

**But getting below error:-**

```
  [Migration\Exception]
  XML file is invalid.

migrate:delta [-r|--reset] [-a|--auto] [--] <config>
```

Why I'm getting this ?please help me to resolve this issue.

**Note:-**

**1:-**  I'm using Magento2.2.5 & Magento1.9.3.8 version

**2:-** As per my R&D, by using delta migrfation we can't again migrate products,categories.is this right?please clarify me.

--
Thanks!!!

**Comment by victor-v-rad** [comment]
Hi @wakar 

Make sure your Magento 2 is in [Default mode](https://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html). 
Yes delta cannot migrate products/categories

**Comment by wakar** [comment]
thanks, Victor for the reply!
Means migration will work only in "default mode"?
I tried in "default mode" but got some new issues so simply I just migrate from the beginning in a new setup & then export & import remaining products, customers into my old migrated setup.
I think Magento team still needs to work on "Delta" Migration.
