### ISSUE TITLE
 Source documents are not mapped: Issue

### ISSUE THREAD

**Issue by wakar** [magento/data-migration-tool#592]
When I'm using:- 

 php bin/magento migrate:settings  vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.8/config.xml

Then getting following error:-

```
[2018-09-20 13:33:44][ERROR]: Source documents are not mapped: core_store,core_store_group,core_website
[2018-09-20 13:33:44][ERROR]: Destination documents are not mapped: store,store_group,store_website

  [Migration\Exception]
  Integrity Check failed
```

Already mapped this into file "map.xml.dist" like:- 

```
 <ignore>
                <document>core_store</document>
            </ignore>
```

Also R&D & apply various solution but it doesn't work.

I'm using fresh Magento2.2.5 version.& my Magento1 version is Magento1.9.3.8

Please help me to fix this issue.it's very urgent.

Thanks!!!

**Comment by victor-v-rad** [comment]
Seems the same in #524 . Please look at my answers. It may help

**Comment by victor-v-rad** [comment]
This error happens when M1 or M2 use prefix in tables name. Please add your prefix in config.xml file in tags
```
<source_prefix />
<dest_prefix />
```

**Comment by LouNik1984** [comment]
Hi, I have this error too, so I added the source prefix to config.xml (I don't have a destination prefix) and run migrate:settings with -r option to start the migration again but the error persists. Any clue on how to solve it?

**Comment by webspeaks** [comment]
I am having the same problem. We do not have the source prefix and dest_prefix but the issue still exists.

M1 version: 1.9.4.1

M2 version: 2.3.1

Any idea?

**Comment by victor-v-rad** [comment]
Check that source tag points to M1 and destination tag to M2

**Comment by webspeaks** [comment]
Sorry, my fault. The database credentials were wrong :(

**Comment by hufex** [comment]
I have the same issue.

php: 7.3 
database: mariadb 10.2.31
OS: linux 
source: 1.9.3.0 
destination: 2.3.4 

debug:

-bash-4.2$ bin/magento migrate:settings -r -a -vvv vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.0/config.xml.dist
Reset the current position of migration to start from the beginning

[2020-02-20 19:34:57][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
[2020-02-20 19:34:57][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
100% [============================] Remaining Time: < 1 sec
[2020-02-20 19:34:57][WARNING]: Source documents are not mapped: core_store,core_store_group,core_website
[2020-02-20 19:34:57][WARNING]: Destination documents are not mapped: store,store_group,store_website
[2020-02-20 19:34:57][INFO][mode: settings][stage: data migration][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
[2020-02-20 19:34:58][INFO][mode: settings][stage: data migration][step: Stores Step]: started
33% [=========>------------------] Remaining Time: < 1 sec
In AbstractFactory.php line 154:
                                                                                                        
  [UnexpectedValueException]                                                                            
  Invalid parameter configuration provided for $sourceDocument argument of Migration\RecordTransformer  
                                                                                                        

Exception trace:
 () at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:154
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:273
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/generated/code/Migration/RecordTransformerFactory.php:43
 Migration\RecordTransformerFactory->create() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/data-migration-tool/src/Migration/Step/Stores/Data.php:100
 Migration\Step\Stores\Data->perform() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:82
 Migration\Mode\AbstractMode->runStage() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/data-migration-tool/src/Migration/Mode/Settings.php:100
 Migration\Mode\Settings->runData() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/data-migration-tool/src/Migration/Mode/Settings.php:58
 Migration\Mode\Settings->run() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:59
 Migration\Console\MigrateSettingsCommand->execute() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/Interception/Interceptor.php:58
 Migration\Console\MigrateSettingsCommand\Interceptor->___callParent() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/Interception/Interceptor.php:138
 Migration\Console\MigrateSettingsCommand\Interceptor->Magento\Framework\Interception\{closure}() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/Interception/Interceptor.php:153
 Migration\Console\MigrateSettingsCommand\Interceptor->___callPlugins() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/generated/code/Migration/Console/MigrateSettingsCommand/Interceptor.php:104
 Migration\Console\MigrateSettingsCommand\Interceptor->run() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/symfony/console/Application.php:893
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/vhosts/20-pre.medikatalogo.com.mx/httpdocs/tienda/bin/magento:23


the only modifications I have made to the config.xml.dist file, are the connections and crypt_key, version 1.9.3.0 has no prefix in tables, previously the migration had already worked, delete everything and install again

can someone give me a help that can be, I have 3 days with this problem. thanks
