### ISSUE TITLE
Magento 2.2.5 - First Name is not visible in Shipping and Billing Address After Migrating from magento 1.9.3.7 to Magento 2.2.5

### ISSUE THREAD

**Issue by Usman1493** [magento/data-migration-tool#594]
### Preconditions

1. Magento 1 (Version 1.9.3.7)
2. Magento 2 (Version 2.2.5)
3. PHP 7.0.2
4. MySQL 5.7

### Steps to reproduce

1. Migration from magento 1 to magento 2
2. Create a customer account
3. Place an order.
4. Reuse saved/default billing or shipping address for next order

![screenshot from 2018-09-25 12-40-07](https://user-images.githubusercontent.com/30326249/46017943-2169ca80-c0f2-11e8-93ed-b431340be65d.png)

When, the customer use a new address. It allows the user to place an order without any error as follows:

It can be seen that First name is present in this case... 

![screenshot from 2018-09-25 10-56-47](https://user-images.githubusercontent.com/30326249/46017987-3fcfc600-c0f2-11e8-80e3-0078893aee1e.png)

I have checked the database and It has the first name saved. But on front end it doesn't display the first name in billing and shipping address as follows:

![screenshot from 2018-09-25 12-48-16](https://user-images.githubusercontent.com/30326249/46018013-5249ff80-c0f2-11e8-9bd1-aa1afa8f9fea.png)

I have also tried editing the default billing and shipping address and when I press the edit button the first name field is empty. I tried to fill the first name field and saved the address, but still it is not displaying the first name.

The next time I press edit button the first name field stays empty as follows:

![screenshot from 2018-09-25 12-46-30](https://user-images.githubusercontent.com/30326249/46018033-6130b200-c0f2-11e8-9694-f9cbdcb82ed8.png)

### Expected result

1. Successfully placed the order

### Actual result

1. 
![screenshot from 2018-09-25 12-40-07](https://user-images.githubusercontent.com/30326249/46018083-81607100-c0f2-11e8-9cc9-f3673185ca69.png)

**Comment by victor-v-rad** [comment]
Hi @Usman1493 

I have tried to reproduce scenario you described but first name works fine in my instance. I will try to research it more

**Comment by Usman1493** [comment]
Hi @victor-v-rad .. I have checked my database as well and firstname is present there..
I checked in these tables:
```
 customer_address_entity

 quote_address

 sales_order_address
```
What could be the reason that in Billing and Shipping address magento is not retrieving the first name?

**Comment by victor-v-rad** [comment]
Maybe it has something to do with theme, Try default Luma theme

**Comment by Usman1493** [comment]
Hey @victor-v-rad.. I have tested the same data with the default `luma theme` and its still showing the same output..` First name is still not visible with shipping and billing address`. So, it has to do with the data.... Waiting for your response on this matter.

![screenshot from 2018-10-03 12-50-46](https://user-images.githubusercontent.com/30326249/46397194-fe02d900-c70a-11e8-89aa-d8e479dad026.png)
