### ISSUE TITLE
Product's Images' URLs are not same after migrating from Magento 1.9 to Magento 2.2

### ISSUE THREAD

**Issue by Knight017** [magento/data-migration-tool#597]
### Preconditions

1. Migration from Magento 1.9 to 2.2 using data-migration-tool
2. Windows 10, XAMPP, PHP 7.1.9 (I know it is not recommended but have to use.)

### Steps to reproduce

1.  Migrated `Magento 1.9.2.3` to `Magento 2.2.3` and after migration, copy the Magento 1's `media/catalog` directory to Magento 2.2's `pub/media/catalog` directory.

2. Fire following commands.

> rm -rf pub/static/* var/di/* var/cache/* var/page_cache/* generated/* var/view_preprocessed/* && php -dmemory_limit=6G bin/magento setup:upgrade && php -dmemory_limit=6G bin/magento setup:static-content:deploy -f

The images on category and product pages are visible now, but they have different URLs which will affect SEO very badly.

### Expected result

1. Product image URLs must be same.like
**Expected Image URLs example** 

> Magento 1.9 url: http://www.domain1.com/media/catalog/product/cache/1/thumbnail/543x403/qwer751fc24f39b632cb88e6c5925d9b/p/r/pr_img01.jpg

> Magento 2.2 url:http://www.domain1.com/media/catalog/product/cache/1/thumbnail/543x403/qwer751fc24f39b632cb88e6c5925d9b/p/r/pr_img01.jpg

### Actual result

1. They have different URLs which will affect SEO.

**Actual Image URLs example** 

> Magento 1.9 url: http://www.domain1.com/media/catalog/product/cache/1/thumbnail/543x403/qwer751fc24f39b632cb88e6c5925d9b/p/r/pr_img01.jpg

> Magento 2.2 url:http://magento2.devdomain.com/pub/media/catalog/product/cache/23577479b544d65e11d54d23e4df6b67/p/r/pr_img01.jpg

 
### Additional notes
As these images are crawled by search engines if the product image URL changes it will affect the site's SEO very badly.

I have added these issue in StackOverflow also [
Product's Images' URLs are not same after migrating from Magento 1.9 to Magento 2.2
](https://magento.stackexchange.com/questions/244809/products-images-urls-are-not-same-after-migrating-from-magento-1-9-to-magento)

Thank you.

**Comment by victor-v-rad** [comment]
Hi @Knight017 

It likely will affect SEO of image search but web search of html pages should be ok. Though I am not an expert in SEO
