### ISSUE TITLE
Unable to unserialize value Magento 1.9.3.0 to 2.2.6

### ISSUE THREAD

**Issue by venkat-korampalli** [magento/data-migration-tool#600]
Preconditions
1. Magento 1.9.3.0
2. Magento 2.2.6
3. Data Migration Tool v2.2.6
4. PHP 7.1.x

Steps to reproduce
1. Run settings migration (success)
2. Run data migration (success with Data type warnings)

Expected result
Migration Successfully Completed with out errors

Actual result
Add to Cart, Order View, Customer Dashboard getting errors.
1. Exception #0 (InvalidArgumentException): Unable to unserialize value.
2. /vendor/magento/framework/Model/ResourceModel/AbstractResource.php(153): Magento\Framework\Serialize\Serializer\Json->unserialize('a:1:{s:15:"info...')

Additional notes
I've gone through the below link: but no luck
https://github.com/magento/data-migration-tool/issues/401

And I've fixed Json.php file with below link, After adding this code I'm able to see pages, but still too many errors. 1. Cart rules conditions and Actions are not populating with M1 values. 2. Order View payment information not showing. 3. Product attributes are not displaying in order view page in admin panel for old orders. 
https://gist.github.com/manojind/9f18bbecaeb3e2bbfb056a634ade62a2

**Comment by victor-v-rad** [comment]
Hi @venkat-korampalli 

Can you trace what table and field contain serialized value?

**Comment by venkat-korampalli** [comment]
Hello @victor-v-rad ,

Thanks for the reply. after a couple of sleepless nights we're able to migrate the data successfully. It appears all the has been migrated successfully. We are currently validating the data against to M1.

Below are the few observations i would like to share with you:

1. All the product attributes appended with "Migration_"

2. We had an issue with configurable product prices. It is displaying as "As low as $0". We have made reindex, cache clean, cleaning var folder multiple times. But nothing seems to be worked out. After selecting any attribute it is showing correct price. Not sure is this a feature or bug? Could you please help us to fix this issue? 
![screen1](https://user-images.githubusercontent.com/13692132/47194857-aef9ac80-d376-11e8-9c4e-a49ff79fee7f.png)

**Comment by victor-v-rad** [comment]
Maybe simple products which are linked to configurable have special prices 0 or with negative value

**Comment by venkat-korampalli** [comment]
Thanks for the quick reply. 

I will check it and respond. just for curiosity why this issue not exists in current M1 store? any ideas? 

It is the same data we imported to M2.

**Comment by venkat-korampalli** [comment]
Hi @victor-v-rad ,

No special prices configured for simple products. below is screen shots in M1 and M2. Any thoughts?

![special-price](https://user-images.githubusercontent.com/13692132/47341498-c9a58b80-d6be-11e8-9918-0b3d585fd3a4.png)
![special-price-m1](https://user-images.githubusercontent.com/13692132/47341499-c9a58b80-d6be-11e8-9111-a129ac8c2aa7.png)

**Comment by victor-v-rad** [comment]
You mean attributes "Price for General Group", "Price for Wholesale - Small Group", "Price for Corporate Group" are missing in M2 after migration?

**Comment by victor-v-rad** [comment]
I see "Special Price From Date" is migrated

**Comment by venkat-korampalli** [comment]
Thanks for the reply. Yes, these attributes no longer required in M2.

**Comment by venkat-korampalli** [comment]
seems to be we are facing the same issue like below, but this solution not working for me.  "catalog_product_entity_decimal" has valid data.

https://magento.stackexchange.com/questions/187780/magento-2-configurable-product-price-in-frontend-0-00-backend-is-ok

**Comment by victor-v-rad** [comment]
https://docs.magento.com/m2/ce/user_guide/catalog/product-price-group.html
>Customer group prices are a component of tier pricing

Look into tier pricing. Are group prices there?

**Comment by venkat-korampalli** [comment]
Yes group prices are exists  in M1, We haven't yet integrated group prices in M2.

**Comment by victor-v-rad** [comment]
If you open "Advanced Pricing" on product edit page of migrated product you should see your group prices

**Comment by venkat-korampalli** [comment]
HI @victor-v-rad 

I've fixed this below way.. Not sure is this correct/valid fix.

Followed the below link, and over ridden a file, this fixed $0 price for configurable products.. but still "As low as" label displaying

https://magento.stackexchange.com/questions/135513/how-magento-getting-configurable-product-lowest-price-of-associated-products

After I've updated final_price.phtml as per my requirement (removed "As low as" related code) from module-configurable-product module.

In Magento 1.x price related code executed from one phtml file, where as in M2 price from two files (different files for Simple and Configurable products).. I'm not sure is this a special feature of Magento 2.x

Hope this will helps some one...
