### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Eav\Model\Entity\Attribute\Source\Config::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by guarinogabriel** [magento/data-migration-tool#601]
### Preconditions

1. Magento 1.9.3.9
2. Magento 2.2.6
3. PHP 7.1.21
4. MySQL 5.7
5. Environment: MacOS with Valet Plus
6. Magento 1 database with custom customer EAV attribute

### Steps to reproduce
1. Ignore the custom customer EAV attribute in the `eav-attribute-groups.xml` file as follows:
![ignore updated](https://user-images.githubusercontent.com/1928452/46897573-dbcf3080-ce59-11e8-8b45-ae1f822b0f27.png)

1. Run the migration using the following command:
`sudo php bin/magento migrate:data -r -a -vvv /path/to/magento2-root/vendor/magento/data-migration-tool/etc/opensource-to-commerce/1.9.3.9/config.xml`

### Expected result

1. The migration works properly and the ignored custom customer EAV attribute is not migrated to the Magento 2 database

### Actual result
1. The custom customer EAV attribute is migrated and it generates the following error in the "Customer Edit" page in the admin panel _(admin/customer/index/edit/id/8/)_:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Eav\Model\Entity\Attribute\Source\Config::__construct() must be of the type array, null given,
called in /Users/gabriel/Projects/m2-migration/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /Users/gabriel/Projects/m2-migration/vendor/magento/module-eav/Model/Entity/Attribute/Source/Config.php:26
Stack trace:
#0 /Users/gabriel/Projects/m2-migration/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Eav\Model\Entity\Attribute\Source\Config->__construct(NULL)
#1 /Users/gabriel/Projects/m2-migration/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Eav\\Mod...', Array)
#2 /Users/gabriel/Projects/m2-migration/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Eav\\Mod...', Array) #3 /Users/gabriel/Projects/m2-migration/vendor/magent in /Users/gabriel/Projects/m2-migration/vendor/magento/module-eav/Model/Entity/Attribute/Source/Config.php on line 26
```

**Comment by guarinogabriel** [comment]
Hi @victor-v-rad,

Any thoughts regarding the issue we are experiencing with the Data Migration Tool?

Regards,
Gabriel

**Comment by victor-v-rad** [comment]
Hi @guarinogabriel 

I created a new customer attribute and assigned to a customer in a store running on Magento Commerce 1.14.3.1. While migration, the attribute was deleted through the tool (in eav-document-groups.xml file). On the Customer Edit page  in Admin Panel of Magento 2.2.6 I got no errors like you have. But you have Magento Community 1.9.3.9 and the customer attribute probably from some extension.

**Comment by guarinogabriel** [comment]
Hi @victor-v-rad,

Shouldn't the custom customer attribute be excluded from the migration as well?

The custom attribute is breaking the customer edit page in the admin panel and we are looking to prevent that attribute from being migrated to Magento 2.

What is the best path to accomplish that with the data migration tool?

Regards.
Gabriel

**Comment by victor-v-rad** [comment]
> Shouldn't the custom customer attribute be excluded from the migration as well?

Yes the tool excludes the attribute and its data. That I found is that eav_attribute_option_value table in M2 contains options of excluded attribute. Not sure it can cause error you have

**Comment by guarinogabriel** [comment]
Thanks for the feedback @victor-v-rad, I confirm that I was able to resolve the issue.

The only pending issue to resolve that we have in our migration is the following:
https://github.com/magento/data-migration-tool/issues/602

Thanks again.
