### ISSUE TITLE
URL key for products is not migrated to Magento 2

### ISSUE THREAD

**Issue by guarinogabriel** [magento/data-migration-tool#602]
### Preconditions

1. Magento 1.9.3.9
2. Magento 2.2.6
3. PHP 7.1.21
4. MySQL 5.7
5. Environment: MacOS with Valet Plus

### Steps to reproduce
1. Run the migration using the following command:
`sudo php bin/magento migrate:data -r -a -vvv /path/to/magento2-root/vendor/magento/data-migration-tool/etc/opensource-to-commerce/1.9.3.9/config.xml`

### Expected result

1. The migration works properly and the URL keys are migrated for all products, and the URL key for products in Magento 1 and Magento 2 is the same

### Actual result
1. The URL keys for products in Magento 1 and Magento 2 are different and contain special characters.

Example - Product in Magento 1:
![m1](https://user-images.githubusercontent.com/1928452/47105125-72fd0500-d219-11e8-8b7f-a9b3fbdf9ae2.png)

Example - Same product in Magento 2 after migration:
![m2](https://user-images.githubusercontent.com/1928452/47105171-8f00a680-d219-11e8-9834-5a2b88f990cb.png)

After saving the product in the Magento 2 admin panel, the URL is key is fixed by Magento but it is not the same URL key than Magento 1:
![m2-2](https://user-images.githubusercontent.com/1928452/47105231-b8213700-d219-11e8-9ff8-168ce50aefdc.png)

**Comment by guarinogabriel** [comment]
@victor-v-rad - What are your thoughts regarding this issue with the URL keys?

**Comment by victor-v-rad** [comment]
Not sure if this #541 is related, but in M2 try to remove data of url_path attribute for this product in catalog_product_entity_varchar table. Clear cache and see if it helped

**Comment by guarinogabriel** [comment]
@victor-v-rad - After removing the URL path for the product and clearing cache, the URL key in the admin panel for the product is empty. After saving the product, the URL key is re-generated but it is different than the original one from Magento 1.

Is there anything in the data migration tool that could cause this behavior?

**Comment by guarinogabriel** [comment]
Closing this issue since it has been resolved. Thanks.
