### ISSUE TITLE
Install data-migration-tool 2.2.6 Problem

### ISSUE THREAD

**Issue by RedDevilEvo** [magento/data-migration-tool#603]
Hi guys, i've some problem to install the Migration-Tool.   I don't know why I have that error. But, I know there is a 2.2.6 version for the Migration-Tool   

Thanks for your help.

> 
> composer config repositories.data-migration-tool git https://github.com/magento/data-migration-tool
> composer require magento/data-migration-tool:2.2.6
> 

![tabarnak_hide](https://user-images.githubusercontent.com/27022907/47309898-9b16aa80-d603-11e8-81be-59a87a5f7965.PNG)

**Comment by victor-v-rad** [comment]
Is your Magento version 2.1.7? If so, then try to use Magento 2.2.6

**Comment by RedDevilEvo** [comment]
> 
> 
> Is your Magento version 2.1.7? If so, then try to use Magento 2.2.6

In my dashboard panel in Magento i have 2.1.7 after any update the 2.1.7 never changed. 
I dont know why.
![2 1 7](https://user-images.githubusercontent.com/27022907/47366634-1c297c80-d6ac-11e8-8254-ae49b08dbc03.PNG)

In the composer i have 2.2.6 and if you take a look on the original post i've tried to install it with 2.2.6

![composer](https://user-images.githubusercontent.com/27022907/47366651-20ee3080-d6ac-11e8-8949-5a038205b6a0.PNG)

**Comment by victor-v-rad** [comment]
> after any update the 2.1.7 never changed.

Magento 2 should be empty with no entities (customers, products, etc.) before migration. Can you install fresh new Magento 2.2.6 and try to migrate?

**Comment by RedDevilEvo** [comment]
I did a new install with Magento 2.1.7 and i had no problem to install.
 
Thanks
