### ISSUE TITLE
What should my next step be?

### ISSUE THREAD

**Issue by niners52** [magento/data-migration-tool#604]
In May I was able to successfully migrate a Magento 1 to Magento 2 site. I have been developing on that site since then. I am now at a point where I need to go live. So I need to move over all data and changes since May. Because of the amount of changes moving the delta is not an option. I only want to move products, customers, and orders. I have tried clearing data- https://www.titechglobal.com/magento-2-x-how-to-clear-test-data-before-production/ but so far it has not worked. What would you recommend?

**Comment by victor-v-rad** [comment]
It is recommended to do first time migration from M1 DB copy for testing purpose and fix issues. After, do migration all over again but from life DB

**Comment by niners52** [comment]
When I use the exact same settings to do the migration it no longer works. I just get a lot of errors.
