### ISSUE TITLE
1.9.3.3 To 2.1.7  '' 3 issues ''

### ISSUE THREAD

**Issue by RedDevilEvo** [magento/data-migration-tool#605]
Hi there,

I did a fresh install of Magento 2.1.7 and i added the Migration-Tool with no issues.
I did no modification in Magento everything was brand new.

My old Magento version is 1.9.3.3 from another server. 
 
I did the migration of settings and data. 

I have 3 issues. 

**1 - After Migration i can't log into my Magento Admin panel.
I've created a new admin user with SSH and still can't log.** 

**2 - My new magento look all stretched.
No it's not the same template as M1 maybe the settings migration did some thing to my new M2 template.**

 
**3 - Nothing seem to have migrated. And there is nothing new in M2 front end.. i can't tell in back end i do not have acess** 

[2018-11-05 18:43:18][ERROR]: Source documents are not mapped:
[2018-11-05 18:42:57][ERROR]: Source fields are not mapped.
[2018-11-05 18:43:18][ERROR]: Source documents are not mapped:

![1](https://user-images.githubusercontent.com/27022907/48021697-38df9e80-e107-11e8-9a14-7e8297bdfe9a.PNG)

Thanks for your help and time.

**Comment by RedDevilEvo** [comment]
After a big headhash i've took a look on all the red parts.

_I dont mind for thoses, they are almost all old pluggins or addons and i dont want it._
**[ERROR]: Source documents are not mapped:**
**[ERROR]: Foreign key (magento_ch_canadapost_quote_param_ibfk_1) constraint fails.**


_I'm not 100% sure for all of those one._
**[ERROR]: Destination documents are not mapped:** 


_But i still have some question who need  answers.._

 **1 -   Why i can't log into my Magento admin panel** 

**2 - Why it seem to have nothing new in my M2 other than my template is broken and i can't access admin panel**

**3 - All i want is my : data base, products , inventory,SKU,descriptions customers, price and tax , settings. Just the basic stuff.  I do not have 10000000 products ,i have around 1000 product and 6000 costumers it should be simple no?**

**4 - If i look into phpMyAdmin there is nothing new.. my customers .. products .. and anything else have not migrated.**

**_Thanks for your help and time._**


**SORRY FOR MY POOR ENGLISH I SPEAK FRENCH I DO MY BEST THANKS GUYS,**

**Comment by victor-v-rad** [comment]
Hi @RedDevilEvo 

Is it possible for you to use the latest Magento 2.2.6 and the tool 2.2.6. It contains many bugfix, so your issues might have already been solved.

**Comment by RedDevilEvo** [comment]
Last time i've tried with 2.2.6 i could not install the Migration-tool you sugest me to try a fresh install. My template use 2.1.7 and if i upgrade it to 2.2.6 it do not update correctly. 

I'm pretty sure i will have problem if i took a fresh install of 2.2.6.  Migrate my stuff and after install my template.  

![c8497f76-bde5-4f8d-b224-7da9998e0650](https://user-images.githubusercontent.com/27022907/48065041-991e2100-e197-11e8-882f-f0aacb1bf6bd.png)

**Comment by RedDevilEvo** [comment]
Ok now i did a fresh install of Magento 2.2.6 with a new DB.

Magento-Migration-tool installed with sucess.

Now i just tried do migrate data and i face that error.

![2](https://user-images.githubusercontent.com/27022907/48084602-2d9f7800-e1c6-11e8-8aa0-06091e51e3f2.PNG)

**Comment by victor-v-rad** [comment]
Are your tables with prefix in DB of M1 or M2?
If so, indicate it in your config.xml 
```
        <source_prefix />
        <dest_prefix />
```
Also to exclude issues with cache, make fresh install of Magento to different folder or remove old folder before installing M2

**Comment by RedDevilEvo** [comment]
Thanks a lot @victor-v-rad for your help and time it's very appreciated.

I did the change with the prefix

**Comment by RedDevilEvo** [comment]
Hi @victor-v-rad 

I think we are near a victory but i still need your help please. 

Now i have that.

>  [ERROR]: Record structure does not contain field psearch_priority

I did a brand new install of Magento 2.2.6 new database with config prefix ajusted

Theres is only that magento in the server and everything should be A1 for the install. 




The command i did 

>.......com [~/public_html]# php bin/magento migrate:data   /home/......./public_html/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.3/config.xml
![38](https://user-images.githubusercontent.com/27022907/48186504-241d2980-e306-11e8-84e4-ce796e48c609.PNG)



>.......com [~/public_html]# php bin/magento migrate:data -a  /home/......./public_html/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.3/config.xml
![39](https://user-images.githubusercontent.com/27022907/48186558-529b0480-e306-11e8-8bc6-03cdc352686f.PNG)
![36](https://user-images.githubusercontent.com/27022907/48184829-2761e680-e301-11e8-9661-90d769043ce7.PNG)





All yellow or red = future error ?
![37](https://user-images.githubusercontent.com/27022907/48185979-a7d61680-e304-11e8-810e-8fe3ccb8e490.PNG)


I'm still looking if anybody else had that issues but if you could help it would be great.

**Comment by victor-v-rad** [comment]
try this fix 13728b3 for
>[ERROR]: Record structure does not contain field psearch_priority

**Comment by RedDevilEvo** [comment]
@victor-v-rad   Thank you for your fast reply. 

I did your fix and now i still have that in yellow. Is this normal ? 
![41](https://user-images.githubusercontent.com/27022907/48189190-98a79680-e30d-11e8-8b41-d7f4e6497f2a.PNG)

And also. 
> 
.......com [~/public_html]# php bin/magento migrate:data -a /home/......./public_html/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.3/config.xml

![40](https://user-images.githubusercontent.com/27022907/48188919-df48c100-e30c-11e8-86dd-d2f5abf0bef3.PNG)

 **_Meigee Blacknwhite   = My old template      I dont want to keep it
 chcanpost2module    = Canada Post addon. I dont want to keep it_**




**_Correct me if i'm wrong but i think i have to '' ignore " those files in the eav-attribute-groups.xml.dist.
**

 
### That's my eav-attibute-groups.xml.dist files
```
 <?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<groups xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../groups.xsd">
    <group name="ignore">
        <attribute type="catalog_product">msrp_enabled</attribute>
        <attribute type="catalog_product">group_price</attribute>
    </group>
    <group name="frontend_input_empty_allowed">
        <attribute type="catalog_product">samples_title</attribute>
        <attribute type="catalog_product">links_title</attribute>
        <attribute type="catalog_product">links_exist</attribute>
        <attribute type="catalog_product">links_purchased_separately</attribute>
        <attribute type="catalog_product">old_id</attribute>
        <attribute type="catalog_product">price_type</attribute>
        <attribute type="catalog_product">sku_type</attribute>
        <attribute type="catalog_product">weight_type</attribute>
        <attribute type="catalog_product">shipment_type</attribute>
        <attribute type="catalog_product">url_path</attribute>
        <attribute type="catalog_category">url_path</attribute>
        <attribute type="catalog_category">path</attribute>
        <attribute type="catalog_category">path_in_store</attribute>
        <attribute type="catalog_category">position</attribute>
        <attribute type="catalog_category">level</attribute>
        <attribute type="catalog_category">all_children</attribute>
        <attribute type="catalog_category">children</attribute>
        <attribute type="catalog_category">children_count</attribute>
        <attribute type="order">currency_rate</attribute>
        <attribute type="order">tax_percent</attribute>
        <attribute type="order">currency_base_id</attribute>
        <attribute type="order">real_order_id</attribute>
        <attribute type="order">currency_code</attribute>
        <attribute type="order_item">qty</attribute>
        <attribute type="order_item">tier_price</attribute>
        <attribute type="order_item">model</attribute>
        <attribute type="order_address">address_id</attribute>
        <attribute type="order_address">tax_id</attribute>
        <attribute type="order_payment">cc_raw_request</attribute>
        <attribute type="order_payment">cc_raw_response</attribute>
        <attribute type="order_status">status</attribute>
        <attribute type="order_status">comments</attribute>
    </group>
</groups>
```
### I'm not 100% sure how i should wrote those lines
```
<groups xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../groups.xsd">
    <group name="ignore">
        <attribute type="catalog_product">msrp_enabled</attribute>
        <attribute type="catalog_product">group_price</attribute>
    </group>
```

### Things that i want to ignore 
```
Class Meigee_CategoriesEnhanced/category_attribute_source_block_grid does not exist but mentioned in: eav_attribute.source_model for attribute_id=1
Class Meigee_CategoriesEnhanced/category_attribute_source_block_ratio does not exist but mentioned in: eav_attribute.source_model for attribute_id=
Class Meigee_CategoriesEnhanced/category_attribute_source_block_labels does not exist but mentioned in: eav_attribute.source_model for attribute_id
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
 Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisablelight does not exist but mentioned in: eav_attribute.source_model for
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_bg does not exist but mentioned in: eav_attribute.source_model for attribute_id=157
Class Meigee_CategoriesEnhanced/category_attribute_source_block_menutype does not exist but mentioned in: eav_attribute.source_model for attribute_
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
Class Meigee_CategoriesEnhanced/category_attribute_source_block_enabledisable does not exist but mentioned in: eav_attribute.source_model for attri
 Class ThemeOptionsBlacknwhite/attribute_source_type does not exist but mentioned in: eav_attribute.source_model for attribute_id=163
 Class ThemeOptionsBlacknwhite/attribute_source_productlayout does not exist but mentioned in: eav_attribute.source_model for attribute_id=164
Class ThemeOptionsBlacknwhite/attribute_source_type does not exist but mentioned in: eav_attribute.source_model for attribute_id=165
 Class ThemeOptionsBlacknwhite/attribute_source_slider does not exist but mentioned in: eav_attribute.source_model for attribute_id=166
 Class ThemeOptionsBlacknwhite/attribute_source_slider does not exist but mentioned in: eav_attribute.source_model for attribute_id=167
Class ThemeOptionsBlacknwhite/attribute_source_relatedpos does not exist but mentioned in: eav_attribute.source_model for attribute_id=168
Class ThemeOptionsBlacknwhite/attribute_source_collateral does not exist but mentioned in: eav_attribute.source_model for attribute_id=169
Class ThemeOptionsBlacknwhite/attribute_source_productimg does not exist but mentioned in: eav_attribute.source_model for attribute_id=173
Class ThemeOptionsBlacknwhite/attribute_source_type does not exist but mentioned in: eav_attribute.source_model for attribute_id=174
Class ThemeOptionsBlacknwhite/attribute_source_type does not exist but mentioned in: eav_attribute.source_model for attribute_id=175
Class ThemeOptionsBlacknwhite/attribute_source_type does not exist but mentioned in: eav_attribute.source_model for attribute_id=176
 Class ThemeOptionsBlacknwhite/attribute_source_brandpos does not exist but mentioned in: eav_attribute.source_model for attribute_id=177
Class ThemeOptionsBlacknwhite/attribute_source_productsidebar does not exist but mentioned in: eav_attribute.source_model for attribute_id=178
 Class chcanpost2module/catalog_product_attribute_source_method does not exist but mentioned in: eav_attribute.source_model for attribute_id=194
```

Thanks again for your time and help @victor-v-rad you are a legend.

**Comment by RedDevilEvo** [comment]
Ok now i figured out how to ignore 70% of the error i had. But i dont know why now i'm stuck with those one.. 

**They do not want to be ignore.** 

### Errors
![43](https://user-images.githubusercontent.com/27022907/48285492-c5080380-e430-11e8-91f9-8a68c023fdba.PNG)

### ID in the SQL 
![42](https://user-images.githubusercontent.com/27022907/48285525-dd781e00-e430-11e8-8e6c-d5bba7677438.PNG)

![44](https://user-images.githubusercontent.com/27022907/48285773-a2c2b580-e431-11e8-9d03-e6c52f36a986.PNG)


### My eav-attribute-groups.xml.dist
![46](https://user-images.githubusercontent.com/27022907/48285962-28defc00-e432-11e8-9376-2bbddf0dc6d7.PNG)

**Comment by RedDevilEvo** [comment]
Ok i figured out ! It was the EAV entity types.

![47](https://user-images.githubusercontent.com/27022907/48288119-0e5c5100-e439-11e8-8d66-732361879b31.PNG)

**Comment by RedDevilEvo** [comment]
I finaly passed trough all errors and i finished the Migration! 

Thank you verry much @victor-v-rad  for your help.

**Comment by victor-v-rad** [comment]
Great! Good to know
