### ISSUE TITLE
Different increment id after migration?

### ISSUE THREAD

**Issue by Desmaster** [magento/data-migration-tool#61]
Getting really close to a flawless migration. 
Today I stumbled upon the following case..

My latest order `increment id` in the source database is `400001429`. Successfully migrated settings and data from source to Magento 2 database. Created new order in Magento 2, order `increment id` seems to be `4000001430`. 

Now I want to see the order in my admin order grid. Couldn't find new order, as it's sorting the orders by `increment id`, *descending*. 
After sorting it by **Purchase Date**, it's sorting properly again:

![after-import](https://cloud.githubusercontent.com/assets/1165302/13149093/6a1c25ea-d660-11e5-93ee-069e41470a76.png)

Why does the migration tool change the last order `increment id`? And would it be possible to skip the change?

**Comment by victor-v-rad** [comment]
Hi,

It is new policy of increment id in Magento 2. The [official doc](http://devdocs.magento.com/guides/v2.0/migration/migration-migrate-additional.html)

**Comment by ilol** [comment]
@Desmaster can you close? Thanks

**Comment by Nehace40** [comment]
@victor-v-rad  link is not working can you please provide working link?

**Comment by C4rter** [comment]
Can somebody explain this a bit more detailed? The link isn't working and I don't understand why increment ids that are created after a migration are now 10 digits long (despite the pattern in module-sales-sequence/Model/Sequence.php still saying 9).
They are only 9 digits in a fresh installation and in Magento 1 as well.
