### ISSUE TITLE
Record structure does not contain field is_visible_on_front

### ISSUE THREAD

**Issue by niners52** [magento/data-migration-tool#610]
I am trying to migrate a Magento 1 install into a clean Magento 2 install. This is 1.9.3.1 to 2.2.6. I get this error-
100% [============================] Remaining Time: < 1 sec
[2018-11-07 21:25:29][INFO][mode: data][stage: data migration][step: EAV Step]: started
57% [================>-----------] Remaining Time: 1 sec
[2018-11-07 21:25:30][ERROR]: Record structure does not contain field is_visible_on_front
[2018-11-07 21:25:30][INFO][mode: data][stage: data migration][step: EAV Step]: Error occurred. Rollback.
[2018-11-07 21:25:30][INFO][mode: data][stage: data migration][step: EAV Step]: EAV Step: rollback
[2018-11-07 21:25:30][INFO][mode: data][stage: data migration][step: EAV Step]: Please fix errors and run Migration Tool again
                         
  [Migration\Exception]  
  Data Migration failed  
                         

Exception trace:
 () at /var/www/html/transfer/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:121
 Migration\Mode\Data->runData() at /var/www/html/transfer/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /var/www/html/transfer/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /var/www/html/transfer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at /var/www/html/transfer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/transfer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /var/www/html/transfer/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /var/www/html/transfer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/html/transfer/bin/magento:23

migrate:data [-r|--reset] [-a|--auto] [--] <config>

is_visible_on_front seems important I am not sure if ignore is the best option here.

**Comment by victor-v-rad** [comment]
Hi @niners52 

Please try this fix 13728b3
Duplicate #595

**Comment by kostia-lev** [comment]
data-migration-tool v.: 2.2.6
1.9.3.9 -> 2.2.6
vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.9/map.xml.dist:
...

            <ignore>
                <field>mailchimp_ecommerce_sync_data.mailchimp_sync_modified</field>
            </ignore>
            <ignore>
                <field>newsletter_subscriber.mailchimp_sync_modified</field>
            </ignore>
...
config.xml:
        <map_file>etc/opensource-to-opensource/1.9.3.9/map.xml.dist</map_file>

[2018-11-24 19:16:32][DEBUG][mode: data][stage: data migration][step: Map Step][table: newsletter_subscriber]: migrating
0% [>---------------------------] Remaining Time: < 1 sec
[2018-11-24 19:16:32][ERROR]: Record structure does not contain field mailchimp_sync_modified
                         
  [Migration\Exception]  
  Data Migration failed  
                         

Exception trace:
 () at /root/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:121
 Migration\Mode\Data->runData() at /root/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /root/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /root/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /root/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /root/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /root/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /root/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /root/bin/magento:23

**Comment by victor-v-rad** [comment]
Please try this fix 13728b3

**Comment by gerym77** [comment]
similar problem here:
[2018-12-03 17:52:53][ERROR]: Record structure does not contain field is_visible_on_checkout

added to ignore tag in map-eav.xml
map.eav.xml defined in config.xml

after fix 13728b3

new error message:
[Exception]                                                                                                                                                       
Notice: Undefined offset: 150 in /home/shop/magento/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 813

Opened new issue #621

**Comment by ramsampathi** [comment]
Hi @victor-v-rad,
Magento1 - 1.9.2.4
Magento2 - 2.2.6
i got the same issue like

[Exception]
  Notice: Undefined offset: 1 in /home/devserve/public_html/thordsenv2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291

and

[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

I tried with many times with new setup but it throws an same errors
please help on this.
Thanks,

**Comment by joakimmag** [comment]
I have the same error as the OP. How do you apply the fix, @victor-v-rad?
Version 1.9.3.4 -> 2.2.6.

**Comment by victor-v-rad** [comment]
it was fixed in 2.2.7. please try it
