### ISSUE TITLE
PayPal sandbox issue

### ISSUE THREAD

**Issue by cscd98** [magento/data-migration-tool#611]
In M1, with the same paypal credentials you are able to switch to sandbox mode and purchase with sandbox paypal. However, in M2, this does not appear to work.

Is it necessary to replace live paypal credentials with sandbox api details? This was not needed in M1.

If that is the case, then feel free to close this issue..

1. Magento 1.14.3.10
2. Magento 2.2.6
3. PHP 7.1.23
4. MySQL 5.7.24

### Steps to reproduce
1. Convert DB from M1 to M2
2. Set PayPal Express Checkout to Sandbox Mode -> Yes
3. Add to basket, click on PayPal Express Checkout, Click on Continue to PayPal
4. User is re-directed to basket, with error message: 'PayPal gateway has rejected request. Security header is not valid (#10002: Security error).'
5. Set Sandbox Mode to No
6. This works as intended.

### Expected result
1. Re-direction to PayPal sandbox - https://www.sandbox.paypal.com

### Actual result
1. PayPal gateway has rejected request. Security header is not valid (#10002: Security error).

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 

M2 may use different PayPay API then it is in M1. Does M1 live paypal credentials work properly and users can use PayPal Express Checkout on M2 after migration?
