### ISSUE TITLE
Duplicate entry in gallery_value. How to delete?

### ISSUE THREAD

**Issue by antonioste** [magento/data-migration-tool#612]
Working magento 2, now in production, with no data in media_gallery
I've try to setup a lot of time the config and Map.xml to migrate only media gallery, But it is impossible because there is an error in table: media_gallery_value_id when tranform in entity_id

Via phpMyAdmin there is some difference in _media_gallery_value

I can't return to an empty Magento 2 DB and restart all migration process.

I must resolve the conflict in _media_gallery_value to will can migrate correctly the _media_gallery

I can truncate (delete, empty) some via phpMyAdmin?

Thanks a lot!
Antonio
Italy

**Comment by antonioste** [comment]
I've resolved in this way:
I've noted that: the table catalog_product_entity_media_gallery_value was 7874 items in Magento 1 and 7875 in Magento 2, some situation in catalog_product_entity_media_gallery_value_to_entity in magento 2, 7875 items.

Via phpMyAdmin I've truncate the 2 table and then re lunch the migration setting up for only Images.

migratetools was do the dirty job and populate correctly the table:
catalog_product_entity_media_gallery
catalog_product_entity_media_gallery_value
catalog_product_entity_media_gallery_value_to_items
With the correct 7874 values!

Now all works fine in Magento 2 and then I continue the work and stop for ever the magento 1 store

**Comment by victor-v-rad** [comment]
Good to know you resolved your issue
