### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry 'x-x-x' for key 'CATALOG_CATEGORY_ENTITY_DATETIME_ENTITY_ID_ATTRIBUTE_ID_STORE_ID'

### ISSUE THREAD

**Issue by anupamyx** [magento/data-migration-tool#614]
Migrating CE 1.9.2 to EE 2.2.6 errors out due to the addition of row_id column in EE schema for catalog_category_entity table and catalog_product_entity table.

Using /vendor/magento/data-migration-tool/etc/opensource-to-commerce/1.9.2.1/config.xml. 

Possible the error is that row_id defaults to 0 and this is why the key  row_id,attribute_id, store_id doesn't stay unique and hence the error. Shouldn't the data migration tool pick up the row_id from the catalog_category_entity table ?

**Comment by victor-v-rad** [comment]
Hi @anupamyx 

I have migrated 1.9.2.1 opensource-to-commerce and no error appeared. Please run the migration with -vvv option and show the error stacktrace here

**Comment by anupamyx** [comment]
Thanks. I was using the wrong file for migration. Thanks for your help.

**Comment by rvoronovmeticulosity** [comment]
I have got the same error. @anupamyx what exactly was error about? Which file for migration was wrong in your case
