### ISSUE TITLE
migrating pages

### ISSUE THREAD

**Issue by nht48823** [magento/data-migration-tool#62]
what is the best way to transfer all the the pages? - how do i go about dumping that table associated with all the pages into the new magento 2 table?

**Comment by victor-v-rad** [comment]
What do you mean when you say 'pages'? Are they CMS Pages?

**Comment by ilol** [comment]
Hey @nht48823. Did you mean CMS pages and blocks?

**Comment by ilol** [comment]
@nht48823 ping
