### ISSUE TITLE
Invalid credentials for 'https://repo.magento.com/packages.json

### ISSUE THREAD

**Issue by gerym77** [magento/data-migration-tool#620]
**Preconditions**
Magento 2.2.6

**Steps to reproduce**
my command line was:
composer require magento/data-migration-tool:2.2.6

**Expected result**
install data migration tool 2.2.6

**Actual result**
ERROR MESSAGE:
[Composer\Downloader\TransportException]                                     
Invalid credentials for 'https://repo.magento.com/packages.json', aborting.

**additional notes**
my auth.jason file looks like this:

{
   "http-basic": {
      "repo.magento.com": {
         "username": "mypublickey",
         "password": "myprivatekey"
      }
   }
}

anyone knows what could be wrong?

many thanks

**Comment by victor-v-rad** [comment]
The 2.2.6 is accessible through composer 
```
$ composer require magento/data-migration-tool:2.2.6
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing magento/data-migration-tool (2.2.6): Downloading (100%)         
Writing lock file
Generating autoload files

```
