### ISSUE TITLE
Undefined offset: 150 in /vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 813

### ISSUE THREAD

**Issue by gerym77** [magento/data-migration-tool#621]
### Preconditions
source: magento 1.9.3.10
destination: Magento 2.2.6
3rd party extensions installed 

### Steps to reproduce

1. php bin/magento migrate:data -r -a vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.10/config.xml

### Expected result
run data migration 

### Actual result
Erros message

[2018-12-03 23:50:41][INFO][mode: data][stage: data migration][step: EAV Step]: started
71% [====================>-------] Remaining Time: < 1 sec

 [Exception]                                                                                                                                                       
Notice: Undefined offset: 150 in /shop/magento/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 813

Exception trace:
 () at /shop/magento/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /shop/magento/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:813
 Migration\Step\Eav\Data->migrateAttributesExtended() at /shop/magento/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:192
 Migration\Step\Eav\Data->perform() at /shop/magento/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:79
 Migration\Mode\AbstractMode->runStage() at /shop/magento/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:119
 Migration\Mode\Data->runData() at /shop/magento/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /shop/magento/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /shop/magento/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /shop/magento/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /shop/magento/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /shop/magento/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /shop/magento/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /shop/magento/bin/magento:23

I deleted attribute_id 150 from catalog_eav_attibutes as mentioned in issue #599
but still the same message. 

anyone has an idea what goes wrong?

**Comment by victor-v-rad** [comment]
Hi @gerym77 

Your Migration/Step/Eav/Data.php file may differ from the original
https://github.com/magento/data-migration-tool/blob/2.2/src/Migration/Step/Eav/Data.php
Please find the line of the error in original Data.php and write its number in the comment.

**Comment by gerym77** [comment]
this is the difference:
my file:   

line 642:            
$record->getValue('attribute_id')` == $data['customDesignAttributeId']


your file: 

line 642-645
in_array($record->getValue('attribute_id'), [
                    $data['customDesignAttributeId'],
                    $data['customLayoutAttributeId']
                ])

but I still have the same error message:
Notice: Undefined offset: 150 in /home/devxxebk/www.dev.emeibaby.com/shop/magento/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 816

havn´t deleted the attribute_id 150 this time!

**Comment by victor-v-rad** [comment]
At the beginning of migration the tool check for [orphaned records](https://database.guide/what-is-an-orphaned-record/) and can throw error like in #455 If such errors were during your migration and you used `--auto | -a` option to bypass the errors, then look at this [troubleshooting document](https://devdocs.magento.com/guides/v2.3/migration/migration-troubleshooting.html#foreign-key-constraint-fails) to know how properly process `Foreign key constraint fails` errors. Orphaned records can be in your EAV tables that were not processed properly.

**Comment by dcwnaveen** [comment]
I got this issue on m.2.3.1 migration. Notice: Undefined offset: 148 in vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 817 
So I have taken the fresh Magento 2.3.1 then migrated the M1.9 data. Everything is looking good.
Because we installed some modules in existing Magento site.
