### ISSUE TITLE
Product Images not showing 

### ISSUE THREAD

**Issue by RedDevilEvo** [magento/data-migration-tool#622]
After a successful migration i have a little problem.

Magento 2.1.7

1- I moved the media folder at the good place in FTP.
2- Now all my product have the good product thumbnails 
3- But if i'm going on the product page it show only the placeholder.
4- In backend there is no image. No thumbnails nothing. 

Is there something special that i should do? 

### Catalog
![1](https://user-images.githubusercontent.com/27022907/49472441-79513b80-f7dd-11e8-8043-ac9dc61624d2.PNG)

### Product Page
![2](https://user-images.githubusercontent.com/27022907/49472442-79513b80-f7dd-11e8-9646-52b6408163a4.PNG)

### BackEnd
![3](https://user-images.githubusercontent.com/27022907/49472443-79513b80-f7dd-11e8-9b96-739381d452a1.PNG)

**Comment by victor-v-rad** [comment]
Hi 
Try to resize images by the command
`php bin/magento catalog:image:resize`

**Comment by RedDevilEvo** [comment]
Hello, already did and not working =/

**Comment by victor-v-rad** [comment]
@RedDevilEvo 
If you use nginx you can take magento2/nginx.conf.sample for proper configuration of rewrites rules for static content (like images)

**Comment by RedDevilEvo** [comment]
Thank you i'll take a look on that.
