### ISSUE TITLE
In Mysql.php line 2594: Table "sequence_catalog_category" does not exist

### ISSUE THREAD

**Issue by aodreman** [magento/data-migration-tool#625]
### Preconditions
Source: CE 1.9.2.4
Destination: CE 2.3.0 - Clean install without sample data
3rd party extensions installed on the source, these are not needed in the new installation.

I only need the categories and the products. However, I went to all the process with the data-migration-tool, and after I ignore the classes that were giving me conflicts I got stuck with the message "In Mysql.php line 2594: Table "sequence_catalog_category" does not exist", I had looked for this table both installations without success, and I would like to know if I am missing another exception. Any help would be appreciated.

Thanks

![console](https://user-images.githubusercontent.com/7330268/49592466-8b4eed80-f947-11e8-9a94-b983b14a8044.png)

**Comment by victor-v-rad** [comment]
Hi @aodreman 

It seems like the DB destination is Magento Commerce (EE) and not Magento Open Source (CE)

**Comment by aodreman-logoscorp** [comment]
Hi @victor-v-rad,

I am using the opensource-to-opensource configuration, or there is anything else I have to do?

**Comment by victor-v-rad** [comment]
I meant your Magento 2 is Magento Commerce (EE) but should be Magento Open Source (CE)

**Comment by aodreman-logoscorp** [comment]
Hi @victor-v-rad, 

The version I had installed as a destination was download from the Magento website, and it has this name Magento-CE-2.3.0-2018-11-27-10-18-29.tar. That is the community edition. Moreover, here is the content of the composer.json

![screen shot 2018-12-17 at 9 56 42 am](https://user-images.githubusercontent.com/12875154/50091585-2a92a100-01e2-11e9-88d1-89b58f537f65.png)

**Comment by daaannorris** [comment]
I am also experiencing this issue, Magento Community 2.3 was installed via composer, and the data migration tool is also set to 2.3.0

`<edition_migrate>opensource-to-opensource</edition_migrate>
        <edition_number>1.9.1.0</edition_number>`

**Comment by daaannorris** [comment]
UPDATE

It looks like the map.xml.dist files were not maintained properly in data migration tool 2.3.0.

I ran a diff on the opensource-to-opensource and it looks like it contains .dist files from commerce, for example
https://github.com/magento/data-migration-tool/blob/2.3.0/etc/opensource-to-opensource/1.9.1.0/map.xml.dist
VS
https://github.com/magento/data-migration-tool/blob/2.2.6/etc/opensource-to-opensource/1.9.1.0/map.xml.dist

I copied the map.xml.dist file from the 2.2.6 version of the data migration tool and it worked without any issues.

Cheers,
Dan
