### ISSUE TITLE
Mismatch of entities in the document: inventory_source_item

### ISSUE THREAD

**Issue by cscd98** [magento/data-migration-tool#628]
### Preconditions
1. Magento 1.14.4.0
2. Magento 2.3.0
3. PHP 7.2.13
4. MySQL 5.7.24

### Steps to reproduce
1. Convert DB from M1 to M2

### Expected result
1. No errors

### Actual result
1.

[2018-12-10 15:34:17][WARNING]: Mismatch of entities in the document: inventory_source_item Source: 6126 Destination: 6119
[2018-12-10 15:34:17][WARNING]: Volume Check failed

**Comment by victor-v-rad** [comment]
Thank you @craigcarnell for reporting the issue 

Some records from `M1 > cataloginventory_stock_item` table were not transferred to `M2 > inventory_source_item`. To find them you can look at the method `\Migration\Step\Inventory\Model\SourceItem::prepareSelect()` . So either there are some records in `cataloginventory_stock_item` with `website_id != 0` or records `catalog_product_entity.entity_id =! cataloginventory_stock_item.product_id`

**Comment by victor-v-rad** [comment]
@craigcarnell was it a bug of the tool?

**Comment by cscd98** [comment]
@victor-v-rad There was a few entries in M1 catalog_product_entity which had no sku which was the cause.
