### ISSUE TITLE
Requested store is not found

### ISSUE THREAD

**Issue by iphoneuser86** [magento/data-migration-tool#63]
Hello,

after import there comes 'Requested store is not found'. How can I edit it?

**Comment by angelflo** [comment]
same problem here

**Comment by redboxmarcins** [comment]
Did you clear your web browser cookies?

**Comment by storets** [comment]
It might related to category database.
some category data generated in catalog_category_entity_* data still has store_id with 0 
after delete rows with store_id =0 from 10 tables.
reimport categories with ub-tool and it works fine but message still shows

**Comment by ilol** [comment]
Thanks, @redboxmarcins !
@angelflo  @iphoneuser86 does it work? 
If yes, can you please close the issue?

**Comment by jordanvector** [comment]
Same issue, no clearing browser web cookies does not solve the issue.

**Comment by Baracuda011** [comment]
Try to run following query in your database, and then try to open website.

SET FOREIGN_KEY_CHECKS=0;
UPDATE `store` SET store_id = 0 WHERE code='admin';
UPDATE `store_group` SET group_id = 0 WHERE name='Default';
UPDATE `store_website` SET website_id = 0 WHERE code='admin';
UPDATE `customer_group` SET customer_group_id = 0 WHERE customer_group_code='NOT LOGGED IN';
SET FOREIGN_KEY_CHECKS=1;

**Comment by pasewebstudio** [comment]
Thank you @Baracuda011 
your query save me a loto of troubles!
