### ISSUE TITLE
Stores not getting migrated

### ISSUE THREAD

**Issue by ryanfern86goa** [magento/data-migration-tool#630]
### Preconditions

1. PHP Version 7.1
2. MySql 5.6
3. Magento version 2.3.0 Commerce
4. Magento old version Commerce 1.14.2.0

### Steps to reproduce

1. run full data migration based on default migration from Commerce 1.14.2.0 to Commerce 2.3.0

### Expected result

1. stores should be copied over
2. Everything should work fine

### Actual result

1. stores should be copied over
2. when visiting stores > configuration , get this error

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The store that was requested wasn't found. Verify the store and try again

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The store that was requested wasn't found. Verify the store and try again.
#0 vendor/magento/module-store/Model/StoreManager.php(167): Magento\Store\Model\StoreRepository->getById('2')

**Comment by victor-v-rad** [comment]
Hi @ryanfern86goa 

Did you migrate settings? Stores and websites are migrated when you run `bin/magento migrate:settings`

**Comment by ryanfern86goa** [comment]
Hi @victor-v-rad 

Thanks for your reply.

I did the entire migration based on the default config.xml file as seen below and it does have the setting step in it (see below). I also noticed the settings (core_config_data) is not copied over too.

php -d memory_limit=-1 bin/magento migrate:data -a commerce-to-commerce/1.14.2.0/config.xml

Thanks and look forward to your reply.

Ryan

`<steps mode="settings">
        <step title="Settings Step">
            <integrity>Migration\Step\Settings\Integrity</integrity>
            <data>Migration\Step\Settings\Data</data>
        </step>
        <step title="Stores Step">
            <integrity>Migration\Step\Stores\Integrity</integrity>
            <data>Migration\Step\Stores\Data</data>
            <volume>Migration\Step\Stores\Volume</volume>
        </step>
    </steps>
    <steps mode="data">
        <step title="Data Integrity Step">
            <integrity>Migration\Step\DataIntegrity\Integrity</integrity>
        </step>
        <step title="EAV Step">
            <integrity>Migration\Step\Eav\Integrity</integrity>
            <data>Migration\Step\Eav\Data</data>
            <volume>Migration\Step\Eav\Volume</volume>
        </step>
        <step title="Custom Customer Attributes Step">
            <integrity>Migration\Step\CustomCustomerAttributes\Integrity</integrity>
            <data>Migration\Step\CustomCustomerAttributes\Data</data>
            <volume>Migration\Step\CustomCustomerAttributes\Volume</volume>
        </step>
        <step title="Customer Attributes Step">
            <integrity>Migration\Step\Customer\Integrity</integrity>
            <data>Migration\Step\Customer\Data</data>
            <volume>Migration\Step\Customer\Volume</volume>
        </step>
        <step title="Map Step">
            <integrity>Migration\Step\Map\Integrity</integrity>
            <data>Migration\Step\Map\Data</data>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Url Rewrite Step">
            <integrity>Migration\Step\UrlRewrite\Version11410to2000</integrity>
            <data>Migration\Step\UrlRewrite\Version11410to2000</data>
            <volume>Migration\Step\UrlRewrite\Version11410to2000</volume>
        </step>
        
        <step title="SalesOrder Step">
            <integrity>Migration\Step\SalesOrder\Integrity</integrity>
            <data>Migration\Step\SalesOrder\Data</data>
            <volume>Migration\Step\SalesOrder\Volume</volume>
        </step>
        <step title="ConfigurablePrices step">
            <integrity>Migration\Step\ConfigurablePrices\Integrity</integrity>
            <data>Migration\Step\ConfigurablePrices\Data</data>
            <volume>Migration\Step\ConfigurablePrices\Volume</volume>
        </step>
        <step title="OrderGrids Step">
            <integrity>Migration\Step\OrderGridsEE\Integrity</integrity>
            <data>Migration\Step\OrderGridsEE\Data</data>
            <volume>Migration\Step\OrderGridsEE\Volume</volume>
        </step>
        <step title="Tier Price Step">
            <integrity>Migration\Step\TierPrice\Integrity</integrity>
            <data>Migration\Step\TierPrice\Data</data>
            <volume>Migration\Step\TierPrice\Volume</volume>
        </step>
        <step title="SalesIncrement Step">
            <integrity>Migration\Step\SalesIncrement\Integrity</integrity>
            <data>Migration\Step\SalesIncrement\Data</data>
            <volume>Migration\Step\SalesIncrement\Volume</volume>
        </step>
        <step title="Inventory Step">
            <integrity>Migration\Step\Inventory\Integrity</integrity>
            <data>Migration\Step\Inventory\Data</data>
            <volume>Migration\Step\Inventory\Volume</volume>
        </step>
        <step title="VisualMerchandiser Step">
            <integrity>Migration\Step\VisualMerchandiser\Integrity</integrity>
            <data>Migration\Step\VisualMerchandiser\Data</data>
            <volume>Migration\Step\VisualMerchandiser\Volume</volume>
        </step>
        <step title="PostProcessing Step">
            <data>Migration\Step\PostProcessing\Data</data>
        </step>
    </steps>
    <steps mode="delta">
        <step title="Custom Customer Attributes Step">
            <delta>Migration\Step\CustomCustomerAttributes\Delta</delta>
            <volume>Migration\Step\CustomCustomerAttributes\Volume</volume>
        </step>
        <step title="Customer Attributes Step">
            <delta>Migration\Step\Customer\Delta</delta>
            <volume>Migration\Step\Customer\Volume</volume>
        </step>
        <step title="Map Step">
            <delta>Migration\Step\Map\Delta</delta>
            <volume>Migration\Step\Map\Volume</volume>
        </step>
        <step title="Log Step">
            <delta>Migration\Step\Log\Delta</delta>
            <volume>Migration\Step\Log\Volume</volume>
        </step>
        <step title="SalesOrder Step">
            <delta>Migration\Step\SalesOrder\Delta</delta>
            <volume>Migration\Step\SalesOrder\Volume</volume>
        </step>
        <step title="OrderGrids Step">
            <delta>Migration\Step\OrderGridsEE\Delta</delta>
            <volume>Migration\Step\OrderGridsEE\Volume</volume>
        </step>
        <step title="SalesIncrement Step">
            <delta>Migration\Step\SalesIncrement\Delta</delta>
            <volume>Migration\Step\SalesIncrement\Volume</volume>
        </step>
        <step title="Inventory Step">
            <delta>Migration\Step\Inventory\Delta</delta>
            <volume>Migration\Step\Inventory\Volume</volume>
        </step>
    </steps>`

**Comment by victor-v-rad** [comment]
Probably it is because you should run the migration of settings
php -d memory_limit=-1 bin/magento **migrate:settings** -a commerce-to-commerce/1.14.2.0/config.xml

**Comment by ryanfern86goa** [comment]
Hi @victor-v-rad 

Thanks for your reply.

I would have assumed this to be part of the entire migration run as I mentioned above.

Are you still looking into why the store's might not be copied over ?

Regards
Ryan

**Comment by victor-v-rad** [comment]
You can compare the data from your `M1 > core_store` and `M2 > store` tables to see the difference and run migration of setting once again to debug why the data is not transferred.
