### ISSUE TITLE
Integrity constraint violation: 1452 Cannot add or update a child row

### ISSUE THREAD

**Issue by Shane1812** [magento/data-migration-tool#631]
migrate data from magento 1.9.2.4 to magento2.26

### Steps to reproduce
1. I test my migration tool from a copy database on local successfully.then try to migrate the data from a live database to another live database,and it failure.
2. I can not find the table 'catalog_product_entity_varchar' on magento 1 so I am not sure what's the
process of migration.Please help

[2018-12-18 12:17:42][INFO][mode: data][stage: data migration][step: Map Step]: started
12% [===>------------------------] Remaining Time: 1 hr
                                                                                                                        
  [PDOException]                                                                                                        
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fai  
  ls (`dbname`.`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ATTR_ID_EAV_ATTR_A  
  TTR_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`))

**Comment by victor-v-rad** [comment]
Hi @Shane1812 
It seems like [orphaned record](https://database.guide/what-is-an-orphaned-record/) caused error. The tool checks for orphaned records at the beginning of migration and throw error like #455 If that was the case and you skipped this error by `--auto` option then read how to properly resolve it in [this guide](https://devdocs.magento.com/guides/v2.3/migration/migration-troubleshooting.html#foreign-key-constraint-fails). Still, during migration of data in Map Step you should not have got this error because the tool send `SET FOREIGN_KEY_CHECKS=0` before migration. This prevents MySQL to throw the error you described. So maybe your live MySQL instance ignores this `SET FOREIGN_KEY_CHECKS=0`

**Comment by Shane1812** [comment]
> Hi @Shane1812
> It seems like [orphaned record](https://database.guide/what-is-an-orphaned-record/) caused error. The tool checks for orphaned records at the beginning of migration and throw error like #455 If that was the case and you skipped this error by `--auto` option then read how to properly resolve it in [this guide](https://devdocs.magento.com/guides/v2.3/migration/migration-troubleshooting.html#foreign-key-constraint-fails). Still, during migration of data in Map Step you should not have got this error because the tool send `SET FOREIGN_KEY_CHECKS=0` before migration. This prevents MySQL to throw the error you described. So maybe your live MySQL instance ignores this `SET FOREIGN_KEY_CHECKS=0`

Hi,thank you for your help,I think it is because the database ignores the SET FOREIGN_KEY_CHECKS=0,the server database is MariaDB,I think the tool set foreign key checks disable dont work on MariaDB,and I am not sure how to make it works...

**Comment by Shane1812** [comment]
@victor-v-rad hi,I think it should not happen because I can see the data exsit in eav_attribute table.it should can find all the attribute _id at the table.I am so confused.

**Comment by victor-v-rad** [comment]
Did you see #455 error at the beginning of migration?

**Comment by Shane1812** [comment]
@victor-v-rad yes,it is not that error,I run the command without -a,and it shows no error.now I try to migrate the data from live database to my computer,and it's still stucked in this step even SET GLOBAL FOREIGN_KEY_CHECKS=0;I got stucked at 'catalog_product_entity_media_gallery_value' in this error too and after I clear some data from my M1 database it migrated smoothly,but in this table I dont know what need to clear because I can find all attribute_id(catalog_product_entity_varchar) in eav_attribute table.

**Comment by victor-v-rad** [comment]
> after I clear some data from my M1 database it migrated smoothly

So was it fixed?

**Comment by Shane1812** [comment]
@victor-v-rad no at this table,I met this error before but not this table but in 'catalog_product_entity_media_gallery_value',that after I clear the data it now can find the data from M2 database means the table migrate successfully.but catalog_product_entity_varchar this table still get stucked.

**Comment by victor-v-rad** [comment]
Maybe catalog_product_entity_varchar has records with empty attribute_id

**Comment by Shane1812** [comment]
@victor-v-rad  I can find all attribute_id(catalog_product_entity_varchar) in eav_attribute table.that's why I am so confused.

**Comment by Shane1812** [comment]
@victor-v-rad I copy the live server database to local server and migrate smooth...then delta it with server database,get this warning:
[2018-12-20 10:37:19][WARNING]: Mismatch of entities in the document: adminnotification_inbox Source: 8877 Destination: 8876
[2018-12-20 10:37:19][WARNING]: Mismatch of entities in the document: catalog_product_entity_int Source: 148744 Destination: 130480
[2018-12-20 10:37:19][WARNING]: Mismatch of entities in the document: catalog_product_entity_varchar Source: 272901 Destination: 250589
[2018-12-20 10:37:19][WARNING]: Volume Check failed
I think that's problem,there are rows missed after migration.Is these data take effect to my M2 website?

**Comment by Abdulkadiragoliya** [comment]
@Shane1812  did you find solution for    SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails `catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`) ON DELETE )

**Comment by Abdulkadiragoliya** [comment]
@victor-v-rad   can you please let me know the solution for 
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails catalog_product_entity_varchar, CONSTRAINT CAT_PRD_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID FOREIGN KEY (attribute_id) REFERENCES eav_attribute (attribute_id) ON DELETE )
