### ISSUE TITLE
Could not unserialize data of sales_flat_order_item

### ISSUE THREAD

**Issue by VZeroCool** [magento/data-migration-tool#632]
### Preconditions

1. Magento 1.9.3.3 to Magento 2.2.6
2. PHP 7.1.x Apache

### Steps to reproduce

1. Install tool using composer 
2. Set up necessary things like modification in config.file 

### Expected result

1. Migrated Successfully

### Actual result

1. Could not unserialize data of sales_flat_order_item.product_options with record id 7

### Additional notes
I've checked document record where tool id pointing error.

There is some broken value compared to other fields.
Checked [https://github.com/magento/data-migration-tool/issues/417](url) 
and 
https://github.com/magento/data-migration-tool/issues/410
But Doesn't quite helpful.

**Comment by victor-v-rad** [comment]
Hi @VZeroCool 

>I've checked document record where tool id pointing error.

What data in the `product_options` field?

**Comment by VZeroCool** [comment]
HI @victor-v-rad ,

Field contains value like `b:0;` Where tool is throwing error. 


Rest of other contains like `a:1:{s:7:"options";a:5:{i:0;a:7:{s:5:"label";s:5:"Shirt";s:5:"value";s:5:"Ivory";s:11:"print_value";s:5:"Ivory";s:9:"option_id";s:13:"502d42051436b";s:11:"option_type";s:9:"drop_down";s:12:"option_value";s:1:"0";s:11:"custom_view";b:0;}i:1;a:7:{s:5:"label";s:7:"Sporran";s:5:"value";s:5:"Black";s:11:"print_value";s:5:"Black";s:9:"option_id";s:13:"502d42051530f";s:11:"option_type";s:9:"drop_down";s:12:"option_value";s:1:"0";s:11:"custom_view";b:0;}i:2;a:7:{s:5:"label";s:4:"Sock";s:5:"value";s:5:"White";s:11:"print_value";s:5:"White";s:9:"option_id";s:13:"502d4205162a6";s:11:"option_type";s:9:"drop_down";s:12:"option_value";s:1:"0";s:11:"custom_view";b:0;}i:3;a:7:{s:5:"label";s:16:"Measurement Form";s:5:"value";s:67:"By checking this box, you agree to send in a completed Sizing Form.";s:11:"print_value";s:67:"By checking this box, you agree to send in a completed Sizing Form.";s:9:"option_id";s:13:"502d42051724e";s:11:"option_type";s:9:"drop_down";s:12:"option_value";s:1:"0";s:11:"custom_view";b:0;}i:4;a:7:{s:5:"label";s:14:"Tartan Pattern";s:5:"value";s:17:"MacLeod of Harris";s:11:"print_value";s:17:"MacLeod of Harris";s:9:"option_id";s:13:"502d4205181ed";s:11:"option_type";s:9:"drop_down";s:12:"option_value";s:1:"0";s:11:"custom_view";b:0;}}}`

**Comment by victor-v-rad** [comment]
I have migrated the serialized data you provided without errors

**Comment by VZeroCool** [comment]
@victor-v-rad  But I'm getting errors If I ignore this field than It's working fine. Also only `b:0;` causing issues. For test purpose If i changed this fields value to null or proper format(That i posted above) than that record related error removed. 

You can give a try with adding 'b:0;' value to same document as I reported above.

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-97342 to fix it. 
You can also replace this [code](https://github.com/magento/data-migration-tool/blob/2.3/src/Migration/Handler/SerializeToJson/SalesOrderItem.php#L74) by 
`if (false === $unserializeData && $value != 'b:0;') {` 
if it is urgent

**Comment by VZeroCool** [comment]
For now I've ignored this column as its not that much important for me. Also your suggest won't work due to I've multiple column that contains values like `b:0;` So can't add that hard coded condition there. Provide some genuine fix.

**Comment by victor-v-rad** [comment]
@VZeroCool  The fix is in f3cdd846246d3f2b26b3c3ac6f48c59032de85a7

**Comment by VZeroCool** [comment]
@victor-v-rad , I had done migration using https://github.com/magento/data-migration-tool/issues/632#issuecomment-449969107

But Now My orders doesn't contain that serialised data.

Now I can see you pushed commit https://github.com/magento/data-migration-tool/issues/632#issuecomment-453408587 .

Thanks for that. But My question is that If i merge this commit than that serialised will be migrated OR it will be ignored ??

**Comment by victor-v-rad** [comment]
`b:0;` means `false`, and json format see it also as `false`. So the string `false` will be in migrated fields
