### ISSUE TITLE
some page "This site can’t be reached"

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#633]
> i have migrate 1.9.3.7 to 2.3, migration successfully completed but after some pages is not opening like:cart,login page,customer register page,checkout

screenshot: https://prnt.sc/lzmxa1

**Comment by victor-v-rad** [comment]
Hi @rakeshdonga 

Any errors during migration?

**Comment by rakeshdonga** [comment]
Thank you for replay
no any error generate in log 
just some page not working still

**Comment by victor-v-rad** [comment]
Usually, if no errors during migration then migrated store should be fine. Since the pages that are not open  relate to customer, your issue can relate to customer attributes. Maybe you have extensions installed in Magento 1 for customers that created unnecessary customer attributes.

**Comment by rakeshdonga** [comment]
no unnecessary customer attributes available also migration complete successfully but not working some pages also cart,checkout,registerpage,login page

**Comment by rakeshdonga** [comment]
@victor-v-rad  any update ? 
i have still problem in admin also cart,login page,customer register page,checkout

**Comment by jethroDavid** [comment]
I have the same problem, any fixed yet?

**Comment by rakeshdonga** [comment]
@jethroDavid  
you have checked in magento1 version which language use in backend  also frontend like french,dutch

**Comment by jethroDavid** [comment]
thanks for your response,
Magento 1.9.1.1, 
_**Backend**_ Locale - English (United State) 
_**Am not so sure if this is the frontend Language**_ Default Store View = Default Store View

**Comment by rakeshdonga** [comment]
@jethroDavid 
i have facing same issue and i have resolved by run deploy command 

> php bin/magento setup:static-content:deploy -f de_DE fr_FR

**Comment by jethroDavid** [comment]
@rakeshdonga thanks men, but it doesn't work
