### ISSUE TITLE
data migration tool issue (1.9.2.4 to 2.3)

### ISSUE THREAD

**Issue by biju-zoondia** [magento/data-migration-tool#634]
I was added new product and update the details and search the product from frontend, but it shows error in log file "No linked stock found" . I also found same issue while adding Stores > Inventory > Stocks details to all websites (multi store) and hit save, gives error in log file "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.3.inventory_stock_2' doesn't exist" and "Can not save link related to Default Source or Default Stock" .

### Preconditions

1.  Magento 1.9.2.4
2.  Magento 2.3
3.  PHP 7.2.12
4. mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper

### Steps to reproduce

1. Migrate a multi store site (Magento 1.9.2.4)
2. Migrate only order & Customer and basic store details    

-------------------------------------------------------------------
migration config file map option details given below 
------------------------------------------------------------------

<options>

        <map_file>etc/opensource-to-opensource/1.9.2.4/map.xml</map_file>
        <eav_map_file>etc/opensource-to-opensource/map-eav.xml.dist</eav_map_file>
        <eav_document_groups_file>etc/opensource-to-opensource/eav-document-groups.xml.dist</eav_document_groups_file>
        <eav_attribute_groups_file>etc/opensource-to-opensource/eav-attribute-groups.xml.dist</eav_attribute_groups_file>
        <log_map_file>etc/opensource-to-opensource/map-log.xml.dist</log_map_file>
        <log_document_groups_file>etc/opensource-to-opensource/log-document-groups.xml.dist</log_document_groups_file>
        <settings_map_file>etc/opensource-to-opensource/settings.xml</settings_map_file>
        <customer_map_file>etc/opensource-to-opensource/map-customer.xml</customer_map_file>
        <customer_document_groups_file>etc/opensource-to-opensource/customer-document-groups.xml</customer_document_groups_file>
        <customer_attribute_groups_file>etc/opensource-to-opensource/customer-attribute-groups.xml</customer_attribute_groups_file>
        <delta_document_groups_file>etc/opensource-to-opensource/deltalog.xml.dist</delta_document_groups_file>
        <order_grids_document_groups_file>etc/opensource-to-opensource/order-grids-document-groups.xml</order_grids_document_groups_file>
        <map_document_groups>etc/opensource-to-opensource/map-document-groups.xml.dist</map_document_groups>
        <class_map>etc/opensource-to-opensource/class-map.xml.dist</class_map>
        <tier_price_map_file>etc/opensource-to-opensource/map-tier-price.xml.dist</tier_price_map_file>
        <stores_map_file>etc/opensource-to-opensource/map-stores.xml</stores_map_file>

    </options> 

### Expected result

1. Migration process successfully completed.

### Actual result

1. https://www.awesomescreenshot.com/image/3800733/50059a1d29562266dc166bd57d8f5919

### Additional notes
1) Category listing page gives timeout issue.

**Comment by victor-v-rad** [comment]
Hi @biju-zoondia 

>Migrate only order & Customer and basic store details

It is better to migrate whole M1 store. If your migrate only order & Customer ..., then result could be the errors you described
