### ISSUE TITLE
  Failed to clone https://github.com/magento/data-migration-tool, git was not found, check that it is installed and in your PATH env.     sh: git: command not found 

### ISSUE THREAD

**Issue by soborked** [magento/data-migration-tool#635]
### Preconditions

1. Magento 2.3 
2. PHP 7.2

### Steps to reproduce

1. composer config repositories.data-migration-tool git https://github.com/magento/data-migration-tool
2. composer require magento/data-migration-tool:2.3.0
3. 

### Expected result

1. Should run without errors.

### Actual result

1. Failed to clone https://github.com/magento/data-migration-tool, git was not found, check that it is installed and in your PATH env.  
2. sh: git: command not found 

### Additional notes
I did some research and was told the issue is related to php 7 as they tried again with php 5.6 and didn't get the issue I mentioned above.

Can someone please confirm or provide a solution as I'm using php 7.2

Thank you.

**Comment by victor-v-rad** [comment]
At the first glance, the issue is not related to the tool code because of the error `git was not found`
