### ISSUE TITLE
eav_entity error at migration from 1.9.3 to 2.2.7

### ISSUE THREAD

**Issue by secaliskan** [magento/data-migration-tool#636]
Hi Now I'm migrating from **1.9.3 to 2.2.7** and I stucked in Data migration. I'M using Centos 6 dedicated hosting with full access to server. I have WHM and Cpanel with PHP 7.0.33
on 1.9 U have free Blog extension Magepalaza Blog but all the error came from this. Attribute errors I fixed ignoring them at eav-attribute-groups.xml.
Bu below entity type error I can not resolve. 

`[2018-12-30 16:33:01][ERROR]: Class mageplaza_betterblog/post does not exist but mentioned in: eav_entity_type.entity_model for entity_type_id=31`
`[2018-12-30 16:33:01][ERROR]: Class mageplaza_betterblog/resource_eav_attribute does not exist but mentioned in: eav_entity_type.attribute_model for entity_type_id=31`
`[2018-12-30 16:33:01][ERROR]: Class mageplaza_betterblog/post_attribute_collection does not exist but mentioned in: eav_entity_type.entity_attribute_collection for entity_type_id=31`

Any clue on this please reply
`

**Comment by rakeshdonga** [comment]
hi @secaliskan 
Try to add next lines to your class-map.xml.dist

<rename>
    <from>vendors/source_vendors</from>
    <to />
</rename>

**Comment by rakeshdonga** [comment]
hi @secaliskan 
You can in class-map.xml.dist add something like

    <rename>
        <from>extentionname/class_name_of_entity_model</from>
        <to />
    </rename>

**Comment by rakeshdonga** [comment]
hi @secaliskan 
You can in class-map.xml.dist add something like

    <rename>
        <from>extentionname/class_name_of_entity_model</from>
        <to />
    </rename>

and migrate. Then remove useless eav_entity_type from DB

**Comment by secaliskan** [comment]
> hi @secaliskan
> You can in class-map.xml.dist add something like
> 
> ```
> <rename>
>     <from>extentionname/class_name_of_entity_model</from>
>     <to />
> </rename>
> ```
> and migrate. Then remove useless eav_entity_type from DB

Hi Rakhesh,
where is this class-map.xml.dist file? this is 2.2.7 and there's no such file...

**Comment by secaliskan** [comment]
> > hi @secaliskan
> > You can in class-map.xml.dist add something like
> > ```
> > <rename>
> >     <from>extentionname/class_name_of_entity_model</from>
> >     <to />
> > </rename>
> > ```
> > and migrate. Then remove useless eav_entity_type from DB
> 
> Hi Rakhesh,
> where is this class-map.xml.dist file? this is 2.2.7 and there's no such file...

There's map.xml.dist under Magento folder/vendor/magento/opensource-to-opensource/1.9.3/map.xml.dist. This file I have to add??

**Comment by rakeshdonga** [comment]
hi @secaliskan 
vendor\magento\data-migration-tool\etc\opensource-to-opensource
class-map.xml.dist file rename and class-map.xml also change in config.xml file 
http://i.prntscr.com/iWCXquYGTN6uRsc-PZUfLA.png

**Comment by secaliskan** [comment]
OK What Rahkesh wrote worked for me;
this class-map.xml.dist file is under 

> magento_root/vendor/magento/data-migration-tool/etc/opensource-to-opensource/class-map.xml.dist

And I have added three lines to this files
`<rename>
            <from>mageplaza_betterblog/post</from>
                <to />
    </rename>
    
    <rename>
            <from>mageplaza_betterblog/resource_eav_attribute</from>
                <to />
    </rename>
    <rename>
            <from>mageplaza_betterblog/post_attribute_collection</from>
                <to />
    </rename>`
And this problem gone, Thank you Rakhes @rakeshdonga
