### ISSUE TITLE
Order is not come after migrate the data from Magento 1.9 to Magento 2.2.6

### ISSUE THREAD

**Issue by parveen12345** [magento/data-migration-tool#637]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by parveen12345** [comment]
Please tell me what is the issue and how resolve it

**Comment by rakeshdonga** [comment]
hi @parveen12345 

any error during migration ? share me here

**Comment by victor-v-rad** [comment]
Hi @parveen12345 

Not clear what is the problem. Please provide more information about it
