### ISSUE TITLE
[Exception]   Notice: Undefined offset: 1 vendor\magento\data-migration-tool\src\Migration\Step\Eav\Data.php on line 291

### ISSUE THREAD

**Issue by azam2000** [magento/data-migration-tool#638]
### Preconditions

1. Hi,
I am using this data-migration-tool, getting below error,
[Exception] Notice: Undefined offset: 1 in vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291

Note: I am migrating datas from magento1.9.2.1to magento 2.1.9

I have searched for solution all has suggested to start the migration again with fresh M2 database.
Could you please suggest me the solution
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by rakeshdonga** [comment]
hi @azam2000 
give me screenshot what is error generate?

**Comment by azam2000** [comment]
![error](https://user-images.githubusercontent.com/7011387/50589940-7617a100-0eaa-11e9-836a-8887da2d973e.png)

**Comment by rakeshdonga** [comment]
hi @azam2000 
you have any file in change ?
may be you are gone wrong way in migration

**Comment by azam2000** [comment]
I have remove some fields in catalog_eav_attribute

**Comment by azam2000** [comment]
if you want check files so i will send you

**Comment by rakeshdonga** [comment]
my skype id rakeshdonga007
 please send me files

**Comment by azam2000** [comment]
which files please specify?

**Comment by rakeshdonga** [comment]
vendor\magento\data-migration-tool\etc\opensource-to-opensource\1.x.x.x
config.xml

**Comment by azam2000** [comment]
ok

**Comment by azam2000** [comment]
i have send on skype

**Comment by victor-v-rad** [comment]
Hi @azam2000 

Many issues were fixed in the latest stable versions of Magento and the tool (2.3.0 or 2.2.7). So consider using it instead of 2.1.9

**Comment by azam2000** [comment]
hi victor-v-rad

problem is that the version i am using is 1.9.2.1 which is not suported to php 7.1 so i will not use latest version of magento 2

**Comment by rakeshdonga** [comment]
hi @azam2000 
magento 1.9.2.1 is supported to php 7.1 you can below extension 
https://github.com/Inchoo/Inchoo_PHP7

**Comment by victor-v-rad** [comment]
or install Magento 2 with the tool on separate server with 7.1
