### ISSUE TITLE
Uncaught TypeError in MigrateSettingsCommand

### ISSUE THREAD

**Issue by jknipper** [magento/data-migration-tool#64]
I've got an error after installing data-migration-tool with composer when I run bin/magento from command line. I'm using version 2.0.2 on PHP 7.

`Fatal error: Uncaught TypeError: Argument 1 passed to Migration\Console\MigrateSettingsCommand::__construct() must be an instance of Migration\Config, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /src/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /src/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:24
Stack trace:
#0 /src/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(97): Migration\Console\MigrateSettingsCommand->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /src/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Conso...', Array)
#2 /src/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Migration\\Conso...')
#3 /src/vendor/magento/data-migration-tool/src/Migration/Console/CommandList.php(52): Magento\Fr in /src/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php on line 24
`

Any help would be appreciated.

**Comment by nfletton** [comment]
I can confirm the same experience on 2.0.2 with PHP 7. It wasn't happening a few weeks ago when I first set up the development site and performed the initial migration. This makes me think it started occurring after a dot release of PHP 7.0 as I've seen a couple come in recently.

I use the following repository on Ubuntu 14.04:
https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by nfletton** [comment]
Decided to switch to PHP 5.6 and this cleared the problem. 7.0 and Magento 2 is a too fragile for me at this time.

**Comment by svewap** [comment]
I'm using PHP 5.6 and this error appers after compiling DI

**Comment by kandrejevs** [comment]
This error appeared after updating to 2.0.6 and compiling DI

**Comment by 4DallasC** [comment]
Yeah, I got this error after compiling Magento 2. I deleted the directories var/di, var/generation/ var/cache var/page_cache and var/view_preprocessed and it all worked fine.

**Comment by craigcarnell** [comment]
I get this error using Magento 2.1 and the Data Migration Tool 2.1:

 /usr/bin/env php -f bin/magento -- maintenance:enable
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Console\MigrateSettingsCommand::__construct() must be an instance of Migration\Config, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/vhosts/magento2-capistrano/releases/20160722103233/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/vhosts/magento2-capistrano/releases/20160722103233/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:24

Stack trace:

#0 /var/www/vhosts/magento2-capistrano/releases/20160722103233/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Migration\Console\MigrateSettingsCommand->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))

#1 /var/www/vhosts/magento2-capistrano/releases/20160722103233/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Conso...', Array)

#2 /var/www/vhosts/magento in /var/www/vhosts/magento2-capistrano/releases/20160722103233/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php on line 24
```

**Comment by 4DallasC** [comment]
@craigcarnell, I don't think the migration tool works with a compiled instance of Magento 2. Try deleting the var/generation and other temporary directories.

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-52162 was created to fix the issue

**Comment by PreacherX** [comment]
Adding another instance of the issue.

Magento 2.1, Migration tool 2.1 loaded from repo.magento.com using composer.  cPanel 58.0.12, EasyApache4 compiled with PHP 7.0.9 and Apache 2.4.23 (cPanel)

This is the second system that has failed to move to production mode for performance testing.  Both VPS' that I have done the migration on have resulted in the same issue.

`bin/magento deploy:mode:set production` resulted in:

> Starting deployment of static content
> Something went wrong while deploying static content. See the error log for details.
> Command returned non-zero exit code:
> /opt/cpanel/ea-php70/root/usr/bin/php -f /home/bluestar/public_html/bin/magento setup:static-content:deploy en_US

The resulting error_log is: 

> [09-Aug-2016 04:03:20 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Console\MigrateSettingsCommand::__construct() must be an instance of Migration\Config, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /home/bluestar/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /home/bluestar/public_html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php:24
> Stack trace:
> #0 /home/bluestar/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Migration\Console\MigrateSettingsCommand->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
> #1 /home/bluestar/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Conso...', Array)
> #2 /home/bluestar/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Migratio in /home/bluestar/public_html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateSettingsCommand.php on line 24

**Comment by flecxie** [comment]
@victor-v-rad: noticed that you checked in these 2 commits to fix this issue in 2.1.1:

- https://github.com/magento-nord/data-migration-tool/pull/1/commits/9d9051288524953d3a6db9bfcb4ac4375f52b52b
- https://github.com/magento-nord/data-migration-tool/pull/1/commits/7a6cacaacd0e6fd0158e2cc59c25cee37019684d

Is there a simple fix or workaround for 2.1.0 users (patches above look a bit complex to manually merge in)? Is my understanding correct that on 2.1.0 one can only switch from developer to production after uninstalling the migration tool?

Thanks!

**Comment by victor-v-rad** [comment]
Though 2.1.1 is not ready yet you can try the fix

**Comment by victor-v-rad** [comment]
> switch from developer to production after uninstalling the migration tool?

you do not necessary need to uninstall the tool to switch to production

**Comment by btwq** [comment]
+1 on Magento 2.1.0. Error occurs on command line after running "bin/magento setup:di:compile"

**Comment by bartoll** [comment]
+1

**Comment by medma-infomatix** [comment]
I have fixed that issue by updating composer using below command.
 
**$ comoser update**

**Comment by hexboxone** [comment]
I have similar problems on Magento 2.1.0 with PHP7, but setup:di:compile works fine and exits with "Generated code and dependency injection configuration successfully."
On static-content:deploy same error's are thrown:
`Fatal error: Uncaught TypeError: Argument 1 passed to Migration\Console\MigrateSettingsCommand::__construct() must be an instance of Migration\Config, instance of Magento\Framework\ObjectManager\ObjectManager given, called in ` 

Note: composer was fresh installed from last version on githup today.

**Comment by victor-v-rad** [comment]
@jknipper @hexboxone 
Please recheck the issue on the last release of the tool 2.1.1

**Comment by ilol** [comment]
Hey, I am temporary closing until any respond.
