### ISSUE TITLE
Magento community edition 2.1.* to 2.3.* - bin/magento setup:upgrade - Schema creation/updates: SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by ghost** [magento/data-migration-tool#641]
Please see https://github.com/magento/magento2/issues/20346
I'm posting this here in case others have the same or similar issue. 
It's possible that the issue with the 2.1.* to 2.3.* upgrade is due to the data being originally migrated using "magento/data-migration-tool"
Thank you.

**Comment by victor-v-rad** [comment]
Hi @mibu31 

It looks like Magento 2.1 does not have UNIQUE KEY (`attribute_set_id`,`attribute_group_code`), but now it has in 2.3. If you renamed migrated group names in Magento 2.1 then such issue can appear.
