### ISSUE TITLE
After migration magento1 to magento2

### ISSUE THREAD

**Issue by anurag0202** [magento/data-migration-tool#642]
After migration from magento 1.9 to magento 2.1.2 using tool configurable product not showing special price in backend. Can someone investigate and let me know the resolved. Its kind of urgent

**Comment by victor-v-rad** [comment]
Hi @anurag0202 
If you try to create a new configurable product in Magento 2 you probably also won't see special price option. At least I do not see it in my Magento 2.3. So the issue is not in the tool

**Comment by anurag0202** [comment]
Hi @victor-v-rad 
I did this already and if I create new configurable products in the same instance then it's showing me. Even If I edit the existing one and save the price that also works. The thing which confuses me that special price is showing in the front-end for each product and even I can place the order with that price all seems working fine in front-end. But in the backend, it's not showing. Problem is that when I applied the discount coupon or rules in that time I am able to rectify this issue and it's not working as expected.

As per your case then it seems to me magento2 bug any inputs on it?

**Comment by victor-v-rad** [comment]
I am not sure it is a bug. All special prices are better to configure in chield products. Configurable product just agregate these products. See https://docs.magento.com/m2/ce/user_guide/catalog/product-price-special.html

**Comment by anurag0202** [comment]
Originally the problem is after Migration from m1 to m2 the configurable child products special price is not visible in the backend under products. But its showing in front-end. If I create the new configurable product as per the reference link that is fine in that case it's working as per normal Magento process.
