### ISSUE TITLE
Data migration Installation error on Magento 2.3

### ISSUE THREAD

**Issue by rohitmittal54** [magento/data-migration-tool#643]
### Preconditions

1. PHP 7.1
2. MySQL 5

### Steps to reproduce

1. Install vanilla Magento 2.3
2. Install data migration tool for 2.3 version, I am installing from repo.magento.com as per docs

### Expected result

1. Data migration tool should be installed.

### Actual result

 ![screenshot from 2019 01 24 11 12 11](https://user-images.githubusercontent.com/42673332/51660833-f4acbd80-1fd4-11e9-82a3-6780b38afe94.png)

### Additional notes

**Comment by victor-v-rad** [comment]
Hi @rohitmittal54 

I tried composer installation of the tool right after composer installation of magento 2 and not faced the issue you have. Inventory-* modules seems also work fine.
