### ISSUE TITLE
What’s new for Magento 2.3.0 appears every time I login, form_key expires?

### ISSUE THREAD

**Issue by cscd98** [magento/data-migration-tool#644]
### Preconditions (*)
1. Magento 2.3.0 from Magento 1.14.4.0
2. PHP 7.2.14
3. MySQL 5.7.25

### Steps to reproduce (*)
1. Install Magento 2.3.0
2. Convert settings/data using data migration tool
3. Login to admin

### Expected result (*)
1. What’s new for Magento 2.3.0 appears once. You then click on it. It never comes back.

### Actual result (*)
1. What’s new for Magento 2.3.0 light box appears
2. Close it
3. You are logged back out.
4. Log back in - it's not there
5. Wait a bit until your session expires
6. Log back into Magento
7. What’s new for Magento 2.3.0 appears again!

https://github.com/magento/magento2/issues/19730

**Comment by victor-v-rad** [comment]
Hi @craigcarnell 

Cannot reproduce it on migrated Magento 2.3.0

**Comment by cscd98** [comment]
@victor-v-rad I seem to have an issue logging into Magento back end, where the form_key has expired the first time I load it. I then login, click on something, logged back out again.

Then I need to login 3rd time.

**Comment by vishveskrish** [comment]
Hi @craigcarnell , 

Agree with you, After migration to 2.3.0, We are getting the same form_key to expire error and we need to reload the page and re-login again.

**Comment by istoutjesdijk** [comment]
I had the same issue and my server time and PHP 7.2 time zone settings were not correct.

**Comment by cscd98** [comment]
The what's new message has gone for me but I still get the issue having to login 3 times.

My timezone in Magento is Europe/London, same setting in PHP. My local computer time is correct.

**Comment by pjw345** [comment]
I think we've both raised issues about this on the Magento 2 github, I don't think it's a migration issue as it only started happening once we upgraded our M2 version to 2.3.0

**Comment by cscd98** [comment]
I have done a clean install of:

Magento CE 2.3.0 - issue exists
Magento CE 2.3-develop as of today - issue does not exist (same database)
Magento EE 2.3.0 - issue exists

Question is, which PR fixed this issue in 2.3-develop!!

**Comment by cscd98** [comment]
Closing, fix here:

https://github.com/magento/magento2/issues/20060
