### ISSUE TITLE
Admin layout not working after migration in magento 2.3

### ISSUE THREAD

**Issue by NitishChauhan1991** [magento/data-migration-tool#645]
After migration in magento 2.3 the admin and product page breadcrumb is showing like xml view. I tried everything by my side but not able to solve. Please check screen shot for more info. And if you want details of the site please let me know i'll provide all.
![magento admin](https://user-images.githubusercontent.com/46959928/51731961-96e6a700-20a2-11e9-9e67-f6735e7beacb.png)

**Comment by victor-v-rad** [comment]
Hi @NitishChauhan1991 

Did you try to migrate to clean magento 2 without any extensions installed? They may be the cause

**Comment by NitishChauhan1991** [comment]
Hello,
Yes, i did it fresh and after that i installed the extension then i run the upgrade and deploy command. After that i got this issue.
