### ISSUE TITLE
migrated multiselect product attribute end up wrong type

### ISSUE THREAD

**Issue by iphigenie** [magento/data-migration-tool#646]
I thought this would already be on record but since I couldn't find it and I have bumped into it twice it's worth reporting

After migration, multi select attributes that showed fine in M1 navigation do not appear in M2
If not fixed, eventually changes to that attribute in migrated products won't save

### Preconditions
1. Start with a Magento1 with some multi select attributes
2. Make one of the attributes "show in layered navigation"

### The problem

In Magento 1 multiple select attributes are created with backend type text. 
In Magento 2 multiple select attributes are created with backend type varchar.

Migrated multiple select attributes are migrated to Magento 2 with backend type text. 
The migrated attribute data is therefore in a different table than it would be if native.

### Consequences:

At first glance everything will work fine

But:

- multi select attributes will **not appear** in the layered navigation even though they did on Magento 1
- If the attribute properties are at any point edited, then changes to the attribute on migrated products will not save properly afterwards. There is no error message, they just aren't saved

### Additional notes

Obviously the problems don't happen at migration but afterwards in M2. 

There is nothing noticeable from the admin that points to a problem. Attribute looks configured right and saves right etc.  Layered navigation shows all attributes of other types. Newly created attributes of multi select type also show fine. No error message is generated anywhere.

But clearly the layered navigation relies explicitely on the values being in the varchar table, without checking, so the layered navigation isnt showing these attributes.

If you edit the attribute and save it, its backend type value will be changed to varchar, but the data remains in the catalog_product_entity_text table. New products will have the attribute data show in the catalog_product_entity_varchar. For migrated products the attribute data will show properly in admin, but **changes won't save**. No error message is generated to show that the update query in the background has failed though.

A manual fix means changing the attribute backend value (in db or by saving) then moving all the data for the affected attributes from catalog_product_entity_text to catalog_product_entity_varchar by query.

I have tried to look around the code if I could find an example of a mapping handler that transforms on backend type into another, but no luck. This could be a "manual cleanup after migration" thing that just **needs to be documented in the "things you need to do manually"**.

see also https://magento.stackexchange.com/questions/192323/attribute-not-shown-in-layer-navigation

**Comment by victor-v-rad** [comment]
Hi @iphigenie 

Thank you for reporting informative issue. It is reproducible and internal ticket MAGETWO-98089 is created to fix it.

**Comment by jamsheer** [comment]
Hi @victor-v-rad Any luck with the above bug?

**Comment by victor-v-rad** [comment]
Sorry @jamsheer for late reply. Not yet but the project of open source and anyone can contribute to make it better.

**Comment by MartinAarts** [comment]
We're having the same issue, and although I found a couple of threads on the internet about this issue I still haven't found a solution.

This breaks a lot of the layered navigation functionality.

**Comment by iphigenie** [comment]
Hi @victor-v-rad if someone familiar with the project could give us a few insights what would be a smart way to shoehorn it I'm happy to have a go. But as I found no similar situation in the code, I'm not sure where to put it. All I have ever done on this one is look around to understand what waw happening when not documented.

The basics are simple, detect that an attribute is multiselect and modify it before or during migration. Copy the data to a different table than it was in the M1

Do we modify the main code or is it best structured  as a separate handler (just in case M1 changes?)

Is it ok to add some information about this to the "not migrated automatically" information in the docs?

@MartinAarts the simple way at the moment is to run a "select ... into ..." to copy the data to the correct table. It is simple if you only have a few attributes, becomes a mess if you have a lot...

**Comment by MartinAarts** [comment]
> @MartinAarts the simple way at the moment is to run a "select ... into ..." to copy the data to the correct table. It is simple if you only have a few attributes, becomes a mess if you have a lot...

I have tried this, but can't get the attributes to be visible in the front end layered navigation.

**Comment by iphigenie** [comment]
@MartinAarts you must also edit the attribute and save it (doesnt matter what you change, it will then correctly be saved with internal storage type varchar) - reindex - hopefully that should do it?

**Comment by MartinAarts** [comment]
@iphigenie Did this too, but still didn't work. Can't figure out what I'm missing...

**Comment by iphigenie** [comment]
@MartinAarts :( then you're stuck with legwork. Maybe create a new product and compare whats in the tables to see if you spot whats missing (you probably already did, sorry!)

When I was trying to get my head around it (first time in Jan 2018, and again this February as I had totally forgotten, duh!), I first edited the attribute to check that it was properly configured for layered navigation (it was). After that I noticed changes to the attribute in a product wouldn't be saved (they were before). I created a clean new attribute and that worked in navigation. So i created a clean new product and once I did that, suddenly the "bad" attribute was in layered navigation, but that one product only.

And then I went to search on stackexchange (why didnt i do that first???), found the ticket I linked to. and compared things in the database. It worked for me to move the rows, reindex, clear caches... but it has been a while.

**Comment by MartinAarts** [comment]
Thanks @iphigenie got it figured out, and most attributes working again now!

**Comment by lernerValeriy** [comment]
Data are written to the wrong table when Delta Migration is used after this fix.
Data are written to the catalog_product_entity_text but expected catalog_product_entity_varchar.

**Comment by mattyl** [comment]
for those following after and like  me have to work out the sql
INSERT INTO `catalog_product_entity_varchar` (`attribute_id`,`store_id`,`entity_id`,`value`)
SELECT `attribute_id`,`store_id`,`entity_id`,`value`
FROM `catalog_product_entity_text`
WHERE `attribute_id`='xxx'; 
where xxx is the attribute id
this worked for me

**Comment by PascalBrouwers** [comment]
With the 2.4.1 version I see this issue is still there. Multiselect attribute values are not found either in varchar or text table.

**Comment by PascalBrouwers** [comment]
@victor-v-rad or @iphigenie can you open this issue again?

**Comment by iphigenie** [comment]
> for those following after and like me have to work out the sql
> INSERT INTO `catalog_product_entity_varchar` (`attribute_id`,`store_id`,`entity_id`,`value`)
> SELECT `attribute_id`,`store_id`,`entity_id`,`value`
> FROM `catalog_product_entity_text`
> WHERE `attribute_id`='xxx';
> where xxx is the attribute id
> this worked for me

Remember to clear the entries in the text table - these remaining entries just bit me when I upgraded to 2.4.1 and elasticsearch

can't seem to have reopen option, but checking

**Comment by iphigenie** [comment]
@victor-v-rad either something was lost out of the commit https://github.com/magento/data-migration-tool/commit/c65b2839ac03ccc56aab5b37dbada95d61757034 OR some of the changes need to be put into the delta file too 

If you can reopen some of the people in this thread might look into it

**Comment by PascalBrouwers** [comment]
I did a data migration, not a delta migration btw.

**Comment by iphigenie** [comment]
> I did a data migration, not a delta migration btw.

probably worth trying to see what of that commit might have been lost in the 2.4 upgrade - because it had fixed it

**Comment by PascalBrouwers** [comment]
Most of the code is in there. The only change I can find is this:
https://github.com/magento/data-migration-tool/commit/c65b2839ac03ccc56aab5b37dbada95d61757034#diff-2cf82acb061b809f48aeeffe5f07590dd3603a02b8d238326c71f83ee0184b9b

Which in 2.4 looks like:
```
            if ($recordsCountSource != $recordsCountDestination) {
                $documentsToSave[$document] = $recordsCountSource - $recordsCountDestination;
            }
```

**Comment by PascalBrouwers** [comment]
But that looks ok
Also a small difference in src/Migration/Step/PostProcessing/Data/EntityTypeTextToVarcharMover.php
an added
`if ($multiselectIds) {`

**Comment by DegrizNet** [comment]
When migratin with last version there is a problem migrating multi select attributes with filter options. As attributes are as varchar filtration of that attributes is not possible. I fixed issues with code below.

First find attributes with problems:
`SELECT * FROM `eav_attribute` WHERE `backend_type` LIKE 'varchar' AND `frontend_input` LIKE 'multiselect'`
You get IDs of problematic attributes (example 167) than use code below:
`update eav_attribute set backend_type='text',is_user_defined=0 where attribute_id=167;
INSERT INTO catalog_product_entity_text(attribute_id,store_id,entity_id,value)
SELECT attribute_id,store_id,entity_id,value
FROM catalog_product_entity_varchar
WHERE attribute_id='167';
delete from catalog_product_entity_varchar where attribute_id=167;`
This fixed my problems.
