### ISSUE TITLE
You cannot define a correlation name 'links' more than once

### ISSUE THREAD

**Issue by gerym77** [magento/data-migration-tool#648]
### Summary (*)
When I click on a product in frontend detail view in Magento 2.2.6  I get the error message "You cannot define a correlation name 'links' more than once". All date comes from magenta migration tool. I have a lot of imported attributes. Magento is a clean version with no extensions or any changes in the code. there are no attributes called "links"

###  Information on your environment (*)
Magento 2.2.6
migrated from 1.9.3.10

### Examples (*)
this is link to a detail view which shows the error: http://dev.emeibaby.com/en/catalog/product/view/id/426/s/emeibaby-babycarrier-chichi-red-baby-size/category/82/
this is not happening on all products, for example this one works fine:
http://dev.emeibaby.com/en/catalog/product/view/id/630/s/emeibaby-babycarrier-all-surya-mela-baby-size/category/82/

### Expected and actual results (*)
show product standard detail view, 
actual result: error message on some products, not all

**Comment by victor-v-rad** [comment]
Hi @gerym77 

The issue is in \Zend_Db_Select::_join method. You can find the error message there. I can suggest debugging this method to see when 'links' is added into property $this->_parts[self::FROM] for the second time
