### ISSUE TITLE
Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/siteurl/vendor/magento/framework/Config/Dom.php on line 392

### ISSUE THREAD

**Issue by CharanjeetE** [magento/data-migration-tool#649]
### Preconditions (*)
1.I am trying to migrate data from magento 1 to magento 2
2.

### Steps to reproduce (*)
1.Running the below command
sudo php /var/www/siteurl/bin/magento migrate:settings -r /var/www/siteurl/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.7/
2.

### Expected result (*)
1. [Screenshots, logs or description]
   2.The Migration completed message is displayed after the settings are transferred successfully.

### Actual result (*)
1. [Screenshots, logs or description]
2. Warning: DOMDocument::loadXML(): Empty string supplied as input in /var/www/m2.gocleaning.nl/vendor/magento/framework/Config/Dom.php on li
   ne 392

I have checked the system.log and exception.log but not found anything. Please help me to fix this issue.

**Comment by CharanjeetE** [comment]
Please help me to resolve the above.

**Comment by victor-v-rad** [comment]
Hi @CharanjeetE 

I see name of config.xml file is missing. Should be something like this: 
sudo php /var/www/siteurl/bin/magento migrate:settings -r /var/www/siteurl/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.7/config.xml

**Comment by CharanjeetE** [comment]
Now getting this error                                                
  SQLSTATE[HY000] [2002] Connection timed out

**Comment by hzubyrss** [comment]
you running the command without file name you have to give the file name as well which is configu.xml 
Should look like this 
 php /var/www/siteurl/bin/magento migrate:settings -r /var/www/siteurl/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.7/config.xml
