### ISSUE TITLE
"This product doesn't exist" after migrating from 1.9.10 to 2.2.6

### ISSUE THREAD

**Issue by gerym77** [magento/data-migration-tool#653]
### Preconditions

Magento version 1.9.10, 
Magento Version 2.2.6, fresh install
php Version 7.1

### Steps to reproduce

migrating from Magento 1.9.10 to 2.2.6 using data migration tool

### Expected result

be able to edit products in backend

### Actual result

can't edit products in backend of Magento 2.2.6 anymore, same issue with all products
Error message: This product doesn't exist. 
exception log:

> main.CRITICAL: Item (Magento\CatalogInventory\Model\Stock\Status) with the same ID "3203" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\\CatalogInventory\\Model\\Stock\\Status) with the same ID \"3203\" already exists. at /home/shop/magento4/Magento-CE-2/vendor/magento/framework/Data/AbstractSearchResult.php:270)"} []

<img width="1037" alt="bildschirmfoto 2019-02-11 um 22 52 44" src="https://user-images.githubusercontent.com/33874979/52597120-5634af00-2e52-11e9-94dd-6772daa19b39.png">

### Additional notes

**Comment by victor-v-rad** [comment]
Hi @gerym77 

Look into cataloginventory_stock_status table if there are duplicated records with product_id = 3203

**Comment by gerym77** [comment]
Hi @victor-v-rad 
> 
> Look into cataloginventory_stock_status table if there are duplicated records with product_id = 3203

yes there are up to 4 entires for all products.
which ones can I delete?
<img width="646" alt="bildschirmfoto 2019-02-12 um 10 16 59" src="https://user-images.githubusercontent.com/33874979/52624595-5dd67100-2eaf-11e9-9a7a-99512cfbb2e6.png">

**Comment by victor-v-rad** [comment]
Do you have any extensions which allows to use several stock/warehouses with different addresses?

**Comment by gerym77** [comment]
yes there will be but not installed yet, wanted to migrate everything on a clean way first

**Comment by gerym77** [comment]
@victor-v-rad 

I compared the 2 databases now and saw following differences in Magento 1 and 2 for the same product id:

**Magento 2**
<img width="644" alt="bildschirmfoto 2019-02-14 um 14 34 48" src="https://user-images.githubusercontent.com/33874979/52791264-d3d20800-3068-11e9-9d5d-fbd47065acbb.png">

**Magento 1**
<img width="678" alt="bildschirmfoto 2019-02-14 um 14 56 04" src="https://user-images.githubusercontent.com/33874979/52791291-e9dfc880-3068-11e9-9b09-1fd44290e5ce.png">

in map.xml I ignored all fields coming from the warehouse extension like this:

`<ignore><document>erp_inventory</document>
            </ignore>
            <ignore><document>erp_inventory_log</document>
            </ignore>
            <ignore><document>erp_inventory_missed_location</document>
            </ignore>
            <ignore><document>erp_inventory_product</document>
            </ignore>
            <ignore><document>erp_inventory_stock_picture</document>
            </ignore>
            <ignore><document>erp_sales_flat_order_item</document>
            </ignore>
            <ignore><document>erp_sales_history</document>
            </ignore>
            <ignore><document>erp_stock_transfer</document>
            </ignore>
            <ignore><document>erp_stock_transfer_products</document>
            </ignore>
            <ignore><document>erp_stockmovement_adjustment</document>
            </ignore>
            <ignore><document>erp_view_supplyneeds_base</document>
            </ignore>
            <ignore><document>erp_view_supplyneeds_global</document>
            </ignore>
            <ignore><document>erp_view_supplyneeds_warehouse</document>
            </ignore>`

**Comment by victor-v-rad** [comment]
Sorry for late reply. Cannot reach to my working laptop. I will process this issue when I be able to

**Comment by gerym77** [comment]
@victor-v-rad no worries, look forward to hear from you

**Comment by victor-v-rad** [comment]
Hi @gerym77 

If you have this https://www.boostmyshop.com/extension-logistique.html extension installed in your Mangento 1.  You can try the same extension but for Magento 2 https://www.boostmyshop.com/erp-inventory-magento-2.html and migrate. The extension for M2 can be fully compatible with data transferred from M1
Or you can switch to Magento MSI

**Comment by gerym77** [comment]
@victor-v-rad 
I decided to switch to Magento MSI.. but will install this without migrating any data from ERP or any other extension.

now following situation appears:

if I delete all duplicated entries from cataloginventory_stock_status table everything works fine and I can view and edit the product how it should be..

after reindexing data, duplicated entries are showing up again and the same problem comes up again

do you have any idea what I can do about this? 

many thanks

Gery

**Comment by victor-v-rad** [comment]
cataloginventory_stock_status is index table. Here is good documentation about MSI
https://devdocs.magento.com/guides/v2.3/inventory/
https://github.com/magento-engcom/msi/wiki/Technical-Vision.-Catalog-Inventory
