### ISSUE TITLE
Can't view products list in admin

### ISSUE THREAD

**Issue by Pekkonen** [magento/data-migration-tool#654]
### Preconditions (*)
1. Magento 2.3.0.
2. PHP 7.2.14
3. MySQL - 5.6.43
4. data-migration-tool 2.3.0

### Steps to reproduce (*)

1. I have about 6700 products on site (migrated from Magento 1.9 with Data Migration Tool)
2. When I open Catalog - Products I see list of products
3. I need sort products by descending ID and click to "ID header"

### Expected result (*)
1. Standard product list

### Actual result (*)
1. I see an error http://easycaptures.com/fs/uploaded/1144/6116459710.jpg "Attention. Something went wrong." and "Something went wrong with processing the default view and we have restored the filter to its original state."
2. If I click to "OK" I still see infinite loader, can't change sorting for products or change filter settings because this area is inactive - http://easycaptures.com/fs/uploaded/1144/1345750737.png
3. Now I can't view products and can't change any settings, e.g. sort by name etc.
4. Magento logs is clean

**Comment by victor-v-rad** [comment]
Sorry for late reply. Cannot reach to my working laptop. I will process this issue when I be able to

**Comment by Pekkonen** [comment]
Thanks!
I'm not 100% sure that reason of this bug is "data-migration-tool" But on clean Magento 2.3 can't reproduce this issue too... ( I think it's not a bug of Magento core

**Comment by victor-v-rad** [comment]
I migrated a M1 store and be able to sort by Id in products grid without issues.

**Comment by ndianabasi** [comment]
I am having this same issue. I migrated from M1 to M2 for 4 months ago and had been using the backend without any issues. I haven't installed any new extension for the past 3 months. However, this issue just started 2 days ago on a particular user's account. Reset the user's entries on the ui_bookmark table solves the problem temporarily, but returns immediately the user runs a filter on the product listing.
