### ISSUE TITLE
Data migration after product edit not working

### ISSUE THREAD

**Issue by ankit-root** [magento/data-migration-tool#655]
Magento 1.9.0.1 to 2.2.6 data-migration process after catalog edit process not working. we are facing error mention below. we have used opensource-to-opensource migration process.

2019/02/13 13:48:44 [error] 12924#12924: *2997 access forbidden by rule, client: 127.0.0.1, request: "POST /app/etc/config.php HTTP/1.1"
2019/02/13 13:49:34 [error] 12924#12924: *2996 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/html/magentofirst/vendor/magento/framework/View/Element/UiComponentFactory.php on line 220 and defined in /var/www/html/magentofirst/vendor/magento/framework/View/Element/UiComponentFactory.php:172
Stack trace:
#0 /var/www/html/magentofirst/vendor/magento/framework/View/Element/UiComponentFactory.php(220): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('file_upload', NULL)
#1 /var/www/html/magentofirst/vendor/magento/module-ui/Component/Form/Field.php(84): Magento\Framework\View\Element\UiComponentFactory->create('file_upload', 'jvs_file', Array)
#2 /var/www/html/magentofirst/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\Ui\Component\Form\Field->prepare()
#3 /var/www/html/magentofirst/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Mag" while reading response header from upstream, request: "GET /ehplabsc_admin/catalog/product/edit/id/17/key/92aa8bf2ecf6e11ae581cad0e4bcdb858aaccc2cf9e855227c028aae9d0abe6d/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:",  referrer: "/ehplabsc_admin/catalog/product/index/key/b9343c636b54b4e9610ef57d06abc660345bdd4c111005357f6744056ba48db6/"

**Comment by victor-v-rad** [comment]
Sorry for late reply. Cannot reach to my working laptop. I will process this issue when I be able to

**Comment by victor-v-rad** [comment]
HI @ankit-root 

Try to find attributes 'file_upload' or 'jvs_file' in eav_attributes table of M2. These attributes probably from M1 extensions and cause the issue.
