### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'SALES_ORDER_INCREMENT_ID_STORE_ID'          

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [magento/data-migration-tool#656]
Hi,
I am using this data-migration-tool, 
When i migrate from magento 1.9.3.2 to magento 2.3,getting below error,

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'SALES_ORDER_INCREMENT_ID_STORE_ID'     

i tried many times upload fresh DB,still getting this issue

**Comment by victor-v-rad** [comment]
Cannot reach to my working laptop right not. I will process this issue when I be able to

**Comment by victor-v-rad** [comment]
Hi @sumeetmobiwebtech 

Please check if UNQ_SALES_FLAT_ORDER_INCREMENT_ID unique key exists in sales_flat_order table of your M1 DB. You probably have duplicates of data in increment_id field. Fix these duplicates and try to migrate again

**Comment by sumeetmobiwebtech** [comment]
thanks @victor-v-rad , yes this was the error i already solved that.
thanks again
