### ISSUE TITLE
Data Migration setting command after error

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#657]
When i run below command 

`sudo php bin/magento migrate:settings --reset /vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.4.0/config.xml`

after below error showing 

>  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'principal' for key 'STORE_GROUP_CODE'

**Comment by victor-v-rad** [comment]
Cannot reach to my working laptop right not. I will process this issue when I be able to
