### ISSUE TITLE
Extend Data Migration Toool Module

### ISSUE THREAD

**Issue by dhiraj-danode** [magento/data-migration-tool#658]
We only want to migrate customers and order from magento M1 to M2.
So we need to modify config.xml and map.xml

So can we extend those files in app/code

**Comment by victor-v-rad** [comment]
Cannot reach to my working laptop right not. I will process this issue when I be able to

**Comment by victor-v-rad** [comment]
Hi @dhiraj-danode
Right now the tool does not support  partial migration of entities (like catalog, customers, etc.) out of the box. But you always can skip unnecessary steps in your config.xml and ignore unwanted tables in map.xml file and their data won't be migrated. Please see some examples
https://github.com/magento/data-migration-tool/issues/406
https://github.com/magento/data-migration-tool/issues/326
https://github.com/magento/data-migration-tool/issues/427
