### ISSUE TITLE
Migration 1.9.4 to Magento 2.3.0 Setting command after error

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#659]
When i run below command

> sudo php bin/magento migrate:settings --reset vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.4.0/config.xml

**after below error showing**

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'principal' for key 'STORE_GROUP_CODE'`

**Comment by victor-v-rad** [comment]
Hi @rakeshdonga 

The field store_group.code is new in M2 and it has unique key. It creates from store_group.name . Given that core_store_group.name in M1 is not unique it can lead to the issue you have. To hot fix it, you can rename one of your store group with name "principal" to something different. Any way MAGETWO-98530 to fix it

**Comment by rakeshdonga** [comment]
Thank you for help i have solved this issue
