### ISSUE TITLE
Data migration 1.14.4 to 2.2.7 table sales_order_entity doesn't exist

### ISSUE THREAD

**Issue by swgib** [magento/data-migration-tool#662]
### Preconditions

1. Source Magento version: 1.14.4
2. Target Magento version 2.2.7

### Steps to reproduce
1. Install Magento 2.2.7 via composer into empty new environment (Plesk) - Completed
2. Install and configure data migration tool for Magento 2.2.7 - Completed
3. Migrate settings from source Magento into target Magento - Completed
4. Migrate data from source Magento into target Magento - Error

### Expected result
1. The data from the source Magento is imported into the target Magento

### Actual result
After running the data migration command, a little way in I am prompted with the following information with errors:
[INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
84% [=======================>----] Remaining Time: 8 secs

  [Zend_Db_Statement_Exception]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'source.sales_order_entity' doesn't exist, que
  ry was: SELECT DISTINCT  `child`.`entity_id` FROM `s_sales_order_entity_datetime` AS `child`
   LEFT JOIN `sales_order_entity` AS `parent` ON child.entity_id = parent.entity_id WHERE (child.entity_id I
  S NOT NULL) AND (parent.entity_id IS NULL)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'source.sales_order_entity' doesn't exist

### Additional notes
1. There are no underscores in either of the database names - a possible link to another issue raised.
2. The configuration changes made to the data migration config.xml file were entering the basic database details and prefixes. The configuration file in question: /vendor/magento/data-migration-tool/etc/commerce-to-commerce/1.14.4.0/config.xml
3. Checking the source database, the table in question doesn't exist. This thread (https://magento.stackexchange.com/questions/11755/sales-order-table-missing-after-update) suggests that the table may have been removed during a previous upgrade of Magento.

**Comment by victor-v-rad** [comment]
Hi @swgib 

sales_order_entity* tables are from early releases of M1 and should have been converted into sales_flat_order. Please recheck that data in sales_order_entity* also is int sales_flat_order and if it so you can either drop sales_order_entity* tables in DB or just remove "Data Integrity Step" from migration. Internal ticket MAGETWO-98550 to fix it

**Comment by victor-v-rad** [comment]
I cannot to reproduce this issue. Maybe it was a cache issue. I tried to rename sales_order_entity_datetime to s_sales_order_entity_datetime but it did not helped.
