### ISSUE TITLE
Migration Eav step error

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#663]
**data migration > EAV Step**

> `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'`

i have find solution [here][1] but not work for me also i have remove duplicate attribute set 

[![enter image description here][2]][2]

  [1]: https://magento.stackexchange.com/questions/92578/data-migration-eav-step-error
  [2]: https://i.stack.imgur.com/PmbJJ.png

**Comment by victor-v-rad** [comment]
Hi @rakeshdonga 

The advise from stackexchange.com is correct `Restore your Magento 2 database from a copy that you (hopefully) made before running the migration tool.` Please recheck that in restored DB you have only `Default` attribute set in eav_attribute_set table

**Comment by rakeshdonga** [comment]
i have tried this but still not work for me
