### ISSUE TITLE
Custom category attributes disappear on category save

### ISSUE THREAD

**Issue by pocallaghan** [magento/data-migration-tool#664]
### Preconditions
1. Migrating from Magento 1.9.4.0 to Magento 2.3.0.
2. Custom category attributes.

### Steps to reproduce
1. Add a custom attribute to a category in M1 (needs to be done in code, as there's no GUI capability for it).
2. Migrate the store from M1 to M2.
3. Save a category.

### Expected result
1. All attributes associated with the Category prior to saving should still be associated.

### Actual result
1. Upon save of a category, the `attribute_set_id` of the category is set to the default value (this happens in the Save controller), this is an attribute set called `Default`, rather than the attribute set it had before saving which was `Migration_Default`. Since the custom attributes migrated from M1 aren't associated with the new attribute set, those attributes are no longer loaded when the category is loaded.

### Additional notes
Upon save the data for the attribute isn't lost, it's still in the database, it's just no longer loaded when the category is loaded because it filters on attribute_set_id.

**Comment by victor-v-rad** [comment]
Thank you @pocallaghan for reporting this issue and providing a good explanation. Internal ticket MAGETWO-98589 to fix it

**Comment by helmut-hoffer-von-ankershoffen** [comment]
@victor-v-rad : Was there any progress and is there a workaround  to make custom category attributes work after migration?

**Comment by victor-v-rad** [comment]
Hi @helmuthva @pocallaghan 
As a hot fix, you can change the value of default_attribute_set_id field in eav_entity_type table of Magento 2 DB to Migration_Default attribute set. Then clear cache and it should fix the issue with custom category attributes.

**Comment by helmut-hoffer-von-ankershoffen** [comment]
@victor-v-rad :  I can confirm the workaround worked.

**Comment by jesse-thomas** [comment]
Is this fixed in the data migration tool v2.3.3? I am having a similar issue.

**Comment by victor-v-rad** [comment]
yes this particular the issue was fixed in v2.3.3

**Comment by jesse-thomas** [comment]
I wonder if I'm having the same issue or something else. I'm on 2.3.3/2.3.3 magento-ce/data migration tool. 
After I run the migration I have to switch the default_attribute_set_id in eav_entity_type for categories to be able to save custom category attributes. 
But it's just for one module's custom attributes (smile es), two other module's custom attributes are able to save and are included in the Migration_Default attribute set. All attributes are installed before migration, but the smile attributes are not migrated (could that be why they are not included in "Migration_Default").

Not trying to hijack this issue, just trying to track this down. Thanks for the reply!

**Comment by jesse-thomas** [comment]
Reverting the commit above causes the data migration to work as expected for me, allowing custom category attributes that only exist in M2 to be saved. ie sets the default_attribute_set_id to the attribute set with all the attributes. 

Should Migrated_Default contain the M2 only attributes as well?
