### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry '2-1450051200-1450742399-1-1-85-1' for key 'IDX_EAA51B56FF092A0DCB795D1CEF812B7B

### ISSUE THREAD

**Issue by yogeshkhasturi** [magento/data-migration-tool#667]
### Preconditions

1. Using data migration tool 2.2.6
2. Migration from 1.9.3.1 to 2.2.6

### Steps to reproduce

1.  migration data with **bin/magento migrate:data** cammand.

### Expected result

1.  data shold migrate as we are using -a to ignore error

### Actual result

1. [Screenshot, logs]
Getting duplicate error : Integrity constraint violation: 1062 Duplicate entry '2-1450051200-1450742399-1-1-85-1' for key 'IDX_EAA51B56FF092A0DCB795D1CEF812B7B'

![image](https://user-images.githubusercontent.com/32513730/54543315-744a7d80-49c3-11e9-8048-de1e3d1d0baf.png)

### Additional notes

I have search key and table for this error. but no luck. Please help me @victor-v-rad 

Thanks in advance

**Comment by yogeshkhasturi** [comment]
@victor-v-rad would you please help me with this error ?

Thanks

**Comment by victor-v-rad** [comment]
Hi @yogeshkhasturi 

Use -vvv option to see which table of M2 causes this issue. And depending on the situation you can decide  to use map-document-groups.xml for such duplicates. It removes such duplicates during migration. But if you need all the data to be transferred, you can drop the unique index from the table. But dropping such index may also cause other issues.

**Comment by yogeshkhasturi** [comment]
Hi @victor-v-rad 

Thanks! issue is fixed now.
