### ISSUE TITLE
Magento 2.0 Sales Order Grid Empty

### ISSUE THREAD

**Issue by Rdp0888** [magento/data-migration-tool#67]
I have just migrated the data from magento 1.9.3 to magento 2.
The data migrated properly.
But on the admin backend, when I go to Reports->Sales->Orders page. It shows 0 records found.
I have data in sales-order-grid and sales_order.
I have tried clearing cache but still no luck.

Please help

**Comment by redboxmarcins** [comment]
Did you try to refresh stats?

Login to Magento 2 admin then go to Reports -> Statistics -> Refresh Statistics

**Comment by ilol** [comment]
Thanks, @redboxmarcins. 
@Rdp0888  did it help? If yes, can you please close the issue?

**Comment by ilol** [comment]
@Rdp0888  ping

**Comment by gvillafanetapia** [comment]
I'm having the same problem as @rdp-in in version 2.0.7.
Tried the solution suggested by @redboxmarcins but didn't work.

I migrated data from 1.7.0.2 successfully (i can see the data in the database tables) but nothing shows up in the Sales grids (Orders, Shipments, Invoices, etc.).

Any ideas?

Thank you.

**Comment by supanatral** [comment]
Try and redeploy the static content. This worked for me. Here is the code:
`php bin/magento setup:static-content:deploy`
