### ISSUE TITLE
Will there be a Magento 2.2.8 release of this tool?

### ISSUE THREAD

**Issue by ashsmith** [magento/data-migration-tool#670]
### Preconditions

1. You are on 2.2.7 or lower.

### Steps to reproduce

1. Update your magento installation 2.2.8

### Expected result

1. A new version of data migration tool should be available

### Actual result

1. No new version of data migration tool.

### Additional notes

Should there be a new release supporting 2.2.8?

**Comment by victor-v-rad** [comment]
Hi @ashsmith 

Right now the tool supports only one stable Magento 2.3.x branch. If you migrate a store to 2.2.x now, then sooner or later you will need to upgrade it to the latest stable 2.x. In case migration to 2.2.8 is the only option then you can backport commits from tickets MAGETWO-98785 MAGETWO-98724  MAGETWO-98723 MAGETWO-98722 MAGETWO-98720 (see [pull request](https://github.com/magento/data-migration-tool/pull/669) and commits)

**Comment by florincyberion** [comment]
This is unfortunate. I upgraded from 225 to 228 thinking I can just rerun the data migration.

**Comment by antonioste** [comment]
I've not undestand if I can use the 2.2.7 tool to migrate into 2.2.9..

someone can reply me? Thanks.

**Comment by victor-v-rad** [comment]
You can. But likely you will get integrity check errors from new DB fields of Magento 2. It can be ignored by -a option though.
