### ISSUE TITLE
Products Not importing correctly, Magento 1.9.4.0, Magento 2.3.0

### ISSUE THREAD

**Issue by jambardnishvili** [magento/data-migration-tool#671]
### Preconditions

1. I have Data Migration Tool Installed on newest Magento 2 release
2. Source Magento is 1.9.4.0

### Steps to reproduce

1. Tried to import only products by following this article https://github.com/magento/data-migration-tool/issues/406#issuecomment-342501646
2. Tried to do full migration itself aswell
3. Product name appears as described on below screenshot on every product, No price, name and Attributes available

### Expected result

1. All products Imported normally without defects

### Actual result

1. [Screenshot]
![Screenshot from 2019-03-27 19-36-23](https://user-images.githubusercontent.com/43703698/55089927-a9dc1e80-50c7-11e9-9bda-192c542cbf47.png)
This is my config.xml, configured for only products, again clarifying, result is the same when i do full migration
![Screenshot from 2019-03-27 19-37-41](https://user-images.githubusercontent.com/43703698/55090017-d4c67280-50c7-11e9-9696-f90bb27c7e4e.png)
This is the case for all products, it does import all of them but with this defect, only correct thing which is imported is SKU
![Screenshot from 2019-03-27 20-29-31](https://user-images.githubusercontent.com/43703698/55094079-173f7d80-50cf-11e9-8172-144fe365c293.png)
This is the result of full migration, Name and Price is still not displaying and as you can see quantity is messed up, but they are in database when i checked `catalog_product_entity_varchar/decimal cataloginventory_stock_item` tables

**Comment by victor-v-rad** [comment]
Hi @Vandeveon 

As I said in my comment "I have not done such experiments yet." So it was not the complete guide. As for 2.3.0 version of the tool. There is new "Inventory Step" and it is better not to disable it and include into migration.

**Comment by jambardnishvili** [comment]
![Screenshot from 2019-03-28 15-55-50](https://user-images.githubusercontent.com/43703698/55155945-17448980-5172-11e9-84bb-4da7e337b56b.png)
I'm trying to migrate with these options now, but if i do migration without -a option it fails on inventory integrity stage which means table field names and types are different but if i do it with -a it gets past it without displaying any errors, is there any reason why that would be?

![Screenshot from 2019-03-28 18-53-28](https://user-images.githubusercontent.com/43703698/55167646-cee59580-518a-11e9-8ab7-249d379e6266.png)
Result when i did data migration

![Screenshot from 2019-03-28 18-52-43](https://user-images.githubusercontent.com/43703698/55167580-b4132100-518a-11e9-9d50-30a34afbb42f.png)
Result when i did delta migration
