### ISSUE TITLE
Multi-Store Tables missing after migration from 1.9.3.10 to 2.3.0 / 2.3.1

### ISSUE THREAD

**Issue by Darkwolf81** [magento/data-migration-tool#673]
### Preconditions

1. Magento 1.9.3.10
2. Magento 2.3.1

### Steps to reproduce

1. Migrate Settings
2. Migrate Data

### Expected result

1. tables created like sequence_order_2, sequence_invoice_2, catalog_category_product_index_store2

### Actual result

1. Tables that should be created after adding a store are missing. The only tables created from indexer are catalog_category_flat_2 and catalog_product_flat_2
2. stores are migrated in store table. Orders are in the correct store. But i cant create a product or order in store 2 or higher, error is missing table

### Additional notes
I dont know if i do something wromg. I migrate setting, think here it should create the tables while migrate stores. I get no migration errors.

**Comment by victor-v-rad** [comment]
So you added new store in M2 after migration, right? I tried it and right after I added new store, new tables sequence_order_2, sequence_invoice_2, etc. were created without reindexing.

**Comment by Darkwolf81** [comment]
No, the stores were in M1 before migration. After migration the stores are there in the store table, but not the store related tables.

**Comment by victor-v-rad** [comment]
Please see #628 it may had similar root cause with 'sku'

**Comment by Darkwolf81** [comment]
These tables should created while migrating settings.
Log says all ok:

```
[2019-04-04 14:34:09][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
[2019-04-04 14:34:09][INFO][mode: settings][stage: integrity check][step: Stores Step]: started
[2019-04-04 14:34:10][INFO][mode: settings][stage: data migration][step: Settings Step]: started
[2019-04-04 14:34:12][INFO][mode: settings][stage: data migration][step: Stores Step]: started
[2019-04-04 14:34:12][INFO][mode: settings][stage: volume check][step: Stores Step]: started
[2019-04-04 14:34:12][INFO][mode: settings][stage: volume check][step: Stores Step]: Migration completed
```

When i create new storeview in backend, the tables are there (ID 8 in the screens). So i think the catalog_category_product_index_store2, catalog_category_product_index_store4 etc should be created when migrating store entries. Maybe some events not fired when creating the stores in migration process.
![added](https://user-images.githubusercontent.com/29105178/55564962-41112980-56f9-11e9-8b2e-b708ed22a0fb.JPG)
![stores](https://user-images.githubusercontent.com/29105178/55564973-453d4700-56f9-11e9-9182-ab960807e95b.JPG)

**Comment by Darkwolf81** [comment]
reindex after migration solved the problem now, dont know why it did not worked the first times.
