### ISSUE TITLE
Magento 2.3.0 : Data Migration Tool - mode: data unable to complete Map Step

### ISSUE THREAD

**Issue by soborked** [magento/data-migration-tool#675]
### Preconditions

Magento 1.9.1 and Magento 2.3.0
PHP 7.2 

### Steps to reproduce

php bin/magento migrate:data --reset --auto vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.1.0/config.xml

### Expected result

1. Ideally data migration should complete

### Actual result

[2019-04-05 18:08:22][INFO][mode: data][stage: data migration][step: Map Step]: started
13% [===>------------------------] Remaining Time: 2 hrs

Then it becomes Remaining Time: 4 hrs, 8 hrs, 9 hrs, 12 hrs, 14 hrs and doesn't ever finish.

### Additional notes

Hello,

I can complete the mode: settings no problem but I'm unable to complete [mode: data][stage: data migration][step: Map Step]. At first it will say Remaining Time: 2 hrs but then the time just keeps increasing to 14+hrs and never finishes. 

![config_2019-04-05_15-29-31](https://user-images.githubusercontent.com/9466289/55652688-46827880-57ba-11e9-9180-05d3c1a4376f.jpg)
![data_migration_map_step_2019-04-05_15-24-24](https://user-images.githubusercontent.com/9466289/55652695-4aae9600-57ba-11e9-8762-b7bd2281678b.jpg)

I already have map.xml in etc/opensource-to-opensource/1.9.1.0/ so not sure what is causing this issue. Please help.

Thanks in advance.

**Comment by victor-v-rad** [comment]
Hi @soborked 

Thank you for reporting this issue. You set 1 to bulk_size option which is too little. It it tool small. You can set 0 or something greater then 1000

**Comment by soborked** [comment]
Thank you. The issue is resolved.
