### ISSUE TITLE
Magento 2.3.1 : Data Migration Tool - mode:delta stuck in loop

### ISSUE THREAD

**Issue by soborked** [magento/data-migration-tool#676]
### Preconditions

Current Magento 1.9.1.0
Migrating to Magento 2.3.1 on Centos 7, PHP 7.2, MariaDB 10.3.14

### Steps to reproduce

php bin/magento migrate:delta --reset vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.1.0/config.xml 

migrate:settings and migrate:data went through fine. Just migrate:delta causing an issue

### Expected result

migrate:delta should ideally complete 

### Actual result

It stays stuck in a loop unless I manually cancel it:
Mismatch of entities in the document: catalog_product_entity_int Source: 57963 Destination: 55270
Mismatch of entities in the document: catalog_product_entity_varchar Source: 80594 Destination: 76940
Volume Check failed

### Additional notes

![m2-migration-delta-04082019](https://user-images.githubusercontent.com/9466289/55753913-84c9a300-5a19-11e9-918f-087d2e9f4a0a.jpg)

I looked at previous threads that might be related to this issue so I checked my current store (Magento 1.9.1.0) and all products have SKUs so not sure what is causing this issue. Please help.

Thanks in advance.

**Comment by victor-v-rad** [comment]
Hi @soborked 

Thank you for reporting this issue. Did you add these two tables to your deltalog.xml? They are not part of delta by default.

**Comment by soborked** [comment]
Hi Victor, 

Thanks for getting back to me. I did add the two tables in deltalog.xml but now it's showing this error:

![delta-delivering-failed](https://user-images.githubusercontent.com/9466289/55833058-ef93e080-5ae4-11e9-9e76-b7511dac2b3a.jpg)

![m2-migration-delta-04092019-tables-added](https://user-images.githubusercontent.com/9466289/55833147-1225f980-5ae5-11e9-88be-482deb85ff94.jpg)
 
Perhaps I didn't add them properly or in the right position?

**Comment by victor-v-rad** [comment]
Sorry @soborked , I confused you. During migration period admin user should not add new or modify products, categories, etc. Please see [the documentation](https://devdocs.magento.com/guides/v2.3/migration/migration-migrate.html) I assume that was the case. Such modifications wont migrate in delta. But if you do not need these changes then disregard the error 
>Mismatch of entities in the document: catalog_product_entity_int Source: 57963 Destination: 55270
Mismatch of entities in the document: catalog_product_entity_varchar Source: 80594 Destination: 76940
Volume Check failed
