### ISSUE TITLE
Data migration fails due to invalid regex

### ISSUE THREAD

**Issue by MichaelThessel** [magento/data-migration-tool#677]
```
  Warning: preg_replace(): Compilation failed: invalid range in character class at off  
  set 18 in /data/src/m2/vendor/magento/data-migration-tool/src/Migration/Handler/Plac  
  eholder.php on line 71 
```
I believe this is due to the `-` not being escaped in this regex:

https://github.com/magento/data-migration-tool/blob/ae091f5673cc26d1466123ddfabaebdf7af63933/src/Migration/Handler/Placeholder.php#L71

Converting the regex to this:

```
$content = preg_replace('/{{widget type="[\w\-_]+\/[\w\-_]+".+}}/mU', '', $content);
```

solved the problem for me.

**Comment by victor-v-rad** [comment]
Thank you @michizhou for reporting this issue. Internal ticket MAGETWO-99113
