### ISSUE TITLE
Successful Migration but broken backend

### ISSUE THREAD

**Issue by alexWebson** [magento/data-migration-tool#679]
### Preconditions

1. Magento 1.8.1.0 -> Magento 2.3.1 (magento 2 fresh installation)
2. PHP 7.2, Mysql 5.7, Apache 2.4

### Steps to reproduce

1. Migrate M1 to M2 with a backup DB of M1, not live.
1. Settings migration work perfectly, backend and frontend work without problems.
2. Data migrations successful (also without --auto parameter). 
3. Frontend works correctly
4. Backend not display correctly.

### Expected result

1. Backend display correctly.

### Actual result

1.  Head tag of page seems empty, except for one script.
2. The only error available is in console "ReferenceError: require is not defined"
3. In debug.log I found this "main.DEBUG: Request validation failed for action "Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor" [] []"

![Schermata 2019-04-11 alle 16 05 18](https://user-images.githubusercontent.com/29281644/55964568-3d3f5300-5c75-11e9-8d49-d1655843a690.png)
![Schermata 2019-04-11 alle 16 14 41](https://user-images.githubusercontent.com/29281644/55964574-403a4380-5c75-11e9-8459-91c67304daea.png)

**Comment by victor-v-rad** [comment]
Hi @alexWebson 

Thank you for reporting this issue. PHP error log might give more information

**Comment by alexWebson** [comment]
`[Fri Apr 12 13:04:55.968704 2019] [php7:error] [pid 3725] [client 93.65.102.178:53809] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /vendor/magento/module-backend/Block/Dashboard/Orders/Grid.php:95\nStack trace:\n#0 /vendor/magento/module-backend/Block/Widget/Grid/Extended.php(482): Magento\\Backend\\Block\\Dashboard\\Orders\\Grid->_afterLoadCollection()\n#1 /vendor/magento/module-backend/Block/Dashboard/Orders/Grid.php(84): Magento\\Backend\\Block\\Widget\\Grid\\Extended->_prepareCollection()\n#2 /vendor/magento/module-backend/Block/Widget/Grid.php(406): Magento\\Backend\\Block\\Dashboard\\Orders\\Grid->_prepareCollection()\n#3 .../vendor/magento/module-backend/Block/Widget/Grid/Extended.php(508): Magento\\Backend\\Block\\Widget\\Grid->_prepareGrid()\n#4 /vendor/magento/module-backend/Block/Widget/Grid.php(471): Magento\\Backend\\Block\\Widget\\Grid\\Extended->_prepareGrid()\n#5 .../vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\\Backend\\B in .../vendor/magento/module-backend/Block/Dashboard/Orders/Grid.php on line 95, referer: /admin/index/index/key/2a8f9ae9e678fd6e6381e5b86ab7e6e4f8631c74d26bbd84a798f610fbfc1207/`

news from php log

**Comment by victor-v-rad** [comment]
I suggest backup table sales_order_grid and remove all records. Then reindex. The table will be refilled with data

**Comment by mikedubinsky-odb** [comment]
I'm experiencing the same issue @alexWebson described, but deleting the sales_order_grid records and reindexing didn't help. Any additional suggestions would be greatly appreciated.
