### ISSUE TITLE
Magento 1.9.2.4 to Magento 2.2.6 Migration

### ISSUE THREAD

**Issue by pratikhmehta** [magento/data-migration-tool#684]
### Preconditions

1. I want to migrate Magento-2.2.6 from Magento-1.9.2 but in tool i saw from 1.11.0.0 versions. So how can i migrate it ?

**Comment by victor-v-rad** [comment]
Hi @pratikhmehta 
You are probably looking in commerce-to-commerce folder but should in opensource-to-opensource
