### ISSUE TITLE
"Payment method is not available" error

### ISSUE THREAD

**Issue by guarinogabriel** [magento/data-migration-tool#685]
### Preconditions
1. Magento 1 version: 1.9.2.2
2. Magento 2 version: 2.3.0
3. Orders that were placed in the Magento 1 store using any of the Paypal payment methods

### Steps to reproduce
1. Proceed with the data migration
2. Review the orders in the Magento 2 admin panel after the migration

### Expected result
1. The orders should display the payment information

### Actual result
1. The payment information block for the orders is displaying the following text: "Payment method is not available. You still can process offline actions".

### Additional notes

After investigating this problem, I found that this is related to two potential reasons:
* The order was placed in Magento 1 using a custom payment method that is not available in Magento 2.
* The order was placed in Magento 1 using a default payment method that is available in Magento 2 but the payment method code has changed.

I have identified the following methods that should be renamed in the database after the migration to fix the issue:

Name | Method code in Magento 1 | Method code in Magento 2
-- | -- | --
PayPal Express Checkout | paypal_express | paypal_express
Paypal Credit | paypal_express_bml | payflow_express_bml
PayPal Payments Pro | paypal_direct | Need information
PayPal Website Payments Standard | paypal_standard | Need information
PayPal Express Checkout Payflow Edition | paypaluk_express | payflow_express
PayPal Payments Pro Payflow Edition | paypaluk_direct | Need information
Payflow Pro | verisign | payflowpro
PayPal Billing Agreement | paypal_billing_agreement | paypal_billing_agreement
Payflow Link | payflow_link | payflow_link
Payflow Advanced | payflow_advanced | payflow_advanced
Payment by cards or by PayPal account | hosted_pro | hosted_pro

It would be ideal if the renaming is automatically done by the data migration tool during the migration process.

**Comment by victor-v-rad** [comment]
Hi @guarinogabriel 

Thank you for reporting this issue. Internal ticket MAGETWO-99382 to fix it

**Comment by victor-v-rad** [comment]
Hi @guarinogabriel 

Sorry for delay. The fix is in a280dc2

**Comment by guarinogabriel** [comment]
Hi Victor,


Thanks for letting me know.

I will try the updated version of the data migration tool and let you know
if we have any issue.


Thanks again!
Gabriel

**Comment by spaho1986** [comment]
Hi Victor,

I see this configuration in map.xml:  https://cl.ly/e127c76b8836
can you help us how we should handler "authorizenet" payment method?

Best regards.
Ilir

**Comment by jas8522** [comment]
This also occurs when you were using the savedcc payment method with 1.9 which isn't available with 2.x... if the store admin needs to manually process those credit cards but can't view them in Magento 2, how is that suposed to work? Shouldn't Magento2 have a dummy payment gateway that's mapped to the savedcc gateway which allows admins to view the credit card details when viewing the order?
