### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by istoutjesdijk** [magento/data-migration-tool#686]
I'm getting the following error using the Magento 2 Migration Tool 2.3.0 during the Map Step:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0--0--0.0000-0.0000-0-' for key 'UNQ_D2BA9F275EE0D3F3C26A1EC39FD4924D'`

I have searched on Google for this error but cannot find anything similar. How can I find where this is coming from?

Is there a way to find out which table or key is causing this error?

UPDATE: Found it after hours of searching and excluding tables. It is caused by the TIG PostNL plugin.

**Comment by rickbakker** [comment]
@istoutjesdijk Thanks for the info! I'm having the same issues right now. Migration went pretty good, but at 94% in with the data migration i got that exact error. I see that you found out that it's because of the TIG PostNL plugin. How did you manage to fix this error? 

I'm on M1 1.9.4.1 and M2 2.3.4 BTW.

**Comment by istoutjesdijk** [comment]
I don't remember exactly because it's a year ago and I have had allot of other problems with Magento in the meantime. I think I just disabled or deleted the PostNL plugin and installed it again after migration.

Please let me know if this works, I might have some other suggestions if it doesn't.

**Comment by rickbakker** [comment]
Thanks for your reply @istoutjesdijk. I have fixed the issue and did a successful migration. There is a way to ignore the tig_post_nl tables while migrating. You have to make some changes to the config and map files. I did some more searching on Google until i found this piece of text: 

https://docs.tig.nl/display/TIGSD/Migreren+van+Magento+1+naar+2+i.c.m.+de+PostNL+extensie

Check it out. Maybe it's useful sometime. Cheers!
