### ISSUE TITLE
map.xml table ignore issue

### ISSUE THREAD

**Issue by dentonsnet** [magento/data-migration-tool#687]
### Preconditions
1.  Data transfer from Magento 1.9.4.1 to 2.3.1
2. PHP version 7.2

### Steps to reproduce
1. Set up config.xml file to point to map.xml file
2. add to the map.xml table exception rules
3. run migrate:data command 

### Expected result
1. Migration should ignore specified tables and run correctly

### Actual result
1. Command fails as it can not find tables that were specified in ignore.

My config within config.xml
![Screen Shot 2019-05-16 at 11 53 00](https://user-images.githubusercontent.com/16917188/57848804-ac0e4f80-77d1-11e9-8efa-a22c1491f3de.png)

My map.xml config
![Screen Shot 2019-05-16 at 11 53 27](https://user-images.githubusercontent.com/16917188/57848851-c5170080-77d1-11e9-9c58-c121fc95e6e1.png)

The result in my terminal once command has been run
![Screen Shot 2019-05-16 at 11 53 55](https://user-images.githubusercontent.com/16917188/57848887-dd871b00-77d1-11e9-8e2f-9b40726f31d7.png)

 
[Screenshot, logs]

**Comment by victor-v-rad** [comment]
Hi @dentonsnet 

Thank you for reporting this issue. Probably it is not related to map.xml table ignore. Please look at similar #270 #294

**Comment by dentonsnet** [comment]
Hi @victor-v-rad 

Thank you. For anyone else who has this issue, my solution was mentioned in ticket [#270](https://github.com/magento/data-migration-tool/issues/270). I commented out the block added to the config.xml.dist files from commit MAGETWO-60344.
