### ISSUE TITLE
Mapping website_id value using <transform>

### ISSUE THREAD

**Issue by object-source** [magento/data-migration-tool#688]
In my Magento 1 database I have a number of website_id values that need to be mapped to a different value in the Magento 2 database. For example in Magento 1 website_id 9 = website_id 2 in the Magento 2 database. I have inserted the following into the map.xml file:

map > source > field_rules >

```
<transform>
                <field>customer_entity.website_id</field>
                <handler class="\Migration\Handler\Convert">
                    <param name="map" value="[9:2]"/>
                    <param name="defaultValue" value="1" />
                </handler>
</transform>
```

When running the migration tool it seems that this transform rule is being ignored. Is there a better way of mapping website_id values? Or is there a setting I need to change in order to enable this sort of transform field rules?

**Comment by victor-v-rad** [comment]
Hi @object-source 

It is because customer_entity is processed by Customer step. Please use map-customer.xml file
