### ISSUE TITLE
[stage: data migration][step: Map Step] doesn't proceed

### ISSUE THREAD

**Issue by magepro-dev** [magento/data-migration-tool#690]
Hi i have a problem with migration with products ~ 300k

i tried to change bulk_size from 0 to 3000 and nothing 

time more and more but no any process

as well issue 
Document catalog_category_product can not be copied directly because of error: SQLSTATE[42S02]: Base table or view not found

but catalog_category_product is exist at database

### Preconditions

1. Magento 1.9.2.4 -> Magento 2.3.1
2. PHP 7.1.30, Percona 5.7.26
3. 300k products

### Steps to reproduce

1. php bin/magento migrate:data --reset --auto vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml

### Expected result

1. complete migration 

### Actual result

1. 
<img width="1203" alt="Screen Shot 2019-06-03 at 6 47 59 PM" src="https://user-images.githubusercontent.com/50410056/58815379-22afa780-8630-11e9-8ff8-5aa71879caeb.png">

2. config
<img width="944" alt="Screen Shot 2019-06-03 at 6 48 46 PM" src="https://user-images.githubusercontent.com/50410056/58815441-3eb34900-8630-11e9-9a3d-e8ce1e221105.png">

**Comment by victor-v-rad** [comment]
HI @magepro-dev 

It can be Magento 2 cache issue. Please remove cache folder and try to migrate with direct_document_copy = 0

**Comment by magepro-dev** [comment]
thanks for your reply... but i resolved it tonight... just downloaded M1 database and uploaded to the same database with M2. i mean the same mysql server

**Comment by victor-v-rad** [comment]
Good. Thank you for your reply
