### ISSUE TITLE
Update Product data  after one time data migration done

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/data-migration-tool#691]
Hello,

I have done data migration from magento 1.9.1.0 to magento 2.2.6. 
After that I have solved many issues like column type in many of tables. During that time new attributes as well as product attribute options are added in the magento 1.
Now I want that data to be migrated in magento 2. Please let me know how to do that.

Thanks

**Comment by victor-v-rad** [comment]
Right now the tool does not support migration of new or modified products or attributes in delta mode.

**Comment by baljinderimpinge** [comment]
hello @victor-v-rad 
thanks for the reply. So can you please let me know how to proceed to get updated data like attributes, attributes sets, products etc to magento 2?
Also during delta migration, new customers and order are not updated although command line show delta migration is successfully completed.

Thanks

**Comment by victor-v-rad** [comment]
You add these new products and attributes to Magento 2 manually.  Customers and orders are part of delta and should be migrated. Please check that in M1 database tables like m2_cl_sales_flat_order* and triggers trg_sales_flat_order_* are exist

**Comment by baljinderimpinge** [comment]
Hello @victor-v-rad ,

I have checked that m2_cl_sales_flat_order* are present there but triggers trg_sales_flat_order_* are not. Also can you please let me know if we can make any customization in the data tool to migrate also attributes and products in delta migration?

Thanks

**Comment by baljinderimpinge** [comment]
hello @victor-v-rad 
Please let me know. I am waiting for your response.
Thanks

**Comment by victor-v-rad** [comment]
Hi @baljinderimpinge 

As I mentioned in my first comment the tool does not support migration of new or modified products or attributes in delta mode. But the tool is open source and you can make any customization you need. It wont be easy to develop delta functionality to EAV Step and even after it, m2_cl_* log tables should have ids of changed records these records are added by trg_* triggers. In your case it seems will be easier to migrate the store again from scratch and read the [documentation ](https://devdocs.magento.com/guides/v2.3/migration/bk-migration-guide.html)
