### ISSUE TITLE
Commerce to Commerce Data Migration Tool 2.3.1 is not disabling FOREIGN_KEY_CHECKS

### ISSUE THREAD

**Issue by not-art** [magento/data-migration-tool#692]
### Preconditions

1. Data Migration from Magento Commerce 1.14.4.0 to Magento Commerce 2.3.1, using php-fpm 7.2.11 and mysql 5.7 (using nginx / varnish)
2. Magento 2 Database is fresh & recently truncated to ensure no unexpected data is present for the migration
3. Magento 2 database user has full privileges
4. M1 db is hosting in AWS and firewall rule is open so it can talk to our M2 docker container where we're testing the migration. Networking issues are not a problem.

### Steps to reproduce

1. Successfully migrate your settings (we had no issues migrating settings!)
2. Begin the data migration step, using the -a flag to not break on mapping issues

### Expected result

1. EAV should migrate without issue, or should throw more usual data migration tool errors if extra mapping

### Actual result

1. Instead, the Data Migration Tool hard-fails as it is unable to run a TRUNCATE command on some EAV-related tables due to a foreign key check, despite having full DB rights/priviledges, and the M2 database having no data inside of it that it should be trying to truncate.
`[2019-06-12 18:28:55][INFO][mode: data][stage: data migration][step: EAV Step]: started`
`12% [===>------------------------] Remaining Time: < 1 sec`
`In Pdo.php line 235:`
`SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (magento2.eav_attribute, CONSTRAINT EAV_ATTRIBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID FOREIGN KEY (entity_type_id) REFERENCES magento2.eav_entity_type (entity_type_id)), query was: TRUNCATE TABLE eav_entity_type`
`In Pdo.php line 228:`
`SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (magento2.eav_attribute, CONSTRAINT EAV_ATTRIBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID FOREIGN KEY (entity_type_id) REFERENCES magento2.eav_entity_type (entity_type_id))`

Again, note that the user I'm using to run the data migration tool is the root user that created the m2 database and has full ownership / permissions. I should not have to disable FOREIGN_KEY_CHECKS globally to make this data migration tool work; in fact that is woefully problematic as we could run into actual FK issues.

### Additional notes
1. I've looked at the code for the tool and it seems to be setting FOREIGN_KEY_CHECKS = 0 for each session as needed, but it appears to not work for our migration. We can get around this issue by setting SET global FOREIGN_KEY_CHECKS = 0, and disabling foreign key checks at a global level.
2. It seems as though the tool is no longer properly disabling foreign key checks, at least on the EAV step / 1st step of the data migration tool?

**Comment by victor-v-rad** [comment]
Hi @not-art 
FOREIGN_KEY_CHECKS = 0 is the first command at the beginning of MySQL session and 1 is sent during delta delivering. But if the session ends for some reason it is possible that this command is not run after new session initialization. Try to add SET FOREIGN_KEY_CHECKS = 0 into init_statements_destination option in your config.xml

**Comment by not-art** [comment]
I was able to figure my issue out by running the migration with -vvv to see my foreign key check was due to data issues. Thanks, Victor.
