### ISSUE TITLE
Magento2.2.3 Installtion stuck on 0%

### ISSUE THREAD

**Issue by jaishiv** [magento/data-migration-tool#693]
Hello,

 

I have tried to install magento 2.3.1 with sample data but when i go to install option it's stuck at 0% without showing any error.

Advanced option shows look like : -
Starting Magento installation:
File permissions check...
Required extensions check...
Enabling Maintenance Mode...
Installing deployment configuration...

Console log display in loop these 2 URL : -
http://magento.hypeinnovaties.com/setup/index.php/install/progress

http://magento.hypeinnovaties.com/setup/index.php/session/prolong
I have increased
execution time : 36000
memory limit : 128M
On my Local-host it's working fine but on my webmin server it's stuck now.

**Comment by victor-v-rad** [comment]
Hi @jaishiv 

If Data Migration Tool did not cause this issue then probably you need to post it in https://github.com/magento/magento2/issues
