### ISSUE TITLE
unreachable network when try to install

### ISSUE THREAD

**Issue by mscampos92** [magento/data-migration-tool#697]
Hello dear all.

I'm trying to use the data migration tool but when I try to install running the command on root folder I receive a "ssh: connect to host github.com port 22: Network is unreachable" message...

![image](https://user-images.githubusercontent.com/20307166/59991479-f16a3c00-961d-11e9-8d25-7b92352b57ce.png)

On message says something about unreachable network but on this virtual machine doesn't exist firewall or something...

Ideas?

:)

**Comment by victor-v-rad** [comment]
Hi @mscampos92 

And also it says 'Couldn't connect to server'. Try to clone from github

**Comment by mscampos92** [comment]
I reboot the server and now it's downloading.. thank you !
