### ISSUE TITLE
Migrate single store view only

### ISSUE THREAD

**Issue by chris-brabender** [magento/data-migration-tool#70]
Is it possible to configure the data migration tool to migrate data for only a single store view / website?

**Comment by redboxmarcins** [comment]
By looking into configuration files it is all or nothing concept.
I would suggest to make a copy of your source database and DELETE all websites data you don't want to import. Please do it on copy of the database not LIVE/PRODUCTION data

**Comment by ilol** [comment]
Thank you @redboxmarcins.
@chris-brabender does it work for you?
can you please close the issue?
