### ISSUE TITLE
Create Setting entry during migration

### ISSUE THREAD

**Issue by jg-development** [magento/data-migration-tool#701]
### Preconditions
1. Magento 1.9.3.8 => 2.3.1
2. Migration Tool 2.3.1

I am trying to migrate the settings from an old shop to a new one. The problem is, that some settings needed in the new shop aren`t provided by the old one.
Example:
New config entry: "smtp/configuration_option/test_email/from" with "general"
How can I create an entry that is not provided by an old extension?

I tried the following without success (inside settings.xml):
```
<value>
        <transform>
            <path>smtp/configuration_option/test_email/from</path>
            <handler class="\Migration\Handler\SetValue">
                <param name="value" value="general" />
            </handler>
        </transform>
</value>
```
with this in <key>:
```
        <rename>
            <path></path>
            <to>smtp/configuration_option/test_email/from</to>
        </rename>
```
Because the path does not exists in the old one, the key is not in  the mappedNodes variable of the settings reader.

Did anybody have any ideas to create a new config entry during migration?

Greetings Jan

**Comment by victor-v-rad** [comment]
Hi @jg-development 

You can add a new hardcoded array into $sourceRecords in \Migration\Step\Settings\Data::perform() method. And revert changes in the codebase of the tool after migration

**Comment by fooman** [comment]
Alternatively just add them to your `app/etc/config.php` or a new module that includes an `etc/config.xml` file with your values.
