### ISSUE TITLE
Where is corresponding 2.2.9 version?

### ISSUE THREAD

**Issue by danemacmillan** [magento/data-migration-tool#703]
Magento 2 has released `2.2.8` and `2.2.9`, but there are no corresponding versions in the data migration tool. Are we not able to migrate data to those versions from Magento 1? `2.2.7` is the highest version tagged in the `2.2.x` releases.

**Comment by victor-v-rad** [comment]
Please see my comment https://github.com/magento/data-migration-tool/issues/670#issuecomment-477187425
