### ISSUE TITLE
migrated data on M2 short/long description missing new line,break(<br>),etc after migrate m1 to m2

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [magento/data-migration-tool#704]
### Preconditions

1. Using magento 2.3.1 version

### Steps to reproduce

1. Migrate all data successfully from m1 to m2.
2. Product short & long description have some html tags but they are not migrate,html tags are missing

### Expected result

1. Short/Long description must be migrate with HTML tags(like " `<br>`",etc...)

### Actual result

1. Short/Long description they are not including with HTML tags(like "`<br>`",etc.....)

**Comment by victor-v-rad** [comment]
Hi @sumeetmobiwebtech 

Thank you for reporting this issue. I tried to migrate and tags seem ok

![htmltags](https://user-images.githubusercontent.com/106504/61239696-25a8b800-a705-11e9-96a4-a2e523a7f061.png)

**Comment by michel334** [comment]
I have the same problem
Migrating 1.8.1.0 to 2.3.2
The break/newline tags are not explicitly present in the Short Description editor
The client makes newlines in the text bij pressing enter in the default editor (not the wysiwyg editor)
The frontend of Magento 1.8.1.0 shows these as <br> but there is not actual a <br> tag present in the editor

After the migration (Magento 2.3.2) we see the newlines in the editor  but on the frontend the <br> tags are missing in the product descriptions.

**Comment by michel334** [comment]
I solved my issue by adding nl2br function on description

\Magento_Catalog\templates\product\view\attribute.phtml
    <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>><?= /* @escapeNotVerified */ nl2br($_attributeValue) ?></div>

**Comment by sumeetmobiwebtech** [comment]
@michel334 
would you please give full example ?

i have lots of products.We can not do manually.
