### ISSUE TITLE
Quantity is set '0' and product is "out of stock" After migrate data from m1 to m2

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [magento/data-migration-tool#705]
### Preconditions

1. Using magento 2.3.1

### Steps to reproduce

1. Data migrate successfully from m1 to m2.
2. But quantity is set 0 in database and also stock status is "out of stock" but in magento 1 have set quantity more than 0 and stock status is "in stock"

### Expected result

1. Magento 2 Quantity must be set as magento1 and stock status is "in stock" if magento 1 stock status is "in stock"

### Actual result

1. Quantity is set 0 in database

**Comment by victor-v-rad** [comment]
Hi @sumeetmobiwebtech 

Thank you for reporting this issue but I cannot reproduce it. If your Magento 1 uses extensions for inventory it can cause such issue

**Comment by sumeetmobiwebtech** [comment]
@victor-v-rad but in magento 1 database have inventory NOT zero so why when migrate from M1 to M2,then why M2 database inventory is set zero ?
