### ISSUE TITLE
migrate data from magento 1.9.2.3 to magento2.3.2

### ISSUE THREAD

**Issue by Abdulkadiragoliya** [magento/data-migration-tool#706]
migrate data from magento 1.9.3.2 to magento2.3.2

### Steps to reproduce

1. Copy M1 Db to new server , truncate all log tables
2.  configure config.xml 
3.  start migration

### Expected result

1.  should success normally

### Actual result

1.   SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails `catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`) ON DELETE )

### Additional notes
I Checked table catalog_product_entity_varchar  there is no orphans record and no record with empty attribute id.

**Comment by Abdulkadiragoliya** [comment]
@victor-v-rad  can you please answer me?

**Comment by victor-v-rad** [comment]
Hi @Abdulkadiragoliya 

I assume your M1 catalog_product_entity_varchar table does not have unique key for fields entity_id, attribute_id, store_id, but M2 has. What you can do is to add 
```
<document key="entity_id,attribute_id,store_id">catalog_product_entity_varchar</document>
```
into map-document-groups.xml file inside `<group name="destination_documents_update_on_duplicate">`

**Comment by victor-v-rad** [comment]
but be aware that in this case all the duplicates will be removed in M2

**Comment by Abdulkadiragoliya** [comment]
@victor-v-rad   Thanks for Reply but can you please tell me what you mean by but be aware that in this case all the duplicates will be removed in M2 ?

remove duplicate from catalog_product_entity_varchar  or from every table?

**Comment by Abdulkadiragoliya** [comment]
> Hi @Abdulkadiragoliya
> 
> I assume your M1 catalog_product_entity_varchar table does not have unique key for fields entity_id, attribute_id, store_id, but M2 has. What you can do is to add
> 
> ```
> <document key="entity_id,attribute_id,store_id">catalog_product_entity_varchar</document>
> ```
> 
> into map-document-groups.xml file inside `<group name="destination_documents_update_on_duplicate">`

My M2 catalog_product_entity_varchar  table is empty

**Comment by victor-v-rad** [comment]
most likely your M1 catalog_product_entity_varchar table has records with duplicated ids entity_id,attribute_id,store_id. if you add `<document key="entity_id,attribute_id,store_id">catalog_product_entity_varchar</document>` the tool will migrate these with [INSERT ... ON DUPLICATE KEY UPDATE Syntax](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)

**Comment by Abdulkadiragoliya** [comment]
> Hi @Abdulkadiragoliya
> 
> I assume your M1 catalog_product_entity_varchar table does not have unique key for fields entity_id, attribute_id, store_id, but M2 has. What you can do is to add
> 
> ```
> <document key="entity_id,attribute_id,store_id">catalog_product_entity_varchar</document>
> ```
> 
> into map-document-groups.xml file inside `<group name="destination_documents_update_on_duplicate">`

Hello

**Comment by Abdulkadiragoliya** [comment]
> Hi @Abdulkadiragoliya
> 
> I assume your M1 catalog_product_entity_varchar table does not have unique key for fields entity_id, attribute_id, store_id, but M2 has. What you can do is to add
> 
> ```
> <document key="entity_id,attribute_id,store_id">catalog_product_entity_varchar</document>
> ```
> 
> into map-document-groups.xml file inside `<group name="destination_documents_update_on_duplicate">`

@victor-v-rad   i did as you said but i got this error 

(?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?,
   ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?,
  ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?,
   ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?),
   (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?,
   ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?
  , ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?,
   ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?
  , ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?)
  , (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?
  , ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (
  ?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `attribute_id` = VALUES(`attribute_id`
  ), `store_id` = VALUES(`store_id`)


In Mysql.php line 91:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento_magento2`.`catalog_product_entity_
  varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`) ON DELETE )

**Comment by victor-v-rad** [comment]
I'm sorry I misunderstood your initial report. The problem is in orphan records. Please remove `<document key="entity_id,attribute_id,store_id">catalog_product_entity_varchar</document>` and see my comment to this [issue ](https://github.com/magento/data-migration-tool/issues/692#issuecomment-501735464)

**Comment by Abdulkadiragoliya** [comment]
Hello @victor-v-rad   i have update as you said like this
<init_statements_destination>FOREIGN_KEY_CHECKS = 0;</init_statements_destination>

but i got this error :

 php bin/magento migrate:settings vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.3/config.xml

[2019-07-17 15:40:48][INFO][mode: settings][stage: integrity check][step: Settings Step]: started
100% [============================] Remaining Time: < 1 sec
In Mysql.php line 110:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for th
  e right syntax to use near 'FOREIGN_KEY_CHECKS = 0' at line 1, query was: FOREIGN_KEY_CHECKS = 0;


In Mysql.php line 91:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for th
  e right syntax to use near 'FOREIGN_KEY_CHECKS = 0' at line 1

**Comment by Abdulkadiragoliya** [comment]
hello @victor-v-rad 
can you please suggest solution for this issue

**Comment by victor-v-rad** [comment]
Try `SET FOREIGN_KEY_CHECKS = 0` instead of `FOREIGN_KEY_CHECKS = 0`

**Comment by Abdulkadiragoliya** [comment]
hello @victor-v-rad 
Thanks for reply .
Still i get error like : SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento_magento2`.`catalog_product_entity_
  varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ATTR_ID_EAV_ATTR_ATTR_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`) ON DELETE )

can you please give me any solution for it?

**Comment by Abdulkadiragoliya** [comment]
Hello @victor-v-rad
   Thanks for responding me.  Its didn't work for me. I have tried all your suggestion but not get success. Please let me know working solution. Its urgent.

**Comment by victor-v-rad** [comment]
The issue might be not in the tool but in loosing connection between DB servers. You can try to migrate in your local environment and if it works fine then probably the issue not in the tool

**Comment by Abdulkadiragoliya** [comment]
May i sent you a database?

**Comment by victor-v-rad** [comment]
Usually I would take such DB to migrate but right now I am 100% busy with another 2 urgent issue. Sorry for that
