### ISSUE TITLE
Multi website not migrating-2.3.1 and 2.3.2 Magento CE.

### ISSUE THREAD

**Issue by MeenaMonika** [magento/data-migration-tool#707]
**Information:**
PHP version: PHP 7.1.30
Source magento version: 1.9.3.2
Designation magento version: 2.3.2

**Reproduce Steps:**
1.Install Magento 1.9.3.2 version with sample data
2. Create two websites(website A and website B) in vanilla setup magento1 and create two stores(website A-store A, website A-store B,website B-store A, website B-store B)on each website.
3. Install Magento 2.3.2 without sample data and download the data migration tool-"2.3.2".
4. Configure the source and destination.
5. Run the command:

Expected result:
It should migrate all the website and store(website A-store A, website A-store B, website B-store A, website B-store B).

Actual result:
It migrates only one website and one store(website A-store A).

Kindly reproduce this issue.

**Comment by victor-v-rad** [comment]
Hi @MeenaMonika 

If you only  run the command migrate:data it will not migrate stores and websites. Your first command should be migrate:settings and then migrate:data. In migrate:settings your stores and websites are migrated.
