### ISSUE TITLE
[Migration\Exception]  Volume Check failed [mode: data][stage: volume check][step: Url Rewrite Step]

### ISSUE THREAD

**Issue by saiyadsalma** [magento/data-migration-tool#71]
I am migrating from version 1.9.1.0 to version 2.0.0 
Whenever i am trying to migrate data i am getting error of volume check on URL rewrite steps. Please see screenshot for further details.

Help me out to solve the issue.
![screenshot from 2016-03-14 10 33 53](https://cloud.githubusercontent.com/assets/17820834/13735497/654c6f74-e9d0-11e5-8335-f7da54a5d504.png)

**Comment by admin-it** [comment]
I'm having the same exact issue.  Anyone have any answers on this? or ideas?

**Comment by saiyadsalma** [comment]
It is because when you migrating from 1.9.x to 2.x there is a difference arises on the URL rewrite table. To overcome this problem i have commented out the some code of line to prevent this error. It is basically duplicating some of URLs of 1.9.x where in 2.x table structure it ignore duplicate data. 

In **/[path to magento root]/vendor/magento/data-migration-tool/src/Migration/Step/UrlRewrite/Version191to2000.php** commented out from **line no 232 to 236** and add **$result = true;** to skip validation.


![screenshot from 2016-03-25 10 11 23](https://cloud.githubusercontent.com/assets/17820834/14038095/075a3784-f272-11e5-8585-e10c5b63fa47.png)

**Comment by victor-v-rad** [comment]
I guess you have several store views and your CMS Pages assigned both to "All Store Views" and to some particular store simultaneously. Is it right?

**Comment by ilol** [comment]
@saiyadsalma ping :)

**Comment by victor-v-rad** [comment]
@saiyadsalma @admin-it please check the latest 2.0.5 release of the tool it should resolve the issue you have

**Comment by ilol** [comment]
@saiyadsalma @admin-it did it help? Thank you for your questions - it helps us to improve our product.

**Comment by pratikkamani** [comment]
> result

I have to face the same issue. Using this I able to continue migration step. Hope all data successfully migrated.
