### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by rvinothraj** [magento/data-migration-tool#711]
### Preconditions

1.  Magento 2.2.6
2. PHP Version 7.1.27-1+ubuntu18.04.1+deb.sury.org+1
3. mysql 5.0.12

### Steps to reproduce

1. upgrade magento 2.2.6 to 2.3.2 by following https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html
2. Files upgraded using composer 
3. then use to update database module setup using **bin/magento setup:upgrade**
4. Temp table issue found...

### Expected result

1.  Expected to update database 

### Actual result

1. [Screenshot, logs]
> Cache cleared successfully
> File system cleanup:
> /generated/code/Composer
> /generated/code/MSP
> /generated/code/Magento
> /generated/code/Symfony
> 
> The directory '/generated/metadata/' doesn't exist - skipping cleanup
> Updating modules:
> Schema creation/updates:
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.temp' doesn't exist, query was: SHOW CREATE TABLE temp

### Additional notes
Our production website is hosted in AWS. Having custom modules with tables.

**Comment by victor-v-rad** [comment]
Hi @rvinothraj 

Probably the issue you have is not related to this project. You might want to report it in https://github.com/magento/magento2
