### ISSUE TITLE
A non well formed numeric value encountered in checkout Page

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#713]
i have migration Magento 1.9.3.3 to Magento 2.3.2.2 done 

but after shipping methods missing in checkout page and showing below type error

https://prnt.sc/otc04n

and myexcepection.log file error showing 

> main.CRITICAL: Report ID: webapi-5d563f474b66f; Message: Notice: A non well formed numeric value encountered in /vendor/magento/module-shipping/Model/Carrier/AbstractCarrier.php on line 537

**Comment by victor-v-rad** [comment]
Hi @rakeshdonga 

Please try to reconfigure needed shipping method and see if error persists.

**Comment by rakeshdonga** [comment]
hello @victor-v-rad 
still this issue is coming..

**Comment by victor-v-rad** [comment]
@rakeshdonga make sure libsodium version 1.0.13 or later is installed. More info 
https://community.magento.com/t5/Magento-DevBlog/Required-libsodium-upgrade-for-latest-Magento-release/ba-p/134808
