### ISSUE TITLE
Admin store configuration is save but not display in admin panel

### ISSUE THREAD

**Issue by rakeshdonga** [magento/data-migration-tool#714]
I have migrate magento 1.9.3.3 to Magento 2.3.2 

after when Magento2 admin **store->Configration** value save but not showing in admin panel 

it save value successful **core_config_data** table  but not showing in admin panel

**Comment by victor-v-rad** [comment]
Some configuration settings in Magento 1 and Magento 2 have different values in path filed in core_config_data table. Try to clear cache
