### ISSUE TITLE
upgraded to Magento ver. 2.3.2  Payment methods not  working

### ISSUE THREAD

**Issue by mille2018** [magento/data-migration-tool#716]
We have upgraded our website https://www.makevana.com.au/  to Magento ver. 2.3.2 
tried all payment methods like , credit card ,  PayPal, afterpay and zip pay, but no payment method is working except bank transfer.

**Comment by victor-v-rad** [comment]
Hi @mille2018 

Make sure libsodium version 1.0.13 or later is installed. More info 
https://community.magento.com/t5/Magento-DevBlog/Required-libsodium-upgrade-for-latest-Magento-release/ba-p/134808
