### ISSUE TITLE
Customer Custom Attributes doesn't update after Data Migration From M1 to M2 

### ISSUE THREAD

**Issue by codhepstack** [magento/data-migration-tool#717]
### Preconditions

1. Migrated From Magento 1.8.1
2. Migrated To Magento 2.3.1

### Expected result

1. Apart from Customer Custom Attributes, everything is manageable file and customer edit section should also update the custom attributes from admin panel.

### Actual result

1. While updating the customer in the admin panel, only the default attributes are updating excepting the custom attributes. But if I update a customer via customer script, it updates the custom attributes. What is the issue?

**Comment by victor-v-rad** [comment]
Hi @codhepstack 

Thank you for reporting this issue. After migration to Magento 2.3.2 Commerce using the latest Data Migration Tool 2.3-develop I was able to change Customer's Custom Attributes via Admin Panel. Cannot reproduce your scenario
