### ISSUE TITLE
prefix automatically added 

### ISSUE THREAD

**Issue by LioCr** [magento/data-migration-tool#718]
When I launch data migration tool, I encounter the following error : 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'm1.prefix_core_directory_storage' doesn't exist ...

My old magento don't use any prefix and y configure my config.xml like this : 
<source_prefix />
<dest_prefix />

what can I do for DMT stop adding prefix and find my table ? 

Thanks

**Comment by victor-v-rad** [comment]
Hi @LioCr 

Please recheck your config.xml or create new one from config.xml.dist. Also check your map.xml file. It should contain this xml
```
            <rename>
                <document>core_directory_storage</document>
                <to>media_storage_directory_storage</to>
            </rename>
```
and not 
```
            <rename>
                <document>prefix_core_directory_storage</document>
                <to>media_storage_directory_storage</to>
            </rename>
```
