### ISSUE TITLE
Source fields are not mapped.

### ISSUE THREAD

**Issue by ityetti** [magento/data-migration-tool#719]
### Preconditions

1. Magento 2.3.2 Opensource

### Actual result

1. I migrate data from 1.9.3.1 to 2.3.2 and I got strange behaviour with some fields in the source and destination.

> [2019-09-09 19:18:00][ERROR]: Source fields are not mapped. Document: eav_attribute. Fields: category_ids
> [2019-09-09 19:18:00][ERROR]: Source fields are not mapped. Document: catalog_eav_attribute. Fields: layered_navigation_canonical,solr_boost
> [2019-09-09 19:18:00][ERROR]: Destination fields are not mapped. Document: customer_address_entity. Fields: mailbox

2. This fields I already added to the map.xml file. 
This part to the source node.
`<ignore>
                <field>eav_attribute.category_ids</field>
            </ignore>
            <ignore>
                <field>catalog_eav_attribute.layered_navigation_canonical</field>
            </ignore>
            <ignore>
                <field>catalog_eav_attribute.solr_boost</field>
            </ignore>`
This part to the destination->field_rules
 `<ignore>
                <field>customer_address_entity.mailbox</field>
            </ignore>`

And when I run command to migrate I have error which show in the top of the message.

P.S. `-a` param I used already (migration finished without errors), but I want to know why this errors appear.

**Comment by pjw345** [comment]
Just a few things to check and to clear up a few assumptions

when you run the migration command you have to specify a settings file:
(for argument sake lets assume you're migrating from a CE 1.9.3.7 to CE 2.3.2

again lets assume you've taken a copy of the 
vendor\magento\data-migration-tool\etc\opensource-to-opensource\1.9.3.7\config.xml.dist and you're using now using you're version, i.e. config.xml

Then let us assume you've taken a copy of
vendor\magento\data-migration-tool\etc\opensource-to-opensource\1.9.3.7\map.xml.dist and you've updated the source and destination sections and added the fields you want to ignore

Next question is have you remembered to update the config.xml with the path to the new map.xml

<map_file>etc/opensource-to-opensource/1.9.3.7/map.xml</map_file>

**Comment by ityetti** [comment]
@pjw345 Hello. Thanks for your responce.

I have problem just with this certain attributes. All that you wrote done and work. I have another attributes in my map.xml file and they are ignored correct.

**Comment by pjw345** [comment]
Assuming the files are all in the right places, have the right names and are referenced correctly, have you checked that the fields are not duplicated .....

**Comment by ityetti** [comment]
@pjw345 nope, I checked it. 

It is also strange that the customer_address_entity table in the map.xml.dist file is ignored by default. But I still get the error. Magic ✨

**Comment by victor-v-rad** [comment]
Hi @pjw345 @ityetti 
map.xml file is for Map Step which does not process eav_attribute table. This table is processed by EAV Step.

**Comment by ityetti** [comment]
@victor-v-rad ok thank you, I will check it.
But what do with the customer_address_entity.mailbox field?

**Comment by victor-v-rad** [comment]
edit map-customer.xml file
