### ISSUE TITLE
1.9.0.1 to 2.0.2 - Group_price [ERROR]: Source and Destination attributes mismatch. Attribute id: 554

### ISSUE THREAD

**Issue by cybersolutionsllc** [magento/data-migration-tool#72]
When running the data migration from 1.9.0.1 to 2.0.2 I'm getting an error in the EAV step. The error is as follows

[ERROR]: Source and Destination attributes mismatch. Attribute id: 554

I checked the attribute in the back end of 1.9.0.1 and attribute 554 is group_price . I noticed that in etc/ce-to-ce/eav-attribute-groups.xml.dist group_price is added to the ignore group. (But yet it is not ignored?)

What is going on here, and why am I getting this error?

**Comment by kennylawrence** [comment]
I'm having the same problem with this "group_price" catalog_eav_attribute. I am going from 1.9.2.2 to 2.0.4 using the 2.0.2 data-migration tool.

If I delete that line for attribute 145 in catalog_eav_attribute, the migration is able to complete without further errors, but I am unsure of the ramifications of this.  

BTW, if anyone does this using Ampps under windows, for reference, after deleting that line, I get a "mysql server has gone away" message after not much progress. It works at the magemojo host though.

**Comment by ilol** [comment]
thank you @kennylawrence  for hack. @cybersolutionsllc does it work?
btw we are almost ready to release 2.0.5 patch of MT. Follow the update soon

**Comment by victor-v-rad** [comment]
Seems #69 has the same problem and it is registered in our internal scope to fix in future

**Comment by ilol** [comment]
MAGETWO-52161

**Comment by victor-v-rad** [comment]
@cybersolutionsllc 
The issue was fixed in the latest release of the tool 2.1.1
Please recheck

**Comment by victor-v-rad** [comment]
I am closing the issue. Feel free to reopen if it is still actual
