### ISSUE TITLE
run migrate command it error

### ISSUE THREAD

**Issue by KilalaPhu** [magento/data-migration-tool#720]
$ php bin/magento migrate:settings --reset vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.0.1/config.xml

  [Exception]
  Notice: Undefined offset: 32 in E:\xampp\htdocs\magento\vendor\magento\data
  -migration-tool\src\Migration\Console\AbstractMigrateCommand.php on line 10
  6

migrate:settings [-r|--reset] [--] <config>

**Comment by victor-v-rad** [comment]
Hi @KilalaPhu 

I see ce-to-ce directory is in the path to your config.xml file. It looks like you use old data migration tool. It is recommended to use the latest stable version of the tool and Magento. As for now it is 2.3.2

**Comment by KilalaPhu** [comment]
yes i want migrate data base from magento version 1.9.0.1 to new version. but my boss use php 5.6 only. and him don't want and can not use php 7.1 and more, so i use magento 2.1.18 to migrate
maybe it have a lot bug but i had search and fix it

but when migrate it ok i run fontend and backend it error
https://imgur.com/A7eIEAz
line 111:  if ($store->getId() === null) {
            throw new NoSuchEntityException(__('Requested store is not found'));
        }
line 164 :  $store = is_numeric($storeId)
            ? $this->storeRepository->getById($storeId)
            : $this->storeRepository->get($storeId);

**Comment by victor-v-rad** [comment]
make sure you migrated settings as well. When run `bin/magento migrate:settings` stores and websites migrate with this command

**Comment by KilalaPhu** [comment]
yes it had run migrate:settings completed. 
i run migrate:data some time it error and have a time it run slowly and i schedule for shutdown to come home and then i see in database have data but i run agian more time it error and when i run frontend  it error  https://imgur.com/A7eIEAz

**Comment by KilalaPhu** [comment]
then i view database search product and copy all table that, 
search cata and copy all table find 
search eav and coppy all table find
and run 
SET FOREIGN_KEY_CHECKS=0;
UPDATE `store` SET store_id = 0 WHERE code='admin';
UPDATE `store_group` SET group_id = 0 WHERE name='Default';
UPDATE `store_website` SET website_id = 0 WHERE code='admin';
UPDATE `customer_group` SET customer_group_id = 0 WHERE customer_group_code='NOT LOGGED IN';
SET FOREIGN_KEY_CHECKS=1;

the web site had have data product .
