### ISSUE TITLE
Question: can the migrate:delta step continue through upgrade?

### ISSUE THREAD

**Issue by iphigenie** [magento/data-migration-tool#723]
### Question

If I upgdate Magento 2.3.1 to 2.3.2 and the Data Migration tool to 2.3.2, will the status tables used for migrate:delta stay untouched and can it deltas be resumed, or does migration have to be redone from scratch?

It is my undestanding that the delta are generated on the Magento1 database, and I am hoping that if I adapt my configuration without mistakes the delta can be continued on the upgraded code.

**Comment by victor-v-rad** [comment]
Hi @iphigenie 

Sorry for the late reply. You should be able to upgrade to 2.3.2 without issues later on with delta migration. No need to redone from scratch. But keep in mind that you cannot upgrade to the latest 2.3.3 without redone from scratch since there are improvements to Delta migration in this release. More info here 
https://github.com/magento/data-migration-tool/blob/2.3/CHANGELOG.md

**Comment by iphigenie** [comment]
Hi Victor and team.

From my cursory review of the changes 2.3.3 -> 2.3.4 should also be safe, What do you think? @victor-v-rad

**Comment by victor-v-rad** [comment]
Hi Joelle 
Migration 2.3.3 -> 2.3.4 is a job for internal Magento installing scripts. The tool can migrate only M1 -> M2. You can rise this question here https://github.com/magento/magento2/issues

**Comment by iphigenie** [comment]
> Hi Joelle
> Migration 2.3.3 -> 2.3.4 is a job for internal Magento installing scripts. The tool can migrate only M1 -> M2. You can rise this question here https://github.com/magento/magento2/issues

Hi @victor-v-rad  sorry I should have realised you were going to see this without much context.

What I meant it - currently working M1->M2 migration in delta stage with M2 version 2.3.3
Very close to live switchover

Problem is the 2.3.4 upgrade is probably best done and tested before live switch, but not if it breaks the migration
If I update M2 to 2.3.4 and the data migration tool to 2.3.4 and adjust the config, will delta pick up and go on, or are there structural changes that would make it not work (as there was between 2.3.2 and 2.3.3). 

Same question will turn up for 2.3.5

I will have backups etc. etc. but a quick punt "it should be OK" or "it's likely to fail for these steps" would be magic for all of us with ongoing migrations ;)

**Comment by iphigenie** [comment]
At first glance it continued fairly smoothly - though I have several parts of the delta turned off as irrelevant to me so other people's mileage may vary
