### ISSUE TITLE
Error during migration [Integrity constraint violation: 1062 Duplicate entry '80106' for key 'PRIMARY']  

### ISSUE THREAD

**Issue by brunoap62** [magento/data-migration-tool#724]
Can someone help me

**Comment by victor-v-rad** [comment]
Hi @brunoap62 

Duplicate entry error can happen when you run data migration for the second time with --reset option without restoring DB of Magento 2 to its initial state.

**Comment by brunoap62** [comment]
Hi Victor Unfortunately the error always happens even with the empty bank.

Deleting the Url rewrite Step step from config.xml concludes without any errors, but I'm worried that you skipped this step if you think it might cause a problem?

**Comment by victor-v-rad** [comment]
You can regenerate Url rewrites by extension like this https://marketplace.magento.com/thlassche-regeneraterewrites.html But still it might be better to migrate url rewrites by the tool since it migrates url redirects and probably M2 extension cannot generate it

**Comment by brunoap62** [comment]
When left or bulk_size, such as 1 or URL rewrite, takes about 5 hours to complete, and the error is 93% normal is all this delay?

**Comment by brunoap62** [comment]
When I leave bulk_size, like 1, the URL rewrite step goes on, but it takes about 5 hours to complete. When it reaches 93%, I get an error, is it normal all this time?

**Comment by victor-v-rad** [comment]
bulk_size = 1 means it will fetch > process > save, record by record. Better to increase to 1000 at least or set as 0

**Comment by brunoap62** [comment]
Understand. I will test with 1000 when I leave with 0 I get the error [Integrity constraint violation: 1062 Duplicate entry '80106' for key 'PRIMARY']

**Comment by victor-v-rad** [comment]
@brunoap62 please use -vvv option during migration and put here the whole error with stack trace. It could help to narrow down the reason why it happened.

**Comment by brunoap62** [comment]
Ok, this was the result, I can't understand well

Exception trace:
 () at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 PDOStatement->execute() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 Migration\ResourceModel\Adapter\Mysql->insertMultiple() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:137
 Migration\ResourceModel\Adapter\Mysql->insertRecords() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php:46
 Migration\ResourceModel\Destination->saveRecords() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Step/UrlRewrite/Version191to2000.php:224
 Migration\Step\UrlRewrite\Version191to2000->data() at n/a:n/a
 call_user_func() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Step/UrlRewrite/Version191to2000.php:241
 Migration\Step\UrlRewrite\Version191to2000->perform() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:79
 Migration\Mode\AbstractMode->runStage() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:119
 Migration\Mode\Data->runData() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /home/vaporemio/vaporedev/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at /home/vaporemio/vaporedev/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /home/vaporemio/vaporedev/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /home/vaporemio/vaporedev/vendor/magento/framework/Console/Cli.php:102
 Magento\Framework\Console\Cli->doRun() at /home/vaporemio/vaporedev/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /home/vaporemio/vaporedev/bin/magento:23

**Comment by brunoap62** [comment]
![print](https://user-images.githubusercontent.com/56244035/66527255-d25ebf80-ead1-11e9-9929-afd9fa819850.png)

**Comment by brunoap62** [comment]
Ok, these are the results, I couldn't understand well.

(Installation with clean bank)

![print](https://user-images.githubusercontent.com/56244035/66527297-fcb07d00-ead1-11e9-849d-2fb56a6048cc.png)

**Comment by brunoap62** [comment]
Ok, these are the results, I couldn't understand well.

(Installation with clean bank)

Exception trace:
 () at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 PDOStatement->execute() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 Migration\ResourceModel\Adapter\Mysql->insertMultiple() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:137
 Migration\ResourceModel\Adapter\Mysql->insertRecords() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php:46
 Migration\ResourceModel\Destination->saveRecords() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Step/UrlRewrite/Version191to2000.php:224
 Migration\Step\UrlRewrite\Version191to2000->data() at n/a:n/a
 call_user_func() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Step/UrlRewrite/Version191to2000.php:241
 Migration\Step\UrlRewrite\Version191to2000->perform() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:79
 Migration\Mode\AbstractMode->runStage() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:119
 Migration\Mode\Data->runData() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /home/vaporemio/vaporedev/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /home/vaporemio/vaporedev/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at /home/vaporemio/vaporedev/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /home/vaporemio/vaporedev/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /home/vaporemio/vaporedev/vendor/magento/framework/Console/Cli.php:102
 Magento\Framework\Console\Cli->doRun() at /home/vaporemio/vaporedev/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /home/vaporemio/vaporedev/bin/magento:23

![print](https://user-images.githubusercontent.com/56244035/66527326-194cb500-ead2-11e9-9fbb-1dcd578741fe.png)

**Comment by victor-v-rad** [comment]
My guess is that your core_url_rewrite table in M1 does not have primary key for url_rewrite_id field

**Comment by brunoap62** [comment]
I checked now owns the primary key. I will test export straight from the bank in production

**Comment by molotovbliss** [comment]
@victor-v-rad this could be more descriptive with a adding a comment that it's not a boolean but an integer; as it appears with the default config xml being only a `0` is confusing. 

I misinterpreted this as a on/off and not a integer. Limiting the performance benefits of this option. :grimacing:
