### ISSUE TITLE
Admin URL not working after migration to M2.3.3

### ISSUE THREAD

**Issue by jvkranenburg** [magento/data-migration-tool#727]
### Preconditions
1. Magento 1: 1.9.2.4
2. Magento 2: 2.3.3
3. PHP: 7.2.23
4. MySQL: Ver 15.1 Distrib 10.1.41-MariaDB, for Linux (x86_64) using readline 5.1

### Steps to reproduce

1. Install M2.3.3 (everything works fine, frontend and backend)
   ("composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.3.3 domain.com")	
2. Install migration tool 2.3.3
   ("composer require magento/data-migration-tool:2.3.3")
3. Create "vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml" with correct database parameters bulk_size=100 and direct_document_copy=1
4. "bin/magento migrate:settings vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml"
5. "bin/magento migrate:data -a vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.4/config.xml"
6. When the admin session is still open after migration everything is working fine until "bin/magento c:c"
7. Frontend is working fine, all products and menu's are in.
8. Backend returns to 'no-route' cms_page.

### Expected result
1. An admin login screen 

### Actual result
1. Navigate to backend URL returns to 'no-route' cms_page with correct menu and all products working.

![Go-to-backend-url](https://user-images.githubusercontent.com/7745377/66546692-d88a8580-eb3d-11e9-9744-b91d1777c4fd.png)

### Additional notes

Cron's are off! This is requered for migration. But also tried with cron's on after migration.

Already checked a lot of internet suggestions eg:
https://github.com/magento/data-migration-tool/issues/501
https://meetanshi.com/blog/magento-2-backend-not-working-solution/
https://bobcares.com/blog/magento-admin-url-404/

**Comment by jvkranenburg** [comment]
Working .... Had to use the old backend URL! (The M1 one!)

BUT: "bin/magento info:adminuri" returns the generated URI during install M2.3.3.
How to fix this?

**Comment by victor-v-rad** [comment]
Hi @jvkranenburg 

You can change the values of your `admin/url/custom` and `admin/url/custom_path` paths in migrated core_config_data table. The tool does not migrate these values from Magento 1 store

**Comment by victor-v-rad** [comment]
Probably the tool should not migrate `admin/url/use_custom_path` and `admin/url/use_custom` as well. Please remove or change values to `0` in these paths and reply if it helped

**Comment by jvkranenburg** [comment]
![Image 10](https://user-images.githubusercontent.com/7745377/66587339-8459c280-eb8a-11e9-94ce-e720d58b2c53.png)
That's it! Old admin URL was active. Changed to generated one during installation and everything was ok!

Tnx for quick support.

**Comment by victor-v-rad** [comment]
Internal ticket MC-21839 to exclude `admin/url/use_custom_path` and `admin/url/use_custom` from migration
