### ISSUE TITLE
Magento Migration process gets killed automatically.

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#733]
Hi Everyone,

I am new to magento and i am doing a magento migration from version 1.9.2.3 to magento 2.2.4.
My php version is 7.0 and mysql version is 5.6

While running the command
php bin/magento migrate:data -a vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.3/config.xml

i am getting a process killed error at product migration step.
![Screenshot (1)](https://user-images.githubusercontent.com/35400881/67071061-3acb3200-f19f-11e9-8a18-5abea6157703.png)

I have also set the max_execution_time to 6000s and while running command
dmesg | grep php

i came to know that this is memory issue.
![Screenshot (2)](https://user-images.githubusercontent.com/35400881/67071165-72d27500-f19f-11e9-9453-6eed1aff151a.png)
 
Please provide suggestions regarding this and how to continue the migration process.

After reading on github foe similar problem i tried 
php bin/magento migrate:data –r  vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.3/config.xml
But it gives the following Integrity check error.
![Screenshot (3)](https://user-images.githubusercontent.com/35400881/67084719-1f6e2000-f1bb-11e9-825c-32eaa3e7c070.png)

**Comment by victor-v-rad** [comment]
Hi @varun2287 

1. The tool remembers what has been migrated and when stop due to Killed error, you can just rerun migration of data and it will continue from the point where it was stopped. But if rerun with --reset option which start from the beginning and get the error Killed again.
2. You can limit number of records fetched from M1 and inserted to M2 by <bulk_size> option from your config.xml file of Data Migration Tool
3. adding -vvv option to command migrate:data can help to determine which table causes the error

**Comment by varun2287** [comment]
Hi, victor-v-rad 

Thanks for your response.

I have tried the data migration command with -vvv option, it worked as the migration steps reached to sales_flat_order table this time and then get killed.

![Screenshot (5)](https://user-images.githubusercontent.com/35400881/67157940-5c6b1b80-f34f-11e9-9b7b-62f90c49a7f6.png)

As you said i rerun the same command but now the following error came 
![Screenshot (6)](https://user-images.githubusercontent.com/35400881/67157957-abb14c00-f34f-11e9-8b23-1f095efa3edf.png)

Please provide the solution,
Thanks again

**Comment by varun2287** [comment]
I have also used php -dmemory_limit=-1 as a prefix to the migration command, but it didn't worked.

**Comment by varun2287** [comment]
Error.log file gives following error
Out of memory (allocated 1880055808) (tried to allocate 268435464 bytes) in /home/ampscooters/public_html/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169

**Comment by varun2287** [comment]
Hi @victor-v-rad ,
I have tried your suggestions, and it worked a bit for me,
But at further steps i got this
![Screenshot (7)](https://user-images.githubusercontent.com/35400881/67194566-fcd74380-f414-11e9-86f6-cd7b3b841e97.png)
![Screenshot (8)](https://user-images.githubusercontent.com/35400881/67194572-fe087080-f414-11e9-9429-88090f60349b.png)

Please provide solution
