### ISSUE TITLE
After running php bin/magento setup:di:compile my domain stopped working

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#734]
Hi,
I am migrating the data from magento 1.9.2.3 to magento 2.2.4.
I have installed a new theme on my new magento 2(porto theme)
After that when i run the command 
php bin/magento setup:di:compile  the domain and admin panel stopped working.

There is not any error logs.

Please help.

**Comment by victor-v-rad** [comment]
Check out `magento2_root/var/log/system.log` and `magento2_root/var/log/exception.log` files as well as PHP error log. There should be something that can give a hint what happened.
