### ISSUE TITLE
While migrating in magento 2 , no space left on device error raised

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#735]
Hi,

I am migrating from magento 1.9.2.3 to magento 2.2.4 and while running the migration data command 
php bin/magento migrate:data -a vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.2.3/config.xml -vvv
 i got the following error

![image](https://user-images.githubusercontent.com/35400881/67392655-91c97080-f5be-11e9-93ac-191e525a543b.png)
![image](https://user-images.githubusercontent.com/35400881/67392677-9a21ab80-f5be-11e9-91fa-459b335c3f71.png)

I have also set the <bulk_size> to 1000 in config.xml.
As i see on the admin panel products data have been migrated, but orders, customers are not yet migrated.

Please help.

**Comment by victor-v-rad** [comment]
You can increase hard drive space or remove unnecessary data on existing hard drive.

**Comment by varun2287** [comment]
Hi, @victor-v-rad 
I am using not using local system to migrate data, i am using a server and it shows quite a space but still i am getting this error. The Disk usage screennshot is attached. 

![Screenshot (12)](https://user-images.githubusercontent.com/35400881/67950463-9ec60f80-fc0f-11e9-884f-92dfea399cee.png)

Actually the table log_visitor is quite large , it is itself 261 mb of data, is this he issue with it.

Please help, i am in trouble migrating this task.

**Comment by victor-v-rad** [comment]
If there are no other way to increase memory, you can remove "Log Step" from <steps mode="data"> section in your config.xml

**Comment by varun2287** [comment]
Hi @victor-v-rad 

Thanks for the reply,

If I remove the log step from config.xml, will it impact the data being migration, or not?
Please guide me.
