### ISSUE TITLE
Product detail page giving 404 error

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#736]
Hi 
I have migrated products from magento 1.9.2.3 to magento 2.2.4.I have also installed the porto theme on the new store, but there is one issue that product detail page is not opening and giving 404 error everytime.

There is also exception log -
![Screenshot (10)](https://user-images.githubusercontent.com/35400881/67480513-b33d6180-f67d-11e9-9eba-293838eb4dd9.png)

System log
![Screenshot (11)](https://user-images.githubusercontent.com/35400881/67480518-b9334280-f67d-11e9-92b7-15e1f0615342.png)

**Comment by victor-v-rad** [comment]
Taking into account #735 maybe it is because not all data has been migrated.
