### ISSUE TITLE
can not checkout

### ISSUE THREAD

**Issue by KilalaPhu** [magento/data-migration-tool#737]
i use magento migration tool to migrate data base magento 1.9.1 to magento 2.1.18
it run ok and have data but i can not checkout. it error
https://imgur.com/fe8KMfP

i try change new database with sameple data and still use this code. it can checkout. but use database had migrate it error.
https://imgur.com/ekMkES7
country it underfind

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by victor-v-rad** [comment]
Hi @KilalaPhu 

The tool supports Magento 2.1.9 and everything later is either from 2.2 branch or 2.3. It is recommended to use the latest stable version of Magento and Data Migration Tool

**Comment by KilalaPhu** [comment]
@victor-v-rad 
i error same that. can you help me how fix it.
https://github.com/magento/magento2/issues/5873
https://github.com/magento/data-migration-tool/issues/627

you can download database at : https://github.com/KilalaPhu/kilalashop/blob/master/magento2.1.18-07-10-2019.sql

**Comment by KilalaPhu** [comment]
@victor-v-rad 
https://github.com/magento/data-migration-tool/issues/627
