### ISSUE TITLE
can you convert database M1 to M2.1.9 

### ISSUE THREAD

**Issue by KilalaPhu** [magento/data-migration-tool#739]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by victor-v-rad** [comment]
Hi @KilalaPhu 

you can use data migration tool 2.1.9 for migration your Magento 2.1.9. But it is recommended to use the latest stable version and as for now it is 2.3.3
