### ISSUE TITLE
2.0.4 release?

### ISSUE THREAD

**Issue by kennylawrence** [magento/data-migration-tool#74]
development is halted due to unknown ramifications of using 2.0.2 database migration tool with CE 2.0.4! :)

**Comment by mikebranderhorst** [comment]
2.0.4 released soon? What are the alternatives? UberTheme https://github.com/ubertheme/module-ubdatamigration hasn't been updated for a while either.

**Comment by andidhouse** [comment]
we also would like to test 2.0.4 migration as we face some errors using former magento migration versions with no help to solve this. 

Any official statement here (also to the bugs which are solved in the 2.0.4 migration tool)?

**Comment by redboxmarcins** [comment]
Tried to use 2.0.2 tool with 2.0.4 and there is only one table to be ignored.

**Comment by vcpawate** [comment]
If Data migration tool is not available to use with Magenti CE 2.0.4, Is there anyone version of Data migration tool available to use?

Also, please let us know when are you planning to release Data migration Tool v2.0.4?

thanks

**Comment by heyjuke** [comment]
@redboxmarcins Which table is that?

**Comment by maderlock** [comment]
It's really not good enough to state in several places in your documentation "<version> must match the version of the Magento 2 codebase" and then leave this languishing 2 patches behind the current code base.

Please let us know what the schedule is for updating this module.

**Comment by vcpawate** [comment]
Admin please respond, This help will us to schedule

**Comment by victor-v-rad** [comment]
Since 2.0.4 is a patch (namely security and bug fixes) chances are migration won't cost more efforts than the average

**Comment by vcpawate** [comment]
Can you please let us know which data migration tool we should use with CE
2.0.4

**Comment by PascalBrouwers** [comment]
@victor-v-rad  Any word on that update?

**Comment by andidhouse** [comment]
nope! no words on our bugs no words on the migration tool... we have 3 projects with migration from 1.x to 2.0 - all facing massive problems using the migration tool and no help at all here or elsewhere. Thinking at the moment to switch to shopyfy from our magento projects 👎

**Comment by quangdog** [comment]
Another vote for an update here, please....

**Comment by ilol** [comment]
@andidhouse stop stop please. All of us are working hard to release Magento 2.1 soon. Update of Migration tool will be release in the closest time

**Comment by sachittandukar** [comment]
We are stuck on migration as Magento still haven't released migration tool for their latest version.
Why they are so slow on this? How can they expect to us to migrate on latest version if they couldn't provide us proper tool for it?

**Comment by victor-v-rad** [comment]
Normally it takes some time to adapt the tool to recently released Magento 2. Thus the delay occurs. As for now there are Magento 2.0.5 and Data Migration Tool 2.0.5 .
