### ISSUE TITLE
1.13.1.0 -> 2.3.3: empty categories

### ISSUE THREAD

**Issue by fballiano** [magento/data-migration-tool#740]
Hi,
I've setup data-migration-tool and successfully migrated from 1.13.1.0 to 2.3.3, backend is working fine, products are there and they're associated to categories:
<img width="273" alt="Schermata 2019-11-04 alle 11 01 18" src="https://user-images.githubusercontent.com/909743/68116330-73367400-fef2-11e9-9fc7-f084a4ccbb56.png">

Category page says "no products in this category":
<img width="1315" alt="Schermata 2019-11-04 alle 10 57 12" src="https://user-images.githubusercontent.com/909743/68116136-002cfd80-fef2-11e9-8f7b-d0cdddbfb190.png">

But product page (using direct product url) works correctly.

I modified the indexes (all of them are "on schedule" now) to reindex everything, full reindex is done (cache flushed), but still categories are empty.

Do you have any ideas?

**Comment by victor-v-rad** [comment]
Hi @fballiano 

Usually after indexing catalog products appears on Store Front. I wonder if your root category from your screenshot has ID 2 or different number? 
![Default Category (ID 2)](https://user-images.githubusercontent.com/106504/68133103-69f2da80-fee5-11e9-9c40-e60fda3972b7.png)

**Comment by fballiano** [comment]
absolutely, it has ID 2:
<img width="866" alt="Schermata 2019-11-04 alle 15 30 22" src="https://user-images.githubusercontent.com/909743/68133315-0fbf3d00-ff18-11e9-939e-337b1fd75828.png">

**Comment by victor-v-rad** [comment]
Hi @fballiano 
There is a workaround to solve the issue. If use Elasticsearch 6.0+ as Search Engine in Admin Panel configuration and do indexing by running the command *bin/magento indexer:reindex catalogsearch_fulltext* then it fixes the issue

**Comment by fballiano** [comment]
thank @victor-v-rad, it actually works, altho it should work also without requiring this elasticsearch step :-)

**Comment by victor-v-rad** [comment]
The reason why it does not work has yet to be identified. It could be the issue within the tool or caused by some extensions from M1.

**Comment by victor-v-rad** [comment]
@fballiano The fix is in https://github.com/magento/data-migration-tool/commit/cf41bb9a53f06b3729bae24534d3f85372eab8f4
I also provided patch and explanation of root cause in support ticket you created. Soon it will be available.

**Comment by fballiano** [comment]
Hi @victor-v-rad, thanks so much for your support! How can I install the new version? I didn't get any notification on https://support.magento.com/hc/en-us/requests/255873 :-)

Thanks again!

**Comment by victor-v-rad** [comment]
You can get it if backup and then remove vendor/magento/data-migration-tool directory. Then install from the branch 2.3-develop by running the commands
```
composer config repositories.data-migration-tool git https://github.com/magento/data-migration-tool
composer require magento/data-migration-tool:dev-2.3-develop
```
But in https://support.magento.com/hc/en-us/requests/255873 you will soon get instructions how to fix it on the migrated DB.

**Comment by fballiano** [comment]
Thank you very much again!
