### ISSUE TITLE
Undefined offset: 19 in EAV/Data.php on line 279 1.9.0.1 os-os 2.3.2

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/data-migration-tool#742]
### Preconditions

1. Magento 1.9.0.1 OS
2. Magento 2.3.2 OS

### Steps to reproduce

1. Irrelevant.

### Expected result

1. It should just continue or at least tell me what the problem is the integrity checks did not have issues.

### Actual result

Error.
![image](https://user-images.githubusercontent.com/1968109/69133761-4a7dc380-0b1b-11ea-91d2-bd1569296179.png)
```
[2019-11-19 09:19:51][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
[2019-11-19 09:19:52][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:52][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:52][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: integrity check][step: Inventory Step]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:56][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
[2019-11-19 09:19:59][INFO][mode: data][stage: data migration][step: EAV Step]: started
28% [========>-------------------] Remaining Time: < 1 sec
```
```
In ErrorHandler.php line 61:

  [Exception]
  Notice: Undefined offset: 19 in /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 279
```
```
Exception trace:
 () at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:279
 Migration\Step\Eav\Data->migrateAttributeSetsAndGroups() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:190
 Migration\Step\Eav\Data->perform() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:81
 Migration\Mode\AbstractMode->runStage() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:124
 Migration\Mode\Data->runData() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /var/www/html/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:54
 Migration\Console\MigrateDataCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/magento/framework/Interception/Interceptor.php:58
 Migration\Console\MigrateDataCommand\Interceptor->___callParent() at /var/www/html/vendor/magento/framework/Interception/Interceptor.php:138
 Migration\Console\MigrateDataCommand\Interceptor->Magento\Framework\Interception\{closure}() at /var/www/html/vendor/magento/framework/Interception/Interceptor.php:153
 Migration\Console\MigrateDataCommand\Interceptor->___callPlugins() at /var/www/html/generated/code/Migration/Console/MigrateDataCommand/Interceptor.php:104
 Migration\Console\MigrateDataCommand\Interceptor->run() at /var/www/html/vendor/symfony/console/Application.php:893
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:105
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23
````
### Additional notes
I added all the tables I needed to Ignore and fields to ignore, also I wanted to ignore cms page and block related things as to not over-write that content area.

eav_attribute_set table was filled with a bunch of Migration_Default junk.
![image](https://user-images.githubusercontent.com/1968109/69134186-f7584080-0b1b-11ea-816b-c14facd0e9a6.png)

```json
{"attribute_set_id":"31","entity_type_id":"19","attribute_set_name":"Migration_Default","sort_order":"100"}
```

Anyone know how I can fix this? I don't care about these attributes they were not even in my old db.

Ah right, I deleted some orphaned eav entity types that must have been in that position.

```[2019-11-19 06:37:47][WARNING]: Incompatibility in data. Source document: eav_attribute. Field: source_model. Error: Class ves_brand/system_config_source_ListBrand is not mapped in record attribute_id=961
[2019-11-19 06:37:47][WARNING]: Incompatibility in data. Source document: eav_attribute. Field: backend_model. Error: Class awshopbybrand/attribute_brand_backend is not mapped in record attribute_id=964
[2019-11-19 06:37:47][WARNING]: Incompatibility in data. Source document: eav_attribute. Field: frontend_model. Error: Class awshopbybrand/attribute_brand_frontend is not mapped in record attribute_id=964
[2019-11-19 06:37:47][WARNING]: Incompatibility in data. Source document: eav_attribute. Field: source_model. Error: Class awshopbybrand/attribute_brand_source is not mapped in record attribute_id=964

Well I don't care about those I'm not going to use them.
DELETE FROM eav_attribute WHERE attribute_id IN (961,964);
```

So I should delete the EAV type of those id from the both databases.

This means there is no integrity check on eav_attribute_set => eav_entity_type.

**Comment by LiamKarlMitchell** [comment]
![image](https://user-images.githubusercontent.com/1968109/69135250-b2cda480-0b1d-11ea-8bce-25043378bea5.png)

Need to wipe those out too, the old Magento 1 db doesn't have constraints/cascade delete etc it would seem...

```sql
DELETE FROM eav_attribute_set WHERE entity_type_id NOT IN (SELECT entity_type_id FROM eav_entity_type)
```

But now I'm getting this.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '61-96' for key 'EAV_ENTITY_ATTRIBUTE_ATTRIBUTE_SET_ID_ATTRIBUTE_ID'

**Comment by saracassells** [comment]
Did you ever find a fix to the above error? @LiamKarlMitchell

**Comment by LiamKarlMitchell** [comment]
No I rotated onto another project at work and haven't had a chance to go back too it.
I also had to have some MySQL SET options no auto increment on zero, allow invalid dates etc.

When it happens the DB just seems broken, probably need to re-import and run again from the start, but Its a large database from many years of Magento 1... so I was hoping I could continue where it left off but it modifies things and doesn't put it back the way it was if it failed?

Also its a pain in the ass to add all the exclusions for various modules you don't use anymore / tables that you don't care about.

Part of me thinks it should have been a white list not a black list, although i understand why they did this so that you get warnings when there is data that is not explicitly ignored or mapped.

**Comment by PivitParkour94** [comment]
Definitely getting the same issue on my Magento 2.3.3 instance - Migrating from 1.9.3.7.
It's inconsistent, sometimes the undefined offset error is thrown then rerunning the steps, the Duplicate entry error is thrown.
I'm looking into why this is happening

**Comment by tschirmer** [comment]
Same! We've had a couple of migration's we've done that we needed to repeatly reset the database back to a fresh installation of Magento 2 before re-running. Sometimes this would work, and other times it'd fail.

Really not great if you're not able to do a delta migration.

**Comment by PivitParkour94** [comment]
Turns out the results are extremely consistent.

1. Fresh Installed Magento 2.3.2 (I thought I was on 2.3.3) with 2.3.3 migration tool release
2. Run EAV Step at least `bin/magento migrate:data config.xml`
3. Undefined Offset error thrown
4. Run EAV Step at least again (no other changes) `bin/magento migrate:data config.xml`
5. Duplicate Entry error thrown
Repeat Steps 2-5 X times
Going to upgrade my Magento 2 to 2.3.3 and see if this is still an issue

**Comment by PivitParkour94** [comment]
Can confirm this is still an issue on Magento 2.3.3 running the data-migration tool 2.3.4.
@victor-v-rad Do you have any recommendations for getting around this bug?

**Comment by victor-v-rad** [comment]
@LiamKarlMitchell this issue is not reproducible on my vanilla Magento. Make sure your Magento 2 is empty of any data every time you run bin/magento migrate:data. If you have Magento Commerce you can report this issue here https://magento.com/contact-us

**Comment by orozcodiaz** [comment]
Having exactly the same issue with migrating from 1.9.0.1 to 2.3.4

**Comment by LiamKarlMitchell** [comment]
If possible, delete all data and start new website. Migration does not work.
Would be better if the tool imported only things you need like customers and order history.

**Comment by ProxiBlue** [comment]
@victor-v-rad  Why was this closed? is it solved?

**Comment by LiamKarlMitchell** [comment]
My only thoughts are that @victor-v-rad  might have different environment (mysql/php) versions or is not trying it on a Magento 1.9x site that is already long populated with data.

**Comment by ronak2ram** [comment]
Having exactly the same issue with migrating from 1.9.3.2 to 2.3.5

**Comment by orozcodiaz** [comment]
> Having exactly the same issue with migrating from 1.9.3.2 to 2.3.5

For me the problem was someone edited the M1 DB manually and there were some missing data. You can just turn xdebug and find a spot. For me it was missing data for attribute set.
