### ISSUE TITLE
Error 500 on product edit page after migration 1.9.3.10 - 2.3.3

### ISSUE THREAD

**Issue by rddewan** [magento/data-migration-tool#744]
I have been try to do migration every thing goes well but when click on product edit  and customer edit its always giving error 500
/admin_1220ab/catalog/product/edit/id/21/key/39cbbba235d8cd2204c602825b3a4c1ae4e0ddbc52f7cf7778f0a789110ae672/

### Preconditions

1.  Magento 1 = 1.9.3.10
2.  Magento 2 = 2.3.3
3. PHP = 7.3
4. MySQl = 5.6.45

### Steps to reproduce

I have already run
reindex
clear cache
compile 

### Expected result

Product edit page should be shown .
Customer edit page should be shown
If i create a new product i can edit it with no problem but the migrated product i cant edit

**Comment by victor-v-rad** [comment]
Hi @rddewan 

Thank you for reporting this issue. In the directories magento/var/report and magento/var/log you can find more details about this error and share here

**Comment by rddewan** [comment]
hi @victor-v-rad 

Thank you for your reply . I have checked test it many times but it look like if i do migration which has single store its working fine only on the customer side i had to manually removed 3rd party created column from DB Table.
If i do import with multi store site the problem is there in the map.xml  file i found  some mapping config can you provide a sample on how should i map my store here.
```
<ignore>
                <document>core_store</document>
            </ignore>
            <ignore>
                <document>core_store_group</document>
            </ignore>
            <ignore>
                <document>core_website</document>
 </ignore>
```

Thank you

**Comment by victor-v-rad** [comment]
@rddewan Stores and websites are migrated in migrate:settings command inside "Stores Step"

**Comment by rddewan** [comment]
@victor-v-rad  thanks for your information
