### ISSUE TITLE
URL Rewrite error/rollback during migration.

### ISSUE THREAD

**Issue by iovistainc** [magento/data-migration-tool#745]
### Preconditions

1. Magento 1.9.3.9 CE

![wearwell_admin](https://user-images.githubusercontent.com/16300151/69399752-58973400-0d15-11ea-8093-ab3eaffac679.png)

2. Magento 2.3.3
3. PHP 7.2.x

### Steps to reproduce

1. Run migration using instructions at https://devdocs.magento.com/guides/v2.3/migration/migration-tool-install.html
2. Volume check failed at URL Rewrite Step.
3. Error occurred. Rollback.

### Expected result

1. The product URL open should be working.

### Actual result

1. Products are not loading on the frontend. 
2. All products URL are redirected to 404.
3. [Screenshot, logs]

![Screenshot from 2019-11-22 10-32-26](https://user-images.githubusercontent.com/16300151/69399584-ae1f1100-0d14-11ea-82ec-d0b9dacfb942.png)

```
[2019-11-22 05:01:26][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: started
0% [>---------------------------] Remaining Time: < 1 sec
100% [============================] Remaining Time: < 1 sec
[2019-11-22 05:01:27][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Error occurred. Rollback.
[2019-11-22 05:01:27][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Url Rewrite Step: rollback
[2019-11-22 05:01:27][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Please fix errors and run Migration Tool again
[2019-11-22 05:01:27][WARNING]: Volume Check failed

```

**Comment by victor-v-rad** [comment]
Hi @iovistainc 

Thank you for reporting this issue. You can remove the words `implements RollbackInterface` from \Migration\Step\UrlRewrite\Version191to2000 class, run migration and count records core_url_rewrite in Magento 1 and url_rewrite + cms_page in Magento 2 and compare

**Comment by iovistainc** [comment]
Hi @victor-v-rad 

I have removed `implements RollbackInterface` from \Migration\Step\UrlRewrite\Version191to2000 class and re-run migration and still, I got Volume checked failed error for URL Rewrite step. I have compared the count and got a result as below.

Magento 1 core_url_rewrite there are 320444 entries and in Magento 2 url_rewrite (320787) + cms_page (188) = 320975 entries.

**Comment by victor-v-rad** [comment]
it is not clear why it still stop from further migration. Seems like Magento 2 got more url rewrites so probably it is safe to remove `<volume>Migration\Step\UrlRewrite\Version191to2000</volume>` from you config.xml file
