### ISSUE TITLE
Magento 2 data migration error 

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/data-migration-tool#746]
Hello Support,

I am migrating our magento 1.9.1.0 site to mahento 2.2.3 and during data migration I am getting this below error.
Warning: array_key_exists() expects parameter 2 to be array, boolean given
  in /vendor/magento/data-migration-tool/src/Mi
  gration/Handler/SerializeToJson/SalesOrderItem.php on line 77

I have attached the screenshot as well. http://prntscr.com/q1mso5
@victor-v-rad  Please check once and let me know how to solve this issue/

Thanks

**Comment by victor-v-rad** [comment]
Hi @baljinderimpinge 

Thank you for reporting this issue. Internal ticket MC-29169 was created to fix it
