### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function mime_content_type()  

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#747]
I have migrated the magento from 1.9.2.3 to 2.2.4, but for some reasons i have to upgrade it to 2.3.1

After upgrading magento from version 2.2.4 to 2.3.1, i am getting this error on insert images page in admin panel.

Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/ampscooters/public_html/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php:331 Stack trace: #0 /home/ampscooters/public_html/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(60): Magento\Cms\Model\Wysiwyg\Images\Storage->getFilesCollection('/home/ampscoote...', NULL) #1 /home/ampscooters/public_html/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(74): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFiles() #2 /home/ampscooters/public_html/vendor/magento/module-cms/view/adminhtml/templates/browser/content/files.phtml(15): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFilesCount() #3 /home/ampscooters/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/ampscoote...') #4 /home/ampscooters/public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\C in /home/ampscooters/public_html/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php on line 331

I have checked for this issue and found that php extension fileinfo should be installed, but my fileinfo extension is already installed.

I can't find any other solution.Please help me in this issue.

**Comment by victor-v-rad** [comment]
Hi @varun2287 

Thank you for reporting this issue. This issue could be caused by Magento 2 itself and not by the tool. Please consider to report it in https://github.com/magento/magento2 repository
