### ISSUE TITLE
Magento 2 catgeory admin error after migration

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/data-migration-tool#749]
Hello Support,

I have migrated my magento 1.9.1.0 site to Magento 2.2.3 and everything is working fine except categories in admin.
I am getting this error 
`{"0":"The store that was requested wasn't found. Verify the store and try again.","1":"<pre>#1 Magento\\Store\\Model\\StoreManager->getStore(15) called at [vendor\/magento\/module-cms\/Model\/ResourceModel\/AbstractCollection.php:85]\n#2 Magento\\Cms\\Model\\ResourceModel\\AbstractCollection->performAfterLoad('cms_block_store', 'block_id') called at [vendor\/magento\/module-cms\/Model\/ResourceModel\/Block\/Collection.php:44]`
@victor-v-rad  Please check once and let me know how to solve this issue/

Thanks

**Comment by victor-v-rad** [comment]
Hi @baljinderimpinge 

Thank you for reporting this issue. Please recheck that all stores were migrated. You can check it in 'store', 'store_group', 'store_website' Magento 2 tables
