### ISSUE TITLE
Design of website hampered after running rm -rf generated var/cache var/view-preprocessed

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#751]
Hi ,
I am working on magento 2.3.1 with php 7.1
 My website was running well but there was some image upload issue so i ran following commands-
1-rm -rf generated/* var/cache/* var/view_preprocessed/*
2- php bin/magento setup:upgrade
3-php bin/magento setup:di:compile
4-php bin/magento setup:static-content:deploy -f
5-php bin/magento indexer:reindex
6-php bin/magento cache:clean
7-php bin/magento cache:flush

After that when i reload my website home page the design was completely deteriorated.

After that i rollbacked the backup,the code and media backup rolled back successfully but database backup threw an error-"Multiple queries can't be executed. Run a single query and try again."

I have attached the screenshot of my home page
![home](https://user-images.githubusercontent.com/35400881/69961938-f1f2f100-1532-11ea-864e-71ffba06f145.png)

I have also rerun all the commands from no.2 to no.7 again to see if there is some change but got no success. 
Please provide some solution, as i have no other option to sort this out.
Thanks in advance.

**Comment by victor-v-rad** [comment]
Hi @varun2287 

Thank you for reporting this issue. Migrated Magento 1 store and run all these command you mentioned and all images are in place and Magento 2 without any issues. Please try to use the latest  Magento 2.3.3 and tool 2.3.3
