### ISSUE TITLE
AfterMigrate: Error opening Customer->All Customer in admin panel

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#753]
Hi,
I have migrated from magento 1.9.2.3 to magento 2.2.4 and then i upgraded it to 2.3.3.
I was getting error on 2.2.4 and also now on 2.3.3 while accessing the Customer->All Customers in admin panel.

1 exception(s):
Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Magento\Eav\Model\Entity\Attribute\Source\Config

Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Magento\Eav\Model\Entity\Attribute\Source\Config
<pre>#1 Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Eav\Mode...', array()) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#2 Magento\Framework\ObjectManager\ObjectManager->create('Magento\Eav\Mode...', array()) called at [vendor/magento/framework/Validator/UniversalFactory.php:36]
#3 Magento\Framework\Validator\UniversalFactory->create('Magento\Eav\Mode...') called at [vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php:642]
#4 Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource() called at [vendor/magento/module-customer/Model/AttributeMetadataConverter.php:68]
#5 Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(&Magento\Customer\Model\Attribute#000000002d15e4d90000000030fa02d2#) called at [vendor/magento/module-customer/Model/Metadata/CustomerMetadata.php:87]
#6 Magento\Customer\Model\Metadata\CustomerMetadata->getAttributeMetadata('mailchimp_store_...') called at [vendor/magento/module-customer/Model/Metadata/CustomerMetadata.php:119]
#7 Magento\Customer\Model\Metadata\CustomerMetadata->getAllAttributesMetadata() called at [vendor/magento/module-customer/Model/Metadata/CachedMetadata.php:85]
#8 Magento\Customer\Model\Metadata\CachedMetadata->getAllAttributesMetadata() called at [vendor/magento/module-customer/Ui/Component/Listing/AttributeRepository.php:83]
#9 Magento\Customer\Ui\Component\Listing\AttributeRepository->getList() called at [vendor/magento/module-customer/Ui/Component/Listing/Columns.php:102]
#10 Magento\Customer\Ui\Component\Listing\Columns->prepare() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:164]
#11 Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(&Magento\Customer\Ui\Component\Listing\Columns#000000002d15e51b0000000030fa02d2#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:161]
#12 Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(&Magento\Ui\Component\Listing#000000002d15e5180000000030fa02d2#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:142]
#13 Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(&Magento\Framework\View\Layout\Data\Structure#000000002d15e1160000000030fa02d2#, 'customer_listing', array('attributes' => array('group' => '', 'component' => '', 'aclResource' => '', 'visibilityCondit...' => array())), &Magento\Framework\View\Layout\Interceptor#000000002d15e0870000000030fa02d2#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:103]
#14 Magento\Framework\View\Layout\Generator\UiComponent->process(&Magento\Framework\View\Layout\Reader\Context#000000002d15e6150000000030fa02d2#, &Magento\Framework\View\Layout\Generator\Context#000000002d15e61c0000000030fa02d2#) called at [vendor/magento/framework/View/Layout/GeneratorPool.php:81]
#15 Magento\Framework\View\Layout\GeneratorPool->process(&Magento\Framework\View\Layout\Reader\Context#000000002d15e6150000000030fa02d2#, &Magento\Framework\View\Layout\Generator\Context#000000002d15e61c0000000030fa02d2#) called at [vendor/magento/framework/View/Layout.php:343]
#16 Magento\Framework\View\Layout->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#17 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#18 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#19 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:253]
#20 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:875]
#21 Magento\Framework\View\Layout->getBlock('menu') called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#22 Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Customer...') called at [vendor/magento/module-customer/Controller/Adminhtml/Index/Index.php:28]
#23 Magento\Customer\Controller\Adminhtml\Index\Index->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#24 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#25 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#26 Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#27 Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#28 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor#000000002d15e05d0000000030fa02d2#, &Closure#000000002d15e7a30000000030fa02d2#, &Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#29 Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#), NULL) called at [generated/code/Magento/Customer/Controller/Adminhtml/Index/Index/Interceptor.php:26]
#31 Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/App/FrontController.php:159]
#32 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#, &Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor#000000002d15e05d0000000030fa02d2#) called at [vendor/magento/framework/App/FrontController.php:99]
#33 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#36 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#37 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000002d15e3f00000000030fa02d2#) called at [vendor/magento/framework/App/Http.php:137]
#38 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#39 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000002d15e30f0000000030fa02d2#) called at [index.php:39]
</pre>

Please provide solution for this.

**Comment by varun2287** [comment]
I am getting this error on system.log file, there is some argument related issue.
Type Error occurred when creating object: Magento\Eav\Model\Entity\Attribute\Source\Config, Argument 1 passed to Magento\Eav\Model\Entity\Attribute\Source\Config::__construct() must be of the type array, null given, called in /home/xxx/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116 [] []
[2019-12-05 08:53:14] main.ERROR: Type Error occurred when creating object: Magento\Eav\Model\Entity\Attribute\Source\Config [] []

Screenshot of given error on AbstractFactory.php is
![customer error](https://user-images.githubusercontent.com/35400881/70220542-c2c7c400-176c-11ea-9d64-b49b25886571.png)

**Comment by victor-v-rad** [comment]
If it is still possible you could try to migrate again to the 2.3.3

**Comment by Nandhini27** [comment]
Can you please share solution to fix the above, getting same issue. Migrated from 1.9.3.4 to 2.3.4
