### ISSUE TITLE
Product details in admin panel not showing after migration in magento 2.3.3

### ISSUE THREAD

**Issue by varun2287** [magento/data-migration-tool#754]
Hi @victor-v-rad ,
After migrating from magento 1.9.2.3. to magento 2.2.4 and then upgrading to 2.3.3 i am continuously facing this error.
On Admin panel when i try to edit any product it shows- "Product do not exist"

And the exception log file displays-"Product with ID "<prod_id>" already exists.
While accessing the product detail page from website it is showing 404 error.
I have also checked the database table "catalog_product_entity", but there is no duplication of product ID.
Screenshot of exception.log file.

![product error](https://user-images.githubusercontent.com/35400881/70209791-2a731480-1757-11ea-9cee-5c605223379a.png)

Screenshot of Admin Panel-
![Screenshot (50)](https://user-images.githubusercontent.com/35400881/70209997-981f4080-1757-11ea-8676-4f664af26ee4.png)

Kindly help in the issue, i am very much tired from this error and also provide the suggestion if importing product csv file in magento 2..3 format will work in this case or not?

Thanks in advance.

**Comment by victor-v-rad** [comment]
If it is still possible you could try to migrate again to the 2.3.3

**Comment by varun2287** [comment]
Hi @victor-v-rad ,

I have resolved the error related to admin panel, actually the defect was in CatalogInventory_stock_status table, there was duplicate entries for product_id.
I deleted the duplicate entries and products now opening in the admin panel.

But on the website when i try to open a product, it is giving 500 error.
I have also checked system.log file there is some error.
![Screenshot (13)](https://user-images.githubusercontent.com/35400881/70907559-34d2bf80-202f-11ea-9b6e-6f57d94f1f6a.png)


Please look to this issue, 
Any kind of help is highly admired.
Thank you.
