### ISSUE TITLE
After migration, checkout payment failure SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

### ISSUE THREAD

**Issue by jas8522** [magento/data-migration-tool#755]
### Preconditions
1. SRC: Magento 1.9.4.1, PHP 5.6
2. DST: Magento 2.2.9, PHP 7.1
3. MySQL 5.6.46 on CentOS 6.10 with Plesk Onyx v17.8.11

For all I know it's possible that the store configuration in the SRC store (1.9.x) needs to have some odd values to correctly reproduce this... I have no idea how I'd ever test this to confirm.

### Steps to reproduce

1. Successfully complete migration of data from Magento 1.9.4.1 to 2.2.9
2. As customer, add products to cart
3. Proceed with checkout
4. At final payment screen, press button to complete the order
5. Magento generic error provided on screen and the actual payment processing never occurs (no additions to var/log/payment.log)
6. Debug log at var/log/debug.log shows:

```
[2019-12-03 19:26:58] main.CRITICAL: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES () {"exception":"[object] (Zend_Db_Statement_Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES () at /web/root/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' at /web/root/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []
```

### Expected result
Upon final checkout (step 4 above), the payment info should be sent to the credit card payment gateway (we're using Moneris) and the payment and order should complete successfully.

### Actual result
Rather that sending payment info to the payment gateway and completing the order successfully, Magento throws the above noted SQL error in the debug log and displays a generic internal error on screen.

### Solution
I found the solution to this SQL error here: https://magento.stackexchange.com/questions/110701/magento-2-syntax-error-or-access-violation-1103-incorrect-table-name-query

Specifically, I had to run this SQL query to resolve it:
```
INSERT INTO `mg_sales_sequence_meta` (`meta_id`, `entity_type`, `store_id`, `sequence_table`) VALUES (NULL, 'order', '8', 'mg_sequence_order_8’);
```

### Additional notes
What's particularly strange about this solution is that the store with ID 8 shouldn't matter for this order because we're not checking out with *any* of that store's products. I even removed the store with ID 8 from Magento because we don't need it anymore, and that did *not* resolve the problem -- I still had to run the SQL query above to repair the problem. Why should database entries about a store that's not even being used anymore affect orders with products not in that store?

Bizarrely, if I enable Sandbox mode with our Moneris payment gateway, the payment completes successfully, as does the order. Shouldn't Magento be behaving *exactly* the same while in sandbox mode to ensure that we can fully test payments before taking it out of sandbox mode? Why should it *not* be adding entries to that table while in sandbox mode?

### Suggestions / Recommendations

1. This migration tool should be running all of the SQL recommended by Jitendra Mandloi in that stackexchange article linked above against all store IDs registered in the system just in case a problem like this occurs upon migration. You could probably [use this code](https://github.com/joeshelton-wagento/fixsalessequence) and add the additional queries (as it only covers the first set of queries as is)
2. When a store is removed from Magento, I don't think any of these tables should be reliant upon that store ID existing any longer
3. When in sandbox mode, Magento's side of the payment process should behave identically as it does when in live mode because developers *need* to be able to test this effectively without using real credit card numbers.

I'm happy to answer any questions you might have about this.

**Comment by jas8522** [comment]
To further clarify about my first recommendation above, the [fixsalessequence project's module code](https://github.com/joeshelton-wagento/fixsalessequence) covers automatically looping through all registered stores in Magento, and running the *first* set of SQL queries that were recommended by Jitendra Mandloi in the [stackexchange thread here](https://magento.stackexchange.com/questions/110701/magento-2-syntax-error-or-access-violation-1103-incorrect-table-name-query).

Specifically, it will create all necessary tables like `sequence_creditmemo_STOREID`, `sequence_order_STOREID`, `sequence_invoice_STOREID`, etc. However it will not update the references *to* those tables in `sales_sequence_meta` nor in `sales_sequence_profile` if they are missing.

My suggestion is to enhance the code in the fixsalessequence project to include updating the values in `sales_sequence_meta` and `sales_sequence_profile` then run it after every import/migration of data so there can't be this kind of DB problem post-migration. It seems doing this might be simpler than actually figuring out why the migration tool didn't create the necessary SQL data in the first place.

**Comment by victor-v-rad** [comment]
Hi @jas8522 

Thank you for reporting this issue. Since 2.2.9 Magento and Data Migration Tool have been improved substantially. Please consider migration to 2.3.3. It might solve this issue

**Comment by fredden** [comment]
This problem still exists in version 2.3.5 of the data migration tool.

**Comment by BernardRobbins** [comment]
I also had this same issue, but not with a migration. When the store was created initially, the sales_sequence_meta and sales_sequence_profile records were not created for the store.
