### ISSUE TITLE
Magento community edition 2.1.* to 2.3.* - bin/magento setup:upgrade - Schema creation/updates: SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by Rajat9620** [magento/data-migration-tool#756]
Hello Support,,

I'm upgrading from "magento/product-community-edition": "2.1.9" to "magento/product-community-edition": "2.3.2-p2" using the command-line and getting below error.

php bin/magento setup:upgrade -vvv

Updating modules:
Schema creation/updates:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE', query was: ALTER TABLE `eav_attribute_group` MODIFY COLUMN `attribute_group_name` varchar(255) NULL  COMMENT "Attribute Group Name", MODIFY COLUMN `tab_group_code` varchar(255) NULL  COMMENT "Tab Group Code", ADD CONSTRAINT `EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE` UNIQUE KEY (`attribute_set_id`,`attribute_group_code`)

I have checked one related thread and they asked to open issue for migration.
Check below link:
https://github.com/magento/magento2/issues/20346

Please help me to solve this issue asap.
Thanks

**Comment by Rajat9620** [comment]
Hello @victor-v-rad 
Can you please check the above issue and help me to solve this issue?

Thanks

**Comment by Rajat9620** [comment]
@victor-v-rad @victor-ruiz 
Any update on this please?

**Comment by victor-v-rad** [comment]
you can delete duplicate records from eav_attribute_group it they no longer needed

**Comment by Rajat9620** [comment]
@victor-v-rad 
I can I check if they are needed or not?
