### ISSUE TITLE
Cannot configure Map step in a separate module (custom map.xml) 

### ISSUE THREAD

**Issue by BillTsarnas** [magento/data-migration-tool#757]
### Preconditions
1. Magento 2 EE 2.3.1

### Steps to reproduce
1. Create a new module to configure the migration (after installing the data migration tool), as specified in the docs: https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html#configure-migration-in-a-separate-module
https://devdocs.magento.com/guides/v2.3/migration/migration-tool-configure.html#migration-config
2. Add a custom config.xml and map.xml in the new module (data copied over from the relevant xml.dist files, for example `<magento_root>/app/code/ProjectName/Migration/etc/commerce-to-commerce/1.14.2.4/map.xml`)
3. In the custom config.xml, replace the the name of the map file in the options node:
```
<options>
        <map_file>etc/commerce-to-commerce/1.14.2.4/map.xml</map_file>
        ...
  </options>
```
4. Run the migration command using the config.xml in the new custom module:
`php bin/magento -r migrate:data app/code/ProjectName/Migration/etc/commerce-to-commerce/1.14.2.4/config.xml`

### Expected result
1. The tool picks up the map.xml file that resides in the custom migration module

### Actual result
1. Exception is thrown:
 `Invalid map filename: <magento_root>/vendor/magento/data-migration-tool/etc/commerce-to-commerce/1.14.2.4/map.xml`

### Additional notes
The tool always picks up the map xml file from the vendor directory, see https://github.com/magento/data-migration-tool/blob/2.3-develop/src/Migration/Reader/Map.php#L106

**Comment by victor-v-rad** [comment]
Hi @BillTsarnas 

Thank you for reporting this issue. You can try to enter full path of your map.xml file in <map_file>

**Comment by BillTsarnas** [comment]
Hey @victor-v-rad 

I provided the full path of the custom map.xml in the <map_file> (of the custom config.xml), now I get:

```
In Map.php line 85:

  [Migration\Exception]
  Invalid map filename: /Users/<user>/src/<project>/vendor/magento/data-migration-tool//Users/<user>/src/<project>/app/code/<ProjectName>/Migration/etc/commerce-to-co
  mmerce/1.14.2.4/map.xml
```

Clearly the tool code always uses its own root (vendor module) `/Users/<user>/src/<project>/vendor/magento/data-migration-tool/` , and then appends whatever path exists in the <map_file> node of the config.

**Comment by victor-v-rad** [comment]
it was fixed in the latest release of Data Migration Tool 2.3.3 . You can backport it from https://github.com/magento/data-migration-tool/commit/e80bddf8c00d1ef946745acb89b5fe3538ca4eb9 or use Magento 2.3.3 and the tool 2.3.3
