### ISSUE TITLE
catalogsearch_fulltext_scope3' doesn't exist

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/data-migration-tool#76]
After running data-migration some index table is not created, not even when running indexers after doing migration. This error is triggered when trying to save a product in the backend.

Tested this with php 7.0 AND with php 5.6

**Comment by victor-v-rad** [comment]
I have php running on 5.5 ver. but I doubt the issue related to PHP version. Anyway after migrating store with three store view and running the command
`php bin/magento cache:flush && php bin/magento indexer:reindex`
I have got catalogsearch_fulltext_scope1 catalogsearch_fulltext_scope2 catalogsearch_fulltext_scope3 table on my Magento 2

**Comment by PascalBrouwers** [comment]
My stores go till 11, those are all missing. This is just the first error I get when saving the product.

**Comment by ilol** [comment]
@PascalBrouwers  Hope you are doing well. Do you still need assistance with this issue?

**Comment by PascalBrouwers** [comment]
I still have this issue, the only solution is to manually create the tables.

**Comment by victor-v-rad** [comment]
Thank you for raising this problem. An internal issue was created to investigate more thoroughly this case

**Comment by ilol** [comment]
Register ID: MAGETWO-52507
