### ISSUE TITLE
Magento 2 admin translation not working after migration

### ISSUE THREAD

**Issue by Rajat9620** [magento/data-migration-tool#761]
Hello,

I have migrated our magento from 1 to 2.1.6 and then after upgraded magento 2 version from 2.1.6 to 2.3.3 step by step(2.2.5 -> 2.2.9 -> 2.3.0 ->2.3.3). Now I am checking my admin and found one issue. Admin translations are not working. Please check the attached screenshot https://prnt.sc/qhgfyv
This is multi site website with nl_nL language enabled.
@victor-v-rad  @victor-ruiz  Can you please check once and let me know what is the issue.

**Comment by Rajat9620** [comment]
@victor-v-rad  @victor-ruiz 
Any update on this please?

Thanks

**Comment by victor-v-rad** [comment]
Hi @Rajat9620 

Thank you for reporting this issue. I tried to reproduce the issue. Migrated Magento 1 database and switched language. After it all words were correct

**Comment by Rajat9620** [comment]
hello @victor-v-rad 

thanks for the reply. can you please let me know what could be the issue?
Also any idea to solve such issue?

**Comment by victor-v-rad** [comment]
You can try to backup then clean M2 DB > translation table. Then clear cache > relogin in Admin Panel

**Comment by Rajat9620** [comment]
can you please let me know the tables name?

**Comment by victor-v-rad** [comment]
the table name is ```translation```

**Comment by Rajat9620** [comment]
thanks. I will try and get back to you with updates

**Comment by Rajat9620** [comment]
hello @victor-v-rad 
I have truncate the translate table then deploy as well as cleared cache as well. But still there is translation error.
My store has nl_NL language enabled.
What should I need to do now? https://prnt.sc/qk1shg

Thanks

**Comment by Rajat9620** [comment]
Also I have one new issue that product images on home page & listing page are showing from other store. Its working fine on detail page. Currently I have two multisite magento.

**Comment by Rajat9620** [comment]
hello @victor-v-rad 
any update on this please?

**Comment by victor-v-rad** [comment]
I was no able to reproduce the issue. If your store uses Magento Commerce Edition you can create a ticket to our support team and send them your DB for investigation.

**Comment by Rajat9620** [comment]
@victor-v-rad 
can you please let me know where I need to create this ticket?
Also any idea about the product image issue. Images are comming from another store instead of its own store.

Thanks

**Comment by victor-v-rad** [comment]
https://magento.zendesk.com/

**Comment by Rajat9620** [comment]
@victor-v-rad 
I have checked and I am not able to find "Submit a ticket" even after login.
Any help?

Thanks
