### ISSUE TITLE
Simple products price missing for bundle product options

### ISSUE THREAD

**Issue by VZeroCool** [magento/data-migration-tool#764]
### Preconditions

1. Migrate data from Magento 1.9.3.9 to Magento CE 2.3.3
2. PHP 7.2,Apache2

### Steps to reproduce

1. Run data migration tool to migrate data with -- auto option 

### Expected result

1. Price should be in the drop-down and it will reflect the base price of a product when select options.

### Actual result

1. All data including products, Blocks, and other configurations migrated successfully but options have no price for simple products.

### Additional notes
I digged into code and found that `optionConfig` doesn't have any prices for old, base and final If I add manually price to the `Magento\Bundle\Block\Catalog\Product\View\Type::getSelectionItemData` it will start working and also checked tables it has prices.

**Comment by victor-v-rad** [comment]
Hi @VZeroCool 

Thank you for reporting this issue. Internal ticket MC-30208 to process it

**Comment by VZeroCool** [comment]
Hi @victor-v-rad Thanks for ticket can you give me a manual scenario to check this one? any workaround?
As I said above prices are in database, Also if I configure bundle product and add it to cart with options cart also shows prices for selected options.
This problem is only available at the frontend product view.

**Comment by victor-v-rad** [comment]
Hi @VZeroCool 

I have just migrated Magento 1 with bundle product and see the prices for options are visible. Look at the screen shot
<img width="699" alt="migrated_bundle_product" src="https://user-images.githubusercontent.com/106504/71907665-18a7d700-3132-11ea-8a26-abde791c0390.png">

**Comment by VZeroCool** [comment]
Yes, @victor-v-rad I did same thing today morning without checking notifications and it worked for me too. Not sure what's it causing its working at M1 level, I've prices at M2 DB and after quote creation, it is also working. Now it's getting irritating. I'll investigate this tomorrow if you have any quick ideas do share :)
