### ISSUE TITLE
Cannot place order after migration from 1.9.4.1 to 2.3.3

### ISSUE THREAD

**Issue by codedge** [magento/data-migration-tool#766]
When placing an order after running a migration from Magento 1.9.4.1 to Magento 2.3.3 I get the error message `Uncaught Error: Call to a member function getAdditionalInformation()` in `/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php:185`. 
The migration process ran without any problems. All orders and customers where migrated successfully.

The problem exists with online (Paypal) and offline (Cash on delivery) payment methods.

The issues is on this line `$paymentAdditionalInformation = $order->getPayment()->getAdditionalInformation();` wheere `$order->getPayment()` is null. 

### Preconditions (*)

1. After migration from Magento 1.9.4.1 to Magento 2.3.3
2. Migrated only order and customers using [these configs](https://gist.github.com/codedge/9937b20440eb93b5a7c789f6a8ab3c3d) (config.xml + map.xml)
3. Running migration command `php bin/magento migrate:data app/etc/data-migration/config.xml -r -a` which ran without any errors
4. Running indexing `php bin/magento indexer:reindex`

### Steps to reproduce (*)

1. Create an order, take one product, go to checkout
2. Online or offline payment method - no difference
3. After clicking the _Place order_ button the error happens

### Expected result (*)

The order should be created without any problem.

### Actual result (*)

The following error is created as a report file and you get redirected back to the cart page.

```
"Fatal Error: 'Uncaught Error: Call to a member function getAdditionalInformation() on null in \/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php:185
Stack trace:
#0 \/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php(144): Magento\\Sales\\Model\\OrderRepository->setPaymentAdditionalInfo(Object(Magento\\Sales\\Model\\Order\\Interceptor))
#1 \/usr\/share\/nginx\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Sales\\Model\\OrderRepository->get('7653')
#2 \/usr\/share\/nginx\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Sales\\Model\\OrderRepository\\Interceptor->___callParent('get', Array)
#3 \/usr\/share\/nginx\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Sales\\Model\\OrderRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}('7653')
#4 \/usr\/share\/nginx\/html\/generated\/code\/Magento\/Sales\/Model\/OrderRepository\/Interceptor.php(26): Magento\\Sales\\Model\\OrderRepository\\Interceptor->___callPlugins('get', Array, Arra' in '\/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php' on line 185"
```

Issue was first placed here: https://github.com/magento/magento2/issues/26271

**Comment by victor-v-rad** [comment]
Hi  @codedge 

Thank you for reporting this issue. I've tried to produce the issue on vanilla Magento 1 and Magento 2 with your config and map files and placed order without any errors.

**Comment by codedge** [comment]
So, is this then a problem with the data I am importing? I do not have a single point to start debugging. Any suggestion is very welcome.

**Comment by victor-v-rad** [comment]
you can Xdebug setPaymentAdditionalInfo() to figure out why getPayment() method return null

**Comment by codedge** [comment]
Well, `getPayment()` is null because payment cannot be received - [`getPayment`](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order.php#L975) returns null.

It neither can get items from the [`PaymentsCollection`](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order.php#L979) nor is payment set on the order object - `$this->getData('payment')` is `null` as well.

I don't know where the payment should be set initially. I currently testing with PayPal. Maybe someone can point me to where the payment normally is set. So I could debug there, why it is not set  in my case.

**UPDATE**

Another module was interfering. Problem is solved. No M2 bug.

**Comment by javierenciso** [comment]
@codedge having exact same issue with similar preconditions (migrating from 2.2.3 to 2.3.3) and several modules with modifications.
Can I ask you for some orientation in what kind of module was interfering?
Was it modifying the payment? or dispatching any event before time?
Would be very grateful with some help - need to complete migrations asap.
/best
/javier

**Comment by codedge** [comment]
@javierenciso I had a module for debugging purposes that hooked into `checkout` and `payment` events. I wanted to track when the payment object gets empty. Unfortunately this module made, for whatever reasons, that the `getPayment()` method returned `null` - although it did not touch this method or any object around.
