### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by alfabet-alfabet** [magento/data-migration-tool#770]
I need to migrate from our magento 1.7.0.2 to magento 2.2.0

I'm using data-migration-tool on a different server for test purposes, but i'm getting this error.

`Notice: Undefined offset: 1 in /home/mysite/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291`

I've searched online a solution, it appears to me that this is caused by "Orphan records" in my M1 database. Problem is i'm a complete newbie and i've no idea what this means fo sure and, more importat, how to fix this.

**COMPLETE HISTORY**

Our M1 site is quite heavily modified, with a theme, some extensions and few changes that i've made myself (only html/css stuff). Of course I except only the essential things to be transfered (categories, customers, products ..)

I would like to pass our data to a clean new install of magento 2.2.0 (i've chosen this version because we plan to use a theme that require this)

On a new server I've created the new M2 site with php 7.1 and installed the data-migration-tool.

I've configurated the config.xml file with my source and destination databases info, added my prefixes and my cript key. I've also changed bulk_size to 500 and direct_document_copy to 1.

I had to change file AbstractResource.php beacuse was returning an error. I've followed this link https://github.com/magento-panda/data-migration-tool/commit/5fc6ff3c5c89aea88e8843c55fdafc9cf3bd6f3b

When i ran migrate:settings everything seems fine

Problem is, as stated, that when migrate:data is lunched this error is returned

`Notice: Undefined offset: 1 in /home/mysite/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 291`

All this is the results of few days of testing, but keep in mind that i've made this process from scretch starting from a new install of M2, so i don't think that interrupted migration are the cause of my problem.

Do any of you have an idea about what i should do?

**Comment by victor-v-rad** [comment]
Hi @alfabet-alfabet 

You can try to use the latest Data Migration Tool 2.3.3 and Magento 2.3.3. It will increase chances for the successful migration. And do not forget to restore your Magento 2 DB to its initial state in case you want to migrate from the scratch with --reset option
