### ISSUE TITLE
log_visitor table not getting ignored

### ISSUE THREAD

**Issue by deepjoshi94** [magento/data-migration-tool#773]
### Preconditions

Added below code in `map.xml`
`
<document_rules>
            <ignore>
                    <document>customer_visitor</document>
            </ignore>
</document_rules>`

### Steps to reproduce

Executed data migration using  **php bin/magento migrate:data /path/to/config.xml**

### Expected result

1. customer_visitor table should be ignored.

### Actual result

1. customer_visitor not getting ignored and data is being pushed.

**Comment by victor-v-rad** [comment]
Hi @deepjoshi94 

Thank you for reporting this issue. You need to remove "Log Step" from your config.xml file to not migrate log_visitor tables

**Comment by deepjoshi94** [comment]
@victor-v-rad I can comment Log Step and it works if I comment it.
But even if I ignore this particular table it should work without commenting Log Step.

Is this bug in migration tool or am I missing something?

**Comment by deepjoshi94** [comment]
We need to ignore particular document in map-log.xml file.
