### ISSUE TITLE
Source fields are not mapped. Document: checkout_agreement.

### ISSUE THREAD

**Issue by stradd** [magento/data-migration-tool#776]
I m trying to migrate data from Magento 1.9.3.2 to 2.3.3 both Opensource version.
I fixed all source fields are not mapped bugs in map.xml.dist near line 1117

One of many errors was:
Source fields are not mapped. Document: checkout_agreement. Fields: is_required, agreement_type, revocation_product_type

I tried to fix it like all other source fields are not mapped errors

`<ignore><field>checkout_agreement.is_required</field></ignore>`
`<ignore><field>checkout_agreement.agreement_type</field>/ignore>`
`<ignore><field>checkout_agreement.revocation_product_type</field></ignore>`

But this code is ignored.
It works for everyone else.

Any idea what could be the issue?

**Comment by victor-v-rad** [comment]
Hi 

Thank you for reporting this issue. There is code in map.xml file
```
            <ignore>
                <field>checkout_agreement.mode</field>
            </ignore>
```
you can change it this way
```
            <ignore>
                <field>checkout_agreement.mode</field>
            </ignore>
            <ignore>
                <field>checkout_agreement.is_required</field>
            </ignore>
            <ignore>
                <field>checkout_agreement.agreement_type</field>
            </ignore>
            <ignore>
                <field>checkout_agreement.revocation_product_type</field>
            </ignore>

```

**Comment by stradd** [comment]
Hi,
thank you very much, it worked perfectly
