### ISSUE TITLE
Bug in collectCmsPageRewrites for CMS pages on both default and store_id 1

### ISSUE THREAD

**Issue by flecxie** [magento/data-migration-tool#78]
Found a bug collectCmsPageRewrites function which was introduced in the following commit: https://github.com/magento/data-migration-tool/commit/448280028b16437b26cd972cf6085a21a38688ff

The following line causes trouble in case of CMS page exists both for 'default' and for store_id 1:
`                'store_id' => 'IF(cps.store_id = 0, 1, cps.store_id)',`

Results for example in error like this:

```
[2016-04-16 12:15:55][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec


  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'about-us-1' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'
```

The following hack (changing default id to 999 instead of 1) got me past this issue:
`                'store_id' => 'IF(cps.store_id = 0, 999, cps.store_id)',`

**Comment by victor-v-rad** [comment]
I have not managed to reproduce your case. But I faced volume check error when CMS page exists both for 'default' and for store_id 1. I will fix it in next release of the tool. If you could share your cms_page and cms_page_store tables data, maybe then I could reproduce the issue

**Comment by ilol** [comment]
@flecxie ping

**Comment by ilol** [comment]
Hey @flecxie, can I close the issue?

**Comment by flecxie** [comment]
Sorry for delay to reply, trying this again this week with 2.0.7, will update in a few days...

**Comment by flecxie** [comment]
Still experiencing same issue when trying to migrate 1.7.0.2 to 2.0.7, below the relevant tables:

```
mysql> select page_id,identifier from cms_page where identifier="about-us";
+---------+------------+
| page_id | identifier |
+---------+------------+
|       3 | about-us   |
|      24 | about-us   |
|      25 | about-us   |
|      26 | about-us   |
|      27 | about-us   |
|      38 | about-us   |
|      46 | about-us   |
|      57 | about-us   |
+---------+------------+
8 rows in set (0.00 sec)

mysql> select * from cms_page_store where (page_id=3 or page_id=24 or page_id=25 or page_id=26 or page_id=27 or page_id=38 or page_id=46 or page_id=57);
+---------+----------+
| page_id | store_id |
+---------+----------+
|       3 |        2 |
|      24 |        3 |
|      25 |        4 |
|      26 |        1 |
|      27 |        0 |
|      38 |        6 |
|      46 |        5 |
|      57 |        8 |
+---------+----------+
8 rows in set (0.00 sec)
```

The one with store_id=0 is the trouble maker.

**Comment by ilol** [comment]
Hey @flecxie. We fixed the issue. Try 2.1.1 of MT. 

I am temporary closing until any respond.
