### ISSUE TITLE
Confused around Delta Migration Category data (rewrites?)

### ISSUE THREAD

**Issue by iphigenie** [magento/data-migration-tool#782]
I created a category on my old site, and noticed that the delta migration did not create a category on the new site.

That's actually fine by me, I don't use categories a lot, so I can create the category on the new site too, in preparation. Obviously it gets the same ID.

Next delta I get an error from CATALOG_CATEGORY_ENTITY_INT_ENTITY_ID_ATTRIBUTE_ID_STORE_ID as migration tries to enter the data for that category and it is already there.

Is there a way to make this a touch more forgiving and not insert what is already there? I had to delete the category which means they cant be in sync even manually, it is a shame.

Is there a way around this as I near release i need to re-create the categories but I would also still like to keep orders in sync. I guess I just disable the Rewrite step at that point?

**Comment by victor-v-rad** [comment]
Hi @iphigenie 

Thank you for reporting this issue. You also can add new tables in map-document-groups.xml.dist for update on duplicate behavior

**Comment by iphigenie** [comment]
Looking at other tickets around rewrites these category/product deltas cause a few bugs. 

Perhaps worth mentioning in the docs somewhere that if your delta phase will last a while, unless people really need the old category/product rewrites for url keys that were changed, it is much simpler to turn off the category/products rewrites during the migration. Either on both sides or on the new M2 site. Can always recreate a fresh batch on the site later.
