### ISSUE TITLE
Is this tool help to migrate DB2 database into MySQL?

### ISSUE THREAD

**Issue by subesingh1981** [magento/data-migration-tool#787]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by victor-v-rad** [comment]
The tool was tested to migrate from MySQL to MySQL. Here https://firebearstudio.com/blog/magento-2-db2-data-import.html can help
