### ISSUE TITLE
Magento 2 web setup wizard gives 404 error after migration

### ISSUE THREAD

**Issue by Rajat9620** [magento/data-migration-tool#789]
Hello,
After successfull migration from 2.2.9 to 2.3.3, magento web setup wizard gives 404 error.
Can you please help me to solve such issue?

@victor-v-rad  @victor-ruiz 

Thanks

**Comment by victor-v-rad** [comment]
Hi @Rajat9620 

Thank you for reporting this issue. I was not able to reproduce it on the latest migrated 2.3.4

**Comment by Rajat9620** [comment]
@victor-v-rad  any help to solve this issue?

**Comment by victor-v-rad** [comment]
The issue is not reproducible on vanilla Magento. You can find log files which can help in finding root cause.
