### ISSUE TITLE
ignore fields doesn't seems to work as supposed

### ISSUE THREAD

**Issue by etessari** [magento/data-migration-tool#79]
Error:
Source fields are not mapped. Document: catalog_product_option. Fields: image_path,customoptions_is_onetime

I have added field as ignored to map.xml:
`<source>
<field_rules>
<ignore><datatype>catalog_product_option.customoptions_is_onetime</datatype></ignore>
<ignore><datatype>catalog_product_option.image_path</datatype></ignore>
</field_rules>
</source>`

**Comment by victor-v-rad** [comment]
Hi,
Use <ignore><field> instead of <ignore><datatype>

**Comment by ilol** [comment]
Can close?

**Comment by ilol** [comment]
Thanks!
