### ISSUE TITLE
Related Products didn't import - 1.9.4.1 to 2.3.3

### ISSUE THREAD

**Issue by asifsomy** [magento/data-migration-tool#793]
### Preconditions

PHP 7.2
MYSQL 5.7
Magento 1.9.4.1CE to  Magento 2.3.3CE

### Steps to reproduce

Migrate data using data-migration-tool for above mentioned versions

### Expected result

1. There should be related products linked to imported products

### Actual result

1. There is no related product. catalog_product_link table has no new data.

**Comment by victor-v-rad** [comment]
Hi @asifsomy 

Thank you for reporting this issue. The issue is not reproducible. catalog_product_link table contains migrated data from Magento 1
