### ISSUE TITLE
update 2.3.3 tag

### ISSUE THREAD

**Issue by Morgy93** [magento/data-migration-tool#796]
Hello,

would it be possible to upgrade the 2.3.3 tag to the latest changes from 2.3 branch? (Or something like that)
Currently it's not possible to provide a config with a separate module, because it looks at the wrong place for some xml.
This is fixed in later releases, but not for the 2.3.3 one.

To be more specific:

https://github.com/magento/data-migration-tool/blob/2.3.3/src/Migration/Reader/Groups.php#L52
`$xmlFile = $this->getRootDir() . $groupsFile;`
This one doesn't work, because it doesn't respect the seperate modules xml files.

It should be something like this one:
https://github.com/magento/data-migration-tool/blob/2.3.3/src/Migration/Reader/Map.php#L83
`$configFile = file_exists($mapFile) ? $mapFile : $this->getRootDir() . $mapFile;`

And like you can see it is indeed fixed for the 2.3.4:
https://github.com/magento/data-migration-tool/blob/2.3.4/src/Migration/Reader/Groups.php#L52
`$xmlFile = file_exists($groupsFile) ? $groupsFile : $this->getRootDir() . $groupsFile;`

But if someone (like me) wants to migrate to 2.3.3 with config from a separate module, it just will not work at the moment.

**Comment by victor-v-rad** [comment]
Hi @Morgy93 

Thank you for reporting this issue. You can fork the repository and backport these fixes

**Comment by KeithBradley** [comment]
Hi @victor-v-rad 

This issue also exists within ClassMap.php

https://github.com/magento/data-migration-tool/blob/be109a7cff992b697160ed1074b4881fc6197aa6/src/Migration/Reader/ClassMap.php#L71
