### ISSUE TITLE
Deltalog Error: Base table or view not found

### ISSUE THREAD

**Issue by carlos-reynosa** [magento/data-migration-tool#798]
### Preconditions

1. Running migrate data process from M1 CE 1.9.2.4
2. Importing into commerce 2.3.3
3. Using custom module for config customizations 
4. Source is a remote database
5. Running process within a production mode docker environment using the https://github.com/magento/magento-cloud-docker project
6. Using magento/data-migration-tool version  2.3.4

### Steps to reproduce

1. ./bin/magento migrate:data -a  vendor/pdp/migration/etc/opensource-to-commerce/1.9.2.4/config.xml 

### Expected result

1. Migrate data process should not throw an error during data migration 

### Actual result

1.  Migrate data process displays an error during stage 'data migration' and step 'PostProcessing':

![image](https://user-images.githubusercontent.com/926773/75304625-9a45e800-57f8-11ea-9125-88df57647bb9.png)

```
In Mysql.php line 110:
                                                                                                                                   
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pdp_magento.enterprise_giftcard_amount' doesn't exist, query was: SE  
  LECT COUNT(*) FROM `enterprise_giftcard_amount`
```
```
In Mysql.php line 91:
                                                                                                                    
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pdp_magento.enterprise_giftcard_amount' doesn't exist

```
### Additional notes
* File etc/opensource-to-commerce/deltalog.xml.dist:93 has reference to enterprise_giftcard_amount

**Comment by victor-v-rad** [comment]
Hi @carlos-reynosa 

Thank you for reporting this issue. Please try the fix from #791
