### ISSUE TITLE
is it possible to migrate only customers and ordes data?

### ISSUE THREAD

**Issue by etessari** [magento/data-migration-tool#80]

**Comment by victor-v-rad** [comment]
The tool does not provide such functionality out of the box

**Comment by quynhvv** [comment]
@guys,
We do have a free Magento 2 migration tool in place (https://www.ubertheme.com/magento-news/magento-2-data-migration-tool/), however the current tool does not support partial data migration yet. 
If you need to get partial data migration, we can help with our custom migration service. Please reach us here if this is what you consider. 

Thanks,

**Comment by mszterlingfsite** [comment]
@quynhvv It looks like advertisement of your services here

**Comment by mszterlingfsite** [comment]
@etessari  it is possible - but you need to tweak xml files to disable steps which are not required.

**Comment by etessari** [comment]
@mszterlingfsite Yes thank you. I have already tried but the tool does not fully satisfy my needs (e.g.  subscribers, wishlist and other stuff). So I decided to go for a custom solution.
