### ISSUE TITLE
Data migration tool: class-map.xml file overridden issue in csutom module

### ISSUE THREAD

**Issue by vishal-7037** [magento/data-migration-tool#805]
### Preconditions

1. Magento 2.3.4
2. PHP 7.2

### Steps to reproduce

1. Create a new separate module to configure data migration tool
2. Override class-map.xml.dist file to new module under app/code/vendor/Migration directory.
3. Then, run data migration command.

### Expected result

It should override properly and command should run successfully

### Actual result

![2020-04-03_18:59:23](https://user-images.githubusercontent.com/38535982/78365942-6fac3380-75dd-11ea-83bf-180ea342f1af.png)

**Comment by victor-v-rad** [comment]
Hi @vishal-7037 

Thank you for reporting and fixing this issue. Internal ticket MC-33062 to fix it
