### ISSUE TITLE
[ERROR]: Integrity check failed due to "core_config_data" document does not exist in the destination resource

### ISSUE THREAD

**Issue by cartoonjazz** [magento/data-migration-tool#807]
Using the data migration tool from 1.9.3.1 to 2.3.4 with the following command

php bin/magento migrate:settings --auto vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.1/config.xml

I receive error 

[2020-04-13 22:14:00][ERROR]: Integrity check failed due to "core_config_data" document does not exist in the destination resource

In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'i2120969_db1.db_core_config_data' do
  esn't exist, query was: SELECT COUNT(*) FROM `db_core_config_data`

In Mysql.php line 91:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dataname_db1.db_core_config_data' doesn't exist

- The 2.3.4 data has a prefix of db_ indicated in the config.xml 

- I applied the fix in MC-31156 https://github.com/magento/data-migration-tool/commit/387e04f80dc55da2481015c807c158b63646a68a
with the same result
the file core_config_data is already in map.xml to be ignored
-config.xml has  
<options>
        <map_file>etc/opensource-to-opensource/1.9.3.1/map.xml</map_file><dest_prefix>db_</dest_prefix>

I have been working on this for hours and can't find anyone online who has gotten by this error. If anyone has any suggestions it would be appreciated.

**Comment by victor-v-rad** [comment]
Hi @cartoonjazz 
Thank you for reporting this issue. Please check Magento 1 and Magento 2 tables prefixes and if they exit add them into your config.xml file of the tool into         

```
<source_prefix />
<dest_prefix/>

```

**Comment by cartoonjazz** [comment]
thank you, As mentioned in my comment - The 2.3.4 data has a prefix of db_ indicated in the config.xml
<options>
<map_file>etc/opensource-to-opensource/1.9.3.1/map.xml</map_file><dest_prefix>db_</dest_prefix>

**Comment by cartoonjazz** [comment]
here are the screen shots of the databases ibb.co/QkVtcZw

**Comment by victor-v-rad** [comment]
It is better to install Magento 2 extensions after migration of settings and data

**Comment by cartoonjazz** [comment]
I have not installed any magento 2 extensions

**Comment by victor-v-rad** [comment]
then probably magento 2 db you showed in screenshot is not from magento 2

**Comment by cartoonjazz** [comment]
yes it is, why do you think it's not the magento data?

**Comment by victor-v-rad** [comment]
please try to find db_core_config_data table in your Magento 2 DB

**Comment by cartoonjazz** [comment]
My Magento 2 install put in 3 databases
1-with a "_db" suffix doesn't contain any tables with the word core 
2 -with a "_mg" suffix that contains the core_config_data table
3-with a "_fr" suffix doesn't contain any tables with the word core 

Since I'm doing the settings migration do I point to the "_mg" suffix in the config file then change it to the _db suffix data to do the data migration?

**Comment by victor-v-rad** [comment]
The tool does not support migration to Magento 2 split database

**Comment by cartoonjazz** [comment]
I installed M2 using installatron and was not asked about splitting the
data. Is there a location I can download a blank data or have Magento
generate a blank data that I can use for the data migration tool?

**Comment by cartoonjazz** [comment]
The config.xml was pointing to the wrong data. After pointing to the correct db everything migrated
