### ISSUE TITLE
url_keys are not unique enough for 2.0

### ISSUE THREAD

**Issue by mszterlingfsite** [magento/data-migration-tool#83]
When migrating url keys from 1.7.0.2 data is copied as it is, so all urls are not unique enough for magento 2.

F.e. moving category will break

**Comment by ilol** [comment]
Thank you, @mszterlingfsite  will discuss it with MT development team.

**Comment by victor-v-rad** [comment]
Hi, @mszterlingfsite 

> moving category will break

I have migrated 1.7.0.2 store to 2.0.5 ver with several categories and products in. Then moved category from subcategory to root and checked it in storefront. After reindexing and cleaning cache category structure was changed accordingly. 

> all urls are not unique enough

Would you share with more specific information?

**Comment by redboxmarcins** [comment]
@victor-v-rad happy to provide a database so you can test it yourself

**Comment by victor-v-rad** [comment]
@redboxmarcins @mszterlingfsite in case the initial version of Magento was before 1.6.0.0 and upgraded to a version that the tool support then it could be problems with successful migration.

**Comment by redboxmarcins** [comment]
@victor-v-rad magento version is 1.7.0.2.

**Comment by victor-v-rad** [comment]
@mszterlingfsite @redboxmarcins 
Please recheck it in the latest version of the tool and close the issue in case it is not actual any more
