### ISSUE TITLE
Price Issue 

### ISSUE THREAD

**Issue by Nehace40** [magento/data-migration-tool#86]
Recently i am migrating all data.
In that i have so many virtual products.
Some virtual product get their price and some product price is empty .
What is the solution of this issue?  

Magento 1.7.0.2 to 2.0.4

**Comment by victor-v-rad** [comment]
Are these products with Tire Price?

**Comment by ND17** [comment]
@victor-v-rad No there is no tier price for empty price products

**Comment by victor-v-rad** [comment]
@Nehace40 
Sorry for so late responding. Is the issue still actual? If so you could send me your DB dump. I would try to migrate and fix it. Here https://github.com/victor-v-rad you can find my email

**Comment by Nehace40** [comment]
@victor-v-rad Its not bug but in old database price is not exist for that products so Price is empty. i am closing this issue
