### ISSUE TITLE
Data Migration Tool with splitted database

### ISSUE THREAD

**Issue by WaPoNe** [magento/data-migration-tool#861]
### Preconditions

1. Magento 1 Community 1.9.2.2
2. Magento 2 Commerce 2.4.1
3. Magento 2 splitted database (https://devdocs.magento.com/guides/v2.4/config-guide/multi-master/multi-master.html)

### Steps to reproduce

1.  php bin/magento migrate:data -a -r app/code/<Vendor>/<Module>/etc/opensource-to-commerce/1.9.2.2/config.xml

### Expected result

1. Data migration correctly completed.

### Actual result

1. Base table or view not found: 1146 Table 'sales_order_grid' doesn't exist, query was: DESCRIBE `sales_order_grid`

### Additional notes
Is it possible to use _Data Migration Tool_ with a destination splitted database?

**Comment by DmitryFurs** [comment]
@WaPoNe it has just been announced that the split database will be deprecated from version 2.4.2. Soon there will be recommendations for moving to a single database.

https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-split-database-functionality-in-Magento-Commerce/ba-p/465187

**Comment by WaPoNe** [comment]
Thanks for the news @DmitryFurs
