### ISSUE TITLE
CE 1.9.2.4 and EE 1.14.2.4 migration - does it support this version?

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#87]

**Comment by victor-v-rad** [comment]
Thought the tool 2.0.5 has not released with supporting of 1.14.2.4, you can easily check that database structure of 1.14.2.3 and 1.14.2.4 is the same. Try using config and map files from 1.14.2.3. It should work.

**Comment by ilol** [comment]
@craigcarnell if this works please close the ticket. Thanks

**Comment by craigcarnell** [comment]
@ilol Will try now hopefully
