### ISSUE TITLE
Product category_ids missing from migrated attribute sets

### ISSUE THREAD

**Issue by kassner** [magento/data-migration-tool#89]
Hi,

Magento 2 uses an attribute called `category_ids` to display the category selector in the product edit form in admin, but still stores data into `catalog_category_product` table, the same way as Magento 1.

This table is populated correctly during migration (tested migration from patched 1.6.2.0 to 2.0.5), but the `category_ids` is not added to all copied attribute sets, so if you edit a product after the migration, it loses its categories association (rows are deleted from `catalog_category_product`) and breadcrumbs URLs (category/subcategory/product.html) is also lost (deleted from `url_rewrite` table), leading to a lot of 404 URLs.

It is possible to avoid losing the data if we add the `category_ids` attribute back to the attribute sets before editing the products in the admin.

Thanks,
Rafael Kassner.

**Comment by vektor-dev** [comment]
Hey Rafael,

We've got the same problem and will let you know if/when we fix it.

Pete

**Comment by phronesis** [comment]
I got the same problems, any progress on this?

**Comment by victor-v-rad** [comment]
@kassner @vektor-dev @phronesis  I have not manage to reproduce your issue
You could share your DB dump of the next Magento 1 tables:
eav_attribute_group
eav_attribute_set
eav_attribute
eav_entity_attribute
catalog_eav_attribute
customer_eav_attribute
eav_entity_type
You can send it through the email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it

**Comment by phronesis** [comment]
Thank you Victor. I'll send it across shortly. Thanks.

**Comment by victor-v-rad** [comment]
@kassner @phronesis 
Please recheck the issue on the latest version of the tool and close if it is fixed

**Comment by Gorkyman** [comment]
@victor-v-rad this is still an issue with the latest version of the tool. My wild guess would be, that this happens when you have a "General" attribute group renamed to something else. We have a client that has all default groups renamed and this happened.

**Comment by victor-v-rad** [comment]
@Gorkyman 

>  that this happens when you have a "General" attribute group renamed

In this case you should have seen the error:` The product attribute set "..." does not contain all required attribute group names "..." ` I do not know why it has not happened. The good way to find it out is to send me your DB (without user passwords) and we will try to migrate and see results.

**Comment by deepikajaniyani** [comment]
We are also facing the same issue, i.e. the category_id is not getting associated with the migrated attribute set, due to which categories are not shown up while editing products from admin.

Category associations with products are getting migrated and products are shown against the categories in front-end. But as soon as we edit the product and save it, the products and category association gets removed.

We also observed that in the migrated product data, " Attribute Set" is also editable from admin. 

We are using the latest version of data migration tool, and Magento EE 2.1.1

**Comment by anethum** [comment]
Hi @victor-v-rad we have also the same issue as @Gorkyman.
What was the solution?`
We are using the Version 2.1.3
the previouse v. 2.1.1 working fine

**Comment by dfelton** [comment]
This is still an outstanding issue in version 2.1.3.
Please see issue #212 for a more details.
