### ISSUE TITLE
Empty Categories and Customer Grid

### ISSUE THREAD

**Issue by justin-at-demac** [magento/data-migration-tool#90]
Following the execution of the data migration tool, I can see in the database that customers and products are present within the database. Through the adminhtml, I can see that products are assigned to categories - with correct scoping for stores. On the frontend, however, this is not reflect. All categories are empty. I have reindexed in full.

In addition, the customers grid in the adminhtml is empty - as it is in the dB. But the customer entity table in the dB is populated.

I've tried this migration with the two most recent revisions of the tool and encountered the same issue. I'm migrating from v1.11.2.0.

**Comment by victor-v-rad** [comment]
Sorry for so late responding. Is the issue still actual? Please recheck the issue on the latest version of the tool and close it if it is fixed
