### ISSUE TITLE
Unable to install data migration tool from github

### ISSUE THREAD

**Issue by engcom-November** [magento/data-migration-tool#901]
### Preconditions

Magento 2.4-develop

### Steps to reproduce

Install data migration tool on 2.4-develop from github. Ref [guide](https://devdocs.magento.com/guides/v2.4/migration/migration-tool-install.html)
**Steps:**
```
    composer config repositories.data-migration-tool git https://github.com/magento/data-migration-tool
    composer require magento/data-migration-tool:2.4.4
    or run > composer require magento/data-migration-tool:~2.4
    bin/magento module:enable Magento_DataMigrationTool
```
### Expected result

Data migration tool is installed successfully.

### Actual result

Unable to install the tool from git hub.

**Comment by victor-v-rad** [comment]
Hi
DMT is tested only with stable Magento version. Please use stable Magento or fork this repo to make necessary changes
