### ISSUE TITLE
Error during migration from CE-1.9.2.2 to CE-2.0.5

### ISSUE THREAD

**Issue by nikul** [magento/data-migration-tool#91]
Hello,

Steps Followed:
I have installed magento 2.0.5 and starting migration of my magento 1.9.2.2. Following steps I have made

    Downloaded data-migration-tool using git repository.
    Made version and crypt key changes in config.xml for 1.9.2.2 in data-migration-tool folder.
    Copied settings.xml with no change
    Executed bin/magento migrate:settings vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml

Expected Results:
Migration Completed

Actual Results:
Getting error while running command "bin/magento migrate:settings vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml"
Error is...
[InvalidArgumentException]
There are no commands defined in the "migrate" namespace.
![migration-error](https://cloud.githubusercontent.com/assets/266397/15713069/7e05f292-2832-11e6-9bd1-dbfe70442c18.PNG)

**Comment by nikul** [comment]
@mazhalai  Any help on this?

**Comment by nikul** [comment]
anyone has solution? please guide...

**Comment by victor-v-rad** [comment]
Hi,
Please follow the instructions from [official docs](http://devdocs.magento.com/guides/v2.0/migration/migration-tool-install.html)

> composer config repositories.magento composer https://repo.magento.com
composer require magento/data-migration-tool:<version>

**Comment by nikul** [comment]
exact same instructions are followed and getting error in running bin/magento migrate:settings vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml
not sure what is missing... 
I checked in files and found like it could not find migrate command or namespace.
any way to debug this error?

**Comment by victor-v-rad** [comment]
Look in composer.json of Magento 2 it should have data-migration-tool in repositories section

**Comment by nikul** [comment]
this is what showing in compoer.json file

"repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool"
        }
    },
    "require": {
        "magento/product-community-edition": "2.0.6",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "2.0.5"
    },

**Comment by victor-v-rad** [comment]
Make sure that "magento/data-migration-tool" exists in "require" section in composer.json and files of Data Migration Tool located in your_magento2_root/vendor/magento/data-migration-tool

**Comment by nikul** [comment]
/vendor/magento/data-migration-tool folder exists and I also made required changes in /vendor/magento/data-migration-tool/etc/ce-to-ce/1.9.2.2/config.xml file

**Comment by kennpie** [comment]
I found I had to empty all the normal Magento2 caches: var/generation, var/cache, var/di, var/page-cache/*, var/view_preprocessed... and then the migrate commands worked. I don't know exactly why that worked.

**Comment by mikebranderhorst** [comment]
magerun2 cache:flush

(bin/magento cache:clean does not work in this case)

**Comment by Jaro99** [comment]
adding **repositories** into composer.json helped here ( **require** was added automatically though) 
i did **composer update data-migration-tool** as well
