### ISSUE TITLE
Error Exception -  Undefined offset: 6 

### ISSUE THREAD

**Issue by carloshernan007** [magento/data-migration-tool#92]
Hi, I working  with magento 1,7,2 to 2,0,7 I have on error.

[ErrorException]     
Undefined offset: 6

![magento-tool](https://cloud.githubusercontent.com/assets/1942655/15714661/0881bc1e-27e1-11e6-90f6-64fe19edda58.png)

Thanks for your help.

**Comment by carloshernan007** [comment]
I checked the line 186 in this line have a array of 5 position;

array(5) {
  [1]=>
  array(4) {
    ["attribute_set_id"]=>
    string(1) "1"
    ["entity_type_id"]=>
    string(1) "4"
    ["attribute_set_name"]=>
    string(17) "Migration_Default"
    ["sort_order"]=>
    string(3) "100"
  }
  [2]=>
  array(4) {
    ["attribute_set_id"]=>
    string(1) "2"
    ["entity_type_id"]=>
    string(1) "5"
    ["attribute_set_name"]=>
    string(17) "Migration_Default"
    ["sort_order"]=>
    string(3) "100"
  }
  [3]=>
  array(4) {
    ["attribute_set_id"]=>
    string(1) "3"
    ["entity_type_id"]=>
    string(1) "6"
    ["attribute_set_name"]=>
    string(17) "Migration_Default"
    ["sort_order"]=>
    string(3) "100"
  }
  [4]=>
  array(4) {
    ["attribute_set_id"]=>
    string(1) "4"
    ["entity_type_id"]=>
    string(1) "7"
    ["attribute_set_name"]=>
    string(17) "Migration_Default"
    ["sort_order"]=>
    string(3) "100"
  }
  [5]=>
  array(4) {
    ["attribute_set_id"]=>
    string(1) "5"
    ["entity_type_id"]=>
    string(1) "8"
    ["attribute_set_name"]=>
    string(17) "Migration_Default"
    ["sort_order"]=>
    string(3) "100"
  }
}

The problem is when looking for a sixth place that does not exist for the case.

array(7) {
  ["attribute_group_id"]=>
  string(2) "14"
  ["attribute_set_id"]=>
  string(1) "6"
  ["attribute_group_name"]=>
  string(17) "Migration_General"
  ["sort_order"]=>
  string(1) "1"
  ["default_id"]=>
  string(1) "0"
  ["attribute_group_code"]=>
  string(0) ""
  ["tab_group_code"]=>
  string(5) "basic"
}

Line 186   $oldAttributeSet = $this->initialData->getAttributeSets('dest')[$record['attribute_set_id']];

**Comment by kennpie** [comment]
I'm doing the exact same migration (1.7.0.2 to 2.0.7) and have the same error, at the same point, with the same stacktrace (but a different index value, obviously)

is there a fix forthcoming, or a workaround? Any suggestions for further debugging?

**Comment by carloshernan007** [comment]
Thanks for your reply , my problem was not clean the database again to present a first mistake, this creates duplicity is everything.

**Comment by toddliningerdesign** [comment]
Hello,

I am facing same problem in Magento 2.1 , is there any solution for that?

**Comment by victor-v-rad** [comment]
@toddliningerdesign @kennpie @carloshernan007 
I suppose some attribute_set_id values in eav_attribute_group table do not exist in eav_attribute_set table. Please check it.

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-56861

**Comment by victor-v-rad** [comment]
Seems the issue appeared with not clean DB of Magento 2. Please reopen if it is not the case.
