### ISSUE TITLE
Upgrade to Magento 2.4.7. with Data Migration Tool not working

### ISSUE THREAD

**Issue by HRR1337** [magento/data-migration-tool#923]
Trying to upgrade magento 2.4.6-p4 to magento 2.4.7 with the data migration tool (that is installed) gives the following error: 

Problem 1
    - Root composer.json requires magento/data-migration-tool 2.4.6 -> satisfiable by magento/data-migration-tool[2.4.6].
    - magento/data-migration-tool 2.4.6 requires symfony/console ^5.4 -> satisfiable by symfony/console[v5.4.0, ..., v5.4.36].
    - You can only install one version of a package, so only one of these can be installed: symfony/console[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.49, v5.0.0, ..., v5.4.36, v6.0.0, ..., v6.4.6, v7.0.0, ..., v7.0.6].
    - magento/product-community-edition 2.4.7 requires symfony/console ^6.4 -> satisfiable by symfony/console[v6.4.0, ..., v6.4.6].
    - Root composer.json requires magento/product-community-edition 2.4.7 -> satisfiable by magento/product-community-edition[2.4.7].
    
composer update -W doesn't work.

**Comment by pjw345** [comment]
Question: Why would you want to use the migration tool for Magento 2.4.x?  

This tool is normally used to migrate Magento 1.x to 2.x  

If you are already on Magento 2.4.x you just have to update your composer.json file and run composer update followed by php bin/magento setup:upgrade and then you're done!

**Comment by HRR1337** [comment]
> Question: Why would you want to use the migration tool for Magento 2.4.x?
> 
> This tool is normally used to migrate Magento 1.x to 2.x
> 
> If you are already on Magento 2.4.x you just have to update your composer.json file and run composer update followed by php bin/magento setup:upgrade and then you're done!

Already did a migration from 1 to 2.4.6, but am not finished. And want to do a clean (read: new orders, attributes, customers etc) when i'm working on 2.4.7. 

Have now removed the data migration tool - > upgraded magento 2.4.7 - > installed today the data migration tool version 2.4.7 and its working.
