### ISSUE TITLE
No Customers Visible In Admin Backend After Migration from Magento 1.9.0.1 to Magento 2.0.7

### ISSUE THREAD

**Issue by vcpawate** [magento/data-migration-tool#94]
While migration there is no error, and migration gets completed successfully,

But when logged in backend, I cannot see any data. 

When I run this command php bin/magento indexer:reindex && php bin/magento cache:clean
and clicked on the customers tab, it goes to  a thinking mode, where mouse cursoer changes to waiting mode, and it will stay there for long time, after 10 mins, I clicked on the dashboard and it logged out of the admin login and it never gets logged in back to the admin panel again, When typed with credentials, it will show the same page with no error,

Again, I have do the installation from beginning,

Please let me know how can I get customers data in the backend?

**Comment by victor-v-rad** [comment]
@vcpawate 
Please recheck the issue on the latest version of the tool and close it if it is fixed
