### ISSUE TITLE
map.xml - ignored tables aren't being ignored

### ISSUE THREAD

**Issue by kennpie** [magento/data-migration-tool#95]
In my map.xml file, the core_url_rewrite table is configured to be ignored on the source side:

`    <source>
        <document_rules>
...
            <ignore>
                <document>core_url_rewrite</document>
            </ignore>
`

... and the url_rewrite table is configured to be ignored on the destination side:

`    <destination>
        <document_rules>
...
            <ignore>
                <document>url_rewrite</document>
            </ignore>
`

So, why does the migration script bother with them?

[2016-06-14 17:38:51][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: 1 sec
100% [============================] Remaining Time: 1 sec document: url_rewrite
[2016-06-14 17:38:51][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Error occurred. Rollback.
[2016-06-14 17:38:51][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Url Rewrite Step: rollback
[2016-06-14 17:38:51][INFO][mode: data][stage: volume check][step: Url Rewrite Step]: Please fix errors and run Migration Tool again

The only way I got past this error was to empty the magneto1 core_url_rewrite table.

**Comment by Caprico85** [comment]
Ignore rules only apply to the map step. URLs are migrated during the URL rewrite step. In your config.xml you have the following part that you need to comment out:

```
<step title="Url Rewrite Step">
    ...
</step>
```

**Comment by redboxmarcins** [comment]
@kennpie I believe it is not an issue, just misconfiguration in your xml files

**Comment by kennpie** [comment]
Understood... perhaps the docs could explain this better. To me, ignoring a table is ignoring a table.

Closing the issue, thanks.
