### ISSUE TITLE
data-migration-tool converts utf8 characters to `?`

### ISSUE THREAD

**Issue by kandrejevs** [magento/data-migration-tool#96]
when migrating data from magento 1 to magento 2, some utf characters are converted to `?`

example:

can't view orders because when migrating data from `sales_flat_order_item` to `sales_order_item table`, `product_options` column contains serialized data. In my case product name contains character `č`, after migration `s:34:"Nohavičky HP25 ružovočierna S/M"` becomes `s:34:"Nohavi?ky HP25 ružovo?ierna S/M"` since `č` is 2 bytes long and `?` is only 1 byte, string is no longer 34 bytes long and unserialize function returns false and throws notice, which cause fatal error, because product options can't be unserialized.

**Comment by victor-v-rad** [comment]
Hi @kandrejevs 
Try this fix https://github.com/magento/data-migration-tool/pull/28

**Comment by kandrejevs** [comment]
Unfortunately, it did not help. value migrated from `customer_entity_varchar` to `customer_entity` loose double byte character and `?` is present.

**Comment by victor-v-rad** [comment]
An internal issue was created MAGETWO-54492

**Comment by Polar77** [comment]
Data-Migration-Tool does not receive data from the source in utf8.  
[Here][1] is a simple solution to this problem


  [1]: http://magento.stackexchange.com/questions/92578/data-migration-eav-step-error/124711#124711

**Comment by ilol** [comment]
Thank you, @Polar77

**Comment by victor-v-rad** [comment]
The bug was fixed in the recent release. Please try it out. Feel free to reopen the issue if it is still relevant.
