### ISSUE TITLE
Magento 2.1 support?

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool#97]
Hi,

When 2.1 is released, can I update to this and the data migration tool will be updated to reflect the changes?
Or will further work be required.

**Comment by victor-v-rad** [comment]
Hi,
It is better to wait the release of data migration tool 2.1 There are lots of changes in Magento 2

**Comment by redboxmarcins** [comment]
@victor-v-rad Will data migration tool 2.1 be released same time as Magento 2.1?

**Comment by victor-v-rad** [comment]
Final test and fix for the tool needs to be done after Magento 2.1 release. So it will take some time.

**Comment by craigcarnell** [comment]
@victor-v-rad Hope the data-migration-tool for 2.1 is updated soon, there are many bugs in 2.0 and I'd rather develop against it.

```
  Problem 1
    - Conclusion: don't install magento/framework 100.1.0
    - Installation request for magento/product-enterprise-edition 2.1.0 -> satisfiable by magento/product-enterprise-edition[2.1.0].
    - Installation request for magento/data-migration-tool 2.0.7 -> satisfiable by magento/data-migration-tool[2.0.7].
    - magento/product-enterprise-edition 2.1.0 requires magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
    - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
    - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
    - Conclusion: don't install magento/framework 100.1.0
```

**Comment by victor-v-rad** [comment]
The tool will be released not only with Magento 2.1 adaptation but also include bugfixes were exist in 2.0

**Comment by craigcarnell** [comment]
@victor-v-rad When will it be released?

**Comment by tadhgbowe** [comment]
Hello. I've just tried:

composer require magento/data-migration-tool:2.1.0

and I get this:

Problem 1
    - The requested package magento/data-migration-tool could not be found in any version, there may be a typo in the package name.

Am I correct in saying there's no data migration available for 2.1.0 yet? If there isn't then I'm assuming it would be best to wait until one is available because 2.1.0 is a completely new beast?

If somebody could confirm then I can go home early :-)

Thanks
Tadhg

**Comment by redboxmarcins** [comment]
@tadhgbowe correct, data migration tool has different release cycle than Magento, so we can expect it couple weeks later than 2.1

**Comment by tadhgbowe** [comment]
redboxmarcins - thank you!

I had been previously playing about with 2.0.7 ce to ce migration tool with decent success. So I shall ignore the potential causes it informed me of and instead wait with great excitement for an updated release very soon!

Cheers
Tadhg

**Comment by djmarcsmith** [comment]
Any update for this ? As keen to get migrated over to 2.1 thankyou

**Comment by ilol** [comment]
Update for MT to support 2.1 is not ready yet. We are working hard on this

**Comment by craigcarnell** [comment]
Works thank you 👍

**Comment by toddliningerdesign** [comment]
@ilol any update?

**Comment by tadhgbowe** [comment]
toddliningerdesign - it's all sorted. You can download v2.1.0 using composer, it installs fine and works okay too. Happy data migrations!

**Comment by toddliningerdesign** [comment]
@tadhgbowe thanks for message.

we facing below error while data migrate

Notice: Undefined offset: 14 in /var/public/html/magento2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433

**Comment by tadhgbowe** [comment]
Hi toddliningerdesign.

Looking at the code that's in moveAttributeToGroup. Is there an attribute group that M2 can't recognise. In our case we decided not to migrate any eav attributes across. Our EE version (1.13.0.2) had been previously upgraded from a older version so for example none of the eav product attributes matched up when the migration tool began (lots of errors). Our source also contained lots of unwanted attributes. So we decided it would be best to migrate customers and sales orders only. That in itself is a little tricky to do and requires some database tidy up afterwards. 

So the error you're getting we've avoided by tweaking other things. No two migrations will be the same. It's a bit of a minefield to identify the source of issues when they do occur. Best of luck!

Cheers
Tadhg

**Comment by toddliningerdesign** [comment]
@tadhgbowe thanks for your response. 

But we need to transfer products as well

**Comment by toddliningerdesign** [comment]
@tadhgbowe thanks for your response. 

But we need to transfer products as well

**Comment by tadhgbowe** [comment]
toddliningerdesign sorry I'm not able to help here. This issue is closed. Perhaps you can raise a new issue specific to the error you're getting. I hope it works out.
T.
