### ISSUE TITLE
SQLSTATE[28000] [1045] Access denied for user 'USERNAME'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by Ganginator** [magento/data-migration-tool#99]
Receiving this error when trying to run the data migration tool:

[Zend_Db_Adapter_Exception]
SQLSTATE[28000] [1045] Access denied for user 'USERNAME'@'localhost' (using password: YES)
[PDOException]
SQLSTATE[28000] [1045] Access denied for user 'USERNAME'@'localhost' (using password: YES)

I've tried the IP, and domain name, as well as localhost, which all recieve the same error?

Near nothing on the net regarding this, so reached out here.

I know the credentials are correct, and the Magento 2 store is up, and running fine.

**Comment by qozmiq** [comment]
Move the DB to your local server, you'll have much more success.
